#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : legalverification.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/legalverification:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalVerification
      summary: Adds a new LegalVerification.
      description: Adds a new LegalVerification. Add additional information here for this endpoint.
      operationId: addLegalVerification
      parameters:
      - name: LegalVerification
        in: body
        description: Request Body that contains data required for creating a new LegalVerification
        required: true
        schema:
          $ref: '#/definitions/LegalVerificationModel'
      responses:
        201:
          description: Returns the Id of the newly created LegalVerification
          headers:
            Location:
              description: URL of newly created LegalVerification
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalVerification
      summary: Retrieves the list of existing LegalVerification.
      description: Retrieves the list of existing LegalVerification. Add additional information here for the this endpoint.
      operationId: getAllLegalVerification
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/legalverification/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalVerification
      summary: Get a  LegalVerification.
      description: Get a  LegalVerification by given id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: id of the LegalVerification that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns LegalVerification
          schema:
            $ref: '#/definitions/LegalVerificationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalVerification
      summary: Update an existing LegalVerification.
      description: Update an existing LegalVerification. Add additional information here for the this endpoint.
      operationId: updateLegalVerification
      parameters:
      - name: id
        in: path
        description: id of the LegalVerification that need to be updated
        required: true
        type: string
      - name: LegalVerification
        in: body
        description: Request Body that contains data required for updating an existing LegalVerification
        required: true
        schema:
          $ref: '#/definitions/LegalVerificationModel'
      responses:
        200:
          description: Returns updated LegalVerification
          schema:
            $ref: '#/definitions/LegalVerificationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalVerification
      summary: Deletes the LegalVerification identified by given ID.
      description: Deletes the LegalVerification identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLegalVerification
      parameters:
      - name: id
        in: path
        description: Id of the LegalVerification that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LegalVerificationModel:
   description: "LegalVerification model"
   type: "object"
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      legalVerificationDetails:
        type: "array"
        items:
          $ref: "#/definitions/LegalVerificationDetailsModel"
  LegalVerificationCollection:
    description: "Collection of LegalVerification."
    type: "object"
    properties:
      LegalVerificationList:
        type: "array"
        items:
          $ref: "#/definitions/LegalVerificationModel"
  LegalVerificationDetailsModel:
    description: "LegalVerificationDetails Model"
    type: "object"
    properties:
      id:
        description: "Id of the LegalVerificationDetails"
        type: "string"
        maxLength: 36
      legalVerificationId:
        description: "legalVerificationId of the LegalVerificationDetails"
        type: "string"
        maxLength: 36
      documentId:
        description: "documentId of the LegalVerificationDetails"
        type: "string"
        maxLength: 36
      documentName:
        description: "documentName of the LegalVerificationDetails"
        type: "string"
      Status:
        description: "Status of the LegalVerificationDetails"
        type: "string"
        maxLength: 20
      legalOpinionDate:
        description: "legalOpinionDate of the LegalVerificationDetails"
        type: "string"
      remarks:
        description: "remarks of the LegalVerificationDetails"
        type: "string"
        maxLength: 300
      legalVerificationDetailsDocument:
        description: legalVerificationDetailsDocument of the legalVerificationDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  LegalVerificationDetailsCollection:
    description: "Collection of LegalVerificationDetails."
    type: "object"
    properties:
      LegalVerificationDetailsList:
        type: "array"
        items:
          $ref: "#/definitions/LegalVerificationDetailsModel"  
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type