#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : legaldetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/legalcounsel:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalCounselInfo
      summary: Adds a new LegalCounselInfo.
      description: Adds a new LegalCounselInfo. Add additional information here for this endpoint.
      operationId: addLegalCounselInfo
      parameters:
      - name: LegalCounselInfo
        in: body
        description: Request Body that contains data required for creating a new LegalCounselInfo
        required: true
        schema:
          $ref: '#/definitions/LegalCounselInfoModel'
      responses:
        201:
          description: Returns the Id of the newly created LegalCounselInfo
          headers:
            Location:
              description: URL of newly created LegalCounselInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalCounselInfo
      summary: Retrieves the list of existing LegalCounselInfo.
      description: Retrieves the list of existing LegalCounselInfo. Add additional information here for the this endpoint.
      operationId: getAllLegalCounselInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/legalcounsel/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalCounselInfo
      summary: Retrieves the LegalCounselInfo by id.
      description: Retrieves the LegalCounselInfo by id. Add additional information here for the this endpoint.
      operationId: getLegalCounselInfoById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the LegalCounselInfo based on given applicationNumber.
          schema:
            $ref: '#/definitions/LegalCounselInfoModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalCounselInfo
      summary: Update an existing LegalCounselInfo.
      description: Update an existing LegalCounselInfo. Add additional information here for the this endpoint.
      operationId: updateLegalCounselInfo
      parameters:
      - name: id
        in: path
        description: id of the LegalCounselInfo that need to be updated
        required: true
        type: string
      - name: LegalCounselInfo
        in: body
        description: Request Body that contains data required for updating an existing LegalCounselInfo
        required: true
        schema:
          $ref: '#/definitions/LegalCounselInfoModel'
      responses:
        200:
          description: Returns updated LegalCounselInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalCounselInfo
      summary: Deletes the LegalCounselInfo identified by given ID.
      description: Deletes the LegalCounselInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLegalCounselInfo
      parameters:
      - name: id
        in: path
        description: Id of the LegalCounselInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LegalCounselInfoModel:
    description: LegalCounselInfo model
    type: object
    properties:
      id:
        description: Id of the LegalCounselInfo
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      legalCounselDetails:
        type: array
        items:
          $ref: '#/definitions/LegalCounselDetailsModel'
  LegalCounselDetailsModel:
    description: LegalCounselDetails model
    type: object
    properties:
      id:
        description: Id of the LegalCounselDetails
        type: string
      legalCounselInfoId:
        description: legalCounselInfoId
        type: string
      legalCounselId:
        description: legalCounselId
        type: string
      legalCounselName:
        description: legalCounselName
        type: string
      legalCounselPartyNumber:
        description: legalCounselPartyNumber
        type: string
      legalCounselLocation:
        description: legalCounselLocation
        type: string
      legalCounselDoc:
        description: legalCounselDoc of the LegalCounselDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'  
      legalTransactionDocuments:
        type: array
        items:
          $ref: '#/definitions/LegalTransactionDocumentsModel'
  LegalTransactionDocumentsModel:
    description: LegalTransactionDocuments model
    type: object
    properties:
      id:
        description: Id of the LegalTransactionDocuments
        type: string
      legalCounselDetailsId:
        description: legalCounselDetailsId
        type: string
      transactionDocumentName:
        description: transactionDocumentName
        type: string
  LegalCounselInfoCollection:
    description: Collection of LegalCounselInfo.
    type: object
    properties:
      LegalCounselInfoList:
        type: array
        items:
          $ref: '#/definitions/LegalCounselInfoModel'
