swagger: '2.0'
info:
  description: "Branch Common Application -- Logging Sub-Module"
  version: 1.0.0
  title: Cash Service
host: 10.184.157.121:9000
basePath: /cash-services
tags:
- name: Logging
  description: API for Logging Operations
schemes:
- http
paths:
#  /service/v1/cash/cashWithdrawal/executeSubmit:
#    post:
#      tags:
#        - "CashTransactionDSService"
#      summary: "Add a new MiscGL request."
#      description: "Add a new Cash Deposit."
#      operationId: "executeSubmit"
#      parameters:
#        - name: "CashWithdrawalData"
#          in: "body"
#          description: "Request Body that contains data required for creating a Cash Deposit"
#          required: true
#          schema:
#            $ref: "#/definitions/CashWithdrawalData"
#        - name: "appId"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "userId"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "branchCode"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "authToken"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "tenantId"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "contentType"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "branchDate"
#          in: "header"
#          type: "string"
#          required: false
#        - name: "sourceCode"
#          in: "header"
#          type: "string"
#          required: true
#      responses:
#        201:
#          description: "Returns message of succes or failure "
#          headers:
#            Location:
#              description: "URL of newly created cheque book request"
#              type: "string"
#          schema:
#            $ref: "#/definitions/APIDTOWrapper"
#        400:
#          description: "Malformed syntax."
#        401:
#          description: "Request does not have sufficient credentials."
#        403:
#          description: "Request is not authorized."
#        405:
#          description: "Invalid input"
#        500:
#          description: "Internal error"
  
  /service/v1/cash/cashWithdrawal:
    post:
      tags:
        - "CashTransactionDSService"
      summary: "Cash Withdrawal API"
      description: "Do a new Cash Withdrawal."
      operationId: "save"
      parameters:
        - name: "CashWithdrawalData"
          in: "body"
          description: "Request Body that contains data required for creating a Cash Withdrawal"
          required: true
          schema:
            $ref: "#/definitions/CashWithdrawalData"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: false
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: false
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          required: false
        - name: "sourceCode"
          in: "header"
          type: "string"
          required: true
      responses:
        201:
          description: "Returns message of succes or failure "
          headers:
            Location:
              description: "URL of newly created Cash Withdrawal"
              type: "string"
          schema:
            $ref: "#/definitions/APIDTOWrapper"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"

  /service/v1/cash/cashDeposit:
    post:
      tags:
        - "CashTransactionDSService"
      summary: "Cash Deposit API"
      description: "Add a new Cash Deposit."
      operationId: "cashDepositExecuteSubmit"
      parameters:
        - name: "CashDepositData"
          in: "body"
          description: "Request Body that contains data required for creating a Cash Deposit"
          required: true
          schema:
            $ref: "#/definitions/CashDepositData"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: false
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: false
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          required: false
        - name: "sourceCode"
          in: "header"
          type: "string"
          required: true
      responses:
        201:
          description: "Returns message of succes or failure "
          headers:
            Location:
              description: "URL of newly created Cash Deposit"
              type: "string"
          schema:
            $ref: "#/definitions/APIDTOWrapper"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
  /service/v1/customer/externalMiscGLRequest:
    post:
      tags:
        - "CashTransactionDSService"
      summary: "Add a new MiscGL request."
      description: "Add a new MiscGL request."
      operationId: "externalMiscGLRequest"
      parameters:
        - name: "extMiscGlCreditReq"
          in: "body"
          description: "Request Body that contains data required for creating a MISC GL Req"
          required: true
          schema:
            $ref: "#/definitions/miscGlCreditData"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: false
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: false
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          required: false
        - name: "sourceCode"
          in: "header"
          type: "string"
          required: true
      responses:
        201:
          description: "Returns message of succes or failure "
          headers:
            Location:
              description: "URL of newly created Misc GL request"
              type: "string"
          schema:
            $ref: "#/definitions/APIDTOWrapper"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"        
definitions:
          
 SubSystemModel:
    type: "object"
    properties:
      datasegment:
        type: string
        description: "CCA Name"
      txnControllerRefNo:
        type: string
        description: "Txn ref no from UI"
      prcDtls:
        type: array
        items:
          $ref: "#/definitions/PrcDtlsModel"
      demDtls:
        type: array
        items:
          $ref: "#/definitions/DenomTxnDtlsModel"
      fxInDemDtls:
        type: array
        items:
          $ref: "#/definitions/FXInDenomTxnDtlsModel"
      fxOutDemDtls:
        type: array
        items:
          $ref: "#/definitions/FXOutDenomTxnDtlsModel"
 
 RemoTmBranchChargeMasterDTO:
    type: object
    allOf:
    - $ref: '#/definitions/GenericDto'
    - type: object
      properties:
        accountclassGroup:
          type: string
          description: ''
        branchCode:
          type: string
          description: ''
        currency:
          type: string
          description: ''
        customerGroup:
          type: string
          description: ''
        functionId:
          type: string
          description: ''
        interBranch:
          type: string
          description: ''
        remoTmBranchChargeDetailList:
          type: array
          items:
            $ref: '#/definitions/RemoTmBranchChargeDetailDTO'
 RemoTmBranchChargeDetailDTO:
    type: object
    properties:
      basis:
        type: string
        description: ''
      chargeCode:
        type: string
        description: ''
      chargeDesc:
        type: string
        description: ''
      chgAcc:
        type: string
        description: ''
      chgAmt:
        type: number
        description: ''
      chgCcy:
        type: string
        description: ''
      chgCrTxnCode:
        type: string
        description: ''
      chgDrTxnCode:
        type: string
        description: ''
      chgRate:
        type: number
        description: ''
      chgType:
        type: string
        description: ''
      id:
        type: string
        description: ''
      maxChg:
        type: number
        description: ''
      minChg:
        type: number
        description: ''
      netting:
        type: string
        description: ''
      parentId:
        type: string
        description: ''
      rateCode:
        type: string
        description: ''
      natureOfCharge:
        type: string
        description: ''
      rateType:
        type: string
        description: ''
      slabType:
        type: string
        description: ''
      RemoTmBranchChargeSlabDTO:
        type: array
        items:
          $ref: '#/definitions/RemoTmBranchChargeSlabDTO'
 RemoTmBranchChargeSlabDTO:
    type: object
    properties:
      amountFrom:
        type: number
        description: ''
      amountTo:
        type: number
        description: ''
      chgAmt:
        type: number
        description: ''
      chgRate:
        type: number
        description: ''
      id:
        type: string
        description: ''
      parentId:
        type: string
        description: ''
 CashWithdrawalData: 
    description: "User Cash Withdrawal Request"
    properties: 
      cashWithdrawalTransaction: 
        $ref: "#/definitions/CashDepositTransaction"
        description: ""
      demDtls: 
        items: 
          $ref: "../api/cash/cashWeb.yaml#/definitions/DenomTxnDtlsModel"
        type: array
      extSysDtls: 
        $ref: "#/definitions/ExtSysDtls"
        description: ""
      prcDtls: 
        items: 
          $ref: "../api/branchcommon/branchCommonWeb.yaml#/definitions/PrcDtlsModel"
        type: array
      sourceCode: 
        description: sourceCode
        type: string
      sourceRefNo: 
        description: sourceRefNo
        type: string
    type: object
 APIDTOWrapper: 
    properties: 
      data: 
        description: ""
        type: object
      messages: 
        $ref: "#/definitions/APIDTO"
    type: object
 CashDepositTransaction: 
    allOf: 
      - 
        properties: 
          cashAmount: 
            description: ""
            type: number
          chequeDate: 
            description: ""
            format: date
            type: string
          chequeNumber: 
            description: ""
            type: string
          fromAccountAmt: 
            description: ""
            type: number
          fromAccountBranch: 
            description: ""
            type: string
          fromAccountCcy: 
            description: ""
            type: string
          fromAccountNumber: 
            description: ""
            type: string
          mobileNumber: 
            description: ""
            type: string
          narrative: 
            description: ""
            type: string
          tellerSeqNumber: 
            description: ""
            type: string
          toAccountAmt: 
            description: ""
            type: number
          toAccountBranch: 
            description: ""
            type: string
          toAccountCcy: 
            description: ""
            type: string
          toAccountNumber: 
            description: ""
            type: string
          txnBranchCode: 
            description: ""
            type: string
          txnCustomer: 
            description: ""
            type: string
          txnDate: 
            description: ""
            format: date
            type: string
          txnRefNumber: 
            description: ""
            type: string
        type: object
    description: "GL Credit Request"
    type: object
 ExtSysDtls: 
    allOf: 
      - 
        properties: 
          sourceCode: 
            description: ""
            type: string
          sourceRefNo: 
            description: ""
            type: string
          sourceRole: 
            description: ""
            type: string
          sourceUser: 
            description: ""
            type: string
          stationId: 
            description: ""
            type: string
          txnBranch: 
            description: ""
            type: string
        type: object
    description: "User Misc GL Credit Request"
    type: object
 APIDTO: 
    properties: 
      codes: 
        items: 
          $ref: "#/definitions/APICode"
        type: array
      httpStatusCode: 
        type: string
      keyId: 
        type: string
      overrideAuthLevelsReqd: 
        type: string
      requestId: 
        type: string
      status: 
        type: string
    type: object
 APICode: 
    properties: 
      arg: 
        type: string
      args: 
        items: 
          type: object
        type: array
      code: 
        type: string
      desc: 
        type: string
      error: 
        type: string
      information: 
        type: string
      language: 
        type: string
      override: 
        type: string
      overrideAuthLevelsReqd: 
        type: string
      type: 
        type: string
    type: object
 CashDepositData: 
    description: "User Misc GL Credit Request"
    properties: 
      cashDepositTransaction: 
        $ref: "#/definitions/CashDepositTransaction"
        description: ""
      demDtls: 
        items: 
          $ref: "../api/cash/cashWeb.yaml#/definitions/DenomTxnDtlsModel"
        type: array
      extSysDtls: 
        $ref: "#/definitions/ExtSysDtls"
        description: ""
      prcDtls: 
        items: 
#          $ref: "../api/branchcommon/branchCommonWeb.yaml#/definitions/PrcDtlsModel"
          $ref: "../api/branchcommon/branchCommonWeb.yaml#/definitions/PrcDtlsModel"
        type: array
      sourceCode: 
        description: sourceCode
        type: string
      sourceRefNo: 
        description: sourceRefNo
        type: string
    type: object
 miscGlCreditData: 
    description: "User Misc GL Credit Request"
    properties: 
      addDtls: 
        $ref: "../api/commonWeb.yaml#/definitions/AdditionalTransactionDetails"
        description: ""
      dataPayload: 
        type: object
      demDtls: 
        items: 
          $ref: "../api/cash/cashWeb.yaml#/definitions/DenomTxnDtlsModel"
        type: array
      extSysDtls: 
        $ref: "#/definitions/ExtSysDtls"
        description: ""
      miscGlCreditTransaction: 
        $ref: "#/definitions/ExtMiscGlCreditRequest"
        description: ""
      prcDtls: 
        items: 
          $ref: "../api/branchcommon/branchCommonWeb.yaml#/definitions/PrcDtlsModel"
        type: array
      sourceCode: 
        description: sourceCode
        type: string
      sourceRefNo: 
        description: sourceRefNo
        type: string
      txnDtls: 
        $ref: "../api/commonWeb.yaml#/definitions/TransactionDetails"
    type: object
 ExtMiscGlCreditRequest: 
    allOf: 
      - 
        properties: 
          chequeDate: 
            description: ""
            format: date
            type: string
          chequeNumber: 
            description: ""
            type: string
          emailId: 
            description: ""
            type: string
          exchangeRate: 
            description: ""
            type: number
          fromAccountAmt: 
            description: ""
            type: number
          fromAccountBranch: 
            description: ""
            type: string
          fromAccountCcy: 
            description: ""
            type: string
          fromAccountNumber: 
            description: ""
            type: string
          mobileNumber: 
            description: ""
            type: string
          narrative: 
            description: ""
            type: string
          netAccountAmt: 
            description: ""
            type: number
          netAccountCcy: 
            description: ""
            type: string
          tellerSeqNumber: 
            description: ""
            type: string
          toAccountAmt: 
            description: ""
            type: number
          toAccountBranch: 
            description: ""
            type: string
          toAccountCcy: 
            description: ""
            type: string
          toAccountNumber: 
            description: ""
            type: string
          totalCharges: 
            description: ""
            type: number
          txnBranchCode: 
            description: ""
            type: string
          txnCustomer: 
            description: ""
            type: string
          txnDate: 
            description: ""
            format: date
            type: string
          txnRefNumber: 
            description: ""
            type: string
          uniqueIdentifierNumber: 
            description: ""
            type: string
          uniqueIdentifierType: 
            description: ""
            type: string
          userRefNumber: 
            description: ""
            type: string
          valueDate: 
            description: ""
            format: date
            type: string
        type: object
    description: "GL Credit Request"
    type: object
             