swagger: "2.0"
info:
  version: "1.0.0"
  title: "Common Definitions File"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
  MarginDetailsDto:
    type: object
    properties:
      marginRefNo:
        type: string
        description: "Margin Reference No"
      intInvoiceRefNo:
        type: string
        description: "Int Invoice Reference No"
      intPaymentRefNo:
        type: string
        description: "Int Payment Reference No"
      invoiceRefNo:
        type: string
        description: "Invoice Reference No"
      paymentRefNo:
        type: string
        description: "Payment Reference No"
      marginAmount:
        type: number
        description: "Margin Amount"
      marginCcy:
        type: string
        description: "Margin Currency"
      buyerId:
        type: string
        description: "Buyer Id"
      buyerName:
        type: string
        description: "Buyer Name"
      supplierId:
        type: string
        description: "Supplier Id"
      supplierName:
        type: string
        description: "Supplier Name"
      productCode:
        type: string
        description: "Product Code"
      programCode:
        type: string
        description: "Program Code"  
      marginHandling:
        type: string
        description: "Margin Handling"
      marginPaymentMode:
        type: string
        description: "Margin Payment Mode"
      supplierAcNo:
        type: string
        description: "Supplier Account No"
      bankCode:
        type: string
        description: "Bank Code"
      bankName:
        type: string
        description: "Bank Name"
      branchCode:
        type: string
        description: "Branch Code"
      routingCode:
        type: string
        description: "Routing Code"
      marginCalculationDate:
        type: string
        format: date
        description: "Margin Calculation Date"
      marginCalculationStatus:
        type: string
        description: "Margin Calculation Status"
      marginProcessingStatus:
        type: string
        description: "Margin Processing Status"
      marginProcessingDate:
        type: string
        format: date
        description: "Margin Processing Date"
      paymentValueDate:
        type: string
        format: date
        description: "Payment Value Date"
      paymentValueMode:
        type: string
        description: "Payment Value Mode"
        
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer
  ResponseDtoWrapper:
    type: object
    properties:
      messages:
        $ref: "#/definitions/ResponseDto"
      data:
        $ref: "#/definitions/ResponseResourceSupport"
  ResponseResourceSupport:
    type: object
  ResponseDto:
   type: object
   properties:
    id:
     type: string
    status:
     type: string
    codes:
     type: array
     items:
      $ref: "#/definitions/ResponseCode"
    requestId:
     type: string
  ResponseCode:
   type: object
   properties:
    Code:
     type: string
    Desc:
     type: string
    Type:
     type: string
    Language:
     type: string
    args:
     type: array
     items:
      type: object
    arg:
     type: string
  Error:
    type: "object"
    properties:
      ecode:
        type: "string"
      etype:
        type: "string"
      edesc:
        type: "string"
  ConductorWorkflowModel:
    description: "ConductorWorkflowModel"
    type: "object"
    properties:
      processCode:
        type: "string"
        description: "Process Code to identify workflow"
      processName:
        type: "string"
        description: "Process Name to identify workflow"
      userId:
        type: "string"
        description: "User Id"
      stageId:
        type: "string"
        description: "Stage Id"
      stageDescription:
        type: "string"
        description: "Stage desc"
      branchCode:     
        type: "string"
        description: "Branch Code"
      errorCode:
        type: "string"
        description: "Error Code"
      errorDesc:
        type: "string"
        description: "Error Desc"
      transactionReferenceNo:
        type: "string"
        description: "Transaction Referenec No"
      processingDate:
        description: "Processing Date"
        type: "string"
      businessDate:
        description: "Business Date"
        type: "string"
      workflowInstanceId:
        description: "Workflow Instance Id"
        type: "string"
      taskInstanceId:
        description: "Task Instance Id"
        type: "string"
      appId:
        description: "AppId of Workflow Service"
        type: "string"
      uri:
        description: "EndPoint of Workflow Service"
        type: "string"
      product:
        description: "Product type to identify service for instrument"
        type: "string"
      applicationCode:
        description: "Application code"
        type: "string"
      instrumentModel:
        $ref: "#/definitions/InstrumentModel"
      discountOffer:
        $ref: "#/definitions/DiscountingModel"         
      financeModel:
        $ref: "#/definitions/FinanceModel"
      manualReconModel:
        $ref: "#/definitions/ManualReconModel"
      marginRefundModel:
        $ref: "#/definitions/MarginRefundModel"
      workflowType:
        description:
        type: "string"    
      productCode:
        description:
        type: "string"    
      event:
        description:
        type: "string"
      priority:
        type: "string"
      amount:
        type: "number"
      customerNumber:
        type: "string"
      currencyCode:
        type: "string"
      productCategory:
        type: "string"
      applicationNumber:
        description: "Reference number without seqno"
        type: "string" 
      server:
        type: "string"
      isFcubsIntegrationReqd:
        type: "string"
      isInProgKafkaTaskReqd:
        type: "string"

  MarginRefundModel:
    description: "MarginRefundModel"
    properties: 
      marginType:
        type: "string"
        description: "Margin Type"
      marginRefNo:
        type: "string"
        description: "Margin Reference Number"
      isExtPaymentSynchronous:
        type: "string"
        description: "External Payment Synchronous Flag"
      instrumentType:
        type: "string"
        description: "Instrument Type"
      supplier:
        type: "string"
        description: "Supplier Name"
      buyer:
        type: "string"
        description: "Buyer Name"
        
  InstrumentModel:
    description: "InstrumentModel"
    properties: 
      action:
        type: "string"
        description: "Action"
      isAutoAuth:
        type: "string"
        description: "IsAutoAuth"
      isFileUpload:
        type: "string"
        description: "isFileUpload"
      isFileAuthorized:
        type: "string"
        description: "isFileUpload"
      isPortalTxn:
        type: "string"
        description: "isPortalTxn"
      instrumentType:
        type: "string"
        description: "Instrument Type"
      partyId:
        type: "string"
        description: "Party id"
      invoiceRefNo:
        type: "string"
        description: "Invoice Ref No"
      isFromML:
        type: "string"
        description: "Check if txn is from ML"
      isMLHumanTaskReqd:
        type: "string"
        description: "Check if ml txn requires human task"
      isAutoProcessingReqInv:
        type: "string"
        description: "Check if ml txn requires human task"
      isManualEnrichmentReqdInv:
        type: "string"
        description: "Check if ml txn requires human task"  
      limitBlockReqdInv:
        type: "string"
        description: "Check if ml txn requires human task"  
      limitUtilRelReqdInv:
        type: "string"
        description: "Check if ml txn requires human task"   
      additionalDetails:
        type: object
      additionalProperties:
        type: object
      isAccountingApplicable:
        description: "isAccountingApplicable"
        type: "string"
      executionId:
        type: "string"
        description: "Execution Id"
      iwpBunchIdentifier:
        type: "string"
        description: "iwpBunchIdentifier"
      fipBunchIdentifier:
        type: "string"
        description: "fipBunchIdentifier"
      nfipBunchIdentifier:
        type: "string"
        description: "nfipBunchIdentifier"
      flowType:
        type: "string"
        description: "flowType"
      isFciIntegrationReqd:
        type: "string"
        description: "Check if fci integration required"          
  FinanceModel:
    description: "FinanceModel"
    properties:
      financeRefNo:
        type: "string"
        description: "financeRefNo"
      financeRefNoSeqNo:
        type: "string"
        description: "financeRefNoSeqNo"
      financeSeqNo:
        type: "integer"
        format: "int64"
      isAutoProcessing:
        type: "string"
        description: "isAutoProcessing flag"
      isLimitBlockReqd:
        type: "string"
        description: "isLimitBlockReqd flag"
      isLimitApplicable:
        type: "string"
        description: "Limit Applicable Flag"
      isAuthRequired:
        type: "string"
        description: "isAuthRequired flag"
      isAccEntriesPostRequired:
        type: "string"
        description: "isAccEntriesPostRequired flag"
      isExternalPaymentRequired:
        type: "string"
        description: "isExternalPaymentRequired flag"
      isLimitUtilReleaseRequired:
        type: "string"
        description: "isLimitUtilReleaseRequired flag"
      isUpdateFinanceMasterReqd:
        type: "string"
        description: "isUpdateFinanceMasterReqd flag"
      isInstrumentUpdateReqd:
        type: "string"
        description: "isInstrumentUpdateReqd flag"
      isObclTxnUpdateReqd:
        type: "string"
        description: "isObclTxnUpdateReqd flag"
      isAlertsAndNotificationReqd:
        type: "string"
        description: "isAlertsAndNotificationReqd flag"
      blockLimitsProcessingReqd:
        type: "string"
        description: "Limits Flag"
      isExtPaymentSynchronous:
        type: "string"
      isAccountingSynchronous:
        type: "string"
      additionalDetails:
        type: object
      additionalProperties:
        type: object

  ManualReconModel:
    description: "ManualReconModel"
    properties:
      isAutoAuth:
        description: "Is Auto Auth"
        type: "string" 
      reconTxnRefNo:
        description: "Transaction Reference Number"
        type: "string"
      isVamIntegrationReqd:
        description: "Flag for Reference Number"
        type: "string"
      isFinanceIntegrationReqd:
        description: "Flag for finance settlement "
        type: "string"
      invAcquireTaskReqd:
        description: "Flag for to acquire invoice task"
        type: "string"
      additionalDetails:
       type: object
       additionalProperties:
        type: object 
  ResponseModel:
    description: "Response Model"
    type: "object"
    properties:
      data:
        type: "object"
      errors:
        type: "object"
      paging:
        type: "object"        
  GenericDto:
    allOf:
     - type: object
       discriminator: resource_type  
  DiscountingModel:
    description: "DiscountingModel"
    properties:
      isAutoAuth:
        type: "string"
        description: "isAutoAuth"
      discountRuleId:  
        type: "string"
        description: "discountRuleId"
      additionalDetails:
        type: object
        additionalProperties:
         type: object           
             