swagger: "2.0"
info:
  version: "1.0.0"
  title: "Credit Note Definitions Yaml file"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
  CreditNoteModel:
    description: "Credit Note Model"
    type: "object"
    properties:
      srcAppCd:
        type: "string"
        description: "Source Application Code"
      creditNoteRefNo:
        type: "string"
        description: "Credit Note System generated RefNo"
      creditNoteId:
        type: "string"
        description: "Credit Note generated Id"
      cnNumber:
        type: "string"
        description: "Credit Note Reference Number"
      seqNo:
        type: "integer"
        format: "int64"
      cnDate:
        type: "string"
        description: "Cn Date"
      cnExpiryDate:
        type: "string"
        description: "Cn Expiry Date"
      linkInvoiceNumber:
        type: "string"
        description: "Pipe seperated invoice numbers"
      supplierId:
        type: "string"
        description: "Supplier Id"
      buyerId:
        type: "string"
        description: "Buyer Id"
      supplierName:
        type: "string"
        description: "Supplier Name"
      supplierDivCode:
        type: "string"
        description: "Supplier Division Code"
      supplierDivName:
        type: "string"
        description: "Supplier Division Name"
      buyerName:
        type: "string"
        description: "Buyer Name"
      buyerDivCode:
        type: "string"
        description: "Buyer Division Code"
      buyerDivName:
        type: "string"
        description: "Buyer Division Name"
      relationCode:
        type: "string"
        description: "Relation Code"
      programCode:
        type: "string"
        description: "Program Code"
      programName:
        type: "string"
        description: "Program Name"
      adjustmentReason:
        type: "string"
        description: "Adjustment Reason"
      remarks:
        type: "string"
        description: "Remarks"
      currency:
        type: "string"
        description: "Currency"
      amount:
        type: number
        description: "Base Cn amount"
      totalAmount:
        type: number
        description: "Total Cn amount"
      netAmount:
        type: number
        description: "Net Cn amount"
      taxAmount:
        type: number
        description: "Tax Amount"
      discountPercentage:
        type: number
        description: "Discount Percentage"
      discountAmount:
        type: number
        description: "Discount Amount"
      taxPercentage:
        type: number
        description: "Tax Percentage"
      fileName:
        type: "string"
        description: "File Name"
      reasonCode:
        type: "string"
        description: "Reason Code"
      reasonErrorCode:
        type: "string"
        description: "Reason Error Code"
      filler1:
        type: "string"
        description: "Filler1"
      filler2:
        type: "string"
        description: "Filler2"
      filler3:
        type: "string"
        description: "Filler3"
      filler4:
        type: "string"
        description: "Filler4"
      filler5:
        type: "string"
        description: "Filler5"
      filler6:
        type: "string"
        description: "Filler6"
      filler7:
        type: "string"
        description: "Filler7"
      filler8:
        type: "string"
        description: "Filler8"
      filler9:
        type: "string"
        description: "Filler9"
      filler10:
        type: "string"
        description: "Filler10"
      cnStatus:
        type: "string"
        description: "Cn Status"
      cnReconcilationStatus:
        type: "string"
        description: "Cn Reconcilation Status"
      transactionRefNo:
        type: "string"
        description: "Transaction Reference Number"
      buyerCode:
        type: "string"
        description: "Buyer Code"
      supplierCode:
        type: "string"
        description: "Supplier code"
      sourceTxnId:
        type: "string"
        description: "Source Transaction Id"
      makerId:
        type: "string"
        description: "Maker Id"
      makerDtStamp:
        type: "string"
        description: "Maker Date Stamp"
      miscCharge1Amount:
        type: number
        description: "Miscellaneous Charge1 Amount"
      miscCharge1Desc:
        type: "string"
        description: "Miscellaneous Charge1 Description"
      miscCharge2Amount:
        type: number
        description: "Miscellaneous Charge2 Amount"
      miscCharge2Desc:
        type: "string"
        description: "Miscellaneous Charge2 Description"
      matchedAmount:
        type: number
        description: "Matched Amount"
      unmatchedAmount:
        type: number
        description: "Unmatched Amount"
      procBranchCode:
        type: "string"
        description: "Proc Branch Code"
      procBranchDate:
        type: "string"
        description: "Proc Branch Date"
      stageId:
        type: "string"
        description: "Stage Id"
      reconTxnStatus:
        type: "string"
        description: "Recon Transaction Status"
      isAutoAuth:
        type: "string"
        description: "Is Auto Authorized"
      isAutoReconcile:
        type: "string"
        description: "Is Auto Authorized"                
      isTxnCreationReqd:
        type: string
        description: "is txn creation required"              
      commodityGridList:
        type: "array"
        items:
          $ref: "#/definitions/CnCommodityGridModel"
      linkedInvoiceList:
        type: array
        items:
          $ref: "#/definitions/LinkedInvoiceModel"
      reconciledPmtAmt:
        type: number
      isRecon:
        type: string
  CreateCreditNoteModel:
    description: "Create Credit Note Model"
    type: "object"
    properties:
      srcAppCd:
        type: "string"
        description: "Source Application Code"
      cnNumber:
        type: "string"
        description: "Credit Note Reference Number"
      cnDate:
        type: "string"
        description: "Cn Date"
      cnExpiryDate:
        type: "string"
        description: "Cn Expiry Date"
      linkInvoiceNumber:
        type: "string"
        description: "Pipe seperated invoice numbers"
      supplierId:
        type: "string"
        description: "Supplier Id"
      buyerId:
        type: "string"
        description: "Buyer Id"
      supplierName:
        type: "string"
        description: "Supplier Name"
      supplierDivName:
        type: "string"
        description: "Supplier Division Name"
      buyerName:
        type: "string"
        description: "Buyer Name"
      buyerDivCode:
        type: "string"
        description: "Buyer Division Code"
      buyerDivName:
        type: "string"
        description: "Buyer Division Name"
      relationCode:
        type: "string"
        description: "Relation Code"
      programCode:
        type: "string"
        description: "Program Code"
      programName:
        type: "string"
        description: "Program Name"
      adjustmentReason:
        type: "string"
        description: "Adjustment Reason"
      currency:
        type: "string"
        description: "Currency"
      remarks:
        type: "string"
        description: "Remarks"        
  CnCommodityGridModel:
    type: "object"
    properties:
      id:
        type: "string"
      seqNo:
        type: "integer"
        format: "int64"
      commodityCode:
        type: "string"
        description: "Commodity Code"
      commodityName:
        type: "string"
        description: "Commodity Name"
      currency:
        type: "string"
        description: "Currency"
      commodityDesc:
        type: "string"
        description: "Commodity Description"
      descriptionOfGoods:
        type: "string"
        description: "Description of Goods"
      unit:
        type: "string"
        description: "Unit"
      invoiceNumber:
        type: "string"
        description: "Invoice Number"
      creditNoteRefNo:
        type: "string"
        description: "Credit Note Reference Number"
      transactionRefNo:
        type: "string"
        description: "Transaction Reference Number"
      discountAmount:
        type: number
        description: "Discount Amount"
      discountPercentage:
        type: number
        description: "Discount Percentage"
      taxAmount:
        type: number
        description: "Tax Amount"
      taxPercentage:
        type: number
        description: "Tax Percentage"
      costPerUnit:
        type: number
        description: "Cost Per Unit"
      totalCost:
        type: number
        description: "Total Cost"
      netCost:
        type: number
        description: "Net cost"
      quantity:
        type: number
        description: "Quantity"
      unitWeight:
        type: number
        description: "Unit Weight"
      totalWeight:
        type: number
        description: "Total weight"
  CreditNoteCollectionDto:
    description: "List of Credit Notes"
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/CreditNoteModel"
      paging:
        $ref: "./CommonDef.yaml#/definitions/PagingDto"
  CreditNoteCollection:
    description: "List of Credit Notes"
    type: "object"
    properties:
      action:
        type: "string"
        description: "Is Auto Authorized"
      sourceTxnId:
        type: "string"
      creditNoteList:
        type: "array"
        items:
          $ref: "#/definitions/CreditNoteModel"
      paging:
        $ref: "./CommonDef.yaml#/definitions/PagingDto"
      errorCode:
        type: "string"
        description: "Error Code"
      errorDesc:
        type: "string"
        description: "Error Desc" 
  CreditNoteWorkflowModel:
    type: "object"
    properties:
      productCode:
        type: "string"
      amount:
        type: "number"
        description: "Amount"
      transactionRefNo:
        type: "string"
        description: "Transaction Reference Number"
      currency:
        type: "string"
        description: "Currency"
      supplier:
        type: "string"
        description: "Supplier"
      isAutoAuth:
        type: "string"
        description: "Is Auto Authorized"
      event:
        type: "string"
        description: "Event"
      buyer:
        type: "string"
        description: "Buyer"
      instrumentType:
        type: "string"
        description: "Instrument Type" 
      channel:
        type: "string"
        description: "Channel"
  CreateCreditNoteV2ResponseCollection:
    description: List of Create Credit Note Service Response
    type: object
    properties:
      txnStatus:
        type: "string" 
      errCode:
        type: "string"
      errDesc:
        type: "string"    
      createCreditNoteResList:
        type: array
        items: 
          $ref: '#/definitions/CreateCreditNoteV2Response'
  CreateCreditNoteV2Response:
    properties:
      sourceTxnId:
        type: "string"
      transactionRefNo:
        type: "string"        
      txnStatus:
        type: "string" 
      errCode:
        type: "string"
      errDesc:
        type: "string"
      creditNoteResList:
        type: array
        items: 
          $ref: '#/definitions/CreditNoteResponse'
  CreditNoteResponse:
    properties:
      cnNumber:
        type: "string"
      cnId:
        type: "string"
      txnStatus:
        type: "string"
      creditNoteRefNo:
        type: "string"
      cnStatus:
        type: "string"                
      errCode:
        type: "string"
      errDesc:
        type: "string" 
  CreateCreditNoteResponseCollection:
    description: List of Create Credit Note Service Response
    type: object
    properties:
      createCreditNoteList:
        type: array
        items: 
          $ref: "#/definitions/CreateCreditNoteResponse"
  CreateCreditNoteResponse:
    properties:
      cnNumber:
        type: "string"
      cnId:
        type: "string"
      transactionRefNo:
        type: "string"        
      supplierId:
        type: "string"
      creditNoteRefNo:
        type: "string"
      cnStatus:
        type: "string"
      cnProcessStatus:
        type: "string"        
      errors:
        type: "array"
        items:
          $ref: "./CommonDef.yaml#/definitions/Error"
  CreditNoteBunchDetailsCollection:
    description: "Details of bunched Credit Notes for transaction"
    type: "object"
    properties:
     rejectedCreditNoteResponseList:
      type: "array"
      items: 
       $ref: "#/definitions/CreateCreditNoteResponse"
     creditNoteBunchDetailsList:
      type: "array"
      items: 
       $ref: "#/definitions/CreditNoteBunchDetails"
     count:
      type: number
  CreditNoteBunchDetails:
    description: "Details of bunched Credit Notes for transaction"
    type: "object"
    properties:
     sourceTxnId:
      type: string    
     transactionRefNo:
      type: string
     creditNoteResponseDetailsList:
      type: "array"
      items: 
       $ref: "#/definitions/CreateCreditNoteResponse"

  UpdateCreditNoteResponse:
    type: "object"
    properties:
      srcAppRefNo:
        type: string
        description: "Src App Reference Number"
      transactionRefNo:
        type: "string"
        description: "Transaction Reference Number"
      trnStatus:
        type: string
        description: "Transaction Status"
      errorCode:
        type: string
        description: "Error Code"
      errorDesc:
        type: string
        description: "Error Description"
      processingDate:
        type: string
        description: "Processing Date"
      refNoList:
        type: array
        items:
          $ref: '#/definitions/CreditNoteTransactionResponse'
  CreditNoteTransactionResponse:
    description: "List of Internal Reference Numbers"
    type: "object"
    properties:
      creditNoteRefNo:
        type: string
        description: "Credit note Reference Number"
      trnStatus:
        type: string
        description: "Transaction Status"
      errorCode:
        type: string
        description: "Error Code"
      errorDesc:
        type: string
        description: "Error Description" 
  LinkedInvoiceModel:
   type: "object"
   properties:
     invoiceNumber:
       type: string
     invoiceRefNo:
       type: string
     invoiceAmount:
       type: number
     miscCharge1Amount:
       type: number
     miscCharge2Amount:
       type: number
     invoiceDate:
       type: string
     invoiceDueDate:
       type: string
     invoiceStatus:
       type: string
     paymentStatus:
       type: string
     currency:
       type: string       