swagger: "2.0"
info:
  version: "1.0.0"
  title: "Discount offer definitions yaml file"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
 DiscountOfferCollection:
  description: "Collection of Instrument Reference numbers for financing."
  type: "object"
  properties:
    data:
        type: array
        items:
          $ref: '#/definitions/DiscountOffer'
    paging:
      type: "object"
 DiscountOffer:
   description: "Finance Transaction Model"
   type: "object"
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
   properties:
      id:
        type: "string"
      seqNo:
        type: "integer"
        format: "int64"
      discountRuleId:
        type: "string"
      discountRuleDesc:
        type: "string"
      requestorPartyRole:
        type: "string"
      requestorParty:
        type: "string"
      relationshipCode:
        type: "string"
      counterpartyRole:
        type: "string"
      counterparty:
        type: "string"
      currency:
        type: "string"
      requestorPartyName:
        type: "string"
      counterPartyName:
        type: "string"
      effectiveDate:
        type: string
      expiryDate:
        type: string
      instrumentAmountFrom:
        type: "number"
      instrumentAmountTo:
        type: "number"
      discountType:
        type: string
      slidingScaleApplicable:
        type: string
      minTenor:
        type: "number"
      maxTenor:
        type: "number"
      discountRate:
        type: "number"
      makerDtStamp:
        type: "integer"
        format: "int64"
      makerId:
        type: "string"
      checkerDtStamp:
        type: "string"
      checkerId:
        type: "string"
      chgPrcTemplateId:
        type: "string"
      chgPrcId:
        type: "string"
      applicabilityBasis:
        type: "string"
      autoApplicable:
        type: "string"
      autoApplicabilityBasis:
        type: "string"
      earlyPaymentDate:
        type: "string"
      channel:
        type: "string"
      sourceTxnId:
        type: "string"
      discountOfferRangeDetail:
        type: array
        items:
          $ref: '#/definitions/DiscountOfferRangeDetail'
      invoiceRefNoList:
        type: array
        items:
          type: string
   required:
      - channel
      - discountRuleDesc
      - requestorPartyRole
      - requestorParty
      - counterparty
      - effectiveDate
      - expiryDate
      - discountType
 DiscountOfferRangeDetail:
   description: "Collection of Instrument Reference numbers for financing."
   type: "object"
   properties:
     discountRuleId:
       type: "string"
     remainingTenorFrom:
       type: "number"
     remainingTenorTo:
       type: "number"
     discountRate:
       type: "number"
     upperDiscountRateThreshold:
       type: "number"
     lowerDiscountRateThreshold:
       type: "number"
     slidingScaleApplicable:
       type: string
 DiscountOfferModelCollection:
  description: "Collection of Discount Offers"
  type: "object"
  properties:
    data:
        type: array
        items:
          $ref: '#/definitions/DiscountOfferServiceModel'
    status:
      description: Status
      type: string
    errorDescription:
      description: errorDescription
      type: string
    errorCode:
      description: errorCode
      type: string          
    paging:
      type: "object"
 DiscountOfferProcessedModel:
  description: "Discount Offer with processed values"
  type: "object"
  properties:
    discountOffer:
      $ref: '#/definitions/DiscountOfferServiceModel'
    discountPercentage:
      type: "number"
    discountAmount:
      type: "number"
    errors:
      type: "string"
 DiscountOfferServiceModel:
   description: "Finance Transaction Model"
   type: "object"
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
   properties:
      id:
        type: "string"
      seqNo:
        type: "integer"
        format: "int64"
      discountRuleId:
        type: "string"
      discountRuleDesc:
        type: "string"
      discountType:
        type: "string"          
      requestorPartyRole:
        type: "string"
      requestorParty:
        type: "string"
      relationshipCode:
        type: "string"
      counterpartyRole:
        type: "string"
      counterparty:
        type: "string"
      currency:
        type: "string"
      requestorPartyName:
        type: "string"
      counterPartyName:
        type: "string"
      effectiveDate:
        type: string
      expiryDate:
        type: string
      instrumentAmountFrom:
        type: "number"
      instrumentAmountTo:
        type: "number"
      discountOfferActiveStatus:
        type: string
      slidingScaleApplicable:
        type: string
      minTenor:
        type: "number"
      maxTenor:
        type: "number"
      discountRate:
        type: "number"
      makerDtStamp:
        type: string
        format: date       
        description: "Maker Dt Stamp" 
      makerId:
        type: "string"
      checkerDtStamp:
        type: string
        format: date       
        description: "Checker Dt Stamp" 
      checkerId:
        type: "string"
      chgPrcTemplateId:
        type: "string"
      chgPrcId:
        type: "string"
      applicabilityBasis:
        type: "string"
      autoApplicable:
        type: "string"
      autoApplicabilityBasis:
        type: "string"
      earlyPaymentDate:
        type: "string"
      action:
        type: "string"
      stageId:
        type: "string"
      sourceTxnId:
        type: "string"        
      discOfferRangeServiceModelList:
        type: array
        items:
          $ref: '#/definitions/DiscOfferRangeServiceModel'
 CmcTmChgPrcTmpltWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CmcTmChgPrcTmpltDTO"    
 CmcTmChgPrcTmpltDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     applicationCode:
      type: string
      description: "Application Code"
     annumBasis:
      type: string
      description: "Annum Basis"
     chgInTxnCcy:
      type: string
      description: "Charge In Transaction Currency Flag"
     chgPrcDesc:
      type: string
      description: "Price Method Description"
     chgPrcTemplateId:
      type: string
      description: "Price Rule Id"
     fixedAmt:
      type: number
      description: "Fixed Amount"
     fixedPct:
      type: number
      description: "Fixed Percentage"
     flatChg:
      type: string
      description: "Flat Charge Flag"
     maxChgAmount:
      type: number
      description: "Maximum Charge Amount"
     maxChgPct:
      type: number
      description: "Maximum Charge Percentage"
     minChgAmount:
      type: number
      description: "Minimum Charge Amount"
     minChgPct:
      type: number
      description: "Minimum Charge Percentage"
     minMaxValidationCriteria:
      type: string
      description: "Min-Max CHarge Criteria"
     prcCategory:
      type: string
      description: "Price Category"
     prcCategoryDesc:
      type: string
      description: "Price Category Description"
     rateCode:
      type: string
      description: "Rate Code Description"
     rateType:
      type: string
      description: "Rate Type Description"
     prcCcy:
      type: string
      description: "Price Rule Currency"
     prcMethod:
      type: string
      description: "Price Method"
     prcMethodDesc:
      type: string
      description: "Price Method Description"
     isSlidingScale:
      type: string
      description: "Sliding Scale Flag"
     category:
      type: string
      description: "Category"      
     CmcTmChgPrcTiersDTO:
      type: array
      items:
       $ref: '#/definitions/CmcTmChgPrcTiersDTO'
     txnControllerRefNo:
      type: string
      description: "Transaction COntroller Reference Number"
 CmcTmChgPrcTiersDTO:
  type: object
  properties:
     amount:
      type: number
      description: "Slab Amount"
     chgPrcTemplateId:
      type: string
      description: "Price Rule Id"
     fromSlab:
      type: number
      description: "Slab start limit"
     id:
      type: string
      description: "Id"
     pct:
      type: number
      description: "Slab Percentage"
     prcMasterId:
      type: string
      description: "Price rule master id"
     toSlab:
      type: number
      description: "Slab end limit"
     unit:
      type: number
      description: "Slab units"
     isSlidingScale:
      type: string
      description: "Sliding Scale Flag"
     upperThreshold:
      type: number
      description: "Upper threshold"
     lowerThreshold:
      type: number
      description: "Lower threshold"      
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 DiscOfferRangeServiceModel:
    description: discount detail
    type: object
    properties:
      id:
        type: string
      seqNo:
        type: number        
      discountRuleId:
        type: string
      remainingTenorFrom:
        type: number
      remainingTenorTo:
        type: number
      discountRate:
        type: number
      upperDiscountRateThreshold:
        type: number
      lowerDiscountRateThreshold:
        type: number
      discountMasterId:
        type: string
 ChgPrcTmplWebModel:
    description: ChgPrcTmplWebModel
    type: object
    properties:
      resourceId:
        description: resource id
        type: string
      resourceName:
        description: resource name
        type: string
      operationType:
        description: operation type
        type: string
      makerId:
        description: maker id
        type: string
      makerDateStamp:
        description: make date stamp
        type: string
        format: date-time
      checkerId:
        description: check id
        type: string
      checkerDateStamp:
        description: checker date stamp
        type: string
        format: date-time
      modNo:
        description: mod no
        type: integer
      recordStatus:
        description: record status flag
        type: string
      authStatus:
        description: auth status flag
        type: string
      onceAuth:
        description: once auth flag
        type: string
      doerRemarks:
        description: doer remarks
        type: string
      approverRemarks:
        description: approver  remarks
        type: string        
      cmcTmChgPrcTmplt:
        $ref: '#/definitions/CmcTmChgPrcTmpltDTO'    
      extendedDatasegments:
        description: data for the extended datasegment operation
        type: array
        items:
          type: object
    required:
        - resourceId
        - operationType    
 DiscountOfferTxnDto:
   description: DiscountOfferTxnDto
   type: object
   properties:
     discountRuleId:
       description: Discount Rule Id
       type: string
 DiscountOfferTxnResponse:
   description: Discount Offer Txn Response
   type: object
   properties:
     status:
       description: Status
       type: string
     errors:
       description: Errors
       type: string
 DiscountOfferResponseModel:
   description: Discount Offer Response for Service
   type: object
   properties:
     dynamicDiscRuleId:
       description: dynamicDiscRuleId
       type: string
     sourceTxnId:
       description: sourceTxnId
       type: string
     status:
       description: Status
       type: string
     errorDescription:
       description: errorDescription
       type: string
     errorCode:
       description: errorCode
       type: string
 DiscountOfferHistCollection:
  description: "Collection of Discount offer History."
  type: "object"
  properties:
    data:
        type: array
        items:
          $ref: '#/definitions/DiscountOfferHistModel'
    paging:
      type: "object"
 DiscountOfferHistModel:
   description: "Discount offer history Model"
   type: "object"
   properties:
      discountRuleId:
        type: "string"
      discountRuleDesc:
        type: "string"
      requestorPartyRole:
        type: "string"
      requestorPartyId:
        type: "string"
      discountType:
        type: string
      slidingScaleApplicable:
        type: string
      discountRate:
        type: "number"
      applicabilityBasis:
        type: "string"
      autoApplicable:
        type: "string"
      autoApplicabilityBasis:
        type: "string"
      earlyPaymentDate:
        type: "string"
      upperDiscountRateThreshold:
        type: "number"
      lowerDiscountRateThreshold:
        type: "number"
      discountOfferStatus:
        type: "string"
      discountOfferActiveStatus:
        type: "string"
      notionalEarlyPayAmt:
        type: "number"
      discountAmount:
        type: "number"
      paymentDate:
        type: "string"
 discOfferSearchModel:
   description: "Discount offer Search Model"
   type: "object"
   properties:
      discountRuleId:
        type: "string"
      discountRuleDesc:
        type: "string"
      discountType:
        type: "string"          
      requestorPartyRole:
        type: "string"
      requestorParty:
        type: "string"
      counterpartyRole:
        type: "string"
      counterparty:
        type: "string"
      effectiveDateFrom:
        type: string
      effectiveDateTo:
        type: string        
      expiryDateFrom:
        type: string
      expiryDateTo:
        type: string
      discountOfferActiveStatus:
        type: string
      applicabilityBasis:
        type: "string"
      autoApplicable:
        type: "string"
      autoApplicabilityBasis:
        type: "string"
      earlyPaymentDate:
        type: "string"
      offset:
        type: integer
      limit:
        type: integer                                