swagger: "2.0"
info:
  description: "obcfpm-project-services"
  version: "1.0.0"
  title: "obcfpm-project-services"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "obcfpmProject"
    description: "API for obcfpmProject Operations"
    
schemes:
- "https"

paths:
 /service/v1/project/createProject:
    post:
      tags:
        - "Project"
      summary: "API for creating a new Project  details."
      description: "API for creating a new Project  details."
      operationId: "createProject"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
        - name: "projectModel"
          in: "body"
          description: "Request Body that contains data required for creating a new project details."
          required: true
          schema:
            $ref: "#/definitions/ProjectModel"
      responses:
        201:
          description: "Returns the model of the newly created project  details"
          headers:
            Location:
              description: "URL of newly created project"
              type: "string"
          schema:
              $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
 /service/v1/project/{projectId}:
    get:
      tags:
        - "Project"
      summary: "Retrieves the existing Project  details."
      description:  "Retrieves the existing Project  details."
      operationId: "getProjectInfoByProjectIdOrAppId"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
        - name: "projectId"
          in: "path"
          required: true
          type: "string"
        - name: "applicationId"
          in: "query"
          required: false
          type: "string"
        - name: "isSummary"
          in: "query"
          required: false
          type: "string"
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
 /service/v1/project/update:
    put:
      tags:
        - "Project"
      summary: "Update an existing Project  details for the given Id."
      description:  "Update an existing Project  details for the given Id."
      operationId: "updateProject"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
        - name: "projectModel"
          in: "body"
          description: "Project  that need to be updated"
          required: true
          schema:
            $ref: "#/definitions/ProjectModel"
      responses:
        200:
          description: "Returns updated Project "
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
 /service/v1/project/submit/{projectId}/{applicationId}:
    post:
      tags:
        - "Project"
      summary: "submit the existing Project  details to Main Table"
      description:  "submit the existing Project  details to Main Table."
      operationId: "submitToMain"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
        - name: "projectId"
          in: "path"
          description: "Project Id for which the Project details has to be submited."
          required: true
          type: "string"
        - name: "applicationId"
          in: "path"
          description: "applicationId for which the Project details has to be submited."
          required: true
          type: "string"
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
 /service/v1/project/updateMainToHistoryReport/{projectId}/{applicationId}:
    post:
      tags:
        - "Project"
      summary: "update existing Project  details to Main Table"
      description:  "update updateMainToHistoryReport  Project  details ."
      operationId: "updateMainToHistoryReport"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
        - name: "projectId"
          in: "path"
          description: "Project Id for which the Project details has to be fetched."
          required: true
          type: "string"
        - name: "applicationId"
          in: "path"
          description: "application Id for which the Project details has to be fetched."
          required: true
          type: "string"
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
