#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : managementprofile.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/managementprofiles:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ManagementProfiles
      summary: Adds a new ManagementProfile.
      description: Adds a new ManagementProfile. Add additional information here for this endpoint.
      operationId: addManagementProfile
      parameters:
      - name: ManagementProfile
        in: body
        description: Request Body that contains data required for creating a new ManagementProfile
        required: true
        schema:
          $ref: '#/definitions/ManagementProfileModel'
      responses:
        201:
          description: Returns the Id of the newly created ManagementProfile
          headers:
            Location:
              description: URL of newly created ManagementProfile
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ManagementProfiles
      summary: Retrieves the list of  ManagementProfile.
      description: Retrieves the list of  ManagementProfile. Add additional information here for the this endpoint.
      operationId: getAllManagementProfile
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/managementprofiles/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ManagementProfiles
      summary: Get a  ManagementProfile.
      description: Update a  ManagementProfile. Add additional information here for the this endpoint.
      operationId: getManagementProfileById
      parameters:
      - name: id
        in: path
        description: id of the ManagementProfile that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated ManagementProfile
          schema:
            $ref: '#/definitions/ManagementProfileModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ManagementProfiles
      summary: Update an  ManagementProfile.
      description: Update an  ManagementProfile. Add additional information here for the this endpoint.
      operationId: updateManagementProfile
      parameters:
      - name: id
        in: path
        description: id of the ManagementProfile that need to be updated
        required: true
        type: string
      - name: ManagementProfile
        in: body
        description: Request Body that contains data required for updating an  ManagementProfile
        required: true
        schema:
          $ref: '#/definitions/ManagementProfileModel'
      responses:
        200:
          description: Returns updated ManagementProfile
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ManagementProfiles
      summary: Deletes the A ManagementProfileidentified by given ID.
      description: Deletes the ManagementProfile identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteManagementProfile
      parameters:
      - name: id
        in: path
        description: Id of the ManagementProfile that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ManagementProfileModel:
   description: ManagementProfile model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      directors:
        description: Directors of the ManagementProfile
        type: array
        items:
          $ref: '#/definitions/DirectorModel'
      managementProfileDocument:
        description: managementProfileDocument of the AutomotiveInfoDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  ManagementProfileCollection:
    description: Collection of ManagementProfile.
    type: object
    properties:
      ManagementProfileList:
        type: array
        items:
          $ref: '#/definitions/ManagementProfileModel'
  DirectorModel:
    description: Director model
    type: object
    properties:
      id:
        description: Id of the Director model
        type: string
        maxLength: 36
      managementProfileId:
        description: DirectorId of the Director model
        type: string
        maxLength: 36
      addressLine1:
        description: AddressLine1 of the Director model
        type: string
        minLength: 0
        maxLength: 105
      addressLine2:
        description: AddressLine2 of the Director model
        type: string
        minLength: 0
        maxLength: 105
      addressLine3:
        description: AddressLine3 of the Director model
        type: string
        minLength: 0
        maxLength: 105
      addressLineD1:
        description: AddressLineD1 of the Director model
        type: string
      addressLineD2:
        description: AddressLineD2 of the Director model
        type: string
      addressLineD3:
        description: AddressLineD3 of the Director model
        type: string
      city:
        description: city of the Director model
        type: string
        minLength: 0
        maxLength: 22
      cityD:
        description: cityD of the Director model
        type: string
        minLength: 0
        maxLength: 22
      country:
        description: country of the Director model
        type: string
        maxLength: 3
      countryD:
        description: countryD of the Director model
        type: string
        maxLength: 3
      directorName:
        description: directorName of the Director model
        type: string
        maxLength: 35
      email:
        description: email of the Director model
        type: string
        minLength: 0
        maxLength: 60
      emailD:
        description: email of the Director model
        type: string
        minLength: 0
        maxLength: 60
      holdingPercentage:
        description: HoldingPercentage of the Director model
        type: integer
        format: int64
        minimum: 0
        maximum: 100
      mobileNumber:
        description: MobileNumber of the Director model
        type: string
        maxLength: 16
      nationality:
        description: Nationality of the Director model
        type: string
        minLength: 0
        maxLength: 16
      taxIdentificationNumber:
        description: TaxIdentificationNumber of the Director model
        type: string
        minLength: 0
        maxLength: 20
      telephoneNumber:
        description: TelephoneNumber of the Director model
        type: string
        maxLength: 16
      telephoneNumberD:
        description: TelephoneNumber of the Director model
        type: string
        maxLength: 16
      zipCode:
        description: ZipCode of the Director model
        type: string
        maxLength: 8
      zipCodeD:
        description: ZipCodeD of the Director model
        type: string
        maxLength: 8
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type  