#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : oblm
#  ** 
#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
#
#  CHANGE HISTORY
#
#  Created By         :  Ketki
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server InterestAccrual server." 
 version: "1.0.0"
 title: "Interest Accrual report Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "interest accrual report"
   description: "Interest Accrual report creation and retrieving"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../interestaccrualreport

 /interestaccrualreport/generateReport:     
  post:
   tags:
    - "interestaccrualreport"
   summary: "Get all valid interestaccrualreport."
   description:  "Get all valid interestaccrualreport. This endpoints will be used to Get all valid interestaccrual maintenance records."
   operationId: "generateInterestAccrualReport"
   parameters:
     - name: InterestAccrualReportInputDTO
       in: "body"
       description: "Request Body that contains data required for creating a new oblm-report-services" 
       required: true
       schema:
         $ref: "#/definitions/InterestAccrualReportInputDTO"   
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/InterestAccrualReportDTOCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"




definitions:
 InterestAccrualDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     structureId:
      type: string
      description: ""
     accountNumber:
      type: string
      description: ""
     accountCurrency:
      type: string
      description: ""
     drcr:
      type: string
      description: ""
     interest:
      type: number
      description: ""
     entryDate:
      type: string
      #format: date
      description: ""  
     cashCCMethod:
      type: string
      description: ""
     
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 InterestAccrualReportInputDTO:
  type: "object"
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     customerId:
      type: string
     structureId:
      type: string
     accountType:
      type: string
     accountNumber:
      type: string
     versionNo:
      type: integer
     fromDate:
      type: string
      format: date
     toDate:
      description: To Date of Exceptions
      type: string
      format: date
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 InterestAccrualReportDTOCollection: 
  description: "Collection of InterestAccrual."
  type: "object"
  properties:
   data:
    $ref: "#/definitions/ReportResponse"
   messages:
    $ref: "#/definitions/ResponseDto"
 UserInformationDTO:
   type: object
   properties: 
      userId:
       type: string
       description: Generated By user id
      dateAndTime:
       type: string
       description: Generated At time   
 InterestAccrualDTOCollection: 
  description: "Collection of entries."
  type: "object"
  properties:
   userInfo:
     type: object
     items:
      $ref: "#/definitions/UserInformationDTO"
   data:
    type: "array"
    items:
     $ref: "#/definitions/InterestAccrualDTO"
   messages:
    $ref: "#/definitions/ResponseDto"  
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 InterestAccrualWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/InterestAccrualDTO"
