#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : oblm
#  ** 
#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
#
#  CHANGE HISTORY
#
#  Created By         :  Ketki
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server structurereport server." 
 version: "1.0.0"
 title: "structure contribution report Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "structure contribution report"
   description: "Structure contribution report creation and retrieving"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../structurecontributionreport
 /structurecontributionreport/generateReport:     
  post:
   tags:
    - "structurecontributionreport"
   summary: "Get all valid structurecontributionreport."
   description:  "Get all valid structurecontributionreport. This endpoints will be used to Get all valid structurecontributionreport maintenance records."
   operationId: "generateStructureContributionreport"
   parameters:
     - name: StructureContributionReportInputDTO
       in: "body"
       description: "Request Body that contains data required for creating a new oblm-report-services" 
       required: true
       schema:
         $ref: "#/definitions/StructureContributionReportInputDTO"   
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/StructureMasterReportDTOCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
 /structurecontributionreport/save:
  post:
   tags:
    - "structurecontributionreport"
   summary: "Adds a new structurecontributionreport."
   description: "Adds a new structurecontributionreport. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "structurecontributionreport" 
      in: "body" 
      description: "Request Body that contains data required for creating a new structurecontributionreport" 
      required: true
      schema:
       $ref: "#/definitions/ReportContributionDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created structurecontributionreport" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
     
definitions:
  StructureMasterheaderDTO:
   type: object
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:
      liquidityType:
       type: string
       description: ""
      participatingAccount:
       type: number
       description: ""
      numberOfSweepPool:
       type: number
       description: ""
      structureTurnover:
       type: number
       description: ""      
  StructureMasterbodyDTO:
   type: object
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:  
      structureId:
       type: string
       description: ""
      structureDescription:
       type: string
       description: "" 
      effectiveDate:
       type: string
       #format: date
       description: ""
      endDate:
       type: string
       #format: date
       description: ""
      versionNo:
       type: number
       description: ""
      liquidityType:
       type: string
       description: ""
      structureDomain:
       type: string
       description: ""
      isMultiBank:
       type: string
       description: ""
      isCrossCurrency:
       type: string
       description: ""
      structureStatus:
       type: string
       description: ""
      participatingAccountCount:
       type: number
       description: ""
      numberOfSweepPool:
       type: number
       description: ""
      headerAccountNumber:
       type: string
       description: ""
      headerAccountDescription:
       type: string
       description: ""                
      headerAccountCurrency:
       type: string
       description: ""
      structureTurnover:
       type: number
       description: ""       
  StructureDetailsDTO:
   type: object
   properties:
     customerId:
       type: string 
     sweepPoolId:
      type: string
      description: ""
     liquidityType:
      type: string
      description: "" 
     childAccountNumber:
      type: string
      description: ""
     childAccountDescription:
      type: string
      description: ""
     childBranchCode:
      type: string
      description: ""              
     childBranchName:
      type: string
      description: ""
     childCurrencyCode:
      type: string
      description: ""
     sweepPoolContribution:
      type: number
      description: ""
     parentAccountNumber:
      type: string
      description: ''
     parentAccountDescription:
      type: string
      description: ''
     parentBranchCode:
      type: string
      description: ''
     parentBranchName:
      type: string
      description: ''
     parentCurrencyCode:
      type: string
      description: ''
     sweepOrPoolContribution:
      type: number
      description: ""                                           
     valueDate:
      type: string
      #format: date
      description: ""
     fxRate:
      type: number
      description: "" 
  ModListKeyDto:
   type: object
   properties:
    modNos:
     type: array
     items:
      type: integer
    remarks:
     type: string
  KeyDto:
   type: object
   properties:
    modNo:
     type: integer
    remarks:
     type: string
  ResponseDto:
   type: object
   properties:
    id:
     type: string
    status:
     type: string
    codes:
     type: array
     items:
      $ref: "#/definitions/ResponseCode"
    requestId:
     type: string
  StructureContributionReportInputDTO:
   type: "object"
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:
      customerId:
       type: string
      structureId:
       type: string
      liquidityType:
       type: string 
      fromDate:
       type: string
       format: date
      toDate:
       description: To Date of Exceptions
       type: string
       format: date
  UserInformationDTO:
   type: object
   properties: 
      userId:
       type: string
       description: Generated By user id
      dateAndTime:
       type: string
       description: Generated At time
  ReportContributionDTO:
   type: object
   properties:
    LmrTbContributionDTO:
     type: "array"
     items:    
      $ref: "#/definitions/LmrTbContributionDTO"   
  LmrTbContributionDTO:
    type: object
    allOf:
    - $ref: '#/definitions/GenericDto'
    - type: object
      properties:
        executionId:
          type: string
          description: ''
        structureId:
          type: string
          description: ''
        toAccountNumber:
          type: string
          description: ''
        toAccountBranch:
          type: string
          description: ''
        toAccountCurrency:
          type: string
          description: ''
        fromAccountNumber:
          type: string
          description: ''
        fromAccountBranch:
          type: string
          description: ''
        fromAccountCurrency:
          type: string
          description: ''
        contributionAmount:
          type: number
          description: ''
        fromCurrencyAmount:
          type: number
          description: ''
        valueDate:
          type: string
          format: date
          description: ''
        fxrate:
          type: number
          description: ''
        status:
          type: string
          description: ''
        modNumber:
          type: string
          description: ''            
  ResponseCode:
   type: object
   properties:
    Code:
     type: string
    Desc:
     type: string
    Type:
     type: string
    Language:
     type: string
    args:
     type: array
     items:
      type: object
    arg:
     type: string
  GenericDto:
   allOf:
    - type: object
      discriminator: resource_type
  StructureMasterReportDTOCollection: 
   description: "Collection of structuredummy."
   type: "object"
   properties:
    messages:
     $ref: "#/definitions/ResponseDto"
    data:
     $ref: "#/definitions/ReportResponse" 
  StructureMasterDTOCollection: 
   description: "Collection of entries."
   type: "object"
   properties:
    userInfo:
     type: object
     items:
      $ref: "#/definitions/UserInformationDTO"
    datahead:
     type: "array"
     items:
      $ref: "#/definitions/StructureMasterheaderDTO"
    datadetails:
     type: "array"
     items:
      $ref: "#/definitions/StructureDetailsDTO"  
    data:
     type: "array"
     items:
      $ref: "#/definitions/StructureMasterbodyDTO"     
    messages:
     $ref: "#/definitions/ResponseDto"  
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer
  ResponseDtoWrapper:
   type: object
   properties:
    messages:
     $ref: "#/definitions/ResponseDto"
    data:
     $ref: "#/definitions/ResponseResourceSupport"
  ResponseResourceSupport:
   type: object
  StructureMasterWrapperDTO:
   type: object
   properties:
    data:
     $ref: "#/definitions/StructureMasterbodyDTO"
