#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : oblm
#  ** 
#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
#
#  CHANGE HISTORY
#
#  Created By         :  Ketki
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server structurereport server." 
 version: "1.0.0"
 title: "structure details report Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "structure details report"
   description: "Structure details report creation and retrieving"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../structuredetailsreport
 /structuredetailsreport/generateReport:     
  post:
   tags:
    - "structuredetailsreport"
   summary: "Get all valid structuredetailsreport."
   description:  "Get all valid structuredetailsreport. This endpoints will be used to Get all valid structuredetailsreport maintenance records."
   operationId: "generateStructureDetailsreport"
   parameters:
     - name: StructureDetailsReportInputDTO
       in: "body"
       description: "Request Body that contains data required for creating a new oblm-report-services" 
       required: true
       schema:
         $ref: "#/definitions/StructureDetailsReportInputDTO"     
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/StructureMasterReportDTOCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
 /structuredetailsreport/save:
  post:
   tags:
    - "structuredetailsreport"
   summary: "Adds a new structuredetailsreport."
   description: "Adds a new structuredetailsreport. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "structuredetailsreport" 
      in: "body" 
      description: "Request Body that contains data required for creating a new structuredetailsreport" 
      required: true
      schema:
       $ref: "#/definitions/StructureMasterbodyDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for creating a new structuredetailsreport" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created structuredetailsreport" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
     
definitions:
  StructureMasterheaderDTO:
   type: object
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:
      liquidityType:
       type: string
       description: ""
      participatingAccount:
       type: number
       description: ""
      newlyCreatedStructures:
       type: string
       description: ""
      totalStructure:
       type: string
       description: ""
      amendedStructure:
       type: string
       description: ""        
  StructureMasterbodyDTO:
   type: object
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:  
      customerId:
       type: string
       description: ""
      effectiveDate:
       type: string
       #format: date
       description: ""
      endDate:
       type: string
       #format: date
       description: ""
      headerAccountCurrency:
       type: string
       description: ""
      headerBranchCode:
       type: string
       description: ""
      headerAccountDescription:
       type: string
       description: ""
      headerAccountNumber:
       type: string
       description: ""
      headerBranchName:
       type: string
       description: ""
      structureType:
       type: string
       description: ""  
      isCrossBorder:
       type: string
       description: ""
      isCrossCurrency:
       type: string
       description: ""
      isMultiBank:
       type: string
       description: ""
      reallocationMethod:
       type: string
       description: ""
      interestMethod:
       type: string
       description: "" 
      participatingAccountCount:
       type: number
       description: ""
      structureStatus:
       type: string
       description: ""
      versionNo:
       type: number
       description: ""
      modNumber:
       type: number
       description: '' 
      structureDomain:
       type: string
       description: ""
      structureDescription:
       type: string
       description: ""
      newlyCreated:
       type: string
       description: ""
      amendedStr:
       type: string
       description: ""
      totalAmend:
       type: string
       description: ""   
      structureId:
       type: string
       description: ""
      checkerDtStamp:
       type: string
       description: ""
       #format: date 
      liquidityType:
       type: string
       description: ""  
  StructureDetailsDTO:
   type: object
   properties:
     branchName:
      type: string
      description: ""
     versionNo:
      type: number
      description: ""
     customerId:
      type: string
      description: "" 
     structureId:
      type: string
      description: ""
     structureDescription:
      type: string
      description: ""  
     currencyCode:
      type: string
      description: ""
     liquidityType:
      type: string
      description: "" 
     branchCode:
      type: string
      description: "" 
     id:
      type: string
      description: ""
     reallocationMethod:
      type: string
      description: ""
     accountDescription:
      type: string
      description: ""
     accountNumber:
      type: string
      description: "" 
     parentAccountDescription:
      type: string
      description: ''
     parentAccountNumber:
      type: string
      description: ''
     parentBranchCode:
      type: string
      description: ''
     parentBranchName:
      type: string
      description: ''
     parentCurrencyCode:
      type: string
      description: '' 
     structureMasterId:
      type: string
      description: ""
     branchExtRef:
      type: string
      description: ""
     sweepConcentrationMethod:
      type: string
      description: ""
     twoWaySweep:
      type: string
      description: ""
     revFreq:
      type: string
      description: ""
     accPriority:
      type: string
      description: ""
     sweepFreq:
      type: string
      description: "" 
     interestMethod:
      type: string
      description: ""
     custExtRef:
      type: string
      description: ""
  ModListKeyDto:
   type: object
   properties:
    modNos:
     type: array
     items:
      type: integer
    remarks:
     type: string
  KeyDto:
   type: object
   properties:
    modNo:
     type: integer
    remarks:
     type: string
  ResponseDto:
   type: object
   properties:
    id:
     type: string
    status:
     type: string
    codes:
     type: array
     items:
      $ref: "#/definitions/ResponseCode"
    requestId:
     type: string
  StructureDetailsReportInputDTO:
   type: "object"
   allOf:
   - $ref: '#/definitions/GenericDto'
   - type: object
     properties:
      customerId:
       type: string
      structureId:
       type: string
      liquidityType:
       type: string 
      fromDate:
       type: string
       format: date
      toDate:
       description: To Date of Exceptions
       type: string
       format: date
  UserInformationDTO:
   type: object
   properties: 
      userId:
       type: string
       description: Generated By user id
      dateAndTime:
       type: string
       description: Generated At time       
  ResponseCode:
   type: object
   properties:
    Code:
     type: string
    Desc:
     type: string
    Type:
     type: string
    Language:
     type: string
    args:
     type: array
     items:
      type: object
    arg:
     type: string
#  BindingResult:
#   type: object
  GenericDto:
   allOf:
    - type: object
      discriminator: resource_type
  StructureMasterReportDTOCollection: 
   description: "Collection of structuredummy."
   type: "object"
   properties:
    messages:
     $ref: "#/definitions/ResponseDto"
    data:
     $ref: "#/definitions/ReportResponse" 
  StructureMasterDTOCollection: 
   description: "Collection of entries."
   type: "object"
   properties:
    userInfo:
     type: object
     items:
      $ref: "#/definitions/UserInformationDTO"   
    datahead:
     type: "array"
     items:
      $ref: "#/definitions/StructureMasterheaderDTO"
    datadetails:
     type: "array"
     items:
      $ref: "#/definitions/StructureDetailsDTO"  
    data:
     type: "array"
     items:
      $ref: "#/definitions/StructureMasterbodyDTO"     
    messages:
     $ref: "#/definitions/ResponseDto"  
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer
  ResponseDtoWrapper:
   type: object
   properties:
    messages:
     $ref: "#/definitions/ResponseDto"
    data:
     $ref: "#/definitions/ResponseResourceSupport"
  ResponseResourceSupport:
   type: object
  StructureMasterWrapperDTO:
   type: object
   properties:
    data:
     $ref: "#/definitions/StructureMasterbodyDTO"
