#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : creditappraisal.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/creditappraisals:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditAppraisal
      summary: Adds a new CreditAppraisal.
      description: Adds a new CreditAppraisal. Add additional information here for this endpoint.
      operationId: addCreditAppraisal
      parameters:
      - name: CreditAppraisal
        in: body
        description: Request Body that contains data required for creating a new CreditAppraisal
        required: true
        schema:
          $ref: '#/definitions/CreditAppraisalModel'
      responses:
        201:
          description: Returns the Id of the newly created CreditAppraisal
          headers:
            Location:
              description: URL of newly created CreditAppraisal
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditAppraisal
      summary: Retrieves the list of  CreditAppraisal.
      description: Retrieves the list of  CreditAppraisal. Add additional information here for the this endpoint.
      operationId: getAllCreditAppraisal
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/creditappraisals/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditAppraisal
      summary: Get a  CreditAppraisal.
      description: Update a  CreditAppraisal. Add additional information here for the this endpoint.
      operationId: getCreditAppraisalById
      parameters:
      - name: id
        in: path
        description: id of the CreditAppraisal that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated CreditAppraisal
          schema:
            $ref: '#/definitions/CreditAppraisalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditAppraisal
      summary: Update an  CreditAppraisal.
      description: Update an  CreditAppraisal. Add additional information here for the this endpoint.
      operationId: updateCreditAppraisal
      parameters:
      - name: id
        in: path
        description: id of the CreditAppraisal that need to be updated
        required: true
        type: string
      - name: RestructuringEntryDetails
        in: body
        description: Request Body that contains data required for updating an  CreditAppraisal
        required: true
        schema:
          $ref: '#/definitions/CreditAppraisalModel'
      responses:
        200:
          description: Returns updated CreditAppraisal
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditAppraisal
      summary: Deletes the A CreditAppraisal identified by given ID.
      description: Deletes the CreditAppraisal identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCreditAppraisal
      parameters:
      - name: id
        in: path
        description: Id of the CreditAppraisal that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  CreditAppraisalModel:
   description: CreditAppraisalModel model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     required:
     - applicationNumber
     - approvalStatus
     properties:
      applicationDate:
        description: applicationDate
        type: string
      customerId:
        description: customerId
        type: string
        maxLength: 36
      liabilityId:
        description: liabilityId
        type: string
        maxLength: 36
      purposeOfCreditApproval:
        description: purposeOfCreditApproval
        type: string
        minLength: 0
        maxLength: 300
      approvalStatus:
        description: approvalStatus
        type: string
        minLength: 0
        maxLength: 12
      creditAppraisalDocument:
        description: creditAppraisalDocument of the creditAppraisal
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel' 
 
  CreditAppraisalCollection:
    description: Collection of CreditAppraisal.
    type: object
    properties:
      creditAprraisalList:
        type: array
        items:
          $ref: '#/definitions/CreditAppraisalModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type