#  This source is part of the Oracle Banking Software Product. 
#  Copyright  2020 , 2020 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : StructuredAddressServiceVA.yaml
#  **
#  ** Module     : cmc
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: This service is used to maintain structured address for Real Account .
 version: "1.0.0"
 title: "StructuredAddressRA Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "structuredaddressserviceservice"
   description: "This service is used to maintain structured address for Real Account ."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../structuredaddressservice

 /service/structuredaddressservice:
  post:
   tags:
    - "structuredaddressservice"
   summary: "Adds a new structuredaddressservice."
   description: "Adds a new structuredaddressservice. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "structuredaddressservice" 
      in: "body" 
      description: "Request Body that contains data required for creating a new structuredaddressservice" 
      required: true
      schema:
       $ref: "#/definitions/StructuredAddressServiceSaveDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created structuredaddressservice" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoServiceWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "structuredaddressservice"
   summary: "Get all valid structuredaddressservice."
   description:  "Get all valid structuredaddressservice. This endpoints will be used to Get all valid structuredaddressservice maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: townName
     required: false
     type: string
   - in: query
     name: strrCountry
     required: false
     type: string
   - in: query
     name: authStat
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   - in: query
     name: onceAuth
     required: false
     type: string
   - in: query
     name: modNo
     required: false
     type: integer
   - in: query
     name: checkerId
     required: false
     type: string
   - in: query
     name: makerId
     required: false
     type: string
   - in: query
     name: postcode
     required: false
     type: string
   - in: query
     name: virtualAccountNo
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/StructuredAddressServiceCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../structuredaddressservice/xxx
#   DELETE    .../structuredaddressservice/xxx
#   GET       .../structuredaddressservice/xxx
#   GET       .../structuredaddressservice/xxx?version=latestrecord
#   GET       .../structuredaddressservice/xxx?version=1

 /service/structuredaddressservice/{virtualAccountNo}:
  put:
   tags:
    - "structuredaddressservice"
   summary: "Update an existing structuredaddressservice."
   description:  "Update an existing structuredaddressservice."
   operationId: "modifyRecord"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
    - name: "structuredaddressservice"
      in: "body"
      description: "Request Body that contains data required for updating an existing structuredaddressservice"
      required: true
      schema:
       $ref: "#/definitions/StructuredAddressServiceSaveDTO"
   responses:
    200:
     description: "Returns updated structuredaddressservice"
     schema:
      $ref: "#/definitions/ResponseDtoServiceWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "structuredaddressservice"
   summary: "Retrieves the structuredaddressservice by ID."
   description:  "Retrieves the structuredaddressservice by ID."
   operationId: "getByNaturalKey"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the structuredaddressservice based on given id."
     schema:
      $ref: "#/definitions/StructuredAddressServiceWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../structuredaddressservice/xxx/close
 /service/structuredaddressservice/{virtualAccountNo}/close:
  patch:
   tags:
    - "structuredaddressservice"
   summary: "Close the structuredaddressservice by given ID."
   description:  "Close the structuredaddressservice identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
    - name: "strAddressCloseReopenDTO"
      in: "body"
      description: Request body contain structuredaddressservice and Modification no of structuredaddressservice maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/StrAddressCloseReopenDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoServiceWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../structuredaddressservice/xxx/reopen

 /service/structuredaddressservice/{virtualAccountNo}/reopen:
  patch:
   tags:
    - "structuredaddressservice"
   summary: "reopen the structuredaddressservice by given ID."
   description:  "reopen the structuredaddressservice identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
    - name: "strAddressCloseReopenDTO"
      in: "body"
      description: Request body contain structuredaddressservice and Modification no of structuredaddressservice maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/StrAddressCloseReopenDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoServiceWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 StructuredAddressServiceSaveDTO:
  type: object
  allOf:
  - type: object
    properties:
     department:
      type: string
      description: "Department"
      maxLength: 70
     subDepartment:
      type: string
      description: "Sub Department"
      maxLength: 70      
     streetName:
      type: string
      description: "Street Name"
      maxLength: 70
     buildingNumber:
      type: string
      description: "Building Number"
      maxLength: 16
     buildingName:
      type: string
      description: "building Name"
      maxLength: 35
     floor:
      type: string
      description: "Floor"
      maxLength: 70
     postbox:
      type: string
      description: "postbox"
      maxLength: 16
     room:
      type: string
      description: "Room"
      maxLength: 70
     postcode:
      type: string
      description: "postcode"
      maxLength: 16
     townName:
      type: string
      description: "Town Name"
      maxLength: 35
     townLocationName:
      type: string
      description: "Town Location Name"
      maxLength: 35
     districtName:
      type: string
      description: "District name"
      maxLength: 35
     countrySubDivision:
      type: string
      description: "Country Sub Division"
      maxLength: 35
     strrCountry:
      type: string
      description: "country"
      maxLength: 2
     virtualAccountNo:
      type: string
      description: "Account number of the External customer"
      minLength: 1
      maxLength: 35
    required:
     - virtualAccountNo
     - strrCountry
     - postcode
     - townName
 StructuredAddressServiceDTO:
  type: object
  allOf:
  - type: object
    properties:
     department:
      type: string
      description: "Department"
      maxLength: 70
     subDepartment:
      type: string
      description: "Sub Department"
      maxLength: 70      
     streetName:
      type: string
      description: "Street Name"
      maxLength: 70
     buildingNumber:
      type: string
      description: "Building Number"
      maxLength: 16
     buildingName:
      type: string
      description: "building Name"
      maxLength: 35
     floor:
      type: string
      description: "Floor"
      maxLength: 70
     postbox:
      type: string
      description: "postbox"
      maxLength: 16
     room:
      type: string
      description: "Room"
      maxLength: 70
     postcode:
      type: string
      description: "postcode"
      maxLength: 16
     townName:
      type: string
      description: "Town Name"
      maxLength: 35
     townLocationName:
      type: string
      description: "Town Location Name"
      maxLength: 35
     districtName:
      type: string
      description: "District name"
      maxLength: 35
     countrySubDivision:
      type: string
      description: "Country Sub Division"
      maxLength: 35
     strrCountry:
      type: string
      description: "country"
      maxLength: 2
     virtualAccountNo:
      type: string
      description: "Account number of the External customer"
      minLength: 1
      maxLength: 35
     makerId:
      type: string
      description: "Maker ID of Virtual Account"
     makerDateStamp:
      type: string
      description: "Date and Time when Virtual Account is created or modified or closed or reopened"
     checkerId:
      type: string
      description: "Checker ID of Virtual Account"
     checkerDateStamp:
      type: string
      description: "Date and Time when some action on Virtual Account is authorized"
     modNo:
      type: integer
      description: "Version number of Virtual Account"
     recordStatus: 
      type: string
      description: "Record Status of Virtual Account"
     authStatus:
      type: string
      description: "Authorization Status of Virtual Account"
     onceAuth:
      type: string
      description: "Flag that indicated if Virtual Account is authorized once or not"
     doerRemarks:
      type: string
      description: "Remarks made by Maker"
     approverRemarks:
      type: string 
      description: "Remarks made by Approver"  
 StrAddressCloseReopenDTO:
  type: object
  properties:
   remarks:
    type: string
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 StructuredAddrResponseDto:
  type: object
  properties:
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/StructuredAddrResponseCode"
 StructuredAddrResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
# NKValuesDto:
#  type: object
#  properties:
#   id:
#    type: string
#   modNo:
#    type: integer
#   wrapper:
#     $ref: "#/definitions/ResponseDto" 
 StructuredAddressServiceCollection: 
  description: "Collection of StructuredAddress."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/StructuredAddressServiceDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoServiceWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/StructuredAddrResponseDto"
   data:
    $ref: "#/definitions/StructuredAddressServiceDTO"
 StructuredAddressServiceWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/StructuredAddressServiceDTO"