swagger: "2.0"
info:
  description: "This yaml contains all the TD model which is part of Term Deposit domain and needs to be shared across services"
  version: "1.0.0"
  title: ""
basePath: "/td"
tags:
- name: "TdWeb"
schemes:
- "http"
paths:
 /td/:
  get:
   tags:
   - "TdWeb"
   operationId: "td"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"
definitions:
 TdTopUpModel:
  type: object
  description: "Term deposit account details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
        type: string
        description: ""    
     recordId:
       type: string
     branchCode:
       type: string
       description: ""       
     interestAmount:
       type: number
       description: ""
     interestRate:
      type: number
      description: ""       
     maturityRate:
      type: number
      description: ""
     maturityAmount:
      type: number
      description: ""
     narrative:
      type: string
      description: ""
     topUpRefNo:
      type: string
      description: ""
     principalAmount:
      type: number
      description: ""
     sourceRefNo:
      type: string
      description: ""  
     tdAcNo:
      type: string
      description: ""
     offAccount:
      type: string
      description: ""
     offBrn:
      type: string
      description: ""
     tenorDays:
      type: number
      description: ""
     tenorMonths:
      type: number
      description: ""
     tenorYears:
      type: number
      description: ""      
     topupAmt:
      type: number
      description: ""
     tdCcy:
      type: string
      description: ""
     offsetAccount:
      type: string
     offsetAccountBrn:
      type: string
     offsetAccountAmt:
      type: number
     offsetAccountCcy:
      type: string
     valueDt:
       type: string
       format: date
       description: ""
     demDtls:
       type: array
       items:
        $ref: '#/definitions/DenomTxnDtlsModel'
     totalPrincipalAmount:
      type: number  
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"

 CusTdSimulateModel:
  type: object
  description: "Term deposit payout details"
  allOf:
  - type: object
    properties:
     cusTdAcc:
       $ref: '#/definitions/CusTDAcc'
     cusTdAccProdData:
       type: array
       items:
        $ref: '#/definitions/CusTdAccProdData'

 CusTdAccProd:
  type: object
  description: "Term deposit payout details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     cusTdAccProdData:
       type: array
       items:
        $ref: '#/definitions/CusTdAccProdData'
       
 CusTdAccProdData:
  type: object
  description: "Term deposit payout details"
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     prod:
       type: string
     waive:
       type: string
     record_stat:
       type: string
     cont_var_roll:
       type: string
     cusTdAccProdEffDateData:
       type: array
       items:
        $ref: '#/definitions/CusTdAccProdEffDate'
       
 CusTdAccProdEffDate:
  type: object
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     udeEffDate:
       type: string
       format: date
     recordStat:
       type: string
     cusTdAccProdUdeValData:
       type: array
       items:
        $ref: '#/definitions/CusTdAccProdUdeVal'
       
 CusTdAccProdUdeVal:
  type: object
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     udeId:
       type: string
     udeValue:
       type: number
     rateCode:
       type: string
     tdRateCode:
       type: string
     udeVariance:
       type: number

 CusTdPayout:
  type: object
  description: "Term deposit payout details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     CusTdPayoutData:
       $ref: '#/definitions/CusTdPayoutData'
 
 CusTdPayoutData:
  type: object
  description: "Term deposit payout details"
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     branchCode:
       type: string
       description: ""
     tdAcNo:
       type: string
       description: ""
     payouttype:
       type: string
       description: ""
     offsetBrn:
      type: string
      description: ""
     offsetAcc:
      type: string
      description: ""
     benfName:
      type: string
      description: ""
     benfAdd1:
      type: string
      description: ""
     benfAdd2:
      type: string
      description: ""
     benfAdd3:
      type: string
      description: ""
     benfAdd4:
      type: string
      description: ""
      
 CusTdAccRollover:
  type: object
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     CusTdAccRolloverData:
       $ref: '#/definitions/CusTdAccRolloverData'
      
 CusTdAccRolloverData:
  type: object
  description: "Term deposit account roll over details"
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     branchCode:
       type: string
       description: ""
     tdAcNo:
       type: string
       description: ""
     rolloverOpt:
      type: string
     rolloverType:
      type: string
      description: ""
     rolloverAmt:
      type: number
      description: ""
     rollTenorDays:
      type: number
      description: ""
     rollTenorMonths:
      type: number
      description: ""
     rollTenorYears:
      type: number
     rolloverCcy:
      type: string
      
 CusTdAccLinked:
  type: object
  description: "Term deposit account linked details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     CusTdAccLinkedData:
       type: array
       items:
        $ref: '#/definitions/CusTdAccLinkedData'
 CusTdAccLinkedData:
  type: object
  description: "Term deposit account linked details"
  allOf:
  - type: object
    properties:
     id:
       type: string
     parentId:
       type: string
     branchCode:
       type: string
       description: ""
     tdAcNo:
       type: string
       description: ""
     customerId:
       type: string
       description: ""
     relationship:
      type: string
      description: ""
     jointHolderType:
      type: string
      description: ""
     startDate:
      type: string
      format: date
      description: ""
     endDate:
      type: string
      format: date
      description: ""
      
 CusTDAcc:
  type: object
  description: "Term deposit account details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
        type: string
        description: ""
     recordId:
       type: string
       description: ""
     branchCode:
       type: string
       description: ""
     tdAcNo:
       type: string
       description: ""
     tdAcDesc:
       type: string
       description: ""
     acOpenDate:
       type: string
       format: date
       description: ""
     txnRefNumber:
       type: string
       description: ""
     accountType:
       type: string
       description: ""
     operationMode:
       type: string
       description: ""
     customerId:
      type: string
      description: ""
     accountClass:
      type: string
      description: ""
     tdAmt:
       type: number
     tdCcy:
       type: string
     intrestRate:
      type: number
     tenorDays:
      type: number
     tenorMonths:
      type: number
     tenorYears:
      type: number
     autoRollover:
       type: string
     maturityAmt:
       type: number
     recordStat:
      type: string
      description: ""
     authStat:
      type: string
      description: ""
     modNo:
      type: string
      description: ""
     makerId:
      type: string
      description: ""
     makerDtStamp:
      type: string
      format: date
      description: ""
     checkerId:
      type: string
      description: ""
     checkerDtStamp:
      type: string
      format: date
      description: ""
     onceAuth:
      type: string
      description: ""
     source:
      type: string
      description: ""
     sourceRefNo:
      type: string
      description: ""
     addDtls:
        $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
        $ref: '#/definitions/TransactionDetails'
     overrideDtls:
        type: array
        items:
          $ref: "#/definitions/BaseOutcomeModel"
          
 CustTdPayInDtls:
  type: object
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     payInData:
        $ref: '#/definitions/PayInData'

 PayInData:
  type: object
  allOf:
  - type: object
    properties:
     parentId:
       type: string
     branchCode:
       type: string
     tdAcNo:
       type: string
     accountCcy:
       type: string
     maturityAmt:
      type: number
     payMode:
      type: string
     payBrn:
       type: string
     payAcc:
      type: string
     chequeNo:
      type: string
     chequeDate:
      type: string
      format: date
     txnAmt:
      type: number
     txnCcy:
      type: string
     offsetAccount:
      type: string
     offsetAccountBrn:
      type: string
     offsetAccountAmt:
      type: number
     offsetAccountCcy:
      type: string
     accountCcyAmt:
      type: number
     exchnageRate:
      type: number

 TDModel:
  type: object
  description: "Term deposit account details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
        type: string
        description: ""
     recordId:
       type: string
       description: ""
     branchCode:
       type: string
       description: ""
     tdAcNo:
       type: string
       description: ""
     tdAcDesc:
       type: string
       description: ""
     acOpenDate:
       type: string
       format: date
       description: ""
     txnRefNumber:
       type: string
       description: ""
     customerId:
      type: string
      description: ""
     accountClass:
      type: string
      description: ""
     tdAmt:
       type: number
     tdCcy:
       type: string
     intrestRate:
      type: number
     tenorDays:
      type: number
     tenorMonths:
      type: number
     tenorYears:
      type: number
     recordStat:
      type: string
      description: ""
     authStat:
      type: string
      description: ""
     accountType:
      type: string
      description: ""
     operationMode:
      type: string
      description: ""
     demDtls:
       type: array
       items:
        $ref: '#/definitions/DenomTxnDtlsModel'
     modNo:
      type: string
      description: ""
     makerId:
      type: string
      description: ""
     makerDtStamp:
      type: string
      format: date
      description: ""
     checkerId:
      type: string
      description: ""
     checkerDtStamp:
      type: string
      format: date
      description: ""
     onceAuth:
      type: string
      description: ""
     source:
      type: string
      description: ""
     sourceRefNo:
      type: string
      description: ""
     cusTdAccInterest:
        type: array
        items:
          $ref: "#/definitions/CusTdAccProdData"
     custTdPayInDtls:
        $ref: "#/definitions/PayInData"    
     cusTdPayout:
        $ref: "#/definitions/CusTdPayoutData"
     cusTdAccRollOver:
        $ref: "#/definitions/CusTdAccRolloverData"
     cusTdAccLinkes:
        type: array
        items:
          $ref: "#/definitions/CusTdAccLinkedData"
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"          

    
 TdRedeemModel:
  type: object
  description: "Term deposit redeem details"
  allOf:
  - type: object
    properties:
     txnControllerRefNo:
       type: string
       description: ""
     datasegment:
       type: string
       description: ""
     recordId:
       type: string
     branchCode:
       type: string
     custId:
       type: string
     tdAccNo:
       type: string
     txnCcy:
       type: string
     redeemMode:
       type: string
     redeemAmt:
      type: number
     tdCcy:
       type: string
     offsetAccount:
      type: string
     offsetAccountBrn:
      type: string
     offsetAccountAmt:
      type: number
     offsetAccountCcy:
      type: string
     wavePenalty:
      type: string
     waiveInterest:
      type: number
     offAccount:
       type: string
     offAccountCcy:
       type: string
     toAccountCcy:
       type: string
     toAccountAmt:
       type: number
     demDtls:
       type: array
       items:
        $ref: '#/definitions/DenomTxnDtlsModel'
     offAccBrn:
       type: string
     offAccName:
       type: string
     recordStat:
      type: string
     authStat:
      type: string
     modNo:
      type: string
     makerId:
      type: string
     makerDtStamp:
      type: string
      format: date
     checkerId:
      type: string
     checkerDtStamp:
      type: string
      format: date
     onceAuth:
      type: string
     sourceRefNo:
      type: string
     redeemRefNo:
      type: string
     addDtls:
        $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
        $ref: '#/definitions/TransactionDetails'
     overrideDtls:
        type: array
        items:
          $ref: "#/definitions/BaseOutcomeModel"

 RdModel:
  type: object
  description: "Recurring Deposit"
  properties:
    datasegment:
      type: string
      description: "CCA Name"
    txnControllerRefNo:
      type: string
      description: "Txn ref no from UI"
    recordId:
      type: string
      description: ""
    rdAccount:
      type: string
      description: ""
    exchangeRate:
      type: string
      description: ""
    totalCharges:
      type: string
      description: ""
    txnAmt:
      type: string
      description: ""
    toAccountAmt:
      type: string
      description: ""
    txnBranchCode:
      type: string
      description: ""
    txnCustomer:
      type: string
      description: ""
    toAccountCcy:
      type: string
      description: ""
    narrative:
      type: string
      description: ""
    txnDate:
      type: string
      description: ""
    txnCcy:
      type: string
      description: ""
    toAccountBranch:
      type: string
      description: ""
    addDtls:
      $ref: '#/definitions/AdditionalTransactionDetails'
    txnDtls:
      $ref: '#/definitions/TransactionDetails'
    overrideDtls:
      type: array
      items:
        $ref: "#/definitions/BaseOutcomeModel"
    demDtls:
      type: array
      items:
        $ref: '#/definitions/DenomTxnDtlsModel'
    prcDtls:
      type: array
      items:
        $ref: "#/definitions/PrcDtlsModel"