#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking CorpoparticipationPending Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : documentexecution.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: syndicationapplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/documentexecution:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - documentexecution
      summary: Adds a new documentexecution.
      description: Adds a new documentexecution. Add additional information here for this endpoint.
      operationId: addDocumentExecution
      parameters:
      - name: DocumentExecutionModel
        in: body
        description: Request Body that contains data required for creating a new documentexecution
        required: true
        schema:
          $ref: '#/definitions/DocumentExecutionModel'
      responses:
        201:
          description: Returns the Id of the newly created Charges
          headers:
            Location:
              description: URL of newly created Charges
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - documentexecution
      summary: Retrieves the list of existing documentexecution.
      description: Retrieves the list of existing documentexecution. Add additional information here for the this endpoint.
      operationId: getAllDocumentExecution
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/documentexecution/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - documentexecution
      summary: Get a  documentexecution.
      description: Get a  documentexecution by given id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: id of the documentexecution that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated documentexecution
          schema:
            $ref: '#/definitions/DocumentExecutionModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - documentexecution
      summary: Update an existing documentexecution.
      description: Update an existing documentexecution. Add additional information here for the this endpoint.
      operationId: updateDocumentExecution
      parameters:
      - name: id
        in: path
        description: id of the documentexecution that need to be updated
        required: true
        type: string
      - name: documentexecution
        in: body
        description: Request Body that contains data required for updating an existing documentexecution
        required: true
        schema:
          $ref: '#/definitions/DocumentExecutionModel'
      responses:
        200:
          description: Returns updated documentexecution
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - documentexecution
      summary: Deletes the documentexecution identified by given ID.
      description: Deletes the documentexecution identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteDocumentExecution
      parameters:
      - name: id
        in: path
        description: Id of the documentexecution that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error    
definitions:
  DocumentExecutionModel:
    description: documentexecution model
    type: object
    required:
    - applicationNumber
    properties:
      id:
        description: Id of the documentexecution
        type: string
      applicationNumber:
        description: Application Number of the documentexecution
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36             
      documentExecutionDetails:
        type: array
        items:
          $ref: '#/definitions/DocumentExecutionDetailsModel'  
  DocumentExecutionCollection:
    description: Collection of documentexecution.
    type: object
    properties:
      documentExecutionList:
        type: array
        items:
          $ref: '#/definitions/DocumentExecutionModel'
  DocumentExecutionDetailsModel:
    description: DocumentExecutionDetails model
    type: object
    required:
    - documentType
    - documentId
    - executionStatus
    - entityType
    - entityName
    properties:
      id:
        description: Id of the DocumentExecutionDetails
        type: string
        maxLength: 36
      documentExecutionId:
        description: documentExecutionId of the DocumentExecutionDetails
        type: string
        maxLength: 36
      documentType:
        description: documentType of the DocumentExecutionDetails
        type: string
        maxLength: 20
      documentId:
        description: documentId of the DocumentExecutionDetails
        type: string
        maxLength: 36 
      executionStatus:
        description: executionStatus of the DocumentExecutionDetails
        type: string
        maxLength: 20  
      entityType:
        description: entityType of the DocumentExecutionDetails
        type: string
        maxLength: 36
      entityName:
        description: entityName of the DocumentExecutionDetails
        type: string                
  DocumentExecutionDetailsCollection:
    description: Collection of DocumentExecutionDetails.
    type: object
    properties:
      DocumentExecutionDetailsList:
        type: array
        items:
          $ref: '#/definitions/DocumentExecutionDetailsModel'
 