#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : RtlParam.yaml
#  **
#  ** Module     : RealTimeLiquidity
#  ** 
#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server realtimeliquidityparameter server." 
 version: "1.0.0"
 title: "realtimeliquidityparameter Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/v1"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "realtimeliquidityparameter"
   description: "RealTimeLiquidityParameter"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../parameter

 /parameter:
  post:
   tags:
    - "realtimeliquidityparameter"
   summary: "Adds a new realtimeliquidityparameter."
   description: "Adds a new realtimeliquidityparameter. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "realtimeliquidityparameter" 
      in: "body" 
      description: "Request Body that contains data required for creating a new realtimeliquidityparameter" 
      required: true
      schema:
       $ref: "#/definitions/LrtTmRtlParamMasterDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created realtimeliquidityparameter" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "realtimeliquidityparameter"
   summary: "Get all valid realtimeliquidityparameter."
   description:  "Get all valid realtimeliquidityparameter. This endpoints will be used to Get all valid realtimeliquidityparameter maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/LrtTmRtlParamMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../parameter/xxx
#   DELETE    .../parameter/xxx
#   GET       .../parameter/xxx
#   GET       .../parameter/xxx?version=latestrecord
#   GET       .../parameter/xxx?version=1

 /parameter/{id}:
  put:
   tags:
    - "realtimeliquidityparameter"
   summary: "Update an existing realtimeliquidityparameter."
   description:  "Update an existing realtimeliquidityparameter."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the realtimeliquidityparameter Maintenance"
      required: true
      type: "string"
    - name: "realtimeliquidityparameter"
      in: "body"
      description: "Request Body that contains data required for updating an existing realtimeliquidityparameter"
      required: true
      schema:
       $ref: "#/definitions/LrtTmRtlParamMasterDTO"
   responses:
    200:
     description: "Returns updated realtimeliquidityparameter"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "realtimeliquidityparameter"
   summary: "Retrieves the realtimeliquidityparameter by ID."
   description:  "Retrieves the realtimeliquidityparameter by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the realtimeliquidityparameter based on given id."
     schema:
      $ref: "#/definitions/LrtTmRtlParamMasterWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "realtimeliquidityparameter"
   summary: "Deletes the realtimeliquidityparameter identified by given ID."
   description:  "Deletes the realtimeliquidityparameter identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the realtimeliquidityparameter maintenance"
      required: true
      type: "string"
    - name: "realtimeliquidityparameter"
      in: "body"
      description: Request body contain realtimeliquidityparameter and Modification no of realtimeliquidityparameter maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../parameter/xxx/approve

 /parameter/{id}/approve:
  patch:
   tags:
    - "realtimeliquidityparameter"
   summary: "Authorize the realtimeliquidityparameter by given ID."
   description:  "Authorize the realtimeliquidityparameter identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the realtimeliquidityparameter maintenance"
      required: true
      type: "string"
    - name: "realtimeliquidityparameter"
      in: "body"
      description: Request body contain realtimeliquidityparameter and Modification no of realtimeliquidityparameter maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../parameter/xxx/close
 /parameter/{id}/close:
  patch:
   tags:
    - "realtimeliquidityparameter"
   summary: "Close the realtimeliquidityparameter by given ID."
   description:  "Close the realtimeliquidityparameter identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the realtimeliquidityparameter maintenance"
      required: true
      type: "string"
    - name: "realtimeliquidityparameter"
      in: "body"
      description: Request body contain realtimeliquidityparameter and Modification no of realtimeliquidityparameter maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../parameter/xxx/reopen

 /parameter/{id}/reopen:
  patch:
   tags:
    - "realtimeliquidityparameter"
   summary: "reopen the realtimeliquidityparameter by given ID."
   description:  "reopen the realtimeliquidityparameter identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the realtimeliquidityparameter maintenance"
      required: true
      type: "string"
    - name: "realtimeliquidityparameter"
      in: "body"
      description: Request body contain realtimeliquidityparameter and Modification no of realtimeliquidityparameter maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../parameter/xxx/unauthorized

 /parameter/{id}/unauthorized:
  get:
   tags:
    - "realtimeliquidityparameter"
   summary: "Retrives the realtimeliquidityparameter by given ID."
   description:  "Retrives the realtimeliquidityparameter identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the realtimeliquidityparameter based on given id."
     schema:
       $ref: "#/definitions/LrtTmRtlParamMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../parameter/xxx/history

 /parameter/{id}/history:
  get:
   tags:
    - "realtimeliquidityparameter"
   summary: "Retrives the realtimeliquidityparameter by given ID."
   description:  "Retrives the realtimeliquidityparameter by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the realtimeliquidityparameter based on given id."
     schema:
       $ref: "#/definitions/LrtTmRtlParamMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 LrtTmRtlParamMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     ismultiaccAllowed:
      type: string
      description: ""
     sysName:
      type: string
      description: ""
     ccyTolerance:
      type: number
      description: ""
     LrtTmRtlParamCountryDTO:
      type: array
      items:
       $ref: '#/definitions/LrtTmRtlParamCountryDTO'
     LrtTmRtlParamCurrencyDTO:
      type: array
      items:
       $ref: '#/definitions/LrtTmRtlParamCurrencyDTO'
     LrtTmRtlParamInterfaceDTO:
      type: array
      items:
       $ref: '#/definitions/LrtTmRtlParamInterfaceDTO'
 LrtTmRtlParamCountryDTO:
  type: object
  properties:
     rtlParamMasterId:
      type: string
      description: ""
     countryCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
  required:
   - rtlParamMasterId
   - countryCode
   - id
 LrtTmRtlParamCurrencyDTO:
  type: object
  properties:
     rtlParamMasterId:
      type: string
      description: ""
     currencyCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
 LrtTmRtlParamInterfaceDTO:
  type: object
  properties:
     branchId:
      type: string
      description: ""
     rtlParamMasterId:
      type: string
      description: "" 
     branchCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
     interfaceId:
      type: string
      description: ""
     externalSystemId:
      type: string
      description: ""
     methodName:
      type: string
      description: ""
  required:
   - branchId
   - id
   - interfaceId
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 LrtTmRtlParamMasterCollection: 
  description: "Collection of rtlParam."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/LrtTmRtlParamMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 LrtTmRtlParamMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/LrtTmRtlParamMasterDTO"



