swagger: "2.0"
info:
  description: "This is a sample server Valuation server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "Collateral Pool Service"
host: "whf00bdm:7801"
basePath: "/collateralpool-services"
tags:
  - name: "CollateralPoolAPI"
    description: "API for Scoring's Operations"
schemes:
- "http"

