#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : bankinginfo.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/bankinginfo:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - BankingInfo
      summary: Adds a new BankingInfo.
      description: Adds a new BankingInfo. Add additional information here for this endpoint.
      operationId: addBankingInfo
      parameters:
      - name: BankingInfo
        in: body
        description: Request Body that contains data required for creating a new BankingInfo
        required: true
        schema:
          $ref: '#/definitions/BankingInfoModel'
      responses:
        201:
          description: Returns the Id of the newly created BankingInfo
          headers:
            Location:
              description: URL of newly created BankingInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - BankingInfo
      summary: Retrieves the list of  BankingInfo.
      description: Retrieves the list of  BankingInfo. Add additional information here for the this endpoint.
      operationId: getAllBankingInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/bankinginfo/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - BankingInfo
      summary: Get a  BankingInfo.
      description: Update a  BankingInfo. Add additional information here for the this endpoint.
      operationId: getBankingInfoById
      parameters:
      - name: id
        in: path
        description: id of the BankingInfo that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated BankingInfo
          schema:
            $ref: '#/definitions/BankingInfoModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - BankingInfo
      summary: Update an  BankingInfo.
      description: Update an  BankingInfo. Add additional information here for the this endpoint.
      operationId: updateBankingInfo
      parameters:
      - name: id
        in: path
        description: id of the BankingInfo that need to be updated
        required: true
        type: string
      - name: BankingInfo
        in: body
        description: Request Body that contains data required for updating an  BankingInfo
        required: true
        schema:
          $ref: '#/definitions/BankingInfoModel'
      responses:
        200:
          description: Returns updated BankingInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - BankingInfo
      summary: Deletes the A Banking info identified by given ID.
      description: Deletes the BankingInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteBankingInfo
      parameters:
      - name: id
        in: path
        description: Id of the BankingInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  BankingInfoModel:
   description: BankingInfo model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      bankingDetails:
        description: Details of the BankingInfo
        type: array
        items:
          $ref: '#/definitions/BankingDetailsModel'
  BankingInfoCollection:
    description: Collection of BankingInfo.
    type: object
    properties:
      BankingInfoList:
        type: array
        items:
          $ref: '#/definitions/BankingInfoModel'
  BankingDetailsModel:
    description: Banking Details model
    type: object
    required:
    - bankName
    - branchLocation
    - accountNumber
    - accountType
    properties:
      id:
        description: Id of the Banking details model
        type: string
        format: int64
        maxLength: 36
      bankinginfoid:
        description: BankingInfoId of the Details model
        type: string
        maxLength: 36
      bankName:
        description: BankName of the Details model
        type: string
        maxLength: 35
      branchLocation:
        description: branchLocation of the Details model
        type: string
        maxLength: 20
      accountNumber:
        description: accountNumber of the Details model
        type: string
        maxLength: 20
      accountType:
        description: accountType of the Details model
        type: string
        maxLength: 20
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type