#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : backofficecomponents.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/backofficecomponents:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Adds a new BackOfficeComponents.
      description: Adds a new BackOfficeComponents. Add additional information here for this endpoint.
      operationId: addBackOfficeComponents
      parameters:
      - name: BackOfficeComponents
        in: body
        description: Request Body that contains data required for creating a new BackOfficeComponents
        required: true
        schema:
          $ref: '#/definitions/BackOfficeComponentsModel'
      responses:
        201:
          description: Returns the Id of the newly created BackOfficeComponents
          headers:
            Location:
              description: URL of newly created BackOfficeComponents
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Retrieves the list of existing BackOfficeComponents.
      description: Retrieves the list of existing BackOfficeComponents. Add additional information here for the this endpoint.
      operationId: getAllBackOfficeComponents
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/backofficecomponents/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Retrieves the BackOfficeComponents by id.
      description: Retrieves the BackOfficeComponents by id. Add additional information here for the this endpoint.
      operationId: getBackOfficeComponentsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the BackOfficeComponents based on given applicationNumber.
          schema:
            $ref: '#/definitions/BackOfficeComponentsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Update an existing BackOfficeComponents.
      description: Update an existing BackOfficeComponents. Add additional information here for the this endpoint.
      operationId: updateBackOfficeComponents
      parameters:
      - name: id
        in: path
        description: id of the BackOfficeComponents that need to be updated
        required: true
        type: string
      - name: BackOfficeComponents
        in: body
        description: Request Body that contains data required for updating an existing BackOfficeComponents
        required: true
        schema:
          $ref: '#/definitions/BackOfficeComponentsModel'
      responses:
        200:
          description: Returns updated BackOfficeComponents
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Deletes the BackOfficeComponents identified by given ID.
      description: Deletes the BackOfficeComponents identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteBackOfficeComponents
      parameters:
      - name: id
        in: path
        description: Id of the BackOfficeComponents that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/clpmcomponentdetails/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - BackOfficeComponents
      summary: Retrieves the list of existing Fee, Margin, Tranche details.
      description: Retrieves the list of existing Fee, Margin, Tranche details. Add additional information here for the this endpoint.
      operationId: getCLPMComponentDetails
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber that needs to be fetched
        required: true
        type: string
      - name: componentType
        in: query
        description: componentType for fee,Margin,tranchedetails
        required: true
        type: string        
      - name: componentName
        in: query
        description: details to be fetched for componentName 
        required: false
        type: string
      - name: trancheInfo
        in: query
        description: additional tranche details to be fetched by given tranche
        required: false
        type: string        
      responses:
        200:
          description: Returns the CLPMToBackofficeComponentMapping based on given applicationNumber.
          schema:
            $ref: '#/definitions/ComponentDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ComponentDetailsModel:
    description: ComponentDetailsModel
    type: object
    properties:
      componentId:
        description: Id of the ComponentDetailsModel
        type: string
      componentType:
        description: componentType
        type: string
      componentMethod:
        description: componentMethod
        type: string
      componentName:
        description: componentName
        type: string
      componentDescription:
        description: componentDescription
        type: string        
  BackOfficeComponentsModel:
    description: BackOfficeComponents model
    type: object
    properties:
      id:
        description: Id of the BackOfficeComponents
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      remarks:
        description: remarks
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string         
      backOfficeComponentsDetails:
        type: array
        items:
          $ref: '#/definitions/BackOfficeComponentsDetailsModel'
  BackOfficeComponentsDetailsModel:
    description: BackOfficeComponentsDetails model
    type: object
    required:
    - clmoComponentName
    - backofficeProduct
    - backofficeComponentName
    - componentDescription
    properties:
      id:
        description: Id of the BackOfficeComponentsDetails
        type: string
      backofficeComponentId:
        description: backofficeComponentId
        type: string
      clmoComponentName:
        description: clmoComponentName
        type: string
      trancheName:
        description: trancheName
        type: string
      backofficeProduct:
        description: backofficeProduct
        type: string
      backofficeComponentName:
        description: backofficeComponentName
        type: string
      componentDescription:
        description: componentDescription
        type: string
      backofficeFeeRule:
        description: backofficeFeeRule
        type: string
  BackOfficeComponentsCollection:
    description: Collection of BackOfficeComponents.
    type: object
    properties:
      BackOfficeComponentsList:
        type: array
        items:
          $ref: '#/definitions/BackOfficeComponentsModel'
