#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cam
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server monitoringinfomaintenance server." 
 version: "1.0.0"
 title: "monitoringinfomaintenance Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "monitoringinfomaintenance"
   description: " Monitoring Information Maintenance Service is a maintenance service related to the covenant maintenance, it has two tables the main table is the monitoring information and the child table is the monitoring information details"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../monitoringinfomaintenance

 /monitoringinfomaintenance:
  post:
   tags:
    - "monitoringinfomaintenance"
   summary: "Adds a new monitoringinfomaintenance."
   description: "Adds a new monitoringinfomaintenance. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "monitoringinfomaintenance" 
      in: "body" 
      description: "Request Body that contains data required for creating a new monitoringinfomaintenance" 
      required: true
      schema:
       $ref: "#/definitions/CfpmTmMonitoringInformationDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created monitoringinfomaintenance" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "monitoringinfomaintenance"
   summary: "Get all valid monitoringinfomaintenance."
   description:  "Get all valid monitoringinfomaintenance. This endpoints will be used to Get all valid monitoringinfomaintenance maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CfpmTmMonitoringInformationCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
     
     
 /monitoringinfomaintenance/monitorinfo/{monitoringInfoId}:
  get:
   tags:
    - "monitoringinfomaintenance"
   summary: "Retrieves the monitoringInfo by monitoringInfoId."
   description:  "Retrieves the monitoringInfo by monitoringInfoId."
   operationId: "getByMonitoringInfoId"
   parameters:
    - name: "monitoringInfoId"
      in: "path"
      description: "Id of the monitoringInfo that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the monitoringInfo that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the monitoringInfo based on given monitoringInfoId."
     schema:
      $ref: "#/definitions/CfpmTmMonitoringInformationWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../monitoringinfomaintenance/xxx
#   DELETE    .../monitoringinfomaintenance/xxx
#   GET       .../monitoringinfomaintenance/xxx
#   GET       .../monitoringinfomaintenance/xxx?version=latestrecord
#   GET       .../monitoringinfomaintenance/xxx?version=1

 /monitoringinfomaintenance/{id}:
  put:
   tags:
    - "monitoringinfomaintenance"
   summary: "Update an existing monitoringinfomaintenance."
   description:  "Update an existing monitoringinfomaintenance."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the monitoringinfomaintenance Maintenance"
      required: true
      type: "string"
    - name: "monitoringinfomaintenance"
      in: "body"
      description: "Request Body that contains data required for updating an existing monitoringinfomaintenance"
      required: true
      schema:
       $ref: "#/definitions/CfpmTmMonitoringInformationDTO"
   responses:
    200:
     description: "Returns updated monitoringinfomaintenance"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "monitoringinfomaintenance"
   summary: "Retrieves the monitoringinfomaintenance by ID."
   description:  "Retrieves the monitoringinfomaintenance by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the monitoringinfomaintenance based on given id."
     schema:
      $ref: "#/definitions/CfpmTmMonitoringInformationWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "monitoringinfomaintenance"
   summary: "Deletes the monitoringinfomaintenance identified by given ID."
   description:  "Deletes the monitoringinfomaintenance identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the monitoringinfomaintenance maintenance"
      required: true
      type: "string"
    - name: "monitoringinfomaintenance"
      in: "body"
      description: Request body contain monitoringinfomaintenance and Modification no of monitoringinfomaintenance maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../monitoringinfomaintenance/xxx/approve

 /monitoringinfomaintenance/{id}/approve:
  patch:
   tags:
    - "monitoringinfomaintenance"
   summary: "Authorize the monitoringinfomaintenance by given ID."
   description:  "Authorize the monitoringinfomaintenance identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the monitoringinfomaintenance maintenance"
      required: true
      type: "string"
    - name: "monitoringinfomaintenance"
      in: "body"
      description: Request body contain monitoringinfomaintenance and Modification no of monitoringinfomaintenance maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../monitoringinfomaintenance/xxx/close
 /monitoringinfomaintenance/{id}/close:
  patch:
   tags:
    - "monitoringinfomaintenance"
   summary: "Close the monitoringinfomaintenance by given ID."
   description:  "Close the monitoringinfomaintenance identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the monitoringinfomaintenance maintenance"
      required: true
      type: "string"
    - name: "monitoringinfomaintenance"
      in: "body"
      description: Request body contain monitoringinfomaintenance and Modification no of monitoringinfomaintenance maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../monitoringinfomaintenance/xxx/reopen

 /monitoringinfomaintenance/{id}/reopen:
  patch:
   tags:
    - "monitoringinfomaintenance"
   summary: "reopen the monitoringinfomaintenance by given ID."
   description:  "reopen the monitoringinfomaintenance identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the monitoringinfomaintenance maintenance"
      required: true
      type: "string"
    - name: "monitoringinfomaintenance"
      in: "body"
      description: Request body contain monitoringinfomaintenance and Modification no of monitoringinfomaintenance maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../monitoringinfomaintenance/xxx/unauthorized

 /monitoringinfomaintenance/{id}/unauthorized:
  get:
   tags:
    - "monitoringinfomaintenance"
   summary: "Retrives the monitoringinfomaintenance by given ID."
   description:  "Retrives the monitoringinfomaintenance identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the monitoringinfomaintenance based on given id."
     schema:
       $ref: "#/definitions/CfpmTmMonitoringInformationCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../monitoringinfomaintenance/xxx/history

 /monitoringinfomaintenance/{id}/history:
  get:
   tags:
    - "monitoringinfomaintenance"
   summary: "Retrives the monitoringinfomaintenance by given ID."
   description:  "Retrives the monitoringinfomaintenance by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the monitoringinfomaintenance based on given id."
     schema:
       $ref: "#/definitions/CfpmTmMonitoringInformationCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CfpmTmMonitoringInformationDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     monitoringInfoDescription:
      type: string
      description: ""
     monitoringInfoId:
      type: string
      description: ""
     CfpmTmMonitoringInfoDtlsDTO:
      type: array
      items:
       $ref: '#/definitions/CfpmTmMonitoringInfoDtlsDTO'
 CfpmTmMonitoringInfoDtlsDTO:
  type: object
  properties:
     elementCode:
      type: string
      description: ""
     elementDescription:
      type: string
      description: ""
     id:
      type: string
      description: ""
     monitoringInformationId:
      type: string
      description: ""
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CfpmTmMonitoringInformationCollection: 
  description: "Collection of monitoringinformation."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CfpmTmMonitoringInformationDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CfpmTmMonitoringInformationWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CfpmTmMonitoringInformationDTO"
 CfpmTmFinancialCodesCollection: 
  description: "Collection of financialcodes."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CfpmTmFinancialCodesDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 CfpmTmFinancialCodesDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     financialCode:
      type: string
      description: ""
     financialDesc:
      type: string
      description: ""
     finCategoryCode:
      type: string
      description: ""
     formula:
      type: string
      description: ""
     inputMode:
      type: string
      description: ""
     CfpmTmFinRatioRangeDetDTO:
      type: array
      items:
       $ref: '#/definitions/CfpmTmFinRatioRangeDetDTO'
     valueType:
      type: string
     docCategoryType:
      type: string
 CfpmTmFinRatioRangeDetDTO:
  type: object
  properties:
     cfpmTmFinancialCodesId:
      type: string
      description: ""
     financialCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
     ratioRangeMaxValue:
      type: number
      description: ""
     ratioRangeMinValue:
      type: number
      description: ""
     score:
      type: number
      description: ""
 