swagger: '2.0'
info:
   description: This is a sample server for file parser server.
   version: 1.0.0
   title: After Approval Service
host: whf00gmh.in.oracle.com:8100
basePath: /obedx-workflow-service
consumes:
   - application/json
produces:
   - application/json
tags:
   -  name: AfterApprovalWebApi
      description: endpoint for web related to Approval
   -  name: AfterApprovalServiceApi
      description: endpoint for services related to Approval
schemes:
   - https
paths:
   /afterApproval:
      post:
         tags:
            - AfterApprovalWebApi
         summary: post approval status for file or record from channel.
         description: post approval status for file or record from channel
         operationId: afterApproval
         parameters:
            -  name: approvalDTO
               in: body
               description: Request Body that contains data required for single approval of file/records.
               required: true
               schema:
                  $ref: '#/definitions/ApprovalDTO'
         responses:
            201:
               description: 'Returns message of succes or failure '
               schema:
                  $ref: '#/definitions/ResponseDtoWrapper'
            400:
               description: Malformed syntax.
            401:
               description: Request does not have sufficient credentials.
            403:
               description: Request is not authorized.
            405:
               description: Invalid input
            500:
               description: Internal error
   /afterApprovalBatch:
      post:
         tags:
            - AfterApprovalWebApi
         summary: batch post approval status for file or record from channel.
         description: post approval status for file or record from channel.
         operationId: afterApprovalBatch
         parameters:
            - name: approvalDTOList
              in: body
              description: Request Body that contains data required for batch approval of file/records.
              required: true
              schema:
                 $ref: '#/definitions/ApprovalDTOList'
         responses:
            201:
               description: 'Returns message of succes or failure '
               schema:
                  $ref: '#/definitions/ResponseDtoWrapper'
            400:
               description: Malformed syntax.
            401:
               description: Request does not have sufficient credentials.
            403:
               description: Request is not authorized.
            405:
               description: Invalid input
            500:
               description: Internal error
definitions:
   ApprovalDTOList:
      description: List of Approval DTO's
      type: object
      properties:
         data:
            type: array
            items:
               $ref: '#/definitions/ApprovalDTO'
   ApprovalDTO:
      description: ApprovalDTO
      type: object
      properties:
         fileId:
            description: File Id
            type: number
         recordId:
            description: Record Id
            type: number
         eventId:
            description: Event Id
            type: string
         checkerUserName:
            description: Checker User Name
            type: string
         checkerFirstName:
            description: Checker First Name
            type: string
         checkerLastName:
            description: checkerLast Name
            type: string
         remarks:
            description: Remarks
            type: string
         approvalOn:
            description: Approval Date Time
            type: string
            format: date-time
            example: '2021-01-30T08:30:00Z'
   ResponseDtoWrapper:
      type: object