#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : consolrolloverdetail.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/consolrolloverdetail:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverDetail
      summary: Adds a new ConsolRolloverDetail.
      description: Adds a new ConsolRolloverDetail. Add additional information here for this endpoint.
      operationId: addConsolRolloverDetail
      parameters:
      - name: ConsolRolloverDetail
        in: body
        description: Request Body that contains data required for creating a new ConsolRolloverDetail
        required: true
        schema:
          $ref: '#/definitions/ConsolRolloverDetailModel'
      responses:
        201:
          description: Returns the Id of the newly created ConsolRolloverDetail
          headers:
            Location:
              description: URL of newly created ConsolRolloverDetail
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverDetail
      summary: Retrieves the list of existing ConsolRolloverDetail.
      description: Retrieves the list of existing ConsolRolloverDetail. Add additional information here for the this endpoint.
      operationId: getAllConsolRolloverDetail
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/consolrolloverdetail/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverDetail
      summary: Retrieves the ConsolRolloverDetail by id.
      description: Retrieves the ConsolRolloverDetail by id. Add additional information here for the this endpoint.
      operationId: getConsolRolloverDetailById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ConsolRolloverDetail based on given applicationNumber.
          schema:
            $ref: '#/definitions/ConsolRolloverDetailModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverDetail
      summary: Update an existing ConsolRolloverDetail.
      description: Update an existing ConsolRolloverDetail. Add additional information here for the this endpoint.
      operationId: updateConsolRolloverDetail
      parameters:
      - name: id
        in: path
        description: id of the ConsolRolloverDetail that need to be updated
        required: true
        type: string
      - name: ConsolRolloverDetail
        in: body
        description: Request Body that contains data required for updating an existing ConsolRolloverDetail
        required: true
        schema:
          $ref: '#/definitions/ConsolRolloverDetailModel'
      responses:
        200:
          description: Returns updated ConsolRolloverDetail
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverDetail
      summary: Deletes the ConsolRolloverDetail identified by given ID.
      description: Deletes the ConsolRolloverDetail identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteConsolRolloverDetail
      parameters:
      - name: id
        in: path
        description: Id of the ConsolRolloverDetail that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ConsolRolloverDetailModel:
    description: ConsolRolloverDetail model
    type: object
    properties:
      id:
        description: Id of the ConsolRolloverDetail
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      consolRolloverDetailsInfo:
        type: array
        items:
          $ref: '#/definitions/ConsolRolloverDetailsInfoModel'
  ConsolRolloverDetailsInfoModel:
    description: ConsolRolloverDetailsInfo model
    type: object
    required:
    - ddRefNo
    - principalRollAmount
    - interestRolloverAmount
    - totalRollAmount
    - driverContract
    properties:
      id:
        description: Id of the ConsolRolloverDetailsInfo
        type: string
      ddRefNo:
        description: ddRefNo
        type: string
        maxLength: 20
      principalRollAmount:
        description: principalRollAmount
        type: number
      interestRolloverAmount:
        description: interestRolloverAmount
        type: number
      totalRollAmount:
        description: totalRollAmount
        type: number
      driverContract:
        description: driverContract
        type: string
        maxLength: 20
      contractCurrency:
        description: contractCurrency
        type: string
  ConsolRolloverDetailCollection:
    description: Collection of ConsolRolloverDetail.
    type: object
    properties:
      ConsolRolloverDetailList:
        type: array
        items:
          $ref: '#/definitions/ConsolRolloverDetailModel'
