#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : legalopiniondetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Collateral Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-collateralservices
tags:
- name: LegalOpinionService
  description: API for Legal Opinion Service
schemes:
- http
paths:
  /web/v1/legalopiniondetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalOpinionDetails
      summary: Adds a new LegalOpinionDetails.
      description: Adds a new LegalOpinionDetails. Add additional information here for this endpoint.
      operationId: addLegalOpinionDetails
      parameters:
      - name: LegalOpinionDetails
        in: body
        description: Request Body that contains data required for creating a new LegalOpinionDetails
        required: true
        schema:
          $ref: '#/definitions/LegalOpinionDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created LegalOpinionDetails
          headers:
            Location:
              description: URL of newly created LegalOpinionDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalOpinionDetails
      summary: Retrieves the list of existing LegalOpinionDetails.
      description: Retrieves the list of existing LegalOpinionDetails. Add additional information here for the this endpoint.
      operationId: getAllLegalOpinionDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/legalopiniondetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalOpinionDetails
      summary: Retrieves the LegalOpinionDetails by id.
      description: Retrieves the LegalOpinionDetails by id. Add additional information here for the this endpoint.
      operationId: getLegalOpinionDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the LegalOpinionDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/LegalOpinionDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LegalOpinionDetails
      summary: Update an existing LegalOpinionDetails.
      description: Update an existing LegalOpinionDetails. Add additional information here for the this endpoint.
      operationId: updateLegalOpinionDetails
      parameters:
      - name: id
        in: path
        description: id of the LegalOpinionDetails that need to be updated
        required: true
        type: string
      - name: LegalOpinionDetails
        in: body
        description: Request Body that contains data required for updating an existing LegalOpinionDetails
        required: true
        schema:
          $ref: '#/definitions/LegalOpinionDetailsMasterModel'
      responses:
        200:
          description: Returns updated LegalOpinionDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LegalOpinionDetails
      summary: Deletes the LegalOpinionDetails identified by given ID.
      description: Deletes the LegalOpinionDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLegalOpinionDetails
      parameters:
      - name: id
        in: path
        description: Id of the LegalOpinionDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LegalOpinionDetailsMasterModel:
    description: Legal Opinion Details Master Model
    type: object
    allOf:
    - $ref: '#/definitions/GenericDatasegmentModel'
    - type: object
      properties:
        processRefNo:
          description: processRefNo
          type: string
        isLocalCollateral:
          description: Is Local Collateral or Not?
          type: boolean
        onboarded:
          description: Is All Collateral Onboarded
          type: boolean
          default: false
        applicationDate:
          description: Application Date
          type: string
        legalOpinionApplicantDetailsList:
          type: array
          items:
           $ref: '#/definitions/LegalOpinionApplicantDetailsModel' 
  LegalOpinionApplicantDetailsModel:
    description: Legal Opinion Applicant Details Model
    type: object
    properties:
      id:
       description: Id of the Legal Opinion Applicant Details Model
       type: string
      legalOpinionDetailsMasterId:
       description: Id of Legal Opinion Details Master Table
       type: string
      applicationNumber:
       description: Application Number
       type: string
       maxLength: 20 
      processRefNo:
       description: Process Ref Number
       type: string
       maxLength: 20
      applicantId:
       description: Applicant ID
       type: string
      partyId:
       description: Party ID
       type: string
      customerId:
       description: Customer ID
       type: string
      customerName:
       description: Customer Name
       type: string
      primaryApplicant:
       description: Primary Applicant Y/N
       type: boolean
      existingCustomer:
       description: Existing Customer Y/N
       type: boolean
      deleteLegal:
       description: Delete Legal
       type: boolean 
      dateOfBirth:
       description: Date of Birth
       type: string
      email:
       description: Email
       type: string
      mobileNumber:
       description: Mobile Number
       type: integer
       format: int64
      mobileIsd:
       description: Mobile ISD
       type: string
      phoneNo:
       description: Phone Number
       type: integer
       format: int64
      phoneIsd:
       description: Phone ISD
       type: string    
      legalOpinionDetailsList:
       type: array
       items:
        $ref: '#/definitions/LegalOpinionDetailsModel'        
  LegalOpinionDetailsModel:
    description: Legal Opinion Details Model
    type: object
    properties:
      id:
       description: Id of the Legal Opinion Details Model
       type: string
      legalOpinionApplicantDetailsId:
       description: Id of Legal Opinion Applicant Details table
       type: string
      applicationNumber:
       description: applicationNumber
       type: string
       maxLength: 20
      processRefNo:
       description: Process Ref No
       type: string
       maxLength: 20
      collateralCode:
       description: Collateral Code
       type: string
      onboardApplicationNumber:
       description: Onboard Application Number
       type: string
      collateralType:
       description: Collateral Type
       type: string
      collateralCategory:
       description: Collateral Category
       type: string
      collateralDesc:
       description: Collateral Description
       type: string
      collateralRefNo:
       description: Collateral Ref No
       type: string
      primaryCollateral:
       description: Primary Collateral
       type: boolean
       default: false
      liabilityId:
       description: Liability Id
       type: string
      liabilityDesc:
       description: Liability Description
       type: string
      deleteCollateral:
       description: Delete Collateral
       type: boolean
      legalOpinionReviewList:
       type: array
       items:
        $ref: '#/definitions/LegalOpinionReviewModel'   
  LegalOpinionReviewModel:
   description: Legal Opinion Review Model
   type: object
   properties:
    id:
     description: Id of the Legal Opinion Review Model
     type: string
    legalOpinionDetailsId:
     description: Id of Legal Opinion Details table
     type: string
    applicationNumber:
     description: applicationNumber
     type: string
     maxLength: 20
    processRefNo:
     description: Process Ref No
     type: string
     maxLength: 20
    legalOpinionSeqNo:
     description: Legal Opinion Sequence Number
     type: integer
    opinionType:
     description: Opinion Type
     type: string
    agencyCode:
     description: Agency Code
     type: string
    agencyName:
     description: Agency Name
     type: string
    legalRemarks:
     description: Legal Remarks
     type: string
    opinionDate:
     description: Opinion Date
     type: string       
  LegalOpinionDetailsMasterCollection:
    description: Collection of LegalOpinionDetailsMasterModel.
    type: object
    properties:
      legalOpinionDetailsMasterModelList:
        type: array
        items:
          $ref: '#/definitions/LegalOpinionDetailsMasterModel'
  GenericDatasegmentModel:
     allOf:
     - type: object
       discriminator: resource_type            