#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : perfectiondetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Collateral Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-collateralservices
tags:
- name: PerfectionService
  description: API for Perfection Service
schemes:
- http
paths:
  /web/v1/perfectiondetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PerfectionDetails
      summary: Adds a new PerfectionDetails.
      description: Adds a new PerfectionDetails. Add additional information here for this endpoint.
      operationId: addPerfectionDetails
      parameters:
      - name: PerfectionDetails
        in: body
        description: Request Body that contains data required for creating a new PerfectionDetails
        required: true
        schema:
          $ref: '#/definitions/PerfectionDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created PerfectionDetails
          headers:
            Location:
              description: URL of newly created PerfectionDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PerfectionDetails
      summary: Retrieves the list of existing PerfectionDetails.
      description: Retrieves the list of existing PerfectionDetails. Add additional information here for the this endpoint.
      operationId: getAllPerfectionDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/perfectiondetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PerfectionDetails
      summary: Retrieves the PerfectionDetails by id.
      description: Retrieves the PerfectionDetails by id. Add additional information here for the this endpoint.
      operationId: getPerfectionDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the PerfectionDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/PerfectionDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PerfectionDetails
      summary: Update an existing PerfectionDetails.
      description: Update an existing PerfectionDetails. Add additional information here for the this endpoint.
      operationId: updatePerfectionDetails
      parameters:
      - name: id
        in: path
        description: id of the PerfectionDetails that need to be updated
        required: true
        type: string
      - name: PerfectionDetails
        in: body
        description: Request Body that contains data required for updating an existing PerfectionDetails
        required: true
        schema:
          $ref: '#/definitions/PerfectionDetailsMasterModel'
      responses:
        200:
          description: Returns updated PerfectionDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - PerfectionDetails
      summary: Deletes the PerfectionDetails identified by given ID.
      description: Deletes the PerfectionDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deletePerfectionDetails
      parameters:
      - name: id
        in: path
        description: Id of the PerfectionDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  PerfectionDetailsMasterModel:
    description: PerfectionDetails Master model
    type: object
    allOf:
    - $ref: '#/definitions/GenericDatasegmentModel'
    - type: object
    properties:
      processRefNo:
       description: Process Ref Number
       type: string
      isLocalCollateral:
       description: Is Local Collateral or Not?
       type: boolean
      onboarded:
       description: Is All Collateral Onboarded
       type: boolean
       default: false
      applicationDate:
       description: Application Date
       type: string
      perfectionApplicantDetailsList:
       type: array
       items:
         $ref: '#/definitions/PerfectionApplicantDetailsModel'
  PerfectionApplicantDetailsModel:
   description: Perfection Applicant Details Model
   type: object
   properties:
    id:
     description: Id of the Perfection Applicant Details Model
     type: string
    perfectionDetailsMasterId:
     description: Id of Perfection Details Master Table
     type: string
    applicationNumber:
     description: Application Number
     type: string
     maxLength: 20 
    processRefNo:
     description: Process Ref Number
     type: string
     maxLength: 20
    applicantId:
     description: Applicant ID
     type: string
    partyId:
     description: Party ID
     type: string
    customerId:
     description: Customer ID
     type: string
    customerName:
     description: Customer Name
     type: string
    primaryApplicant:
     description: Primary Applicant Y/N
     type: boolean
    existingCustomer:
     description: Existing Customer Y/N
     type: boolean
    deletePerfection:
     description: Delete Perfection
     type: boolean 
    dateOfBirth:
     description: Date of Birth
     type: string
    email:
     description: Email
     type: string
    mobileNumber:
     description: Mobile Number
     type: integer
     format: int64
    mobileIsd:
     description: Mobile ISD
     type: string
    phoneNo:
     description: Phone Number
     type: integer
     format: int64
    phoneIsd:
     description: Phone ISD
     type: string    
    perfectionDetailsList:
     type: array
     items:
      $ref: '#/definitions/PerfectionDetailsModel'
  PerfectionDetailsModel:
   description: Perfection Details Model
   type: object
   properties:
    id:
     description: Id of the Perfection Details Model
     type: string
    perfectionApplicantDetailsId:
     description: Id of Perfection Applicant Details table
     type: string
    applicationNumber:
     description: applicationNumber
     type: string
     maxLength: 20
    processRefNo:
     description: Process Ref No
     type: string
     maxLength: 20
    collateralCode:
     description: Collateral Code
     type: string
    onboardApplicationNumber:
     description: Onboard Application Number
     type: string
    collateralType:
     description: Collateral Type
     type: string
    collateralCategory:
     description: Collateral Category
     type: string
    collateralDesc:
     description: Collateral Description
     type: string
    collateralRefNo:
     description: Collateral Ref No
     type: string
    primaryCollateral:
     description: Primary Collateral
     type: boolean
     default: false
    liabilityId:
     description: Liability Id
     type: string
    liabilityDesc:
     description: Liability Description
     type: string
    deleteCollateral:
     description: Delete Collateral
     type: boolean
    perfectionReviewList:
     type: array
     items:
      $ref: '#/definitions/PerfectionReviewModel'
  PerfectionReviewModel:
   description: Perfection Review Model
   type: object
   properties:
    id:
     description: Id of the Perfection Review Model
     type: string
    perfectionDetailsId:
     description: Id of Perfection Details table
     type: string
    applicationNumber:
     description: applicationNumber
     type: string
     maxLength: 20
    processRefNo:
     description: Process Ref No
     type: string
     maxLength: 20
    perfectionSeqNo:
     description: Perfection Sequence Number
     type: integer
    registrationAuthority:
     description: Registration Authority
     type: string
    registrationStatus:
     description: Registration Status
     type: string
    registrationReferenceNumber:
     description: Registartion Reference Number
     type: string
    registrationRequestDate:
     description: Registartion Request Date
     type: string
    registrationDate:
     description: Registartion Date
     type: string
    confirmationDate:
     description: Confirmation Date
     type: string
  PerfectionDetailsMasterCollection:
    description: Collection of PerfectionDetailsMasterModel.
    type: object
    properties:
     perfectionDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/PerfectionDetailsMasterModel'
  GenericDatasegmentModel:
    allOf:
    - type: object
      discriminator: resource_type
