#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : valuationdetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Collateral Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-collateralservices
tags:
- name: ValuationService
  description: API for Valuation Service
schemes:
- http
paths:
  /web/v1/valuationdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ValuationDetails
      summary: Adds a new ValuationDetails.
      description: Adds a new ValuationDetails. Add additional information here for this endpoint.
      operationId: addValuationDetails
      parameters:
      - name: ValuationDetails
        in: body
        description: Request Body that contains data required for creating a new ValuationDetails
        required: true
        schema:
          $ref: '#/definitions/ValuationDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created ValuationDetails
          headers:
            Location:
              description: URL of newly created ValuationDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ValuationDetails
      summary: Retrieves the list of existing ValuationDetails.
      description: Retrieves the list of existing ValuationDetails. Add additional information here for the this endpoint.
      operationId: getAllValuationDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/valuationdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ValuationDetails
      summary: Retrieves the ValuationDetails by id.
      description: Retrieves the ValuationDetails by id. Add additional information here for the this endpoint.
      operationId: getValuationDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ValuationDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/ValuationDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ValuationDetails
      summary: Update an existing ValuationDetails.
      description: Update an existing ValuationDetails. Add additional information here for the this endpoint.
      operationId: updateValuationDetails
      parameters:
      - name: id
        in: path
        description: id of the ValuationDetails that need to be updated
        required: true
        type: string
      - name: ValuationDetails
        in: body
        description: Request Body that contains data required for updating an existing ValuationDetails
        required: true
        schema:
          $ref: '#/definitions/ValuationDetailsMasterModel'
      responses:
        200:
          description: Returns updated ValuationDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ValuationDetails
      summary: Deletes the ValuationDetails identified by given ID.
      description: Deletes the ValuationDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteValuationDetails
      parameters:
      - name: id
        in: path
        description: Id of the ValuationDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ValuationDetailsMasterModel:
    description: ValuationDetails Master model
    type: object
    allOf:
    - $ref: '#/definitions/GenericDatasegmentModel'
    - type: object
    properties:
      processRefNo:
       description: Process Ref Number
       type: string
      isLocalCollateral:
       description: Is Local Collateral or Not?
       type: boolean
      accountCurrency:
       description: Account Currency
       type: string
      onboarded:
       description: Is All Collateral Onboarded
       type: boolean
       default: false
      applicationDate:
       description: Application Date
       type: string
      applicationTotal:
       description: application Total
       type: number 
      valuationApplicantDetailsList:
       type: array
       items:
         $ref: '#/definitions/ValuationApplicantDetailsModel'
  ValuationApplicantDetailsModel:
   description: Valuation Applicant Details Model
   type: object
   properties:
    id:
     description: Id of the Valuation Applicant Details Model
     type: string
    valuationDetailsMasterId:
     description: Id of Valuation Details Master Table
     type: string
    applicationNumber:
     description: Application Number
     type: string
     maxLength: 20 
    processRefNo:
     description: Process Ref Number
     type: string
     maxLength: 20
    applicantId:
     description: Applicant ID
     type: string
    partyId:
     description: Party ID
     type: string
    customerId:
     description: Customer ID
     type: string
    customerName:
     description: Customer Name
     type: string
    primaryApplicant:
     description: Primary Applicant Y/N
     type: boolean
    existingCustomer:
     description: Existing Customer Y/N
     type: boolean
    deleteValuation:
     description: Delete Valuation
     type: boolean 
    dateOfBirth:
     description: Date of Birth
     type: string
    email:
     description: Email
     type: string
    mobileNumber:
     description: Mobile Number
     type: integer
     format: int64
    mobileIsd:
     description: Mobile ISD
     type: string
    phoneNo:
     description: Phone Number
     type: integer
     format: int64
    phoneIsd:
     description: Phone ISD
     type: string 
    applicantTotal:
     description: applicant Total
     type: number   
    valuationDetailsList:
     type: array
     items:
      $ref: '#/definitions/ValuationDetailsModel'
  ValuationDetailsModel:
   description: Valuation Details Model
   type: object
   properties:
    id:
     description: Id of the Valuation Details Model
     type: string
    valuationApplicantDetailsId:
     description: Id of Valuation Applicant Details table
     type: string
    applicationNumber:
     description: applicationNumber
     type: string
     maxLength: 20
    processRefNo:
     description: Process Ref No
     type: string
     maxLength: 20
    collateralCode:
     description: Collateral Code
     type: string
    onboardApplicationNumber:
     description: Onboard Application Number
     type: string
    collateralType:
     description: Collateral Type
     type: string
    collateralCategory:
     description: Collateral Category
     type: string
    collateralDesc:
     description: Collateral Description
     type: string
    collateralRefNo:
     description: Collateral Ref No
     type: string
    primaryCollateral:
     description: Primary Collateral
     type: boolean
     default: false
    liabilityId:
     description: Liability Id
     type: string
    liabilityDesc:
     description: Liability Description
     type: string
    collateralCCY:
     description: Collateral CCY
     type: string
    collateralAmount:
     description: Collateral Amount
     type: number
    haircut:
     description:  HairCut %
     type: number
    deleteCollateral:
     description: Delete Collateral
     type: boolean
    valuationReviewList:
     type: array
     items:
      $ref: '#/definitions/ValuationReviewModel'
  ValuationReviewModel:
   description: Valuation Review Model
   type: object
   properties:
    id:
     description: Id of the Valuation Review Model
     type: string
    valuationDetailsId:
     description: Id of Valuation Details table
     type: string
    applicationNumber:
     description: applicationNumber
     type: string
     maxLength: 20
    processRefNo:
     description: Process Ref No
     type: string
     maxLength: 20
    valuationSeqNo:
     description: Valuation Sequence Number
     type: integer
    valuationType:
     description: Valuation Type
     type: string
    valuationCCY:
     description: Valuation Currency
     type: string
    valuationAmount:
     description: Valuation Amount
     type: number
    agencyCode:
     description: Agency Code
     type: string
    agencyName:
     description: Agency Name
     type: string
    valuationDate:
     description: Valuation Date
     type: string
  ValuationDetailsMasterCollection:
    description: Collection of ValuationDetailsMasterModel.
    type: object
    properties:
     valuationDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/ValuationDetailsMasterModel'
  GenericDatasegmentModel:
    allOf:
    - type: object
      discriminator: resource_type