#  This source is part of the Oracle Banking Software Product. 
#  Copyright  2018 , 2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : customercategory
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server customercategories server." 
 version: "1.0.0"
 title: "customercategories Service"
host: "ofss220245:7001"
basePath: "/cmc-customer-category-services"
tags:
 - name: "customercategories"
   description: "API for customercategories Operations"

schemes:
- "http"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../customercategories

 /customercategories:
  post:
   tags:
    - "customercategories"
   summary: "Adds a new customercategories."
   description: "Adds a new customercategories. Add additional information here for this endpoint."
   operationId: "saveRecord"
   consumes:
   - "application/json"
   - "application/xml"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "customercategories" 
      in: "body" 
      description: "Request Body that contains data required for creating a new customercategories" 
      required: true
      schema:
       $ref: "#/definitions/CmcTmCustomerCategoryDto"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created customercategories" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "customercategories"
   summary: "Get all valid customercategories."
   description:  "Get all valid customercategories. This endpoints will be used to Get all valid customercategoriesmaintanence records."
   operationId: "getAll"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - name: "customerCategory"
     in: "query"
     description: "Filtered on basis of Customer Category"
     type: "string"
   - in: query
     name: authStatus
     required: false
     type: string
   - in: query
     name: recordStatus
     required: false
     type: string
   responses: 
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CmcTmCustomerCategoryCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../customercategories/xxx
#   DELETE    .../customercategories/xxx
#   GET       .../customercategories/xxx
#   GET       .../customercategories/xxx?version=latestrecord
#   GET       .../customercategories/xxx?version=1

 /customercategories/{id}:
  put:
   tags:
    - "customercategories"
   summary: "Update an existing customercategories."
   description:  "Update an existing customercategories."
   operationId: "modifyRecord"
   consumes:
   - "application/json"
   - "application/xml"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the customercategories Maintenance"
      required: true
      type: "string"
    - name: "customercategories"
      in: "body"
      description: "Request Body that contains data required for updating an existing customercategories"
      required: true
      schema:
       $ref: "#/definitions/CmcTmCustomerCategoryDto"
   responses:
    200:
     description: "Returns updated customercategories"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "customercategories"
   summary: "Retrieves the customercategories by ID."
   description:  "Retrieves the customercategories by ID."
   operationId: "getById"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the customercategories based on given id."
     schema:
      $ref: "#/definitions/CmcTmCustomerCategoryWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "customercategories"
   summary: "Deletes the customercategories identified by given ID."
   description:  "Deletes the customercategories identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   consumes:
   - "application/json"
   - "application/xml"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the customercategories maintenance"
      required: true
      type: "string"
    - name: "customercategories"
      in: "body"
      description: Request body contain customercategories and Modification no of customercategories Maintenece which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../customercategories/xxx/approve

 /customercategories/{id}/approve:
  patch:
   tags:
    - "customercategories"
   summary: "Authorize the customercategories by given ID."
   description:  "Authorize the customercategories identified by given ID."
   operationId: "authorize"
   consumes:
   - "application/json"
   - "application/xml"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the customercategories maintenance"
      required: true
      type: "string"
    - name: "customercategories"
      in: "body"
      description: Request body contain customercategories and Modification no of customercategories maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../customercategories/xxx/close
 /customercategories/{id}/close:
  patch:
   tags:
    - "customercategories"
   summary: "Close the customercategories by given ID."
   description:  "Close the customercategories identified by given ID."
   operationId: "closeRecord"
   consumes:
   - "application/json"
   - "application/xml"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the customercategories maintenance"
      required: true
      type: "string"
    - name: "customercategories"
      in: "body"
      description: Request body contain customercategories and Modification no of customercategories maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../customercategories/xxx/reopen

 /customercategories/{id}/reopen:
  patch:
   tags:
    - "customercategories"
   summary: "reopen the customercategories by given ID."
   description:  "reopen the customercategories identified by given ID."
   operationId: "reopenRecord"
   consumes:
   - "application/json"
   - "application/xml"
   produces: 
   - "application/json"
   - "application/xml"   
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the customercategories maintenance"
      required: true
      type: "string"
    - name: "customercategories"
      in: "body"
      description: Request body contain customercategories and Modification no of customercategories maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../customercategories/xxx/unauthorized

 /customercategories/{id}/unauthorized:
  get:
   tags:
    - "customercategories"
   summary: "Retrives the customercategories by given ID."
   description:  "Retrives the customercategories identified by given ID."
   operationId: "authQuery"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the customercategories based on given id."
     schema:
       $ref: "#/definitions/CmcTmCustomerCategoryCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../customercategories/xxx/history

 /customercategories/{id}/history:
  get:
   tags:
    - "customercategories"
   summary: "Retrives the customercategories by given ID."
   description:  "Retrives the customercategories by ID."
   operationId: "getHistory"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the customercategories based on given id."
     schema:
       $ref: "#/definitions/CmcTmCustomerCategoryCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
# path to  view changes of  record
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../customercategories/xxx/history

 /customercategories/{id}/viewchanges:
  get:
   tags:
    - "customercategories"
   summary: "Retrives the customercategories by given ID."
   description:  "Retrives the customercategories by ID."
   operationId: "viewChanges"
   produces:
   - "application/json"
   - "application/xml"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the customercategory based on given id."      
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CmcTmCustomerCategoryDto:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     customerCategory:
      type: string
      description: "customerCategory"
      minLength: 0
      maxLength: 10
      pattern: "^[A-Z0-9*_]*$"
     customerCategoryDesc:
      type: string
      description: "customerCategoryDesc"
      minLength: 0
      maxLength: 105
     populateChangesLog:
      type: string
      description: "populateChangesLog"
      minLength: 0
      maxLength: 1
      pattern: "^(?:Y|N)$"
    required:
    - customerCategory
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CmcTmCustomerCategoryCollection: 
  description: "Collection of customercategory."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CmcTmCustomerCategoryDto"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CmcTmCustomerCategoryWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CmcTmCustomerCategoryDto" 

