#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : syndicationrequirement.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/syndicationrequirement:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Adds a new SyndicationRequirement.
      description: Adds a new SyndicationRequirement. Add additional information here for this endpoint.
      operationId: addSyndicationRequirement
      parameters:
      - name: SyndicationRequirement
        in: body
        description: Request Body that contains data required for creating a new SyndicationRequirement
        required: true
        schema:
          $ref: '#/definitions/SyndicationRequirementModel'
      responses:
        201:
          description: Returns the Id of the newly created SyndicationRequirement
          headers:
            Location:
              description: URL of newly created SyndicationRequirement
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Retrieves the list of existing SyndicationRequirement.
      description: Retrieves the list of existing SyndicationRequirement. Add additional information here for the this endpoint.
      operationId: getAllSyndicationRequirement
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/syndicationrequirement/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Retrieves the SyndicationRequirement by id.
      description: Retrieves the SyndicationRequirement by id. Add additional information here for the this endpoint.
      operationId: getSyndicationRequirementById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the SyndicationRequirement based on given applicationNumber.
          schema:
            $ref: '#/definitions/SyndicationRequirementModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Update an existing SyndicationRequirement.
      description: Update an existing SyndicationRequirement. Add additional information here for the this endpoint.
      operationId: updateSyndicationRequirement
      parameters:
      - name: id
        in: path
        description: id of the SyndicationRequirement that need to be updated
        required: true
        type: string
      - name: SyndicationRequirement
        in: body
        description: Request Body that contains data required for updating an existing SyndicationRequirement
        required: true
        schema:
          $ref: '#/definitions/SyndicationRequirementModel'
      responses:
        200:
          description: Returns updated SyndicationRequirement
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Deletes the SyndicationRequirement identified by given ID.
      description: Deletes the SyndicationRequirement identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteSyndicationRequirement
      parameters:
      - name: id
        in: path
        description: Id of the SyndicationRequirement that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/syndicationrequirement/summary/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - SyndicationRequirement
      summary: Retrieves the Syndication Requirement Summary.
      description: Retrieves the Syndication Requirement Summary.
      operationId: getSyndicationRequirementSummary
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the Syndication Requirement that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the Syndication Requirement based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  SyndicationRequirementModel:
    description: SyndicationRequirement model
    type: object
    properties:
      id:
        description: Id of the SyndicationRequirement
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      totalExpFacilityAmount:
        description: Total Expected Facility Amount
        type: number
      facilityCurrency:
        description: Facility Currency
        type: string
        maxLength: 4
      syndicationRequirementDetails:
        type: array
        items:
          $ref: '#/definitions/SyndicationRequirementDetailsModel'
  SyndicationRequirementDetailsModel:
    description: SyndicationRequirementDetails model
    type: object
    required:
    - facilityType
    - expFacilityAmount
    - facilityCurrency
    - expFacilityStartDate
    properties:
      id:
        description: Id of the SyndicationRequirementDetails
        type: string
      synReqId:
        description: synReqId
        type: string
      facilityType:
        description: Facility Type
        type: string
        maxLength: 36
      expFacilityAmount:
        description: Expected Facility Amount
        type: number
      facilityCurrency:
        description: Facility Currency
        type: string
        maxLength: 4
      expFacilityStartDate:
        description: Expected Facility Start Date
        type: string
      expFacilityTenor:
        description: Expected Facility Tenor
        type: number
      syndicationRequirementUtilCcy:
        type: array
        items:
          $ref: '#/definitions/SyndicationRequirementUtilCcyModel'
      syndicationFacilityPurpose:
        type: array
        items:
          $ref: '#/definitions/SyndicationFacilityPurposeModel'
      syndicationExpectedCollateral:
        type: array
        items:
          $ref: '#/definitions/SyndicationExpectedCollateralModel'
  SyndicationRequirementUtilCcyModel:
    description: SyndicationRequirementUtilCcy model
    type: object
    required:
    - utilCurrencyCode
    properties:
      id:
        description: Id of the SyndicationRequirementUtilCcy
        type: string
      synReqDetailsId:
        description: synReqDetailsId
        type: string
      utilCurrencyCode:
        description: Util Currency
        type: string
  SyndicationFacilityPurposeModel:
    description: SyndicationFacilityPurpose model
    type: object
    required:
    - facilityPurpose
    properties:
      id:
        description: Id of the SyndicationFacilityPurpose
        type: string
      synReqDetailsId:
        description: synReqDetailsId
        type: string
      facilityPurpose:
        description: Facility Purpose
        type: string
  SyndicationExpectedCollateralModel:
    description: SyndicationExpectedCollateral model
    type: object
    properties:
      id:
        description: Id of the SyndicationExpectedCollateral
        type: string
      synReqDetailsId:
        description: synReqDetailsId
        type: string
      expectedCollateralCode:
        description: expected Collateral
        type: string
  SyndicationRequirementSummaryModel:
    description: Syndication Requirement Summary model
    type: object
    properties:
      facilityType:
        description: Facility Type of the Syndication Requirement
        type: string
        maxLength: 36
      expFacilityAmount:
        description: Expected Facility Amount of the Syndication Requirement
        type: number
        maxLength: 36
  SyndicationRequirementCollection:
    description: Collection of SyndicationRequirement.
    type: object
    properties:
      SyndicationRequirementList:
        type: array
        items:
          $ref: '#/definitions/SyndicationRequirementModel'
