#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : scheduleBreakup.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/schedulebreakup:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleBreakup
      summary: Adds a new ScheduleBreakup.
      description: Adds a new ScheduleBreakup. Add additional information here for this endpoint.
      operationId: addScheduleBreakup
      parameters:
      - name: ScheduleBreakup
        in: body
        description: Request Body that contains data required for creating a new ScheduleBreakup
        required: true
        schema:
          $ref: '#/definitions/ScheduleBreakupModel'
      responses:
        201:
          description: Returns the Id of the newly created ScheduleBreakup
          headers:
            Location:
              description: URL of newly created ScheduleBreakup
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleBreakup
      summary: Retrieves the list of existing ScheduleBreakup.
      description: Retrieves the list of existing ScheduleBreakup. Add additional information here for the this endpoint.
      operationId: getAllScheduleBreakup
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/schedulebreakup/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleBreakup
      summary: Retrieves the ScheduleBreakup by id.
      description: Retrieves the ScheduleBreakup by id. Add additional information here for the this endpoint.
      operationId: getScheduleBreakupById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ScheduleBreakup based on given applicationNumber.
          schema:
            $ref: '#/definitions/ScheduleBreakupModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleBreakup
      summary: Update an existing ScheduleBreakup.
      description: Update an existing ScheduleBreakup. Add additional information here for the this endpoint.
      operationId: updateScheduleBreakup
      parameters:
      - name: id
        in: path
        description: id of the ScheduleBreakup that need to be updated
        required: true
        type: string
      - name: ScheduleBreakup
        in: body
        description: Request Body that contains data required for updating an existing ScheduleBreakup
        required: true
        schema:
          $ref: '#/definitions/ScheduleBreakupModel'
      responses:
        200:
          description: Returns updated ScheduleBreakup
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleBreakup
      summary: Deletes the ScheduleBreakup identified by given ID.
      description: Deletes the ScheduleBreakup identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteScheduleBreakup
      parameters:
      - name: id
        in: path
        description: Id of the ScheduleBreakup that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ScheduleBreakupModel:
    description: ScheduleBreakup model
    type: object
    allOf:
    - $ref: '#/definitions/GenericDatasegmentModel'
    - type: object
    properties:
      id:
        description: Id of the ScheduleBreakup
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      remarks:
        description: remarks
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      contractReferenceNumber:
        description: contractReferenceNumber
        type: string
      scheduleDetails:
        type: array
        items:
          $ref: '#/definitions/ScheduleDetailsModel'
  ScheduleDetailsModel:
    description: ScheduleDetails model
    type: object
    properties:
      id:
        description: Id of the ScheduleDetails
        type: string
      scheduleBreakupId:
        description: scheduleBreakupId
        type: string
      dueDate:
        description: dueDate
        type: string
      totalAmountDue:
        description: totalAmountDue
        type: number
      totalAmountPaid:
        description: totalAmountPaid
        type: number
      currency:
        description: currency
        type: string
      componentDetails:
        type: array
        items:
          $ref: '#/definitions/ComponentDetailsModel'
  ComponentDetailsModel:
    description: ComponentDetails model
    type: object
    properties:
      id:
        description: Id of the ComponentDetails
        type: string
      scheduleDetailsId:
        description: scheduleDetailsId
        type: string
      component:
        description: component
        type: string
      description:
        description: description
        type: string
      amountDue:
        description: amountDue
        type: number
      amountPaid:
        description: amountPaid
        type: number
      currency:
        description: currency
        type: string
  ScheduleBreakupCollection:
    description: Collection of ScheduleBreakup.
    type: object
    properties:
      ScheduleBreakupList:
        type: array
        items:
          $ref: '#/definitions/ScheduleBreakupModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type  
