#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : rolloverpreferences.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/rolloverpreferences:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RolloverPreferences
      summary: Adds a new RolloverPreferences.
      description: Adds a new RolloverPreferences. Add additional information here for this endpoint.
      operationId: addRolloverPreferences
      parameters:
      - name: RolloverPreferences
        in: body
        description: Request Body that contains data required for creating a new RolloverPreferences
        required: true
        schema:
          $ref: '#/definitions/RolloverPreferencesModel'
      responses:
        201:
          description: Returns the Id of the newly created RolloverPreferences
          headers:
            Location:
              description: URL of newly created RolloverPreferences
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RolloverPreferences
      summary: Retrieves the list of  RolloverPreferences.
      description: Retrieves the list of  RolloverPreferences. Add additional information here for the this endpoint.
      operationId: getAllRolloverPreferences
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/rolloverpreferences/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RolloverPreferences
      summary: Get a  RolloverPreferences.
      description: Update a  RolloverPreferences. Add additional information here for the this endpoint.
      operationId: getRolloverPreferencesById
      parameters:
      - name: id
        in: path
        description: id of the RolloverPreferences that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated RolloverPreferences
          schema:
            $ref: '#/definitions/RolloverPreferencesModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RolloverPreferences
      summary: Update an  RolloverPreferences.
      description: Update an  RolloverPreferences. Add additional information here for the this endpoint.
      operationId: updateRolloverPreferences
      parameters:
      - name: id
        in: path
        description: id of the RolloverPreferences that need to be updated
        required: true
        type: string
      - name: RolloverPreferences
        in: body
        description: Request Body that contains data required for updating an  RolloverPreferences
        required: true
        schema:
          $ref: '#/definitions/RolloverPreferencesModel'
      responses:
        200:
          description: Returns updated RolloverPreferences
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - RolloverPreferences
      summary: Deletes the A RolloverPreferencesidentified by given ID.
      description: Deletes the RolloverPreferences identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteRolloverPreferences
      parameters:
      - name: id
        in: path
        description: Id of the RolloverPreferences that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  RolloverPreferencesModel:
   description: RolloverPreferences model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     required:
     - maturityType
     - amountType
     - rolloverMode
     - rolloverMechanism
     - rolloverWithSpecialAmount
     properties:
      amountType:
        description: rollOverType of the RolloverPreferences
        type: string
        maxLength: 20
      currencyCode:
        description: currencyCode of the RolloverPreferences
        type: string
        maxLength: 3
      specialAmount:
        description: specialAmount  of the RolloverPreferences
        type: number
        minimum: 0
      treatSpecialAmount:
        description: treatSpecialAmount of the RolloverPreferences
        type: string
      liquidateOverdueSchedules:
        description: liquidateOverdueSchedules of the RolloverPreferences
        type: string
      maturityType:
        description: maturityType of the RolloverPreferences
        type: string
        maxLength: 20
      maturityDate:
        description: treatSpecialAmount of the RolloverPreferences
        type: string
      noticeDays:
        description: noticeDays of the RolloverPreferences
        type: number
        minLength: 0
        maxLength: 5
      maturityDays:
        description: maturityDays of the RolloverPreferences
        type: number
        minLength: 0
        maxLength: 5
      noticePeriod:
        description: noticePeriod of the RolloverPreferences
        type: number
        minLength: 0
        maxLength: 5
      noticeFrequency:
        description: noticeFrequency of the RolloverPreferences
        type: string
        maxLength: 1
      rolloverMode:
        description: rolloverMode of the RolloverPreferences
        type: string
        maxLength: 1
      rolloverMechanism:
        description: rolloverMechanism of the RolloverPreferences
        type: string
        maxLength: 1
      scheduleDefinition:
        description: scheduleDefinition of the RolloverPreferences
        type: string
        maxLength: 1
      rateDefinition:
        description: rateDefinition of the RolloverPreferences
        type: string
        maxLength: 1
      rolloverWithSpecialAmount:
        description: rolloverWithSpecialAmount of the RolloverPreferences
        type: string
        maxLength: 1
      rolloverInterestDetails:
        type: array
        items:
          $ref: '#/definitions/RolloverInterestDetailsModel'
  RolloverInterestDetailsModel:
    description: Rollover Interest Details
    type: object
    required:
    - component
    - rateType
    - subRateType
    - rate
    properties:
      id:
        description: Id of the Rollover Interest Details
        type: string
        maxLength: 36
      rolloverPreferencesId:
        description: Id of the Rollover Interest Details
        type: string
        maxLength: 36
      component:
        description: Component Name
        type: string
        maxLength: 22
      rateType:
        description: rateType either floating or fixed or special rate
        type: string
        maxLength: 12
      subRateType:
        description: subRateType values for the selected rate type
        type: string
        maxLength: 12
      spread:
        description: specify the spread for the rate
        type: number
        maxLength: 3
        minLength: 0
      amount:
        description: specify the flat interest rate amount
        type: number
        minimum: 0
      rate:
        description: allow to input rate in case of special rate user input
        type: string
  RolloverPreferencesCollection:
    description: Collection of RolloverPreferences.
    type: object
    properties:
      RolloverPreferencesList:
        type: array
        items:
          $ref: '#/definitions/RolloverPreferencesModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type