#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cam
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server questionnaire definition server." 
 version: "1.0.0"
 title: "Questionnaire Definition Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "questionnairedetails"
   description: "A micro service that will maintain questionnaire details in a separate table. This service will also provide APIs for GET, PUT, DELETE, GET by id, Authorize the given record, Reopen and Close APIs for the maintenance records."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../questionnairedetails

 /questionnairedetails:
  post:
   tags:
    - "questionnairedetails"
   summary: "Adds a new questionnairedetails."
   description: "Adds a new questionnairedetails. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "questionnairedetails" 
      in: "body" 
      description: "Request Body that contains data required for creating a new questionnairedetails" 
      required: true
      schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for creating a new questionnairedetails" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created questionnairedetails" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "questionnairedetails"
   summary: "Get all valid questionnairedetails."
   description:  "Get all valid questionnairedetails. This endpoints will be used to Get all valid questionnairedetails maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../questionnairedetails/xxx
#   DELETE    .../questionnairedetails/xxx
#   GET       .../questionnairedetails/xxx
#   GET       .../questionnairedetails/xxx?version=latestrecord
#   GET       .../questionnairedetails/xxx?version=1

 /questionnairedetails/{id}:
  put:
   tags:
    - "questionnairedetails"
   summary: "Update an existing questionnairedetails."
   description:  "Update an existing questionnairedetails."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the questionnairedetails Maintenance"
      required: true
      type: "string"
    - name: "questionnairedetails"
      in: "body"
      description: "Request Body that contains data required for updating an existing questionnairedetails"
      required: true
      schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for modify an existing record questionnairedetails" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    200:
     description: "Returns updated questionnairedetails"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "questionnairedetails"
   summary: "Retrieves the questionnairedetails by ID."
   description:  "Retrieves the questionnairedetails by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the questionnairedetails based on given id."
     schema:
      $ref: "#/definitions/CfpmTmQuestionnaireMasterWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "questionnairedetails"
   summary: "Deletes the questionnairedetails identified by given ID."
   description:  "Deletes the questionnairedetails identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the questionnairedetails maintenance"
      required: true
      type: "string"
    - name: "questionnairedetails"
      in: "body"
      description: Request body contain questionnairedetails and Modification no of questionnairedetails maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
     
 /questionnairedetails/categoryCode/{categoryCode}:
  get:
   tags:
    - "questionnairedetails"
   summary: "Get all valid questionnairedetails for the given category code."
   description:  "Get all valid questionnairedetails for the given category code. This endpoints will be used to Get all valid questionnairedetails maintenance records."
   operationId: "getQuestionnaireByCatCode"
   parameters:
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - name: "categoryCode"
     in: "path"
     description: "Category Code for which the questionnaire details has to be fetched."
     required: true
     type: "string"
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../questionnairedetails/xxx/approve

 /questionnairedetails/{id}/approve:
  patch:
   tags:
    - "questionnairedetails"
   summary: "Authorize the questionnairedetails by given ID."
   description:  "Authorize the questionnairedetails identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the questionnairedetails maintenance"
      required: true
      type: "string"
    - name: "questionnairedetails"
      in: "body"
      description: Request body contain questionnairedetails and Modification no of questionnairedetails maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../questionnairedetails/xxx/close
 /questionnairedetails/{id}/close:
  patch:
   tags:
    - "questionnairedetails"
   summary: "Close the questionnairedetails by given ID."
   description:  "Close the questionnairedetails identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the questionnairedetails maintenance"
      required: true
      type: "string"
    - name: "questionnairedetails"
      in: "body"
      description: Request body contain questionnairedetails and Modification no of questionnairedetails maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../questionnairedetails/xxx/reopen

 /questionnairedetails/{id}/reopen:
  patch:
   tags:
    - "questionnairedetails"
   summary: "reopen the questionnairedetails by given ID."
   description:  "reopen the questionnairedetails identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the questionnairedetails maintenance"
      required: true
      type: "string"
    - name: "questionnairedetails"
      in: "body"
      description: Request body contain questionnairedetails and Modification no of questionnairedetails maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../questionnairedetails/xxx/unauthorized

 /questionnairedetails/{id}/unauthorized:
  get:
   tags:
    - "questionnairedetails"
   summary: "Retrives the questionnairedetails by given ID."
   description:  "Retrives the questionnairedetails identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the questionnairedetails based on given id."
     schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../questionnairedetails/xxx/history

 /questionnairedetails/{id}/history:
  get:
   tags:
    - "questionnairedetails"
   summary: "Retrives the questionnairedetails by given ID."
   description:  "Retrives the questionnairedetails by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the questionnairedetails based on given id."
     schema:
       $ref: "#/definitions/CfpmTmQuestionnaireMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CfpmTmQuestionnaireMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     categoryCode:
      type: string
      description: ""
     questionnaireId:
      type: string
      description: ""
     questionnaireDesc:
      type: string
      description: ""
     questionDetails:
      type: array
      items:
       $ref: '#/definitions/CfpmTmQuestionnaireDetailsDTO'
 CfpmTmQuestionnaireDetailsDTO:
  type: object
  properties:
     cfpmTmQuestionnaireMasterId:
      type: string
      description: ""
     factor:
      type: number
      description: ""
     id:
      type: string
      description: ""
     subCategoryCode:
      type: string
      description: ""
     questionCode:
      type: string
      description: ""
     questionDescription:
      type: string
      description: ""
     answerDetails:
      type: array
      items:
       $ref: '#/definitions/CfpmTmQstnAnswrDetailsDTO'
 CfpmTmQstnAnswrDetailsDTO:
  type: object
  properties:
     answerDescription:
      type: string
      description: ""
     answerCode:
      type: string
      description: ""
     cfpmTmQuestionnaireDetailsId:
      type: string
      description: ""
     id:
      type: string
      description: ""
     questionCode:
      type: string
      description: ""
     score:
      type: number
      description: ""
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CfpmTmQuestionnaireMasterCollection: 
  description: "Collection of questionnaire."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CfpmTmQuestionnaireMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CfpmTmQuestionnaireMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CfpmTmQuestionnaireMasterDTO"
