#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : creditapproval.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/creditapproval:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditApproval
      summary: Adds a new CreditApproval.
      description: Adds a new CreditApproval. Add additional information here for this endpoint.
      operationId: addCreditApproval
      parameters:
      - name: CreditApproval
        in: body
        description: Request Body that contains data required for creating a new CreditApproval
        required: true
        schema:
          $ref: '#/definitions/CreditApprovalModel'
      responses:
        201:
          description: Returns the Id of the newly created CreditApproval
          headers:
            Location:
              description: URL of newly created CreditApproval
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditApproval
      summary: Retrieves the list of existing CreditApproval.
      description: Retrieves the list of existing CreditApproval. Add additional information here for the this endpoint.
      operationId: getAllCreditApproval
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/creditapproval/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditApproval
      summary: Retrieves the CreditApproval by id.
      description: Retrieves the CreditApproval by id. Add additional information here for the this endpoint.
      operationId: getCreditApprovalById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CreditApproval based on given applicationNumber.
          schema:
            $ref: '#/definitions/CreditApprovalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditApproval
      summary: Update an existing CreditApproval.
      description: Update an existing CreditApproval. Add additional information here for the this endpoint.
      operationId: updateCreditApproval
      parameters:
      - name: id
        in: path
        description: id of the CreditApproval that need to be updated
        required: true
        type: string
      - name: CreditApproval
        in: body
        description: Request Body that contains data required for updating an existing CreditApproval
        required: true
        schema:
          $ref: '#/definitions/CreditApprovalModel'
      responses:
        200:
          description: Returns updated CreditApproval
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditApproval
      summary: Deletes the CreditApproval identified by given ID.
      description: Deletes the CreditApproval identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCreditApproval
      parameters:
      - name: id
        in: path
        description: Id of the CreditApproval that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  CreditApprovalModel:
    description: CreditApproval model
    type: object
    properties:
      id:
        description: Id of the CreditApproval
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string
      remarks:
        description: remarks
        type: string
      creditApprovalInitiationStatus:
        description: crApprvlInitiateStatus
        type: string
      initialApplicationRef:
        description: initialApplicationRef
        type: string
      creditApprovalDetails:
        type: array
        items:
          $ref: '#/definitions/CreditApprovalDetailsModel'
      creditConditions:
        type: array
        items:
          $ref: '#/definitions/CreditConditionsModel'
  CreditApprovalDetailsModel:
    description: CreditApprovalDetails model
    type: object
    properties:
      id:
        description: Id of the CreditApprovalDetails
        type: string
      creditApprvlId:
        description: creditApprvlId
        type: string
      trancheId:
        description: trancheId
        type: string
      trancheName:
        description: trancheName
        type: string
      trancheCurrency:
        description: trancheCurrency
        type: string
      proposedAmount:
        description: proposedAmount
        type: number
      approvedAmount:
        description: approvedAmount
        type: number
  CreditConditionsModel:
    description: CreditConditions model
    type: object
    properties:
      id:
        description: Id of the CreditConditions
        type: string
      creditApprvlId:
        description: creditApprvlId
        type: string
      creditCondition:
        description: creditCondition
        type: string
      condDueDate:
        description: condDueDate
        type: string
      condStage:
        description: condStage
        type: string
  CreditApprovalCollection:
    description: Collection of CreditApproval.
    type: object
    properties:
      CreditApprovalList:
        type: array
        items:
          $ref: '#/definitions/CreditApprovalModel'
