#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : drawdownsettlements.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/drawdownsettlements:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DDSettlementTrancheLinkage
      summary: Adds a new DDSettlementTrancheLinkage.
      description: Adds a new DDSettlementTrancheLinkage. Add additional information here for this endpoint.
      operationId: addSettlementTrancheLinkage
      parameters:
      - name: DDSettlementTrancheLinkageModel
        in: body
        description: Request Body that contains data required for creating a new DDSettlementTrancheLinkage
        required: true
        schema:
          $ref: '#/definitions/DDSettlementTrancheLinkageModel'
      responses:
        201:
          description: Returns the Id of the newly created DDSettlementTrancheLinkage
          headers:
            Location:
              description: URL of newly created DDSettlementTrancheLinkage
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DDSettlementTrancheLinkage
      summary: Retrieves the list of existing DDSettlementTrancheLinkage.
      description: Retrieves the list of existing DDSettlementTrancheLinkage. Add additional information here for the this endpoint.
      operationId: getAllSettlementTrancheLinkage
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/drawdownsettlements/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DDSettlementTrancheLinkage
      summary: Retrieves the DDSettlementTrancheLinkage by id.
      description: Retrieves the DDSettlementTrancheLinkage by id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DDSettlementTrancheLinkage based on given applicationNumber.
          schema:
            $ref: '#/definitions/DDSettlementTrancheLinkageModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DDSettlementTrancheLinkage
      summary: Update an existing DDSettlementTrancheLinkage.
      description: Update an existing DDSettlementTrancheLinkage. Add additional information here for the this endpoint.
      operationId: updateSettlementTrancheLinkage
      parameters:
      - name: id
        in: path
        description: id of the DDSettlementTrancheLinkage that need to be updated
        required: true
        type: string
      - name: settlementtranchelinkage
        in: body
        description: Request Body that contains data required for updating an existing DDSettlementTrancheLinkage
        required: true
        schema:
          $ref: '#/definitions/DDSettlementTrancheLinkageModel'
      responses:
        200:
          description: Returns updated DDSettlementTrancheLinkage
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DDSettlementTrancheLinkage
      summary: Deletes the DDSettlementTrancheLinkage identified by given ID.
      description: Deletes the DDSettlementTrancheLinkage identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteSettlementTrancheLinkage
      parameters:
      - name: id
        in: path
        description: Id of the DDSettlementTrancheLinkage that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  DDSettlementTrancheLinkageModel:
    description: DDSettlementTrancheLinkage model
    type: object
    required:
    - applicationNumber
    properties:
      id:
        description: Id of the DDSettlementTrancheLinkage
        type: string
      applicationNumber:
        description: Application Number of the settlementtranchelinkage
        type: string
      processRefNumber:
        description: Process Ref Number
        type: string
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      settlementParties:
        type: array
        items:
          $ref: '#/definitions/DDSettlementPartiesModel'
  DDSettlementPartiesModel:
    description: DDSettlementParties model
    type: object
    properties:
      id:
        description: Id of the DDSettlementParties
        type: string
        maxLength: 36
      settlementTrancheLinkageId:
        description: settlementTrancheLinkageId
        type: string
        maxLength: 36
      partyName:
        description: partyName
        type: string
        maxLength: 35
      partyNumber:
        description: partyNumber
        type: string
        maxLength: 20
      partyId:
        description: partyId
        type: string
        maxLength: 36
      ssiPartyName:
        description: ssiPartyName
        type: string
        maxLength: 35
      ssiPartyNumber:
        description: ssiPartyNumber
        type: string
        maxLength: 20
      ssiPartyId:
        description: ssiPartyId
        type: string
        maxLength: 36
      settlementInstructions:
        type: array
        items:
          $ref: '#/definitions/DDSettlementInstructionsModel'
  DDSettlementInstructionsModel:
    description: DDSettlementInstructions model
    type: object
    properties:
      id:
        description: Id of the DDSettlementInstructions
        type: string
        maxLength: 36
      settlementPartiesId:
        description: settlementPartiesId
        type: string
        maxLength: 36
      settlementCurrency:
        description: settlementCurrency of the SettlementInstructionss
        type: string
        maxLength: 3
      ssiMnemonic:
        description: ssiMnemonic of the SettlementInstructionss
        type: string
        maxLength: 12
      beneficiaryName:
        description: Beneficiary name of the SettlementInstructionss
        type: string
        maxLength: 36
      beneficiaryBankAccNo:
        description: Beneficiary Account Number of the SettlementInstructionss
        type: string
        maxLength: 36
      beneficiaryBank:
        description: Beneficiary Bank of the SettlementInstructionss
        type: string
        maxLength: 36
      beneficiaryBankBranch:
        description: Beneficiary Bank Branch of the SettlementInstructionss
        type: string
        maxLength: 36
      beneficiaryBICCode:
        description: Beneficiary Bank Identifier Code of the SettlementInstructionss
        type: string
        maxLength: 36
      charges:
        description: Beneficiary Bank Identifier Code of the SettlementInstructionss
        type: string
        maxLength: 15
      correspondentBankAccNo:
        description: Beneficiary Account Number of the SettlementInstructionss
        type: string
        maxLength: 20
      correspondentBank:
        description: Beneficiary Bank of the SettlementInstructionss
        type: string
        maxLength: 35
      correspondentBankBranch:
        description: Beneficiary Bank Branch of the SettlementInstructionss
        type: string
        maxLength: 20
      correspondentBICCode:
        description: Beneficiary Bank Identifier Code of the SettlementInstructionss
        type: string
        maxLength: 11
      primaryFlag:
        description: SettlementInstruction is primary or not
        type: string
        maxLength: 1
      existingSSIFlag:
        description: SettlementInstruction is primary or not
        type: string
        maxLength: 1
      isINTNLAccountFlag:
        description: SettlementInstruction is intnla account or not
        type: string
        maxLength: 1
      settlementSequenceNumber:
        description: settlementSequenceNumber for SettlementInstruction
        type: string
        maxLength: 2
      payAccount:
        description: payAccount for SettlementInstruction
        type: string
        maxLength: 20
      receiveAccount:
        description: receiveAccount for SettlementInstruction
        type: string
        maxLength: 20
      payBranch:
        description: payBranch for SettlementInstruction
        type: string
        maxLength: 20
      receiveBranch:
        description: receiveBranch for SettlementInstruction
        type: string
        maxLength: 20
      payAccountCurrency:
        description: payAccountCurrency for SettlementInstruction
        type: string
        maxLength: 3
      receiveAccountCurrency:
        description: receiveAccountCurrency for SettlementInstruction
        type: string
        maxLength: 3
  DDSettlementTrancheLinkageCollection:
    description: Collection of DDSettlementTrancheLinkage.
    type: object
    properties:
      settlementTrancheLinkageList:
        type: array
        items:
          $ref: '#/definitions/DDSettlementTrancheLinkageModel'
