#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : dealpersonaldetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/dealpersonaldetails/summary/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Retrieves the DealPersonalDetails Summary.
      description: Retrieves the DealPersonalDetails Summary.
      operationId: getDealPersonalDetailsSummary
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the DealPersonalDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DealPersonalDetails based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/dealpersonaldetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Adds a new DealPersonalDetails.
      description: Adds a new DealPersonalDetails. Add additional information here for this endpoint.
      operationId: addDealPersonalDetails
      parameters:
      - name: DealPersonalDetails
        in: body
        description: Request Body that contains data required for creating a new DealPersonalDetails
        required: true
        schema:
          $ref: '#/definitions/DealPersonalDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created DealPersonalDetails
          headers:
            Location:
              description: URL of newly created DealPersonalDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Retrieves the list of existing DealPersonalDetails.
      description: Retrieves the list of existing DealPersonalDetails. Add additional information here for the this endpoint.
      operationId: getAllDealPersonalDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/dealpersonaldetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Retrieves the DealPersonalDetails by id.
      description: Retrieves the DealPersonalDetails by id. Add additional information here for the this endpoint.
      operationId: getDealPersonalDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DealPersonalDetails based on given applicationNumber.
          schema:
            $ref: '#/definitions/DealPersonalDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Update an existing DealPersonalDetails.
      description: Update an existing DealPersonalDetails. Add additional information here for the this endpoint.
      operationId: updateDealPersonalDetails
      parameters:
      - name: id
        in: path
        description: id of the DealPersonalDetails that need to be updated
        required: true
        type: string
      - name: DealPersonalDetails
        in: body
        description: Request Body that contains data required for updating an existing DealPersonalDetails
        required: true
        schema:
          $ref: '#/definitions/DealPersonalDetailsModel'
      responses:
        200:
          description: Returns updated DealPersonalDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Deletes the DealPersonalDetails identified by given ID.
      description: Deletes the DealPersonalDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteDealPersonalDetails
      parameters:
      - name: id
        in: path
        description: Id of the DealPersonalDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/dealpersonaldetails/projectnames:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DealPersonalDetails
      summary: Retrieves the DealPersonalDetails by id.
      description: Retrieves the DealPersonalDetails by id. Add additional information here for the this endpoint.
      operationId: getProjectNames
      parameters:
      - name: partyNumber
        in: query
        description: Id that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Returns the DealPersonalDetails based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  DealPersonalDetailsModel:
    description: DealPersonalDetails model
    type: object
    properties:
      id:
        description: Id of the DealPersonalDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      remarks:
        description: remarks
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      requesterName:
        description: Requester Name
        type: string
      transactionName:
        description: Transaction Name
        type: string
      dealPersonalDepartment:
        type: array
        items:
          $ref: '#/definitions/DealPersonalDepartmentModel'
  DealPersonalDepartmentModel:
    description: DealPersonalDepartment model
    type: object
    properties:
      id:
        description: Id of the DealPersonalDepartment
        type: string
      dealPersonalDetailsId:
        description: dealPersonalDetailsId
        type: string
      departmentName:
        description: Department Name
        type: string
      dealPersonal:
        description: Deal Personal
        type: string
        maxLength: 35
      name:
        description: Name
        type: string
        maxLength: 35
      email:
        description: Email
        type: string
  DealPersonalDetailsSummaryModel:
    description: DealPersonalDetails Summary model
    type: object
    properties:
      approverName:
        description: Approver Name of the DealPersonalDetails
        type: string
        maxLength: 36
      approverEmail:
        description: Approver Email of the DealPersonalDetails
        type: string
        maxLength: 36
  DealPersonalDetailsCollection:
    description: Collection of DealPersonalDetails.
    type: object
    properties:
      DealPersonalDetailsList:
        type: array
        items:
          $ref: '#/definitions/DealPersonalDetailsModel'
  MaintenanceCollection:
     description: Collection of DealPersonalDetails.
     type: object
     properties:
      data:
        type: array
        items:
          $ref: '#/definitions/MaintenanceProjectModel'
  MaintenanceProjectModel:
    description: DealPersonalDetails Summary model
    type: object
    properties:
      projectName:
        type: string
