#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : AccServicesPrefDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: AccServicesPrefDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /accservicesprefdetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for Account service preference Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/accservicesprefdetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - accServicesPrefDetails
      summary: Adds a new accservicesprefdetails.
      description: Adds a new accservicesprefdetails. Add additional information here for this endpoint.
      operationId: addAccServicesPrefDetails
      parameters:
      - name: AccServicesPrefDetails
        in: body
        description: Request Body that contains data required for creating a new accservicesprefdetails
        required: true
        schema:
          $ref: '#/definitions/AccServicesPrefMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created AccServicesPrefDetails.
          headers:
            Location:
              description: URL of newly created AccServicesPrefDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - accServicesPrefDetails
      summary: Retrieves the list of existing AccServicesPrefDetails.
      description: Retrieves the list of existing AccServicesPrefDetails. Add additional information here for the this endpoint.
      operationId: getAllAccServicesPrefDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the AccServicesPrefDetails that needs to be fetched
        required: true
        type: string
      - name: processRefNo
        in: query
        description: processRefNo of the AccServicesPrefDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/accservicesprefdetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - accServicesPrefDetails
      summary: Get By ID
      description: Retrieves the Account service preference details by Id. Add additional information here for the this endpoint.
      operationId: getAccServicesPrefDetailsById
      parameters:
      - name: id
        in: path
        description: ID of the Account service preference details that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AccServicesPrefDetails based on given ID.
          schema:
            $ref: '#/definitions/AccServicesPrefMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - accServicesPrefDetails
      summary: Update an existing AccServicesPrefDetails.
      description: Update an existing AccServicesPrefDetails. Add additional information here for the this endpoint.
      operationId: updateAccServicesPrefDetails
      parameters:
      - name: id
        in: path
        description: id of the Account Service Preference Details that need to be updated
        required: true
        type: string
      - name: AccServicesPrefDetails
        in: body
        description: Request Body that contains data required for updating an existing AccServicesPrefDetails
        required: true
        schema:
          $ref: '#/definitions/AccServicesPrefMasterModel'
      responses:
        200:
          description: Returns updated AccServicesPrefDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - accServicesPrefDetails
      summary: Deletes the AccServicesPrefDetails identified by given ID.
      description: Deletes the AccServicesPrefDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAccServicesPrefDetails
      parameters:
      - name: id
        in: path
        description: Id of the AccServicesPrefDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 AccServicesPrefMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     action:
      type: string
      description: action
     channel:
      type: string
      description: Channel 
     processRefNo:
      description: "Process reference number of Account Services Prefrences"
      type: string
      maxLength: 20
     applicationDate:
      type: string
      description: "Application initition date of Account Service Prefrences"
     accServicesPrefDetailsModel:
      type: array
      items:
       $ref: '#/definitions/AccServicesPrefDetailsModel'  
 AccServicesPrefDetailsModel:
    description: "Facility details of account"
    type: object
    properties:
     id:
      description: id
      type: string
     accSrvsPrefMasterId:
      description: id
      type: string 
     applicantId:
      description: Applicant Id
      type: string 
     primaryApplicant:
      description: Is PrimaryApplicant?
      type: boolean   
     applicantDetails:
      $ref: '#/definitions/ApplicantDetails'
     bankingChnlSubscription:
      $ref: '#/definitions/BankingChnlSubscription'
     communicationChnlSubscription:
      $ref: '#/definitions/CommunicationChnlSubscription'
 
 ApplicantDetails:
   description: "ApplicantDetailsModel"
   type: object
   properties:     
    custImgId:
     description: Customer Image Id
     type: string    
    title:
     description: title
     type: string
    custFullName:
     description: custName
     type: string
    dateOfBirth:
     description: dateOfBirth
     type: string 
    email:
      description: email
      type: string
    mobileNo:
      description: mobileNo
      type: string
    phoneNo:
      description: phoneNo
      type: string
    customerType:
      description: customerType
      type: string
    bussinessName:
      description: bussiness Name
      type: string
    incorporationDate:
      description: Date of Incorporation
      type: string

       
 BankingChnlSubscription:
   description: "Banking channel subscription details of account"
   type: object
   properties:
     directBanking:
      type: string
      description: "Direct Banking Channel Subscription applicable or not (Y/N)"
      pattern: '[Y,N]'
     directBankingAllowed:
      type: boolean
      description: "Direct banking Allowed?" 
     kioskBanking:
      type: string
      description: "KIOSK banking channel subscription applicable or not (Y/N)"
      pattern: '[Y,N]'
     kioskBankingAllowed:
      type: boolean
      description: "Kiosk banking Allowed?" 
     phoneBanking:
      type: string
      description: "Phone banking channel subscription applicable or not (Y/N)"
      pattern: '[Y,N]'
     phoneBankingAllowed:
      type: boolean
      description: "Phone banking Allowed?" 
 CommunicationChnlSubscription:
   description: "Communication Channel Details of account"
   type: object
   properties:
     email:
      type: string
      description: "E-Mail communication channel subscription applicable or not (Y/N)"
      pattern: '[Y,N]'
     emailAllowed:
      type: boolean
      description: "Email Communication Allowed?" 
     post:
      type: string
      description: "Post communication channel subscription applicable or not (Y/N)"                        
      pattern: '[Y,N]'
     postAllowed:
      type: boolean
      description: "Post Communication Allowed?"                        
     sms:
      type: string
      description: "SMS communication channel subscription applicable or not (Y/N)"
      pattern: '[Y,N]'
     smsAllowed:
      type: boolean
      description: "SMS Communication Allowed?"
     preference:
      type: string
      description: "Preferred communication channel"     
 AccServicesPrefMasterModelCollection:
    description: Collection of AccServicesPrefMasterModel.
    type: object
    properties:
     accServicesPrefMasterModelList:
      type: array
      items:
       $ref: '#/definitions/AccServicesPrefMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type