#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2019 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : TDAggregate.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Saving Application Service
host: localhost:7001
basePath: /saving-application-services
tags:
- name: TDAggregate
  description: API for SavingApplication Operations
schemes:
- http
paths:
  /web/v1/term-deposit/submittohost:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TDAggregate
      summary: Send the Term Deposit application to host.
      description: Submit Term Deposit application aggregate.
      operationId: saveTDApplication
      parameters:
      - name: tDAggregateModel
        in: body
        description: Request Body that contains data required for creating a new SavingApplicationAggregateModel
        required: true
        schema:
          $ref: '#/definitions/TDAggregateModel'
      responses:
        201:
          description: Returns the Id of the newly created BankingInfo
          headers:
            Location:
              description: URL of newly created BankingInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error              
definitions:
  TDAggregateModel:
    description: TDAggregateModel
    type: object
    properties:
      applicationNo:
        description: "Application Number"
        type: string
        maxLength: 20
      processRefNo:
        description: "processRefNo for which saving account application data needs to be fetched"
        type: string  
        maxLength: 20
      custNo:
        description: "Customer Number"
        type: string
      accountClass:
        description: "Account class"
        type: string
      accountDetailsModel:
        $ref: '#/definitions/AccountDetailsModel'
      applicantDetailsMasterModel:
        $ref: '#/definitions/ApplicantDetailsMasterModel'                                           
    required:
     - custNo
     - accountClass
     
     
  termDepositAggregateRequest:
    description: termDepositDetails
    type: object
    properties:
     applicationNo:
       description: "Application reference number"
       type: string
       maxLength: 20 
     processRefNo:
       description: "Process reference number"
       type: string
       maxLength: 20
     accountClass:
       description: "accountClass"
       type: string
       maxLength: 20 
     branch:
       description: "branch"
       type: string
       maxLength: 20
     custNo:
       description: "custNo"
       type: string
       maxLength: 20
     amount:
       description: "amount"
       type: string
       maxLength: 20
     maturityDate:
       description: "maturityDate"
       type: string
     tdTenureYears:
        description: Term Deposit Tenure in Years.
        type: number
     tdTenureMonths:
        description: Term Deposit Tenure in Months.
        type: number
     tdTenureDays:
        description: Term Deposit Tenure in Months.
        type: number
     businessProductCode:
      type: string
      description: ""     
     valueDate:
       description: "valueDate"
       type: string
     currency:
       description: "currency"
       type: string
     fundByMode:
       description: "fundByMode"
     fundByCash:
       description: "fundByCash"
       type: string
     fundByAcc:
       description: "fundByAcc"
       type: string
     fundByCheque:
       description: "fundByCheque"
       type: string      
     payInDetails:
       $ref: '#/definitions/payInDetails'
     payOutDetails:
       $ref: '#/definitions/payOutDetails'
     accountDetailsModel:
       $ref: "#/definitions/AccountDetailsModel"
     nomineeDetailsMasterModel:
       $ref: "#/definitions/NomineeDetailsMasterModel"
     mandateDetailsMasterModel:
       $ref: "#/definitions/MandateDetailsMasterModel"
     accServicesPrefMasterModel:
       $ref: "#/definitions/AccServicesPrefMasterModel"
     accServicesPrefDetailsModel:
       $ref: "#/definitions/AccServicesPrefDetailsModel"  
     interestDetailsMasterModel:
       $ref: "#/definitions/InterestDetailsMasterModel"
     customObject:
       type: object
     additionalAttributes:
       type: array
       items:
         type: object
     
     