#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : accountBalanceService.yaml
#  **
#  ** Module     : obremo-srv-cus-customer-services
#  **
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  **
#  **
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  **
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :
#  Changed By         :
#  Change Description :
#  Change On          :
#  Search String      :
#
#  -------------------------------------------------------------------------------------------------------


swagger: "2.0"
info:
  description: "This is a sample server AccountBalance server."
  version: "1.0.0"
  title: "Account Balance service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "AccountBalanceService"
    description: "service is to update the ddissuance data into data base"

schemes:
  - "https"

paths:
  /service/v1/datasegment/accountbalance/fetch/{accountNo}/branch/{branch}:
    get:
      tags:
        - "accountBalanceService"
      summary: "Retrieves the accountBalance by Account Number."
      description: ""
      operationId: "fetchServiceAccountBalance"
      parameters:
        - name: "accountNo"
          in: "path"
          type: "string"
          required: true
        - name: "branch"
          in: "path"
          type: "string"
          required: true
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: false
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "sourceCode"
          in: "header"
          type: "string"
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorised."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
definitions:

 ResponseModel:
    description: "Response Model"
    type: "object"
    properties:
      data:
        type: "object"
      errors:
        type: "object"
      paging:
        type: "object"                
  