#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : additionaltranches.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/additionaltranches:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AdditionalTranches
      summary: Adds a new AdditionalTranches.
      description: Adds a new AdditionalTranches. Add additional information here for this endpoint.
      operationId: addAdditionalTranches
      parameters:
      - name: AdditionalTranches
        in: body
        description: Request Body that contains data required for creating a new AdditionalTranches
        required: true
        schema:
          $ref: '#/definitions/AdditionalTranchesModel'
      responses:
        201:
          description: Returns the Id of the newly created AdditionalTranches
          headers:
            Location:
              description: URL of newly created AdditionalTranches
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AdditionalTranches
      summary: Retrieves the list of existing AdditionalTranches.
      description: Retrieves the list of existing AdditionalTranches. Add additional information here for the this endpoint.
      operationId: getAllAdditionalTranches
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: trancheId that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/additionaltranches/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AdditionalTranches
      summary: Retrieves the AdditionalTranches by id.
      description: Retrieves the AdditionalTranches by id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AdditionalTranches based on given applicationNumber.
          schema:
            $ref: '#/definitions/AdditionalTranchesModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AdditionalTranches
      summary: Update an existing AdditionalTranches.
      description: Update an existing AdditionalTranches. Add additional information here for the this endpoint.
      operationId: updateAdditionalTranches
      parameters:
      - name: id
        in: path
        description: id of the AdditionalTranches that need to be updated
        required: true
        type: string
      - name: AdditionalTranches
        in: body
        description: Request Body that contains data required for updating an existing AdditionalTranches
        required: true
        schema:
          $ref: '#/definitions/AdditionalTranchesModel'
      responses:
        200:
          description: Returns updated AdditionalTranches
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - AdditionalTranches
      summary: Deletes the AdditionalTranches identified by given ID.
      description: Deletes the AdditionalTranches identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAdditionalTranches
      parameters:
      - name: id
        in: path
        description: Id of the AdditionalTranches that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  AdditionalTranchesModel:
    description: additionaltranches model
    type: object
    properties:
      id:
        description: Id of the additionaltranches
        type: string
      applicationNumber:
        description: Application Number of the additionaltranches
        type: string
      processRefNumber:
        description: Process Ref Number of the additionaltranches
        type: string 
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      additionalTrancheDetails:
        type: array
        items:
          $ref: '#/definitions/AdditionalTrancheDetailsModel'  
  AdditionalTranchesCollection:
    description: Collection of additionaltranches.
    type: object
    properties:
      additionaltranchesList:
        type: array
        items:
          $ref: '#/definitions/AdditionalTrancheDetailsModel'
  AdditionalTrancheDetailsModel:
    description: AdditionalTrancheDetails model
    type: object
    properties:
      id:
        description: Id of the AdditionalTrancheDetails
        type: string
        maxLength: 36
      additionaltrancheId:
        description: additionaltrancheId of the AdditionalTrancheDetails
        type: string
        maxLength: 36
      trancheId:
        description: trancheId of the AdditionalTrancheDetails
        type: string
        maxLength: 36
      trancheName:
        description: trancheName of the AdditionalTrancheDetails
        type: string
        maxLength: 50
      trancheProductCode:
        description: trancheProductCode of the AdditionalTrancheDetails
        type: string
        maxLength: 4
      trancheCostCentre:
        description: trancheCostCentre of the AdditionalTrancheDetails
        type: string
        maxLength: 20
      loanCurrency:
        description: loanCurrency of the AdditionalTrancheDetails
        type: string
        maxLength: 4
      maximumLoans:
        description: maximumLoans of the AdditionalTrancheDetails
        type: number
      minimumLoanAmount:
        description: minimumAmount of the AdditionalTrancheDetails
        type: number
      maximumLoanAmount:
        description: maximumLoanAmount of the additionaltranches
        type: number
      cusipNumber:
        description: cusipNumber of the additionaltranches
        type: string
      drawdownProductDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownProductsDetailsModel'
  DrawdownProductsCollection:
    description: Collection of drawdownproducts.
    type: object
    properties:
      drawdownproductsList:
        type: array
        items:
          $ref: '#/definitions/DrawdownProductsDetailsModel'
  DrawdownProductsDetailsModel:
    description: DrawdownProductsDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownProductsDetails
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber of the DrawdownProductsDetails
        type: string
        maxLength: 36
      additionalTrancheDetailsId:
        description: additionalTrancheDetailsId of the DrawdownProductsDetails
        type: string
        maxLength: 36
      drawdownProductCode:
        description: drawdownProductCode of the DrawdownProductsDetails
        type: string
        maxLength: 36