#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : conditionssubsequents.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/conditionssubsequents:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConditionsSubsequents
      summary: Adds a new ConditionsSubsequents.
      description: Adds a new ConditionsSubsequents. Add additional information here for this endpoint.
      operationId: addConditionsSubsequents
      parameters:
      - name: ConditionsSubsequents
        in: body
        description: Request Body that contains data required for creating a new ConditionsSubsequents
        required: true
        schema:
          $ref: '#/definitions/ConditionsSubsequentsModel'
      responses:
        201:
          description: Returns the Id of the newly created ConditionsSubsequents
          headers:
            Location:
              description: URL of newly created ConditionsSubsequents
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConditionsSubsequents
      summary: Retrieves the list of existing ConditionsSubsequents.
      description: Retrieves the list of existing ConditionsSubsequents. Add additional information here for the this endpoint.
      operationId: getAllConditionsSubsequents
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/conditionssubsequents/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConditionsSubsequents
      summary: Retrieves the ConditionsSubsequents by id.
      description: Retrieves the ConditionsSubsequents by id. Add additional information here for the this endpoint.
      operationId: getConditionsSubsequentsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ConditionsSubsequents based on given applicationNumber.
          schema:
            $ref: '#/definitions/ConditionsSubsequentsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConditionsSubsequents
      summary: Update an existing ConditionsSubsequents.
      description: Update an existing ConditionsSubsequents. Add additional information here for the this endpoint.
      operationId: updateConditionsSubsequents
      parameters:
      - name: id
        in: path
        description: id of the ConditionsSubsequents that need to be updated
        required: true
        type: string
      - name: ConditionsSubsequents
        in: body
        description: Request Body that contains data required for updating an existing ConditionsSubsequents
        required: true
        schema:
          $ref: '#/definitions/ConditionsSubsequentsModel'
      responses:
        200:
          description: Returns updated ConditionsSubsequents
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ConditionsSubsequents
      summary: Deletes the ConditionsSubsequents identified by given ID.
      description: Deletes the ConditionsSubsequents identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteConditionsSubsequents
      parameters:
      - name: id
        in: path
        description: Id of the ConditionsSubsequents that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ConditionsSubsequentsModel:
    description: ConditionsSubsequents model
    type: object
    properties:
      id:
        description: Id of the ConditionsSubsequents
        type: string
        maxLength: 36
      maintainanceId:
        description: maintainanceId
        type: string
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string
      remarks:
        description: remarks
        type: string
      conditionsSubsequentDetails:
        type: array
        items:
          $ref: '#/definitions/ConditionsSubsequentDetailsModel'
  ConditionsSubsequentDetailsModel:
    description: ConditionsSubsequentDetails model
    type: object
    properties:
      id:
        description: Id of the ConditionsSubsequentDetails
        type: string
      condSubsDetailsId:
        description: condSubsDetailsId
        type: string
      name:
        description: condSubsName
        type: string
      description:
        description: condSubsDesc
        type: string
      customerName:
        description: customerName
        type: string
      dealPersonalId:
        description: dealPersonalId
        type: string
      partyId:
        description: partyId
        type: string
      projectName:
        description: projectName
        type: string
      dueBy:
        description: dueBy
        type: string
      reminderDays:
        description: reminderDays
        type: number
  ConditionsSubsequentsCollection:
    description: Collection of ConditionsSubsequents.
    type: object
    properties:
      ConditionsSubsequentsList:
        type: array
        items:
          $ref: '#/definitions/ConditionsSubsequentsModel'
