swagger: "2.0"
info:
  description: "This is a sample server FieldInvestigation server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "FieldInvestigation Service"
host: "whf00anh:7731"
basePath: "/fieldinvestigation-services"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "FieldInvestigationAPI"
    description: "API for Field Investigation's Operations"
    
schemes:
- "https"

paths:
  /service/v1/fieldInvestigation/{entityReferenceNumber}:
    get:
      tags:
        - "fieldInvestigationService"
      summary: "Retrieves the list of existing Field Investigations from Main."
      description:  "Retrieves the list of existing Field Investigations. Add additional information here for the this endpoint."
      operationId: "getFieldInvestigationsMain"
      parameters:
        - name: "entityReferenceNumber"
          in: "path"
          description: "entityReferenceNumber of the details that needs to be fetched"
          required: true
          type: "string"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystem"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystemReferenceNo"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
    delete:
      tags:
        - "fieldInvestigationService"
      summary: "Deletes the Field Investigation identified by given ID"
      description:  "Deletes the Field Investigation identified by given ID"
      operationId: "deleteFieldInvestigationMain"
      parameters:
        - name: "entityReferenceNumber"
          in: "path"
          description: "entityReferenceNumber of the Field Investigation that needs to be deleted"
          required: true
          type: "string"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystem"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystemReferenceNo"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
      responses:
        200:
          description: "Successful operation."
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"