#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ${enityName}.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: corporateproductenrichment
host: 10.184.157.121:9000
basePath: /corporateproductenrichment
tags:
- name: corporateproductenrichment
  description: API for corporateproductenrichment Operations
schemes:
- http
paths:
  /web/v1/corporateproductenrichment:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ObcmTmCorpEnrchProdEnrchMstr
      summary: Adds a new ObcmTmCorpEnrchProdEnrchMstr.
      description: Adds a new ObcmTmCorpEnrchProdEnrchMstr. Add additional information here for this endpoint.
      operationId: addObcmTmCorpEnrchProdEnrchMstr
      parameters:
      - name: ObcmTmCorpEnrchProdEnrchMstr
        in: body
        description: Request Body that contains data required for creating a new ObcmTmCorpEnrchProdEnrchMstr
        required: true
        schema:
          $ref: '#/definitions/ObcmTmCorpEnrchProdEnrchMstrDTO'
      responses:
        201:
          description: Returns the Id of the newly created ObcmTmCorpEnrchProdEnrchMstr
          headers:
            Location:
              description: URL of newly created ObcmTmCorpEnrchProdEnrchMstr
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ObcmTmCorpEnrchProdEnrchMstrDTO:
    description: ObcmTmCorpEnrchProdEnrchMstr model
    type: object
    allOf:
    - $ref: '#/definitions/BaseGenericModelDS'
    - type: object
      properties:    
       id:
        type: string
        description: "Id"
       action:
        type: string
        description: "Action"
       autoAuth:
        type: string
        description: "Auto Auth"
       modificationStatus:
        type: string
        description: "Modification Status"   
       datasegmentCode:
        type: string
        description: "Datasegment Code"
       checkerRemarks:
        type: string
        description: "checkerRemarks" 
       makerRemarks:
        type: string
        description: "makerRemarks"
       enrichmentId:
        description: enrichmentId
        type: string
       txnControllerRefNo:
        type: string
        description: "Transaction Controller Reference Number"
       obcmTmCorpEnrchProdEnrchDtls:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchProdEnrchDtlsDTO'
  ResponseDto:
   type: object
   properties:
    id:
     type: string
    status:
     type: string
    codes:
     type: array
     items:
      $ref: "#/definitions/ResponseCode"
    requestId:
     type: string
  ResponseCode:
   type: object
   properties:
    Code:
     type: string
    Desc:
     type: string
    Type:
     type: string
    Language:
     type: string
    args:
     type: array
     items:
      type: object
    arg:
     type: string
  BaseGenericModelDS:
   allOf:
    - type: object
      discriminator: resource_type

  ObcmTmCorpEnrchProdEnrchDtlsDTO:
   type: object
   properties:
     dataType:
      type: string
      description: ""
     enrchLabel:
      type: string
      description: ""
     fieldLength:
      type: string
      description: ""
     id:
      type: string
      description: ""
     lvlOfEnrch:
      type: string
      description: ""
     productCode:
      type: string
      description: ""
     productDesc:
      type: string
      description: ""
     productCategory:
      type: string
      description: ""
     prodEnrchMstrId:
      type: string
      description: ""
     validations:
      type: string
      description: ""
     minValue:
      type: integer
      description: ""
     orderingNo:
      type: integer
      description: "Product's ordering number"
     obcmTmCorpEnrchProdEnrchMstr:
      type: array
      items:
        $ref: '#/definitions/ObcmTmCorpEnrchProdEnrchMstrDTO'
  ObcmTmCorpEnrchProdEnrchMstrCollection:
    description: Collection of ObcmTmCorpEnrchProdEnrchMstr.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchProdEnrchMstrDTO'
      paging:
       $ref: "#/definitions/PagingDto"
  ObcmTmCorpEnrchProdEnrchDetailsCollection: 
   description: "Collection of corpenrchprodenrchmstr."
   type: "object"
   properties:
     data:
       type: "array"
       items: 
         $ref: '#/definitions/ObcmTmCorpEnrchProdEnrchDtlsDTO'
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer
  ResponseDtoWrapper:
   type: object
   properties:
    messages:
     $ref: "#/definitions/ResponseDto"
    data:
     $ref: "#/definitions/ResponseResourceSupport"
  ResponseResourceSupport:
   type: object
  ObcmTmCorpEnrchProdEnrchMstrWrapperDTO:
   type: object
   properties:
    data:
     $ref: "#/definitions/ObcmTmCorpEnrchProdEnrchMstrDTO"
  ObcmTmCorpEnrchProdEnrchDetailsDTO:
    type: "object"
    description: "Corporate Enrichment Information Product Details" 
    properties:
       dataType:
        type: "string"
        description: "Data Type used for corporate enrichment information Product Details"
       enrchLabel:
        type: "string"
        description: "Enrich Label used for corporate enrichment information Product Details"
       fieldLength:
        type: "string"
        description: "Field length used for corporate enrichment information Product Details"
       lvlOfEnrch:
        type: "string"
        description: "Level of enrichment used for corporate enrichment information Product Details"
       productCode:
        type: "string"
        description: "Product code used for corporate enrichment information Product Details"
       productDesc:
        type: "string"
        description: "Product description used for corporate enrichment information Product Details"
       productCategory:
        type: "string"
        description: "Product category used for corporate enrichment information Product Details"
       validations:
        type: "string"
        description: "Validations used for corporate enrichment information Product Details"
       minValue:
        type: integer
        description: "Minimum Of value used for used for corporate enrichment information Product Details"
       orderingNo:
        type: integer
        description: "Product's ordering number"