#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ${enityName}.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: obcmtmcorpenrchpckupmstr
host: 10.184.157.121:9000
basePath: /obcmtmcorpenrchpckupmstr
tags:
- name: obcmtmcorpenrchpckupmstr
  description: API for obcmtmcorpenrchpckupmstr Operations
schemes:
- http
paths:
  /web/v1/obcmtmcorpenrchpckupmstr:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ObcmTmCorpEnrchPckupMstr
      summary: Adds a new ObcmTmCorpEnrchPckupMstr.
      description: Adds a new ObcmTmCorpEnrchPckupMstr. Add additional information here for this endpoint.
      operationId: addObcmTmCorpEnrchPckupMstr
      parameters:
      - name: ObcmTmCorpEnrchPckupMstr
        in: body
        description: Request Body that contains data required for creating a new ObcmTmCorpEnrchPckupMstr
        required: true
        schema:
          $ref: '#/definitions/ObcmTmCorpEnrchPckupMstrDTO'
      responses:
        201:
          description: Returns the Id of the newly created ObcmTmCorpEnrchPckupMstr
          headers:
            Location:
              description: URL of newly created ObcmTmCorpEnrchPckupMstr
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ObcmTmCorpEnrchPckupMstrDTO:
    description: ObcmTmCorpEnrchPckupMstr model
    type: object
    allOf:
    - $ref: '#/definitions/BaseGenericModelDS'
    - type: object
      properties:    
       id:
        type: string
        description: "Id"
       action:
        type: string
        description: "Action"
       autoAuth:
        type: string
        description: "Auto Auth"
       modificationStatus:
        type: string
        description: "Modification Status"   
       datasegmentCode:
        type: string
        description: "Datasegment Code"
       checkerRemarks:
        type: string
        description: "checkerRemarks" 
       makerRemarks:
        type: string
        description: "makerRemarks"
       enrichmentId:
        description: enrichmentId
        type: string
       txnControllerRefNo:
        type: string
        description: "Transaction Controller Reference Number"
       obcmTmCorpEnrchPckupDtls:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchPckupDtlsDTO'
  BaseGenericModelDS:
   allOf:
    - type: object
      discriminator: resource_type

  ObcmTmCorpEnrchPckupDtlsDTO:
    description: ObcmTmCorpEnrchPckupDtls model
    type: object
    properties:
      id:
        description: Id of the ObcmTmCorpEnrchPckupDtls
        type: string
      addln1:
        description: addln1
        type: string
      addln2:
        description: addln2
        type: string
      addln3:
        description: addln3
        type: string
      addln4:
        description: addln4
        type: string
      agrmntDate:
        description: agrmntDate
        type: string
        format: date
      cntctPerson:
        description: cntctPerson
        type: string
      cntry:
        description: cntry
        type: string
      cntryCode:
        description: cntryCode
        type: string
      cntryName:
        description: cntryName
        type: string
      courierCode:
        description: courierCode
        type: string
      courierCodeDesc:
        description: courierCodeDesc
        type: string
      dayOfWeek:
        description: dayOfWeek
        type: string
      fax:
        description: fax
        type: number
      freq:
        description: freq
        type: string
      locationCode:
        description: locationCode
        type: string
      locationDesc:
        description: locationDesc
        type: string
      pckupMstrId:
        description: pckupMstrId
        type: string
      pickupCode:
        description: pickupCode
        type: string
      pickupFor:
        description: pickupFor
        type: string
      pickupOnHldys:
        description: pickupOnHldys
        type: string
      pickupPt:
        description: pickupPt
        type: string
      pickupSlot:
        description: pickupSlot
        type: string
      pickupType:
        description: pickupType
        type: string
      postalCode:
        description: postalCode
        type: number
      prEmailId:
        description: prEmailId
        type: string
      prPhoneNo:
        description: prPhoneNo
        type: number
      retrnDispatch:
        description: retrnDispatch
        type: string
      scEmailId:
        description: scEmailId
        type: string
      scPhoneNo:
        description: scPhoneNo
        type: number
      chqRtnAddln1:
        description: chqRetnAddln1
        type: string
      chqRtnAddln2:
        description: chqRetnAddln2
        type: string
      chqRtnAddln3:
        description: chqRetnAddln3
        type: string
      chqRtnAddln4:
        description: chqRetnAddln4
        type: string
      obcmTmCorpEnrchPckupMstr:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchPckupMstrDTO'
  ObcmTmCorpEnrchPckupMstrCollection: 
   description: "Collection of corpenrchpckupmstr."
   type: "object"
   properties:
    data:
     type: "array"
     items: 
      $ref: "#/definitions/ObcmTmCorpEnrchPckupMstrDTO"
    paging:
     $ref: "#/definitions/PagingDto"
  PagingDto:
   type: object
   properties:
     totalResults:
       type: integer 
  status:
   type: "string"
   description: "Status Enum specifying the type of Request. ACTIVE - (CREATE/MODIFY) and DELETE"
  ObcmTmCorpEnrchPickupDetailsDTO:
   type: "object"
   allOf:
   - $ref: '#/definitions/ObcmTmCorpEnrchPckupDetailsDTO'
   - type: "object"
     properties:
      status:
       $ref: '#/definitions/status'
  ObcmTmCorpEnrchPckupDetailsDTO:
    type: "object"
    description: "Corporate Enrichment PickUp details Data"
    properties:
       addln1:
        type: "string"
        description: "Address line 1 used corporate enrichment pickUp details response"
       addln2:
        type: "string"
        description: "Address line 2 used corporate enrichment pickUp details response"
       addln3:
        type: "string"
        description: "Address line 3 used corporate enrichment pickUp details response"
       addln4:
        type: "string"
        description: "Address line 4 used corporate enrichment pickUp details response"
       agrmntDate:
        type: "string"
        description: "Arragment date used corporate enrichment pickUp details response"
       cntctPerson:
        type: "string"
        description: "Contact person used corporate enrichment pickUp details"
       cntryCode:
        type: "string"
        description: "Country code used corporate enrichment pickUp details response"
       cntryName:
        type: "string"
        description: "Country name used corporate enrichment pickUp details response"
       courierCode:
        type: "string"
        description: "Courier Code used corporate enrichment pickUp details response"
       courierCodeDesc:
        type: "string"
        description: "CourierCode Description used corporate enrichment pickUp details response"
       dayOfWeek:
        type: "string"
        description: "DayOfWeek used corporate enrichment pickUp details response"
       fax:
        type: "number"
        description: "Fax number used corporate enrichment pickUp details response"
       freq:
        type: "string"
        description: "Frequency used corporate enrichment pickUp details response"
       locationCode:
        type: "string"
        description: "LocationCode used corporate enrichment pickUp details response"
       locationDesc:
        type: "string"
        description: "LocationDesc used corporate enrichment pickUp details response"
       pickupCode:
        type: "string"
        description: "PickupCode used corporate enrichment pickUp details response"
       pickupFor:
        type: "string"
        description: "PickupFor used corporate enrichment pickUp details response"
       pickupOnHldys:
        type: "string"
        description: "PickupOnHldys used corporate enrichment pickUp details response"
       pickupPt:
        type: "string"
        description: "Pickup point used corporate enrichment pickUp details response"
       pickupSlot:
        type: "string"
        description: "PickupSlot used corporate enrichment pickUp details"
       pickupType:
        type: "string"
        description: "PickupType used corporate enrichment pickUp details"
       postalCode:
        type: "number"
        description: "PostalCode used corporate enrichment pickUp details" 
       prEmailId:
        type: "string"
        description: "Pre EmailId used corporate enrichment pickUp details"
       prPhoneNo:
        type: "number"
        description: "Pre PhoneNo used corporate enrichment pickUp details"
       retrnDispatch:
        type: "string"
        description: "Return Dispatch used corporate enrichment pickUp details"
       scEmailId:
        type: "string"
        description: "Source EmailId used corporate enrichment pickUp details"
       scPhoneNo:
        type: "number"
        description: "Source PhoneNo used corporate enrichment pickUp details"
       chqRtnAddln1:
        type: "string"
        description: "Cheque return Address line 1 used corporate enrichment pickUp details"
       chqRtnAddln2:
        type: "string"
        description: "Cheque return Address line 2 used corporate enrichment pickUp details"
       chqRtnAddln3:
        type: "string"
        description: "Cheque return Address line 3 used corporate enrichment pickUp details"
       chqRtnAddln4:
        type: "string"
        description: "Cheque return Address line 4 used corporate enrichment pickUp details"
  ObcmTmCorpEnrchPckupDTO:
    type: object
    description: "Corporate Enrichment Pick up Data"
    properties:
       corporateId:
        type: string
        description: "Corporate id used for corporate enrichment pick up data"
       locationCode:
        type: string
        description: "Available location code used for corporate enrichment pick up data"
       pickupCode:
        type: string
        description: "Pickup code mapped to corporate or location code will be returned"
       pickupPt:
        type: string
        description: "Name of the pick up point"
       cntctPerson:
        type: string
        description: "Name of the contact person"
       pickupFor:
        type: string
        description: "Cheque or Cash"
       pickupType:
        type: string
        description: "Constant value Adhoc / on call"
       courierCode:
        type: string
        description: "List of existing courier codes can be fetched from back office"
       addln1:
        type: string
        description: "Address line 1"
       addln2:
        type: string
        description: "Address line 2"
       addln3:
        type: string
        description: "Address line 3"
       addln4:
        type: string
        description: "Address line 4"
       cntry:
        type: string
        description: Country of pickup point"
       cntryCode:
        type: string
        description: "Country Code of pickup point"
       cntryName:
        type: string
        description: "Country Name of pickup point"
       postalCode:
        type: number
        description: "Postal code of pickup point"
       prPhoneNo:
        type: number
        description: "Primary number of contact"
       prEmailId:
        type: string
        description: "Email of contact"
       authStatus:
        type: string
        description: "A or U"
       modNo:
        type: integer
        description: "Modification number of record"
       agrmntDate:
        type: string
        format: date
        description: "Arranegment data"
       courierCodeDesc:
        type: string
        description: "Courier Code Description"
       dayOfWeek:
        type: string
        description: "DayOfWeek used for corporate enrichment pick up data"
       fax:
        type: number
        description: "Fax number used for corporate enrichment pick up data"
       freq:
        type: string
        description: "Frequency used for corporate enrichment pick up data"
       id:
        type: string
        description: "Id value used for corporate enrichment pick up data"
       locationDesc:
        type: string
        description: "Location Description used for corporate enrichment pick up data"
       pckupMstrId:
        type: string
        description: "Pick Up master Id used for corporate enrichment pick up data"
       pickupOnHldys:
        type: string
        description: "pickupOnHldys used for corporate enrichment pick up data"
       pickupSlot:
        type: string
        description: "PickupSlot used for corporate enrichment pick up data"
       retrnDispatch:
        type: string
        description: "Return Dispatch used for corporate enrichment pick up data"
       scEmailId:
        type: string
        description: "Source EmailId used for corporate enrichment pick up data"
       scPhoneNo:
        type: number
        description: "Source PhoneNo used for corporate enrichment pick up data"
       chqRtnAddln1:
        type: string
        description: "Cheque Return Address line 1"
       chqRtnAddln2:
        type: string
        description: "Cheque Return Address line 2"
       chqRtnAddln3:
        type: string
        description: "Cheque Return Address line 3"
       chqRtnAddln4:
        type: string
        description: "Cheque Return Address line 4"
  ObcmTmCorpEnrchPckupDTOCollection: 
   description: "Collection of Corporate Enrichment pick up."
   type: "object"
   properties:
    data:
     type: "array"
     description: "List of Corporate Enrichment pick up data"
     items: 
      type: object 