#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2019 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : collateralcreation.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Collateral Creation Services
host: localhost:7001
basePath: /obremo-rpm-cmn-hostservices
tags:
- name: Collateral Creation Services
  description: API for Collateral Creation Services Operations
schemes:
- http
paths:
   /web/v1/collateralcreation:
    post:
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralCreation
      summary: Create Collateral 
      description: Create Collateral 
      operationId: createCollateral
      parameters:
      - name: collateralDetails
        in: body
        description: Request Body that contains data required for creating new collateral
        required: true
        schema:
          $ref: '#/definitions/CollateralCreationModel'
      - description: "User Id"
        in: header
        name: userId
        required: true
        type: string
      - description: "Branch Code"
        in: header
        name: branchCode
        required: true
        type: string        
      - description: Source
        in: header
        name: sourceCode
        required: false
        type: string
        default: "OBREMO"
      - description: appId
        in: header
        name: appId
        required: true
        type: string      
      responses:
        201:
          description: Returns the Id of the newly created Collateral
          headers:
            Location:
              description: URL of newly created Collateral
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error  
definitions:
  CollateralCreationModel:
   description: " Collateral Creation Model"
   type: object
   properties:      
     collateralCode:
      description: Collateral Code
      type: string
     collateralDesc:
      description: Collateral Description
      type: string
     collateralAmountCCY:
      description: Collateral Amount CCY
      type: string
     amountConsidered:
      description: Amount Considered
      type: string
     collateralAvlFromDate:
      description: Collateral From Date
      type: string
     collateralAvlToDate:
      description: Collateral To Date
      type: string
     collateralBranch:
      description: Collateral Branch
      type: string
     liabilityId:
      description: Liability Id
      type: string
     collateralAmount:
      description: Collateral Amount
      type: string
     collateralType:
      description: Collateral Type
      type: string
     collateralDetailsModelJsonString:
      description: CollateralDetailsModel JsonString
      type: string
