#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : holidaypreferences.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/holidaypreferences:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - HolidayPreferences
      summary: Adds a new HolidayPreferences.
      description: Adds a new HolidayPreferences. Add additional information here for this endpoint.
      operationId: addHolidayPreferences
      parameters:
      - name: HolidayPreferences
        in: body
        description: Request Body that contains data required for creating a new HolidayPreferences
        required: true
        schema:
          $ref: '#/definitions/HolidayPreferencesModel'
      responses:
        201:
          description: Returns the Id of the newly created HolidayPreferences
          headers:
            Location:
              description: URL of newly created HolidayPreferences
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - HolidayPreferences
      summary: Retrieves the list of  HolidayPreferences.
      description: Retrieves the list of  HolidayPreferences. Add additional information here for the this endpoint.
      operationId: getAllHolidayPreferences
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/holidaypreferences/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - HolidayPreferences
      summary: Get a  HolidayPreferences.
      description: Update a  HolidayPreferences. Add additional information here for the this endpoint.
      operationId: getHolidayPreferencesById
      parameters:
      - name: id
        in: path
        description: id of the HolidayPreferences that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated HolidayPreferences
          schema:
            $ref: '#/definitions/HolidayPreferencesModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - HolidayPreferences
      summary: Update an  HolidayPreferences.
      description: Update an  HolidayPreferences. Add additional information here for the this endpoint.
      operationId: updateHolidayPreferences
      parameters:
      - name: id
        in: path
        description: id of the HolidayPreferences that need to be updated
        required: true
        type: string
      - name: HolidayPreferences
        in: body
        description: Request Body that contains data required for updating an  HolidayPreferences
        required: true
        schema:
          $ref: '#/definitions/HolidayPreferencesModel'
      responses:
        200:
          description: Returns updated HolidayPreferences
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - HolidayPreferences
      summary: Deletes the A HolidayPreferencesidentified by given ID.
      description: Deletes the HolidayPreferences identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteHolidayPreferences
      parameters:
      - name: id
        in: path
        description: Id of the HolidayPreferences that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  HolidayPreferencesModel:
   description: HolidayPreferences model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      holidayTreatmentPreferences:
        description: Details of the HolidayPreferences
        type: array
        items:
          $ref: '#/definitions/HolidayPreferencesDetailsModel'
  HolidayPreferencesCollection:
    description: Collection of HolidayPreferences.
    type: object
    properties:
      HolidayPreferencesList:
        type: array
        items:
          $ref: '#/definitions/HolidayPreferencesModel'
  HolidayPreferencesDetailsModel:
    description: HolidayPreferencesDetailsModel
    type: object
    required:
    - holidayTreatmentPreferenceType
    properties:
      id:
        description: Id of the HolidayPreferencesDetails
        type: string
        maxLength: 36
      holidayPreferenceId:
        description: holidayPreferenceId of the Details model
        type: string
        maxLength: 36
      holidayTreatmentPreferenceType:
        description: holidayTreatmentPreferenceType of the HolidayPreferences
        type: string
        maxLength: 20
      holidayCheck:
        description: holidayCheck of the HolidayPreferences
        type: string
        maxLength: 20
      holidayCurrencyCode:
        description: holidayCurrencyCode of the HolidayPreferences
        type: string
        maxLength: 3
      ignoreHoliday:
        description: ignoreHoliday  of the HolidayPreferences
        type: string
        maxLength: 1
      cascadeSchedule:
        description: cascadeSchedule of the HolidayPreferences
        type: string
        maxLength: 20
      moveAcrossMonth:
        description: moveAcrossMonth of the HolidayPreferences
        type: string
        maxLength: 20
      scheduleMovement:
        description: scheduleMovement of the HolidayPreferences
        type: string
        maxLength: 3
      moveForwardBackward:
        description: moveForward/moveBackward of the HolidayPreferences
        type: string
        maxLength: 1
      includeBranchHoliday:
        description: includeBranchHoliday of the HolidayPreferences
        type: string
        maxLength: 1
      useFacilityCurrency:
        description: useFacilityCurrency of the HolidayPreferences
        type: string
        maxLength: 1
      useContractCurrency:
        description: useContractCurrency of the HolidayPreferences
        type: string
        maxLength: 1
      useTrancheCurrency:
        description: useTrancheCurrency of the HolidayPreferences
        type: string
        maxLength: 1
      useLocalCurrency:
        description: useLocalCurrency of the HolidayPreferences
        type: string
        maxLength: 1
      moveRevisionSchedules:
        description: moveRevisionSchedules of the HolidayPreferences
        type: string
        maxLength: 1
      movePaymentSchedules:
        description: movePaymentSchedules of the HolidayPreferences
        type: string
        maxLength: 1
      moveCommitmentReductionSchedules:
        description: moveCommitmentReductionSchedules of the HolidayPreferences
        type: string
        maxLength: 1
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type