#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : internaldepartmentapproval.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/internaldepartmentapproval:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InternalDepartmentApproval
      summary: Adds a new InternalDepartmentApproval.
      description: Adds a new InternalDepartmentApproval. Add additional information here for this endpoint.
      operationId: addInternalDepartmentApproval
      parameters:
      - name: InternalDepartmentApproval
        in: body
        description: Request Body that contains data required for creating a new InternalDepartmentApproval
        required: true
        schema:
          $ref: '#/definitions/InternalDepartmentApprovalModel'
      responses:
        201:
          description: Returns the Id of the newly created InternalDepartmentApproval
          headers:
            Location:
              description: URL of newly created InternalDepartmentApproval
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InternalDepartmentApproval
      summary: Retrieves the list of existing InternalDepartmentApproval.
      description: Retrieves the list of existing InternalDepartmentApproval. Add additional information here for the this endpoint.
      operationId: getAllInternalDepartmentApproval
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/internaldepartmentapproval/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InternalDepartmentApproval
      summary: Retrieves the InternalDepartmentApproval by id.
      description: Retrieves the InternalDepartmentApproval by id. Add additional information here for the this endpoint.
      operationId: getInternalDepartmentApprovalById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the InternalDepartmentApproval based on given applicationNumber.
          schema:
            $ref: '#/definitions/InternalDepartmentApprovalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InternalDepartmentApproval
      summary: Update an existing InternalDepartmentApproval.
      description: Update an existing InternalDepartmentApproval. Add additional information here for the this endpoint.
      operationId: updateInternalDepartmentApproval
      parameters:
      - name: id
        in: path
        description: id of the InternalDepartmentApproval that need to be updated
        required: true
        type: string
      - name: InternalDepartmentApproval
        in: body
        description: Request Body that contains data required for updating an existing InternalDepartmentApproval
        required: true
        schema:
          $ref: '#/definitions/InternalDepartmentApprovalModel'
      responses:
        200:
          description: Returns updated InternalDepartmentApproval
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - InternalDepartmentApproval
      summary: Deletes the InternalDepartmentApproval identified by given ID.
      description: Deletes the InternalDepartmentApproval identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteInternalDepartmentApproval
      parameters:
      - name: id
        in: path
        description: Id of the InternalDepartmentApproval that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  InternalDepartmentApprovalModel:
    description: InternalDepartmentApproval model
    type: object
    properties:
      id:
        description: Id of the InternalDepartmentApproval
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      internalDepartmentApprovalDetails:
        type: array
        items:
          $ref: '#/definitions/InternalDepartmentApprovalDetailsModel'
  InternalDepartmentApprovalDetailsModel:
    description: InternalDepartmentApprovalDetails model
    type: object
    required:
    - departmentName
    - approverName
    - approverEmail
    - signOffStatus
    properties:
      id:
        description: Id of the InternalDepartmentApprovalDetails
        type: string
      intDeptApprvlId:
        description: intDeptApprvlId
        type: string
      departmentName:
        description: Department Name
        type: string
        maxLength: 36
      approverName:
        description: Approver Name
        type: string
        maxLength: 36
      approverEmail:
        description: Approver Email
        type: string
        maxLength: 100
      signOffStatus:
        description: Sign Off Status
        type: string
      signOffDate:
        description: Sign Off Date
        type: string
      signOffComment:
        description: Sign Off Comment
        type: string
      requestedDocument:
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'  
  InternalDepartmentApprovalCollection:
    description: Collection of InternalDepartmentApproval.
    type: object
    properties:
      InternalDepartmentApprovalList:
        type: array
        items:
          $ref: '#/definitions/InternalDepartmentApprovalModel'
