#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : arrangerconfirmation.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/arrangerconfirmation:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ArrangerConfirmation
      summary: Adds a new ArrangerConfirmation.
      description: Adds a new ArrangerConfirmation. Add additional information here for this endpoint.
      operationId: addArrangerConfirmation
      parameters:
      - name: ArrangerConfirmation
        in: body
        description: Request Body that contains data required for creating a new ArrangerConfirmation
        required: true
        schema:
          $ref: '#/definitions/ArrangerConfirmationModel'
      responses:
        201:
          description: Returns the Id of the newly created ArrangerConfirmation
          headers:
            Location:
              description: URL of newly created ArrangerConfirmation
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ArrangerConfirmation
      summary: Retrieves the list of existing ArrangerConfirmation.
      description: Retrieves the list of existing ArrangerConfirmation. Add additional information here for the this endpoint.
      operationId: getAllArrangerConfirmation
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/arrangerconfirmation/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ArrangerConfirmation
      summary: Retrieves the ArrangerConfirmation by id.
      description: Retrieves the ArrangerConfirmation by id. Add additional information here for the this endpoint.
      operationId: getArrangerConfirmationById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ArrangerConfirmation based on given applicationNumber.
          schema:
            $ref: '#/definitions/ArrangerConfirmationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ArrangerConfirmation
      summary: Update an existing ArrangerConfirmation.
      description: Update an existing ArrangerConfirmation. Add additional information here for the this endpoint.
      operationId: updateArrangerConfirmation
      parameters:
      - name: id
        in: path
        description: id of the ArrangerConfirmation that need to be updated
        required: true
        type: string
      - name: ArrangerConfirmation
        in: body
        description: Request Body that contains data required for updating an existing ArrangerConfirmation
        required: true
        schema:
          $ref: '#/definitions/ArrangerConfirmationModel'
      responses:
        200:
          description: Returns updated ArrangerConfirmation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ArrangerConfirmation
      summary: Deletes the ArrangerConfirmation identified by given ID.
      description: Deletes the ArrangerConfirmation identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteArrangerConfirmation
      parameters:
      - name: id
        in: path
        description: Id of the ArrangerConfirmation that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ArrangerConfirmationModel:
    description: ArrangerConfirmation model
    type: object
    properties:
      id:
        description: Id of the ArrangerConfirmation
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks
        type: string
      ovarallCommitmentExpected:
        description: Overall Commitment Expected
        type: number
      ovarallCommitmentReceived:
        description: Overall Commitment Received
        type: number
      diffInOverallCommitment:
        description: Difference in Overall Commitment
        type: number
      syndicationCurrency:
        description: Syndication Currency
        type: string
      arrangerConfirmationDetails:
        type: array
        items:
          $ref: '#/definitions/ArrangerConfirmationDetailsModel'
      arrangerTrancheSummary:
        type: array
        items:
          $ref: '#/definitions/ArrangerTrancheSummaryModel'
  ArrangerConfirmationDetailsModel:
    description: ArrangerConfirmationDetails model
    type: object
    required:
    - lenderId
    - lenderName
    - syndicationCurrency
    properties:
      id:
        description: Id of the ArrangerConfirmationDetails
        type: string
      arrangerConfirmationId:
        description: arrangerConfirmationId
        type: string
      lenderId:
        description: Lender ID
        type: string
        maxLength: 36
      lenderName:
        description: Lender Name
        type: string
        maxLength: 36
      totalAllocation:
        description: Total Allocation
        type: number
      syndicationCurrency:
        description: Syndication Currency
        type: string
      responseStatus:
        description: Response Status
        type: string
      arrangerTrancheConfirmation:
        type: array
        items:
          $ref: '#/definitions/ArrangerTrancheConfirmationModel'
  ArrangerTrancheConfirmationModel:
    description: ArrangerTrancheConfirmation model
    type: object
    required:
    - trancheId
    - tranchName
    - allocatedCommitment
    - trancheCcy
    - syndicationCcy
    properties:
      id:
        description: Id of the ArrangerTrancheConfirmation
        type: string
      arrangerConfDetailsId:
        description: arrangerConfDetailsId
        type: string
      trancheId:
        description: Tranche ID
        type: string
        maxLength: 36
      tranchName:
        description: Tranche Name
        type: string
      allocatedCommitment:
        description: Allocated Commitment
        type: number
      receivedCommitment:
        description: Received Commitment
        type: number
      allocatedComtmntInSyndCcy:
        description: Allocated Commitment in Syndication Ccy
        type: number
      receivedComtmntInSyndCcy:
        description: Received Commitment in Syndication Ccy
        type: number
      trancheCcy:
        description: Tranche Currency
        type: string
      syndicationCcy:
        description: Syndication Currency
        type: string
      lenderId:
        description: Lender ID
        type: string
        maxLength: 36
  ArrangerTrancheSummaryModel:
    description: ArrangerTrancheSummary model
    type: object
    required:
    - trancheId
    - tranchName
    - totalExpectedCommitment
    - trancheCcy
    properties:
      id:
        description: Id of the ArrangerTrancheSummary
        type: string
      arrangerConfirmationId:
        description: arrangerConfirmationId
        type: string
      trancheId:
        description: Tranche ID
        type: string
        maxLength: 36
      tranchName:
        description: Tranche Name
        type: string
      totalExpectedCommitment:
        description: Total Allocated Commitment
        type: number
      totalReceivedCommitment:
        description: Total Received Commitment
        type: number
      trancheCcy:
        description: Tranche Currency
        type: string
  ArrangerConfirmationCollection:
    description: Collection of ArrangerConfirmation.
    type: object
    properties:
      ArrangerConfirmationList:
        type: array
        items:
          $ref: '#/definitions/ArrangerConfirmationModel'
