swagger: "2.0"
info:
  description: "Service to issue cheque book."
  version: "1.0.0"
  title: "Customer Account Statement Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "CustomerAccStatement"
    description: ""

schemes:
  - "https"

paths:
 /CustomerAccStatement/:
  get:
   tags:
   - "CustomerAccStatement"
   operationId: "cash"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"

definitions:
  AccountStatementDTO:
    type: object
    description: "Customer Acc Statement"
    allOf:
      - type: object
        properties:
          recordId:
            type: string
            description: ""
          txnControllerRefNo:
            type: string
            description: ""
          datasegment:
            type: string
            description: ""   
          accNo:
            type: string
            description: ""            
          accBrn:
            type: string
            description: ""   
          stmtType:
            type: string
            description: ""
          stmtFrequency:
            type: string
            description: ""        
          formDt:
            type: string
            format: date
          toDt:
            type: string
            format: date
          narrative:
            type: string
            description: ""
          updatedBy:
            type: string
            description: ""
          updatedTs:
            type: string
            format: date
            description: ""
          createdBy:
            type: string
            description: ""
          createdTs:
            type: string
            format: date
            description: ""
          status:
            type: string
            description: ""
          txnBrnCode:
            type: string
            description: ""
          txnDate:
            type: string
            format: date
            description: ""
          balanceType:
            type: string
          txnRefNo:
            type: string
            description: ""
          version:
            type: number
            description: "" 
          dcn:
            type: string
            description: "DCN refrence from UBS on success of account statment request"           
          addDtls:
              $ref: '#/definitions/AdditionalTransactionDetails'
          txnDtls:
              $ref: '#/definitions/TransactionDetails'
          overrideDtls:
            type: array
            items: 
              $ref: "#/definitions/BaseOutcomeModel"
                 
