#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : tranchedetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/tranche/summary/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Retrieves the Tranche Summary.
      description: Retrieves the Tranche Summary.
      operationId: getTrancheSummary
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the Tranche that needs to be fetched
        required: true
        type: string
      - name: trancheName
        in: query
        description: trancheName
        required: false
        type: string
      responses:
        200:
          description: Returns the Tranche based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal
  /web/v1/tranche:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Adds a new Tranche.
      description: Adds a new Tranche. Add additional information here for this endpoint.
      operationId: addTranche
      parameters:
      - name: Tranche
        in: body
        description: Request Body that contains data required for creating a new Tranche
        required: true
        schema:
          $ref: '#/definitions/TrancheModel'
      responses:
        201:
          description: Returns the Id of the newly created Tranche
          headers:
            Location:
              description: URL of newly created Tranche
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Retrieves the list of existing Tranche.
      description: Retrieves the list of existing Tranche. Add additional information here for the this endpoint.
      operationId: getAllTranches
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: trancheId that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/tranche/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Retrieves the Tranche by id.
      description: Retrieves the Tranche by id. Add additional information here for the this endpoint.
      operationId: getTrancheById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the Tranche based on given applicationNumber.
          schema:
            $ref: '#/definitions/TrancheModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Update an existing Tranche.
      description: Update an existing Tranche. Add additional information here for the this endpoint.
      operationId: updateTranche
      parameters:
      - name: id
        in: path
        description: id of the Tranche that need to be updated
        required: true
        type: string
      - name: Tranche
        in: body
        description: Request Body that contains data required for updating an existing Tranche
        required: true
        schema:
          $ref: '#/definitions/TrancheModel'
      responses:
        200:
          description: Returns updated Tranche
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - Tranche
      summary: Deletes the Tranche identified by given ID.
      description: Deletes the Tranche identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteTranche
      parameters:
      - name: id
        in: path
        description: Id of the Tranche that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  TrancheSummaryModel:
    description: Tranche Summary model
    type: object
    properties:
      trancheId:
        description: trancheId
        type: string
        maxLength: 36
      trancheName:
        description: trancheName
        type: string
        maxLength: 35
      trancheCurrency:
        description: trancheCurrency
        type: string
        maxLength: 3      
      trancheAmount:
        description: trancheAmount
        type: integer
        format: int64
      trancheType:
        description: trancheType
        type: string
        maxLength: 20
      trancheEffectiveDate:
        description: trancheEffectiveDate
        type: string
      trancheExpiryDate:
        description: trancheExpiryDate
        type: string
      trancheMaturityDate:
        description: trancheMaturityDate
        type: string
  TrancheModel:
    description: Tranche model
    type: object
    properties:
      id:
        description: Id of the Tranche
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      remarks:
        description: remarks
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      syndicationType:
        description: Type of Syndication
        type: string
      totalFacilityCurrency:
        description: Facility Currency
        type: string
        maxLength: 3
      totalFacilityAmount:
        description: Facility Amount
        type: number
      numberOfTranches:
        description: Minimum Loan Amount
        type: number
      purposeOfSyndication:
        description: This field captures the purpose of Syndication
        type: string
        maxLength: 255
      trancheDetails:
        type: array
        items:
          $ref: '#/definitions/TrancheDetailsModel'
  TrancheDetailsModel:
    description: TrancheDetails model
    type: object
    properties:
      id:
        description: Id of the TrancheDetails
        type: string
      trancheAmount:
        description: trancheAmount
        type: number
      trancheAvailabilityPeriod:
        description: TrancheAvailabilityPeriod of the trancheDetails
        type: number
      trancheBenchmarkRate:
        description: Tranche Benchmark Rate
        type: string
        maxLength: 20
      trancheCurrency:
        description: Currency
        type: string
        maxLength: 3
      trancheEffectiveDate:
        description: Effective Date
        type: string
      trancheExpiryDate:
        description: Expiry Date
        type: string
      trancheFXRate:
        description: Foreign Exchange Rate
        type: number
      trancheId:
        description: Lender ID
        type: string
        maxLength: 36
      trancheInterestType:
        description: Tranche Interest Type
        type: string
        maxLength: 36
      trancheMaturityDate:
        description: Maturity Date
        type: string
      trancheMaturityPeriod:
        description: Tranche Interest Type
        type: number
      trancheName:
        description: Tranche Name
        type: string
      trancheRepaymentType:
        description: Tranche Repayment Type
        type: string
      trancheType:
        description: Tranche Type
        type: string
      trancheBorrowers:
        type: array
        items:
          $ref: '#/definitions/TrancheBorrowerModel'
      trancheInterestPeriods:
        type: array
        items:
          $ref: '#/definitions/TrancheInterestPeriodModel'
      tranchePurposeList:
        type: array
        items:
          $ref: '#/definitions/TranchePurposeModel'
      trancheUtilizationCurrencies:
        type: array
        items:
          $ref: '#/definitions/TrancheUtilizationCurrenciesModel'
  TrancheBorrowerModel:
    description: TrancheBorrower model
    type: object
    properties:
      id:
        description: Id of the TrancheBorrower
        type: string
      trancheBorrowerId:
        description: trancheBorrowerId
        type: string
      trancheDetailsId:
        description: Tranche Details Id
        type: string
  TrancheInterestPeriodModel:
    description: TrancheInterestPeriod model
    type: object
    properties:
      id:
        description: Id of the TrancheInterestPeriod
        type: string
      trancheInterestPeriod:
        description: trancheInterestPeriod
        type: number
      trancheDetailsId:
        description: Tranche Details Id
        type: string
  TranchePurposeModel:
    description: TranchePurpose model
    type: object
    properties:
      id:
        description: Id of the TranchePurpose
        type: string
      tranchePurpose:
        description: tranchePurpose
        type: string
      trancheDetailsId:
        description: Tranche Details Id
        type: string
  TrancheUtilizationCurrenciesModel:
    description: TrancheUtilizationCurrencies model
    type: object
    properties:
      id:
        description: Id of the TrancheUtilizationCurrencies
        type: string
      trancheUtilizationCurrency:
        description: trancheUtilizationCurrency
        type: string
        maxLength: 3
      trancheDetailsId:
        description: Tranche Details Id
        type: string
  TrancheCollection:
    description: Collection of Tranche.
    type: object
    properties:
      TrancheList:
        type: array
        items:
          $ref: '#/definitions/TrancheModel'
