#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : revenuedetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /loansyndication-services
tags:
- name: LoanSyndication
  description: API for LoanSyndication Operations
schemes:
- http
paths:
  /web/v1/revenuedetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RevenueDetails
      summary: Adds a new RevenueDetails.
      description: Adds a new RevenueDetails. Add additional information here for this endpoint.
      operationId: addRevenueDetails
      parameters:
      - name: RevenueDetails
        in: body
        description: Request Body that contains data required for creating a new RevenueDetails
        required: true
        schema:
          $ref: '#/definitions/RevenueDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created RevenueDetails
          headers:
            Location:
              description: URL of newly created RevenueDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RevenueDetails
      summary: Retrieves the list of  RevenueDetails.
      description: Retrieves the list of  RevenueDetails. Add additional information here for the this endpoint.
      operationId: getAllRevenueDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: page
        in: query
        description: Page
        required: false
        type: integer
      - name: limit
        in: query
        description: Page Size
        required: false
        type: integer
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/revenuedetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RevenueDetails
      summary: Get a  RevenueDetails.
      description: Get a  Revenue Details by given id. Add additional information here for the this endpoint.
      operationId: getRevenueDetailsById
      parameters:
      - name: id
        in: path
        description: id of the RevenueDetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated RevenueDetails
          schema:
            $ref: '#/definitions/RevenueDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RevenueDetails
      summary: Update an  RevenueDetails.
      description: Update an  RevenueDetails. Add additional information here for the this endpoint.
      operationId: updateRevenueDetails
      parameters:
      - name: id
        in: path
        description: id of the RevenueDetails that need to be updated
        required: true
        type: string
      - name: RevenueDetails
        in: body
        description: Request Body that contains data required for updating an  RevenueDetails
        required: true
        schema:
          $ref: '#/definitions/RevenueDetailsModel'
      responses:
        200:
          description: Returns updated RevenueDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - RevenueDetails
      summary: Deletes the A RevenueDetailsidentified by given ID.
      description: Deletes the RevenueDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteRevenueDetails
      parameters:
      - name: id
        in: path
        description: Id of the RevenueDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  RevenueDetailsModel:
    description: RevenueDetails model
    type: object
    required:
    - expectedRevenue
    - expectedCost
    - balanceSheetUsage
    - riskWeightedAst
    properties:
      id:
        description: Id of the RevenueDetails
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the RevenueDetails
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string  
      dataSegmentCode:
        description: Data segment code
        type: string
      expectedRevenue:
        description: Expected Revenue
        type: number
      expectedRevenueCurrency:
        description: Expected Revenue Currency
        type: string
        maxLength: 3	
      expectedCost:
        description: Expected Cost 
        type: number        
      expectedCostCurrency:
        description: Expected Cost Currency
        type: string
        maxLength: 3      
      balanceSheetUsage:
        description: Balance Sheet Usage
        type: number        
      balanceSheetUsageCurrency:
        description: Balance Sheet Usage Currency
        type: string
        maxLength: 3
      riskWeightedAst:
        description: riskWeightedAst
        type: number
      riskWeightedAstCurrency:
        description: riskWeightedAst Currency
        type: string
        maxLength: 3
      remarks:
        description: Remarks of the RevenueDetails
        type: string
        maxLength: 300
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
  RevenueDetailsCollection:
    description: Collection of RevenueDetails.
    type: object
    properties:
      RevenueDetailsList:
        type: array
        items:
          $ref: '#/definitions/RevenueDetailsModel'
