#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cam
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server financialcategory server." 
 version: "1.0.0"
 title: "financialcategory Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "financialcategory"
   description: "Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services. Web API for Financial Category Services."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../financialcategory

 /financialcategory:
  post:
   tags:
    - "financialcategory"
   summary: "Adds a new financialcategory."
   description: "Adds a new financialcategory. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "financialcategory" 
      in: "body" 
      description: "Request Body that contains data required for creating a new financialcategory" 
      required: true
      schema:
       $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created financialcategory" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "financialcategory"
   summary: "Get all valid financialcategory."
   description:  "Get all valid financialcategory. This endpoints will be used to Get all valid financialcategory maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: categoryCode
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../financialcategory/xxx
#   DELETE    .../financialcategory/xxx
#   GET       .../financialcategory/xxx
#   GET       .../financialcategory/xxx?version=latestrecord
#   GET       .../financialcategory/xxx?version=1

 /financialcategory/{id}:
  put:
   tags:
    - "financialcategory"
   summary: "Update an existing financialcategory."
   description:  "Update an existing financialcategory."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the financialcategory Maintenance"
      required: true
      type: "string"
    - name: "financialcategory"
      in: "body"
      description: "Request Body that contains data required for updating an existing financialcategory"
      required: true
      schema:
       $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYDTO"
   responses:
    200:
     description: "Returns updated financialcategory"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "financialcategory"
   summary: "Retrieves the financialcategory by ID."
   description:  "Retrieves the financialcategory by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the financialcategory based on given id."
     schema:
      $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "financialcategory"
   summary: "Deletes the financialcategory identified by given ID."
   description:  "Deletes the financialcategory identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the financialcategory maintenance"
      required: true
      type: "string"
    - name: "financialcategory"
      in: "body"
      description: Request body contain financialcategory and Modification no of financialcategory maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
     
#   path to get the primary category

 /financialcategory/primarycategory:
  get:
   tags:
    - "financialcategory"
   summary: "Retrieves all the primary financialcategory."
   description:  "Retrieves all the primary financialcategory."
   operationId: "getPrimaryCategories"
   parameters:
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
    - name: "categoryCode"
      in: "query"
      description: "Category Code that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the primary financialcategory list."
     schema:
      $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"     

#   path to get the secondary category

 /financialcategory/secondarycategory/{parentCode}:
  get:
   tags:
    - "financialcategory"
   summary: "Retrieves all the secondary financialcategory."
   description:  "Retrieves all the secondary financialcategory."
   operationId: "getSecondaryCategories"
   parameters:
    - name: "parentCode"
      in: "path"
      description: "parent category code of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the primary financialcategory list."
     schema:
      $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"     
 
 /financialcategory/subCategoryCode:
  get:
   tags:
    - "financialcategory"
   summary: "Retrieves all the subcategory."
   description:  "Retrieves all the subcategory."
   operationId: "getSubCategories"
   parameters:
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
    - name: "categoryCode"
      in: "query"
      description: "Category Code that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the primary financialcategory list."
     schema:
      $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error" 


# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../financialcategory/xxx/approve

 /financialcategory/{id}/approve:
  patch:
   tags:
    - "financialcategory"
   summary: "Authorize the financialcategory by given ID."
   description:  "Authorize the financialcategory identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the financialcategory maintenance"
      required: true
      type: "string"
    - name: "financialcategory"
      in: "body"
      description: Request body contain financialcategory and Modification no of financialcategory maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../financialcategory/xxx/close
 /financialcategory/{id}/close:
  patch:
   tags:
    - "financialcategory"
   summary: "Close the financialcategory by given ID."
   description:  "Close the financialcategory identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the financialcategory maintenance"
      required: true
      type: "string"
    - name: "financialcategory"
      in: "body"
      description: Request body contain financialcategory and Modification no of financialcategory maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../financialcategory/xxx/reopen

 /financialcategory/{id}/reopen:
  patch:
   tags:
    - "financialcategory"
   summary: "reopen the financialcategory by given ID."
   description:  "reopen the financialcategory identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the financialcategory maintenance"
      required: true
      type: "string"
    - name: "financialcategory"
      in: "body"
      description: Request body contain financialcategory and Modification no of financialcategory maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../financialcategory/xxx/unauthorized

 /financialcategory/{id}/unauthorized:
  get:
   tags:
    - "financialcategory"
   summary: "Retrives the financialcategory by given ID."
   description:  "Retrives the financialcategory identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the financialcategory based on given id."
     schema:
       $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../financialcategory/xxx/history

 /financialcategory/{id}/history:
  get:
   tags:
    - "financialcategory"
   summary: "Retrives the financialcategory by given ID."
   description:  "Retrives the financialcategory by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the financialcategory based on given id."
     schema:
       $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CFPM_TM_FINANCIAL_CATEGORYDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     categoryCode:
      type: string
      description: ""
     categoryDescription:
      type: string
      description: ""
     parentCategoryCode:
      type: string
      description: ""
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CFPM_TM_FINANCIAL_CATEGORYCollection: 
  description: "Collection of financialcategory."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CFPM_TM_FINANCIAL_CATEGORYWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CFPM_TM_FINANCIAL_CATEGORYDTO"
