#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : overwritesettlement.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/overwritesettlement:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - SettlementOverwrite
      summary: Adds a new SettlementOverwrite.
      description: Adds a new SettlementOverwrite. Add additional information here for this endpoint.
      operationId: addSettlementOverwrite
      parameters:
      - name: SettlementOverwrite
        in: body
        description: Request Body that contains data required for creating a new SettlementOverwrite
        required: true
        schema:
          $ref: '#/definitions/SettlementOverwriteModel'
      responses:
        201:
          description: Returns the Id of the newly created SettlementOverwrite
          headers:
            Location:
              description: URL of newly created SettlementOverwrite
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - SettlementOverwrite
      summary: Retrieves the list of existing SettlementOverwrite.
      description: Retrieves the list of existing SettlementOverwrite. Add additional information here for the this endpoint.
      operationId: getAllSettlementOverwrite
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/overwritesettlement/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - SettlementOverwrite
      summary: Retrieves the SettlementOverwrite by id.
      description: Retrieves the SettlementOverwrite by id. Add additional information here for the this endpoint.
      operationId: getSettlementOverwriteById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the SettlementOverwrite based on given applicationNumber.
          schema:
            $ref: '#/definitions/SettlementOverwriteModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - SettlementOverwrite
      summary: Update an existing SettlementOverwrite.
      description: Update an existing SettlementOverwrite. Add additional information here for the this endpoint.
      operationId: updateSettlementOverwrite
      parameters:
      - name: id
        in: path
        description: id of the SettlementOverwrite that need to be updated
        required: true
        type: string
      - name: SettlementOverwrite
        in: body
        description: Request Body that contains data required for updating an existing SettlementOverwrite
        required: true
        schema:
          $ref: '#/definitions/SettlementOverwriteModel'
      responses:
        200:
          description: Returns updated SettlementOverwrite
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - SettlementOverwrite
      summary: Deletes the SettlementOverwrite identified by given ID.
      description: Deletes the SettlementOverwrite identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteSettlementOverwrite
      parameters:
      - name: id
        in: path
        description: Id of the SettlementOverwrite that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  SettlementOverwriteModel:
    description: SettlementOverwrite model
    type: object
    properties:
      id:
        description: Id of the SettlementOverwrite
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string
      remarks:
        description: remarks
        type: string
      productCode:
        description: productCode
        type: string
      generalLedgerDetails:
        type: array
        items:
          $ref: '#/definitions/GeneralLedgerDetailsModel'
  GeneralLedgerDetailsModel:
    description: GeneralLedgerDetails model
    type: object
    properties:
      id:
        description: Id of the GeneralLedgerDetails
        type: string
      settlementOverwriteId:
        description: settlementOverwriteId
        type: string
      component:
        description: Component Name
        type: string
        maxLength: 36
      internalGL:
        description: INTERNAL GL
        type: string
        maxLength: 36
      internalGLDescription:
        description: Internal GL Description
        type: string
        maxLength: 100
      overwriteDefaultSI:
        description: Overwrite SI
        type: string
        maxLength: 1
  SettlementOverwriteCollection:
    description: Collection of SettlementOverwrite.
    type: object
    properties:
      SettlementOverwriteList:
        type: array
        items:
          $ref: '#/definitions/SettlementOverwriteModel'
