#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : OBREMO
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server businessproducthosts server." 
 version: "1.0.0"
 title: "businessproducthosts Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "businessproducthosts"
   description: "It will map the selected business product with host and will display the list of product and with help of some rules and conditions it will display the result that will be like margin and rate of interest for that product...."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../businessproducthosts

 /businessproducthosts:
  post:
   tags:
    - "businessproducthosts"
   summary: "Adds a new businessproducthosts."
   description: "Adds a new businessproducthosts. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "businessproducthosts" 
      in: "body" 
      description: "Request Body that contains data required for creating a new businessproducthosts" 
      required: true
      schema:
       $ref: "#/definitions/RpmTmBussprodHostMasterDTO"
    #- name: "bindingResult" 
    #  in: "body" 
    #  description: "Request Body that contains data required for creating a new businessproducthosts" 
    #  required: false
    #  schema:
    #   $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created businessproducthosts" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "businessproducthosts"
   summary: "Get all valid businessproducthosts."
   description:  "Get all valid businessproducthosts. This endpoints will be used to Get all valid businessproducthosts maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: authStat
     required: false
     type: string
   - in: query
     name: businessProductCode
     required: false
     type: string
   - in: query
     name: checkerId
     required: false
     type: string
   - in: query
     name: hostProductCode
     required: false
     type: string
   - in: query
     name: makerId
     required: false
     type: string
   - in: query
     name: modNo
     required: false
     type: integer
   - in: query
     name: onceAuth
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/RpmTmBussprodHostMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../businessproducthosts/xxx
#   DELETE    .../businessproducthosts/xxx
#   GET       .../businessproducthosts/xxx
#   GET       .../businessproducthosts/xxx?version=latestrecord
#   GET       .../businessproducthosts/xxx?version=1

 /businessproducthosts/{id}:
  put:
   tags:
    - "businessproducthosts"
   summary: "Update an existing businessproducthosts."
   description:  "Update an existing businessproducthosts."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the businessproducthosts Maintenance"
      required: true
      type: "string"
    - name: "businessproducthosts"
      in: "body"
      description: "Request Body that contains data required for updating an existing businessproducthosts"
      required: true
      schema:
       $ref: "#/definitions/RpmTmBussprodHostMasterDTO"
    #- name: "bindingResult" 
    #  in: "body" 
    #  description: "Request Body that contains data required for modify an existing record businessproducthosts" 
    #  required: false
    #  schema:
    #   $ref: "#/definitions/BindingResult"
   responses:
    200:
     description: "Returns updated businessproducthosts"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "businessproducthosts"
   summary: "Retrieves the businessproducthosts by ID."
   description:  "Retrieves the businessproducthosts by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the businessproducthosts based on given id."
     schema:
      $ref: "#/definitions/RpmTmBussprodHostMasterWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
 /businessproducthosts/{id}/delete:     
  patch:
   tags:
    - "businessproducthosts"
   summary: "Deletes the businessproducthosts identified by given ID."
   description:  "Deletes the businessproducthosts identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the businessproducthosts maintenance"
      required: true
      type: "string"
    - name: "businessproducthosts"
      in: "body"
      description: Request body contain businessproducthosts and Modification no of businessproducthosts maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../businessproducthosts/xxx/approve

 /businessproducthosts/{id}/approve:
  patch:
   tags:
    - "businessproducthosts"
   summary: "Authorize the businessproducthosts by given ID."
   description:  "Authorize the businessproducthosts identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the businessproducthosts maintenance"
      required: true
      type: "string"
    - name: "businessproducthosts"
      in: "body"
      description: Request body contain businessproducthosts and Modification no of businessproducthosts maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../businessproducthosts/xxx/close
 /businessproducthosts/{id}/close:
  patch:
   tags:
    - "businessproducthosts"
   summary: "Close the businessproducthosts by given ID."
   description:  "Close the businessproducthosts identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the businessproducthosts maintenance"
      required: true
      type: "string"
    - name: "businessproducthosts"
      in: "body"
      description: Request body contain businessproducthosts and Modification no of businessproducthosts maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../businessproducthosts/xxx/reopen

 /businessproducthosts/{id}/reopen:
  patch:
   tags:
    - "businessproducthosts"
   summary: "reopen the businessproducthosts by given ID."
   description:  "reopen the businessproducthosts identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the businessproducthosts maintenance"
      required: true
      type: "string"
    - name: "businessproducthosts"
      in: "body"
      description: Request body contain businessproducthosts and Modification no of businessproducthosts maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../businessproducthosts/xxx/unauthorized

 /businessproducthosts/{id}/unauthorized:
  get:
   tags:
    - "businessproducthosts"
   summary: "Retrives the businessproducthosts by given ID."
   description:  "Retrives the businessproducthosts identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the businessproducthosts based on given id."
     schema:
       $ref: "#/definitions/RpmTmBussprodHostMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../businessproducthosts/xxx/history

 /businessproducthosts/{id}/history:
  get:
   tags:
    - "businessproducthosts"
   summary: "Retrives the businessproducthosts by given ID."
   description:  "Retrives the businessproducthosts by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the businessproducthosts based on given id."
     schema:
       $ref: "#/definitions/RpmTmBussprodHostMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 RpmTmBussprodHostMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     businessProductCode:
      type: string
      description: ""
     txnControllerRefNo:
      type: string
      description: "Transaction Reference ID that is generated for every operation performed"      
     hostProductCode:
      type: string
      description: ""
     hostProductDesc:
      type: string
      description: ""
     provisionMode:
      type: string
      description: ""
     productType:
      type: string
      description: ""
     productSubType:
      type: string
      description: ""  
     action:
      type: string
      description: ""
     checkerRemarks:
      type: string
      description: ""
     makerRemarks:
      type: string
      description: ""   
     RpmTmBussprodComponentDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmBussprodComponentDTO'
    required:
     - businessProductCode
     - hostProductCode
     - RpmTmBussprodComponentDTO
 RpmTmBussprodComponentDTO:
  type: object
  properties:
     businessProductCode:
      type: string
      description: ""
     bussprodMasterId:
      type: string
      description: ""
     componentCode:
      type: string
      description: ""
     componentType:
      type: string
      description: "" 
     description:
      type: string
      description: ""
     display:
      type: string
      description: ""
     displayName:
      type: string
      description: ""
     hostProductCode:
      type: string
      description: ""
     mainComponent:
      type: string
      description: "" 
     id:
      type: string
      description: ""
     serialNo:
      description: Component sequence number
      type: integer 
     waiverAllowed:
      type: string
      description: ""
      pattern: '[Y,N]'
     ammendAllowed:
      type: string
      description: ""
      pattern: '[Y,N]'  
     RpmTmBussprodUdeDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmBussprodUdeDTO'
 RpmTmBussprodUdeDTO:
  type: object
  properties:
     ammendAllowed:
      type: string
      description: ""
     businessProductCode:
      type: string
      description: ""
     bussprodComponentId:
      type: string
      description: ""
     componentCode:
      type: string
      description: ""
     des:
      type: string
      description: ""
     display:
      type: string
      description: ""
     displayName:
      type: string
      description: ""
     hostProductCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
     marginAllowed:
      type: string
      description: ""
     udeId:
      type: string
      description: ""
     udeType:
      type: string
      description: "UDE Type"
      pattern: '[A,R]'
     udeMin:
      type: number
      description: "Min interest "
     udeMax:
      type: number
      description: "Max interest " 
     waiverAllowed:
      type: string
      description: ""
     RpmTmBussprodFormulaDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmBussprodFormulaDTO'
 RpmTmBussprodFormulaDTO:
  type: object
  properties:
     businessProductCode:
      type: string
      description: ""
     bussprodUdeId:
      type: string
      description: ""
     card:
      type: string
      description: ""
     chargeBasis:
      type: string
      description: ""
     code:
      type: string
      description: ""
     componentCode:
      type: string
      description: ""
     description:
      type: string
      description: ""
     displayName:
      type: string
      description: ""
     formulaName:
      type: string
      description: ""
     frequency:
      type: string
      description: ""
     hostProductCode:
      type: string
      description: ""
     id:
      type: string
      description: ""
     result:
      type: string
      description: ""
     rules:
      type: string
      description: ""
     type:
      type: string
      description: ""

 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 RpmTmBussprodHostMasterCollection: 
  description: "Collection of bussprodhost."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/RpmTmBussprodHostMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"    
 RpmTmBussprodHostMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/RpmTmBussprodHostMasterDTO"    
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 OrchestratorDTO:    
  type: object    
