#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : OBREMO
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server productattributes server." 
 version: "1.0.0"
 title: "productattributes Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "productattributes"
   description: "As a BANK USER,Administrator,Supervisor,Marketing Head,Product Manager I want a Product Attribute Data Segment So that, product related attributes can be updated for Business Product Maintenance which will further use to provide detail description of the business product."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../productattributes

 /productattributes:
  post:
   tags:
    - "productattributes"
   summary: "Adds a new productattributes."
   description: "Adds a new productattributes. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "productattributes" 
      in: "body" 
      description: "Request Body that contains data required for creating a new productattributes" 
      required: true
      schema:
       $ref: "#/definitions/RpmTmProdAttrMasterDTO"
    #- name: "bindingResult" 
    #  in: "body" 
    #  description: "Request Body that contains data required for creating a new productattributes" 
    #  required: false
    #  schema:
    #   $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created productattributes" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "productattributes"
   summary: "Get all valid productattributes."
   description:  "Get all valid productattributes. This endpoints will be used to Get all valid productattributes maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: authStat
     required: false
     type: string
   - in: query
     name: businessProductCode
     required: false
     type: string
   - in: query
     name: checkerId
     required: false
     type: string
   - in: query
     name: makerId
     required: false
     type: string
   - in: query
     name: modNo
     required: false
     type: integer
   - in: query
     name: onceAuth
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/RpmTmProdAttrMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../productattributes/xxx
#   DELETE    .../productattributes/xxx
#   GET       .../productattributes/xxx
#   GET       .../productattributes/xxx?version=latestrecord
#   GET       .../productattributes/xxx?version=1

 /productattributes/{id}:
  put:
   tags:
    - "productattributes"
   summary: "Update an existing productattributes."
   description:  "Update an existing productattributes."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the productattributes Maintenance"
      required: true
      type: "string"
    - name: "productattributes"
      in: "body"
      description: "Request Body that contains data required for updating an existing productattributes"
      required: true
      schema:
       $ref: "#/definitions/RpmTmProdAttrMasterDTO"
    #- name: "bindingResult" 
    #  in: "body" 
    #  description: "Request Body that contains data required for modify an existing record productattributes" 
    #  required: false
    #  schema:
    #   $ref: "#/definitions/BindingResult"
   responses:
    200:
     description: "Returns updated productattributes"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "productattributes"
   summary: "Retrieves the productattributes by ID."
   description:  "Retrieves the productattributes by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the productattributes based on given id."
     schema:
      $ref: "#/definitions/RpmTmProdAttrMasterWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
     
 /productattributes/getbyBusinessproduct:
  get:
   consumes:
   - application/json
   - application/xml
   produces:
   - application/json
   - application/xml  
   tags:
    - "productattributes"
   summary: "Retrieves the productattributes Details by businessProductCode."
   description:  "Retrieves the productattributes Details by businessProductCode."
   operationId: "getByBusinessProductCode"
   parameters:
    - name: "businessProductCode"
      in: query
      description: "businessProductCode of the record that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the productattributes based on given businessProductCodes."
     schema:
      $ref: "#/definitions/RpmTmProdAttrMasterWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"        
     
 /productattributes/{id}/delete:      
  patch:
   tags:
    - "productattributes"
   summary: "Deletes the productattributes identified by given ID."
   description:  "Deletes the productattributes identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the productattributes maintenance"
      required: true
      type: "string"
    - name: "productattributes"
      in: "body"
      description: Request body contain productattributes and Modification no of productattributes maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../productattributes/xxx/approve

 /productattributes/{id}/approve:
  patch:
   tags:
    - "productattributes"
   summary: "Authorize the productattributes by given ID."
   description:  "Authorize the productattributes identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the productattributes maintenance"
      required: true
      type: "string"
    - name: "productattributes"
      in: "body"
      description: Request body contain productattributes and Modification no of productattributes maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../productattributes/xxx/close
 /productattributes/{id}/close:
  patch:
   tags:
    - "productattributes"
   summary: "Close the productattributes by given ID."
   description:  "Close the productattributes identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the productattributes maintenance"
      required: true
      type: "string"
    - name: "productattributes"
      in: "body"
      description: Request body contain productattributes and Modification no of productattributes maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../productattributes/xxx/reopen

 /productattributes/{id}/reopen:
  patch:
   tags:
    - "productattributes"
   summary: "reopen the productattributes by given ID."
   description:  "reopen the productattributes identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the productattributes maintenance"
      required: true
      type: "string"
    - name: "productattributes"
      in: "body"
      description: Request body contain productattributes and Modification no of productattributes maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/OrchestratorDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../productattributes/xxx/unauthorized

 /productattributes/{id}/unauthorized:
  get:
   tags:
    - "productattributes"
   summary: "Retrives the productattributes by given ID."
   description:  "Retrives the productattributes identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the productattributes based on given id."
     schema:
       $ref: "#/definitions/RpmTmProdAttrMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../productattributes/xxx/history

 /productattributes/{id}/history:
  get:
   tags:
    - "productattributes"
   summary: "Retrives the productattributes by given ID."
   description:  "Retrives the productattributes by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the productattributes based on given id."
     schema:
       $ref: "#/definitions/RpmTmProdAttrMasterCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 RpmTmProdAttrMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     businessProductCode:
      type: string
      description: ""
     txnControllerRefNo:
      type: string
      description: "Transaction Reference ID that is generated for every operation performed"  
     productSubType:
      type: string
      description: ""
     productType:
      type: string
      description: ""     
     businessProductImage:
      type: string
      description: ""
     businessProductSummary:
      type: string
      description: ""
      maxLength: 200
     comments:
      type: string
      description: ""
     productBrochure:
      type: string
      description: ""
     termsandcondition:
      type: string
      description: ""
     RpmTmProdAttrFeatureDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmProdAttrFeatureDTO'
     RpmTmProdAttrElgbDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmProdAttrElgbDTO'
     RpmTmProdAttrFeeChargesDTO:
      type: array
      items:
       $ref: '#/definitions/RpmTmProdAttrFeeChargesDTO'  
    required:
     - businessProductCode
 RpmTmProdAttrFeatureDTO:
  type: object
  properties:
     businessProductCode:
      type: string
      description: ""
     dispOnCat:
      type: string
      description: ""
     featureDesc:
      type: string
      description: ""
     featureName:
      type: string
      description: ""
     id:
      type: string
      description: ""
     prodAttrMasterId:
      type: string
      description: ""
     serialNo:
      description: Sequence number for Attribute Feature
      type: integer  
  #required:
   #- businessProductCode
 RpmTmProdAttrElgbDTO:
  type: object
  properties:
     businessProductCode:
      type: string
      description: ""
     dispOnCat:
      type: string
      description: ""
     eligDesc:
      type: string
      description: ""
     eligName:
      type: string
      description: ""
     id:
      type: string
      description: ""
     prodAttrMasterId:
      type: string
      description: ""
     serialNo:
      description: Sequence number for Attribute Eligibility
      type: integer  
  #required:
   #- businessProductCode
 RpmTmProdAttrFeeChargesDTO:
  type: object
  properties:
     businessProductCode:
      type: string
      description: ""
      maxLength: 6
     dispOnCat:
      type: string
      description: ""
     feeChargesDesc:
      type: string
      description: ""
      maxLength: 400
     feeChargesName:
      type: string
      description: ""
      maxLength: 100
     id:
      type: string
      description: ""
     prodAttrMasterId:
      type: string
      description: ""
     serialNo:
      description: Sequence number for Fee and Charges
      type: integer 
  #required:
   #- businessProductCode



 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 RpmTmProdAttrMasterCollection: 
  description: "Collection of prodattr."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/RpmTmProdAttrMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"     
 RpmTmProdAttrMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/RpmTmProdAttrMasterDTO"
     
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 OrchestratorDTO:    
  type: object