#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : consolrollovermain.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/consolrollovermain:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverMain
      summary: Adds a new ConsolRolloverMain.
      description: Adds a new ConsolRolloverMain. Add additional information here for this endpoint.
      operationId: addConsolRolloverMain
      parameters:
      - name: ConsolRolloverMain
        in: body
        description: Request Body that contains data required for creating a new ConsolRolloverMain
        required: true
        schema:
          $ref: '#/definitions/ConsolRolloverMainModel'
      responses:
        201:
          description: Returns the Id of the newly created ConsolRolloverMain
          headers:
            Location:
              description: URL of newly created ConsolRolloverMain
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverMain
      summary: Retrieves the list of existing ConsolRolloverMain.
      description: Retrieves the list of existing ConsolRolloverMain. Add additional information here for the this endpoint.
      operationId: getAllConsolRolloverMain
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/consolrollovermain/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverMain
      summary: Retrieves the ConsolRolloverMain by id.
      description: Retrieves the ConsolRolloverMain by id. Add additional information here for the this endpoint.
      operationId: getConsolRolloverMainById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ConsolRolloverMain based on given applicationNumber.
          schema:
            $ref: '#/definitions/ConsolRolloverMainModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverMain
      summary: Update an existing ConsolRolloverMain.
      description: Update an existing ConsolRolloverMain. Add additional information here for the this endpoint.
      operationId: updateConsolRolloverMain
      parameters:
      - name: id
        in: path
        description: id of the ConsolRolloverMain that need to be updated
        required: true
        type: string
      - name: ConsolRolloverMain
        in: body
        description: Request Body that contains data required for updating an existing ConsolRolloverMain
        required: true
        schema:
          $ref: '#/definitions/ConsolRolloverMainModel'
      responses:
        200:
          description: Returns updated ConsolRolloverMain
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ConsolRolloverMain
      summary: Deletes the ConsolRolloverMain identified by given ID.
      description: Deletes the ConsolRolloverMain identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteConsolRolloverMain
      parameters:
      - name: id
        in: path
        description: Id of the ConsolRolloverMain that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ConsolRolloverMainModel:
    description: ConsolRolloverMain model
    type: object
    properties:
      id:
        description: Id of the ConsolRolloverMain
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      trancheRefNo:
        description: trancheRefNo
        type: string
        maxLength: 20
      valueDate:
        description: valueDate
        type: string
      customerNumber:
        description: customerNumber
        type: string
        maxLength: 20
      contractCurrencyLOV:
        description: contractCurrencyLOV
        type: array
        items:
          type: string
      productCodeLOV:
        description: productCodeLOV
        type: array
        items:
          type: string
      contractCurrency:
        description: contractCurrency
        type: string
      productCode:
        description: productCode
        type: string
        maxLength: 20
      rolloverType:
        description: rolloverType
        type: string
      rolloverAmount:
        description: rolloverAmount
        type: string
      maturityDate:
        description: maturityDate
        type: string
      maturityDays:
        description: maturityDays
        type: number
      rolloverBy:
        description: rolloverBy
        type: string
      rolloverMode:
        description: rolloverMode
        type: string
        maxLength: 20
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number
        type: string
        maxLength: 36
  ConsolRolloverMainCollection:
    description: Collection of ConsolRolloverMain.
    type: object
    properties:
      ConsolRolloverMainList:
        type: array
        items:
          $ref: '#/definitions/ConsolRolloverMainModel'
