swagger: "2.0"
info:
  description: "This is a sample BPM server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "BPM Service"
host: "whf00anh:7701"
basePath: "/bpm-services"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "BPMSoaApi"
    description: "API for BPM SOA"
    
schemes:
- "https"

paths:
  /service/v1/bpm/:
    post:
      tags:
        - "soa"
      summary: "Calls bpm soa service."
      description: "Calls bpm soa service."
      operationId: "callBPMSOA"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: true
        - name: "bpm"
          in: "body"
          description: "Request Body that contains data required for calling bpm soa service"
          required: true
          schema:
            $ref: "#/definitions/TransactionHeaderModel"
      responses:
        201:
          description: "Returns the outcome of calling bpm soa service"
          headers:
            Location:
              description: "Returns the outcome of calling bpm soa service"
              type: "string"
          schema:
              $ref: "#/definitions/InlineResponse"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
definitions:
  InlineResponse:
    type: "object"
    description: "Response of the newly called service"
    properties:
      message1:
       type: "string"
      message2:
       type: "string"
  TransactionHeaderModel:
    type: "object"
    properties:
      processRefNo:
        type: "string"
      taskOutcome:
        type: "string"
      currentUser:
        type: "string"
      branchCode:
        type: "string"
      processName:
        type: "string"
      taskId:
        type: "string"
      currentStage:
        type: "string"
      tab:
        type: "string"
      taskPriority:
        type: "string"
      instanceId:
        type: "string"
      moduleCode:
        type: "string"
      isFromCAM:
        type: "boolean"
      externalCheckReq:
        type: "boolean"
      fieldInvestigationReq:
        type: "boolean"
      externalValuationReq:
        type: "boolean"
      internalValuationReq:
        type: "boolean"
      legalOpinionReq:
        type: "boolean"
      riskEvaluationReq:
        type: "boolean"
      externalCheckAgencySelected:
        type: "boolean"
      externalValAgencySelected:
        type: "boolean"
      legalFirmSelected:
        type: "boolean"
      isCollatCreateSelected:
        type: "boolean"
      collateralValue:
        type: "number"
      oldCollateralValue:
        type: "number"
      isFromCollateralEvaluation:
        type: "boolean"
      isFromCollateralReview:
        type: "boolean"
      isSubmissionAndAwaitingReq:
        type: "boolean"
      serviceName:
        type: "string"
      ownerEstimatedValue:
        type: "number"
      marketValue:
        type: "number"
      bankValue:
        type: "number"
      customerId:
        type: "string"
      collateralType:
        type: "string"
      collateralCode:
        type: "string"
      collateralCurrency:
        type: "string"
      taskCreationDate:
        type: "string"
        format: "date-time"
      submitFlag:
        type: "boolean"
      source:
        type: "string"
      isKYCRequired:
        type: "boolean"
      isCreditRatingRequired:
        type: "boolean"
      stageUpdateFlag:
        type: "boolean"
      collateralSubmissionReq:
        type: "boolean"
      awaitForConfirmation:
        type: "boolean"
      documentSafeKeepingReq:
        type: "boolean"
      updateCategory:
        type: "string"