swagger: "2.0"
info:
  version: "1.0.0"
  title: "Charges Pricing Template Definitions"

paths:
  /:
    get:
      responses:
        201:
          description: "Charges Pricing Template Definitions Yaml File"
     
definitions:
  ObPrcMethodsModel:
    description: "Pricing Methods Model"
    type: "object"
    properties:
      id:
        description: "Id of the Parameter"
        type: "integer"
        format: "int64"
      applicationCode:
        description: "Application Id"
        type: "string"
      prcCategory:
        description: "Pricing Category"
        type: "string"
      prcCategoryDesc:
        description: "Pricing Category Description"
        type: "string"
      prcMethod:
        description: "Pricing Method"
        type: "string"
      prcMethodDesc:
        description: "Pricing Method Description"
        type: "string"
      slabType:
        description: "Slab Type"
        type: "string"
  
  ObPrcCategoryModel:
    description: "Pricing Category Model"
    type: "object"
    properties:
      prcCategory:
        description: "Pricing Category"
        type: "string"
      prcCategoryDesc:
        description: "Pricing Category Description"
        type: "string"
  
  ObPrcMethodsCollection:
    description: "Collection of list of Parameters."
    type: "object"
    properties:
      ObPrcMethodsModel:
        type: "array"
        items:
          $ref: "#/definitions/ObPrcMethodsModel"
  
  ObPrcCategoryCollection:
    description: "Collection of list of Parameters."
    type: "object"
    properties:
      ObPrcCategoryModel:
        type: "array"
        items:
          $ref: "#/definitions/ObPrcCategoryModel" 
  
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer

  ModListKeyDto:
   type: object
   properties:
    modNos:
     type: array
     description: "Mod No"
     items:
      type: integer
    remarks:
     type: string
     description: "Remarks"

  KeyDto:
   type: object
   properties:
    modNo:
     type: integer
     description: "Mod no"
    remarks:
     type: string
     description: "Remarks"

  ResponseDto:
   type: object
   properties:
    id:
     type: string
     description: "Id"
    status:
     type: string
     description: "Status"
    codes:
     type: array
     description: "Codes"
     items:
      $ref: "#/definitions/ResponseCode"
    requestId:
     type: string
  
  ResponseCode:
   type: object
   properties:
    Code:
     type: string
     description: "Code"
    Desc:
     type: string
     description: "Description"
    Type:
     type: string
     description: "Type"
    Language:
     type: string
     description: "Language"
    args:
     type: array
     description: "Args"
     items:
      type: object
    arg:
     type: string
     description: "Args"

  GenericDto:
   allOf:
    - type: object
      discriminator: resource_type
      
  SlabDetails:
    type: object
    properties:
      fromSlab:
        type: number
        description: "From Slab"
      toSlab:
        type: number
        description: "To Slab"
      amount:
        type: number
        description: "Amount"
      percentage:
        type: number
        description: "Percentage"
      unit:
        type: number
        description: "Unit"

  ChargeCodeDetails:
    type: object
    properties:
      txnRefNo:
        type: string
        description: "Transaction Reference Number"
      partyId:
        type: string
        description: "Party Id"
      chargeCode:
        type: string
        description: "Charge Code"
      chargeCodeDesc:
        type: string
        description: "Charge Code Description"
      parentChargeCode:
        type: string
        description: "Parent Charge Code"
      chargeGroup:
        type: string
        description: "Charge Group"
      chargeCategory:
        type: string
        description: "Charge Category"
      chargeType:
        type: string
        description: "Charge Type"
      chargeSharing:
        type: string
        description: "Charge Sharing"
      partyToCharge:
        type: string
        description: "Party To Charge"
      chargeSharingPct:
        type: number
        description: "Charge Sharing Pct"
      chargeCriteria:
        type: string
        description: "Charge Criteria"
      chargeCriteriaValue:
        type: number
        description: "Charge Criteria Value"
      referenceStartDate:
        type: string
        description: "Reference Start Date"
      referenceStartDateValue:
        type: string
        description: "Reference Start Date Value"
      referenceEndDate:
        type: string
        description: "Reference End Date"
      referenceEndDateValue:
        type: string
        description: "Reference End Date Value"
      tenor:
        type: number
        description: "Tenor"
      priceTemplateId:
        type: string
        description: "Price Template Id"
      priceMethod:
        type: string
        description: "Price Method"
      priceMethodDesc:
        type: string
        description: "Price Method Description"
      txnCcy:
        type: string
        description: "Transaction Currency"
      priceCcy:
        type: string
        description: "Price Currency"
      chargeInTxnCcy:
        type: string
        description: "Charge In Transaction Currency"
      flatCharge:
        type: string
        description: "Flat Charge"
      fixedAmt:
        type: number
        description: "Fixed Amount"
      fixedPct:
        type: number
        description: "Fixed Pct"
      annumBasis:
        type: number
        description: "Annum Basis"
      allowWaive:
        type: string
        description: "Allow Waive"
      autoWaive:
        type: string
        description: "Auto Waive"
      allowOverride:
        type: string
        description: "Allow Override"
      collectionType:
        type: string
        description: "Collection Type"
      collectionFreq:
        type: string
        description: "Collection Frequency"
      collectionRefPeriod:
        type: string
        description: "Collection Reference Period"
      collectionUnits:
        type: number
        description: "Collection Units"
      calcType:
        type: string
        description: "Calculate Type"
      calcFreq:
        type: string
        description: "Calculate Frequency"
      calcRefPeriod:
        type: string
        description: "Calculate Reference Period"
      calcUnits:
        type: number
        description: "Calculate Units"
      allowPrcModify:
        type: string
        description: "Allow Price Modify"
      exchangeRate:
        type: number
        description: "Exchange Rate"
      slabDetails:
        description: "Slab Details"
        type: "array"
        items:
          $ref: "#/definitions/SlabDetails" 
          
  ChargeCodeDetailsCollection:
    type: object
    properties:
      priceMethods:
        description: "Price Methods"
        type: "array"
        items:
          $ref: "#/definitions/ChargeCodeDetails"
          
  ScfTransOutputResponse:
    description: "Output response from transaction API"
    type: "object"
    properties:
      queryList:
        type: "array"
        items:
          $ref: "#/definitions/ScfFilterQueryModel"
          
  ScfFilterQueryModel:
    description: "Query and attribute list model"
    type: "object"
    properties:
      query:
        description: "Filter Query"
        type: "string"
      ScfTransCriteriaQueryAttributeModel:
        type: "array"
        items:
          $ref: "#/definitions/ScfTransCriteriaQueryAttributeModel"
          
  ScfAttribute:
    description: "Represents each attribute of the records filtered in calling service using filter query"
    type: "object"
    properties:
      attributeName:
        description: "Name of the attribute representing DB column name"
        type: "string"
      attributeValue:
        description: "Value of the corresponding column in DB"
        type: "string"
        
  ScfFilterRecords:
    description: "Represents the records filtered in calling service using filter query"
    type: "object"
    properties:
      attributeList:
        type: "array"
        items:
          $ref: "#/definitions/ScfAttribute"
          
  ScfFilterInput:
    description: "Represents the input request of the final filter service call from transaction services"
    type: "object"
    properties:
      category:
        description: "Represents the category of the filter"
        type: "string"
      applicationCode:
        description: "Represents the applicationCode of the filter"
        type: "string"
      filterRecords:
        type: "array"
        items:
          $ref: "#/definitions/ScfFilterRecords"
          
  ScfFilterOutput:
    description: "Represents the best possible combination for the given category"
    type: "object"
    properties:
      attributeList:
        type: "array"
        items:
          $ref: "#/definitions/ScfAttribute"
          
  ScfTransCriteriaQueryAttributeModel:
    description: "Query for each type of given category"
    type: "object"
    properties:
      paramIndex:
        description: "Input parameter index in the query"
        type: "integer"
      paramName:
        description: "Input parameter name in the query"
        type: "string"
      columnName:
        description: "Corresponding column of the input parameter index in the query"
        type: "string"
      mappedParam:
        type: "string"
        
  ScfFilterParamModelKeyCollection:
    description: "Collection of list of Parameters."
    type: "object"
    properties:
      category:
        description: "category of the param"
        type: "string"
      ScfFilterParamModelCollection:
        type: "array"
        items:
          $ref: "#/definitions/ScfFilterParamModelCollection"

  ScfFilterParamModelCollection:
    description: "Collection of Scf filter parameters"
    type: "object"
    properties:
      type:
        description: "Filter criteria"
        type: "string"
      hierarchy:
        description: "hierarchy of the criteria"
        type: "string"
      ScfFilterParamModel:
        type: "array"
        items:
          $ref: "#/definitions/ScfFilterParamModel"

  ScfFilterParamModel:
    description: "Scf Filter Parameters model"
    type: "object"
    properties:
      parameter:
        description: "Name of the parameter"
        type: "string"
      label:
        description: "Label of the parameter for given language"
        type: "string"
      columnName:
        description: "Name of the mapped column for given parameter"
        type: "string"
      fieldType:
        description: "Field Type"
        type: "string"
      endpointValue:
        description: "Endpoint Value"
        type: "string"
      reqParams:
        description: "Request Parameters"
        type: "string"
      lovConfig:
        description: "LOV Config Data"
        type: "array"
        items:
         $ref: "#/definitions/Map"

  SfsSystemParamCollection:
    description: "Collection of list of Parameters."
    type: "object"
    properties:
      SfsSystemParamModel:
        type: "array"
        items:
          $ref: "#/definitions/SfsSystemParamModel"
  SfsSystemParamModel:
    description: "Sfs System Param model"
    type: "object"
    properties:
      id:
        description: "Id of the Parameter"
        type: "integer"
        format: "int64"
      key:
        description: "Key for the parameter.This is a unique constraint"
        type: "string"
      value:
        description: "Configured value which will be used in rest of application."
        type: "string"

  StringStringMap:
    type: object
    additionalProperties:
      type: string
            
  ChargesRequestDto:
    type: object
    properties:
      applicationCode:
        type: string
        description: "Application Code"
      category:
        type: string
        description: "Category"
      txnMap:
        $ref: "#/definitions/StringStringMap"
      chargeCodes:
        type: "array"
        description: "Charge Codes"
        items:
          type: "string"
              
  ChargesResponseDto:
    type: object
    properties:
      chargeDetails:
        description: "Charge Details"
        type: "array"
        items:
          $ref: "#/definitions/ChargesDetails"
          
  ChargesDetails:
    type: object
    properties:
      txnRefNo:
        type: string
        description: "Transaction Reference Number"
      partyId:
        type: string
        description: "Party Id"
      chargeCode:
        type: string
        description: "Charge Code"
      partyToCharge:
        type: string
        description: "Party To Charge"
      priceMethod:
        type: string
        description: "Price Method"
      charge:
        type: number
        description: "Charge"
      chargeCcy:
        type: string
        description: "Charge Currency"
      exchangeRate:
        type: number
        description: "Exchange Rate"
        
  CmcTmChgPrcTmpltCollection: 
    description: "Collection of Charge Price Rules."
    type: "object"
    properties:
      data:
        type: "array"
        items: 
          $ref: "#/definitions/CmcTmChgPrcTmpltDTO"
      paging:
        $ref: "#/definitions/PagingDto"
        
  CmcTmChgPrcTmpltDTO:
    type: object
    allOf:
      - $ref: '#/definitions/GenericDto'
      - type: object
    properties:
      applicationCode:
        type: string
        description: "Application Code"
      annumBasis:
        type: string
        description: "Annum Basis"
      chgInTxnCcy:
        type: string
        description: "Charge In Transaction Currency Flag"
      chgPrcDesc:
        type: string
        description: "Price Method Description"
      chgPrcTemplateId:
        type: string
        description: "Price Rule Id"
      fixedAmt:
        type: number
        description: "Fixed Amount"
      fixedPct:
        type: number
        description: "Fixed Percentage"
      flatChg:
        type: string
        description: "Flat Charge Flag"
      maxChgAmount:
        type: number
        description: "Maximum Charge Amount"
      maxChgPct:
        type: number
        description: "Maximum Charge Percentage"
      minChgAmount:
        type: number
        description: "Minimum Charge Amount"
      minChgPct:
        type: number
        description: "Minimum Charge Percentage"
      minMaxValidationCriteria:
        type: string
        description: "Min-Max CHarge Criteria"
      prcCategory:
        type: string
        description: "Price Category"
      prcCategoryDesc:
        type: string
        description: "Price Category Description"
      prcCcy:
        type: string
        description: "Price Rule Currency"
      prcMethod:
        type: string
        description: "Price Method"
      prcMethodDesc:
        type: string
        description: "Price Method Description"
      ObTmChgPrcTiersDTO:
        type: array
        items:
          $ref: '#/definitions/CmcTmChgPrcTiersDTO'
      CmcTmChgPrcTiersDTO:
        type: array
        items:
          $ref: '#/definitions/CmcTmChgPrcTiersDTO'
      txnControllerRefNo:
        type: string
        description: "Transaction COntroller Reference Number"
      
  CmcTmChgPrcTiersDTO:
    type: object
    properties:
      amount:
        type: number
        description: "Slab Amount"
      chgPrcTemplateId:
        type: string
        description: "Price Rule Id"
      fromSlab:
        type: number
        description: "Slab start limit"
      id:
        type: string
        description: "Id"
      pct:
        type: number
        description: "Slab Percentage"
      prcMasterId:
        type: string
        description: "Price rule master id"
      toSlab:
        type: number
        description: "Slab end limit"
      unit:
        type: number
        description: "Slab units"
        
  CmcTmChgPrcTmpltWrapperDTO:
    type: object
    properties:
      data:
        $ref: "#/definitions/CmcTmChgPrcTmpltDTO"
        
  ResponseDtoWrapper:
   type: object
   properties:
     messages:
      $ref: "#/definitions/ResponseDto"
     data:
      $ref: "#/definitions/ResponseResourceSupport"
  ResponseResourceSupport:
   type: object
  OrchestratorDTO:
   type: object

  ChgPrcTmplWebModel:
    description: ChgPrcTmplWebModel
    type: object
    properties:
      resourceId:
        description: "Resource id"
        type: string
      resourceName:
        description: "Resource name"
        type: string
      operationType:
        description: "Operation type"
        type: string
      makerId:
        description: "Maker id"
        type: string
      makerDateStamp:
        description: "Maker date stamp"
        type: string
        format: date-time
      checkerId:
        description: "Check id"
        type: string
      checkerDateStamp:
        description: "Checker date stamp"
        type: string
        format: date-time
      modNo:
        description: "Mod no"
        type: integer
      recordStatus:
        description: "Record status flag"
        type: string
      authStatus:
        description: "Auth status flag"
        type: string
      onceAuth:
        description: "Once auth flag"
        type: string
      doerRemarks:
        description: "Doer remarks"
        type: string
      approverRemarks:
        description: "Approver  remarks"
        type: string
      cmcTmChgPrcTmplt:
        $ref: '#/definitions/CmcTmChgPrcTmpltDTO'
      extendedDatasegments:
        description: "Data for the extended datasegment operation"
        type: array
        items:
          type: object
    required:
      - resourceId
      - operationType