#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ubsproductprocessor.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: UBS Product Processor
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: UBS Product Processor
  description: API for UBS Product Processor
schemes:
- http
paths:
  /backoffice/ratequotations:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RateQuotation
      summary: Get the Rate quotation.
      description: Get the Rate quotation.
      operationId: generateRateQuotation
      parameters:
      - name: RateQuotation
        in: body
        description: Request Body that contains data required to get rate quotation
        required: true
        schema:
          $ref: '#/definitions/RateQuotationModel'
      responses:
        201:
          description: Returns the rate quotation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /backoffice/treasuryrates:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TreasuryRate
      summary: Book the Treasury Rate.
      description: Book the Treasury Rate.
      operationId: bookTreasuryRates
      parameters:
      - name: TreasuryRate
        in: body
        description: Request Body that contains data required to book treasury rate
        required: true
        schema:
          $ref: '#/definitions/TreasuryRateModel'
      responses:
        201:
          description: Returns the treasury rate
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error        
  /backoffice/ratequotations/bookcontract/{ticketReferenceNumber}:
    patch:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RateQuotation
      summary: Get the Rate quotation.
      description: Get the Rate quotation.
      operationId: bookRateQuotationContract
      parameters:
      - name: RateQuotation
        in: body
        description: Request Body that contains data required to get rate quotation
        required: true
        schema:
          $ref: '#/definitions/RateQuotationModel'
      - name: ticketReferenceNumber
        in: path
        description: Ticket Reference Number
        required: true
        type: string
      responses:
        201:
          description: Returns the rate quotation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /backoffice/ratequotations/reversecontract/{ticketReferenceNumber}:
    patch:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RateQuotation
      summary: Get the Rate quotation.
      description: Get the Rate quotation.
      operationId: reverseRateQuotationContract
      parameters:
      - name: RateQuotation
        in: body
        description: Request Body that contains data required to get rate quotation
        required: true
        schema:
          $ref: '#/definitions/RateQuotationModel'
      - name: ticketReferenceNumber
        in: path
        description: Ticket Reference Number
        required: true
        type: string
      responses:
        201:
          description: Returns the rate quotation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /backoffice/treasuryRate/gettreasuryrate/{ticketReferenceNumber}:
    patch:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TreasuryRate
      summary: Get the treasury Rate.
      description: Get the Treasury Rate.
      operationId: getTreasuryRateDetails
      parameters:
      - name: treasuryRate
        in: body
        description: Request Body that contains data required to get treasury rate
        required: true
        schema:
          $ref: '#/definitions/TreasuryRateModel'
      - name: ticketReferenceNumber
        in: path
        description: Ticket Reference Number
        required: true
        type: string
      responses:
        201:
          description: Returns the treasury rate
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error       
definitions:
  RateQuotationModel:
    description: RateQuotationModel
    type: object
    properties:
      id:
        description: Id of the RolloverPreferences
        type: string
        maxLength: 36
      ticketReferenceNumber:
        description: Ticket Reference Number
        type: string
        maxLength: 20
      loanAmount:
        description: Loan Amount
        type: number
        minimum: 0
      loanCurrency:
        description: Loan Currency
        type: string
        maxLength: 3
      facilityId:
        description: Facility Id
        type: string
        minimum: 0
        maximum: 20
      rate:
        description: rate
        type: number
        minimum: 0
      generatedTimestamp:
        description: Generated TimeStamp
        type: string
      validity:
        description: Validity Duration
        type: string
        maxLength: 20
      valid:
        description: Valid
        type: string
        minLength: 0
        maxLength: 1
      blocked:
        description: Blocked
        type: string
        minLength: 0
        maxLength: 1
  TreasuryRateModel:
    description: TreasuryRateModel
    type: object
    properties:
      id:
        description: Id of the RolloverPreferences
        type: string
        maxLength: 36
      ticketReferenceNumber:
        description: Ticket Reference Number
        type: string
        maxLength: 20
      loanAmount:
        description: Loan Amount
        type: number
        minimum: 0
      loanCurrency:
        description: Loan Currency
        type: string
        maxLength: 3
      facilityId:
        description: Facility Id
        type: string
        minimum: 0
        maximum: 20
      rate:
        description: rate
        type: number
        minimum: 0
      partyId:
        description: partyId
        type: integer
      partyName:
        description: partyName
        type: string  
      generatedTimestamp:
        description: Generated TimeStamp
        type: string
      validity:
        description: Validity Duration
        type: string
        maxLength: 20
      valid:
        description: Valid
        type: string
        minLength: 0
        maxLength: 1
      blocked:
        description: Blocked
        type: string
        minLength: 0
        maxLength: 1      