#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : furtherconditionsprecedent.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /clmo-syndicationapplication-services
tags:
- name: LoanApplication
  description: API for Syndication Application Operations
schemes:
- http
paths:
  /web/v1/furthercp:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FurtherCPs
      summary: Adds a new FurtherCPs.
      description: Adds a new FurtherCPs. Add additional information here for this endpoint.
      operationId: addFurtherCPs
      parameters:
      - name: FurtherCPs
        in: body
        description: Request Body that contains data required for creating a new FurtherCPDetails
        required: true
        schema:
          $ref: '#/definitions/FurtherCPModel'
      responses:
        201:
          description: Returns the Id of the newly created FurtherCPDetails
          headers:
            Location:
              description: URL of newly created FurtherCPDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FurtherCPs
      summary: Retrieves the list of existing FurtherCPs.
      description: Retrieves the list of existing FurtherCPs. Add additional information here for the this endpoint.
      operationId: getAllFurtherCPs
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/furthercp/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FurtherCPs
      summary: Get a  FurtherCP.
      description: Update a  FurtherCP. Add additional information here for the this endpoint.
      operationId: getFurtherCPsById
      parameters:
      - name: id
        in: path
        description: id of the FurtherCPDetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated FurtherCP
          schema:
            $ref: '#/definitions/FurtherCPModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FurtherCPs
      summary: Update an existing FurtherCP.
      description: Update an existing FurtherCPDetails. Add additional information here for the this endpoint.
      operationId: updateFurtherCPs
      parameters:
      - name: id
        in: path
        description: id of the FurtherCP that need to be updated
        required: true
        type: string
      - name: FurtherCPs
        in: body
        description: Request Body that contains data required for updating an existing FurtherCPDetails
        required: true
        schema:
          $ref: '#/definitions/FurtherCPModel'
      responses:
        200:
          description: Returns updated FurtherCPDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - FurtherCPs
      summary: Deletes the FurtherCPs identified by given ID.
      description: Deletes the FurtherCPDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteFurtherCPs
      parameters:
      - name: id
        in: path
        description: Id of the FurtherCPDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FurtherCPModel:
   description: FurtherCPDetails model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      processRefNumber:
        description: Process Ref Number 
        type: string
      furtherCPWaiverDetails:
        description: FurtherCP Waiver Details
        type: array
        items:
          $ref: '#/definitions/FurtherCPWaiverDetailsModel' 
      cpStatus:
        description: CP Status
        type: string
        maxLength: 1
      waiver:
        description: waiver
        type: string
        maxLength: 1
      furtherCPSatisfactionDoc:
        description: FurtherCPSatisfactionDoc of the FurtherCp
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  FurtherCPWaiverDetailsModel:
     description: FurtherCPWaiverDetails model
     type: object
     properties:
      id:
        description: Id of the FurtherCPWaiverDetailsModel
        type: string
        maxLength: 36          
      furtherCPId:
        description: furtherCPId
        type: string
        maxLength: 36
      waiverCondition:
        description: Waiver Condition
        type: string
        maxLength: 20
      waiverAuthority:
        description: Waiver Authority
        type: string
      waiverApproval:
        description: Waiver Approval
        type: string
        maxLength: 1
      furtherCPWaiverApprovalDoc:
        description: applicantDetailsDocument of the ApplicantDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  FurtherCPDetailsCollection:
    description: Collection of FurtherCPDetails.
    type: object
    properties:
      FurtherCPDetailsList:
        type: array
        items:
          $ref: '#/definitions/FurtherCPWaiverDetailsModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type