#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : furthercp.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
  - name: SyndicationApplication
    description: API for SyndicationApplication Operations
schemes:
  - http
paths:
  /web/v1/furthercp:
    post:
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      tags:
        - FurtherCP
      summary: Adds a new FurtherCP.
      description: Adds a new FurtherCP. Add additional information here for this endpoint.
      operationId: addFurtherCP
      parameters:
        - name: FurtherCP
          in: body
          description: Request Body that contains data required for creating a new FurtherCP
          required: true
          schema:
            $ref: '#/definitions/FurtherCPModel'
      responses:
        201:
          description: Returns the Id of the newly created FurtherCP
          headers:
            Location:
              description: URL of newly created FurtherCP
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - FurtherCP
      summary: Retrieves the list of existing FurtherCP.
      description: Retrieves the list of existing FurtherCP. Add additional information here for the this endpoint.
      operationId: getAllFurtherCP
      parameters:
        - name: applicationNumber
          in: query
          description: applicationNumber of the user that needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/furthercp/{id}:
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - FurtherCP
      summary: Retrieves the FurtherCP by id.
      description: Retrieves the FurtherCP by id. Add additional information here for the this endpoint.
      operationId: getFurtherCPById
      parameters:
        - name: id
          in: path
          description: Id that needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Returns the FurtherCP based on given applicationNumber.
          schema:
            $ref: '#/definitions/FurtherCPModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      tags:
        - FurtherCP
      summary: Update an existing FurtherCP.
      description: Update an existing FurtherCP. Add additional information here for the this endpoint.
      operationId: updateFurtherCP
      parameters:
        - name: id
          in: path
          description: id of the FurtherCP that need to be updated
          required: true
          type: string
        - name: FurtherCP
          in: body
          description: Request Body that contains data required for updating an existing FurtherCP
          required: true
          schema:
            $ref: '#/definitions/FurtherCPModel'
      responses:
        200:
          description: Returns updated FurtherCP
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
        - application/json
        - application/xml
      tags:
        - FurtherCP
      summary: Deletes the FurtherCP identified by given ID.
      description: Deletes the FurtherCP identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteFurtherCP
      parameters:
        - name: id
          in: path
          description: Id of the FurtherCP that needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FurtherCPModel:
    description: FurtherCP model
    type: object
    properties:
      id:
        description: Id of the FurtherCP
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      remarks:
        description: remarks
        type: string
      overallCpCondition:
        description: overallCpCondition
        type: string
      furtherCPDetails:
        type: array
        items:
          $ref: '#/definitions/FurtherCPDetailsModel'
  FurtherCPDetailsModel:
    description: FurtherCPDetails model
    type: object
    properties:
      id:
        description: Id of the FurtherCPDetails
        type: string
      furtherCpId:
        description: furtherCpId
        type: string
      cpCategory:
        description: cpCategory
        type: string
      cpSection:
        description: cpSection
        type: string
      cpDefinition:
        description: cpDefinition
        type: string
      cpStatus:
        description: cpStatus
        type: string
      waiver:
        description: waiver
        type: string
      exceptionalApproval:
        description: exceptionalApproval
        type: string
      cpRemarks:
        description: cpRemarks
        type: string
      furtherCPDoc:
        type: array
        items:
          $ref: '#/definitions/FurtherCPDocModel'
  FurtherCPDocModel:
    description: FurtherCPDoc model
    type: object
    properties:
      id:
        description: Id of the FurtherCPDoc
        type: string
      parentDatasegmentId:
        description: parentDatasegmentId
        type: string
      documentLinkageId:
        description: documentLinkageId
        type: string
      documentType:
        description: documentType
        type: string
      documentName:
        description: documentName
        type: string
  FurtherCPCollection:
    description: Collection of FurtherCP.
    type: object
    properties:
      FurtherCPList:
        type: array
        items:
          $ref: '#/definitions/FurtherCPModel'
