#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : partyrole.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Party Role Services
host: 10.184.157.121:9000
schemes:
- http
paths:
  /web/v1/partyrole:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PartyRole
      summary: Adds a new Party.
      description: Adds a new Party. Add additional information here for this endpoint.
      operationId: addParty
      parameters:
      - name: Party
        in: body
        description: Request Body that contains data required for creating a new Party
        required: true
        schema:
          $ref: '#/definitions/PartyModel'
      responses:
        201:
          description: Returns the Id of the newly created Party
          headers:
            Location:
              description: URL of newly created Party
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  PartyModel:
    description: Party model
    type: object
    properties:
      id:
        description: Id of the Party
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string
      remarks:
        description: remarks
        type: string
      validateSave:
        description: validate Save flag
        type: string
      partyDetails:
        type: array
        items:
          $ref: '#/definitions/PartyDetailsModel'
  PartyDetailsModel:
    description: PartyDetails model
    type: object
    properties:
      id:
        description: Id of the PartyDetails
        type: string
      keyId:
        description: Maintenance Id of the PartyDetails
        type: string
      modNo:
        description: Mod Number
        type: number
      partyNumber:
        description: partyNumber
        type: string
      partyName:
        description: partyName
        type: string
      partyId:
        description: partyId
        type: string
      maintenancePartyId:
        description: maintenancePartyId
        type: string
      countryOfIncorporation:
       type: string
       description: "Country Of Incorporation"
      dateOfIncorporation:
       type: string
       description: "Date Of Incorporation"
      demographicType:
       type: string
       description: "Demographic Type"
      organizationType:
       type: string
       description: "Organization Type"
      kycStatus:
       type: string
       description: "KYC Status"
      holdingPattern:
       type: string
       description: "Holding Pattern"
      partyType:
       type: string
       description: "Party Type"
      placeOfIncorporation:
       type: string
       description: "Place Of Incorporation"
      onboardingRefNumber:
        description: Onboarding Ref Number
        type: string
      onboardingStatus:
        description: onboardingStatus
        type: string
      externalCustomer:
        description: externalCustomer
        type: string
      existingParty:
        description: Existing Party
        type: string
        maxLength: 1
      updatePartyMaintenance:
        description: Update Party Maintenance
        type: string
        maxLength: 1
      languageCode:
        type: string
        description: "Language Code"
      reportLocale:
        type: string
        description: "Report Locale"
      address:
       $ref: '#/definitions/AddressModel'
      partyContact:
        type: array
        items:
          $ref: '#/definitions/PartyContactModel'
      partyRole:
        type: array
        items:
          $ref: '#/definitions/PartyRoleModel'
  PartyContactModel:
    description: PartyContact model
    type: object
    properties:
      id:
        description: Id of the PartyContact
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      maintenanceContactId:
        description: maintenanceContactId
        type: string
      salutation:
       type: string
       description: "Salutation"
      firstName:
        type: string
        description: "First Name"
      lastName:
        type: string
        description: "Last Name"
      designation:
        description: designation
        type: string
      partyId:
        type: string
        description: "Party Id"
      partyContactMedia:
        type: array
        items:
          $ref: '#/definitions/PartyContactMediaModel'
      partyContactRole:
        type: array
        items:
          $ref: '#/definitions/PartyContactRoleModel'
  PartyRoleModel:
    description: PartyRole model
    type: object
    properties:
      id:
        description: Id of the PartyRole
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      role:
        description: role
        type: string
  PartyContactMediaModel:
    description: PartyContactMedia model
    type: object
    properties:
      id:
        description: Id of the PartyContactMedia
        type: string
      maintenanceContactMediaId:
        description: maintenanceContactMediaId
        type: string
      mediaAddress:
        description: mediaAddress
        type: string
      mediaType:
        description: mediaType
        type: string
      partyContactId:
        description: partyContactId
        type: string
      preferredFlag:
        description: preferredFlag
        type: string
      address:
        $ref: '#/definitions/AddressModel'
  AddressModel:
    description: Address model
    type: object
    properties:
      id:
        description: Id of the PartyContactRole
        type: string
      parentId:
        description: parent Id
        type: string
      maintenanceAddressId:
        description: maintenanceAddressId
        type: string
      addressType:
        description: addressType
        type: string
      area:
        description: area
        type: string
      building:
        description: building
        type: string
      city:
        description: city
        type: string
      country:
        description: country
        type: string
      landmark:
        description: landmark
        type: string
      locality:
        description: locality
        type: string
      state:
        description: state
        type: string
      street:
        description: street
        type: string
      zipcode:
        description: zipcode
        type: string
  PartyContactRoleModel:
    description: PartyContactRole model
    type: object
    properties:
      id:
        description: Id of the PartyContactRole
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      role:
        description: role
        type: string
      partyContactId:
        description: partyContactId
        type: string
  PartyCollection:
    description: Collection of Party.
    type: object
    properties:
      PartyList:
        type: array
        items:
          $ref: '#/definitions/PartyModel'
