#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : mandatedocumentreview.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/mandatedocumentreview:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDocumentReview
      summary: Adds a new MandateDocumentReview.
      description: Adds a new MandateDocumentReview. Add additional information here for this endpoint.
      operationId: addMandateDocumentReview
      parameters:
      - name: MandateDocumentReview
        in: body
        description: Request Body that contains data required for creating a new MandateDocumentReview
        required: true
        schema:
          $ref: '#/definitions/MandateDocumentReviewModel'
      responses:
        201:
          description: Returns the Id of the newly created MandateDocumentReview
          headers:
            Location:
              description: URL of newly created MandateDocumentReview
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDocumentReview
      summary: Retrieves the list of existing MandateDocumentReview.
      description: Retrieves the list of existing MandateDocumentReview. Add additional information here for the this endpoint.
      operationId: getAllMandateDocumentReview
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/mandatedocumentreview/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDocumentReview
      summary: Retrieves the MandateDocumentReview by id.
      description: Retrieves the MandateDocumentReview by id. Add additional information here for the this endpoint.
      operationId: getMandateDocumentReviewById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the MandateDocumentReview based on given applicationNumber.
          schema:
            $ref: '#/definitions/MandateDocumentReviewModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDocumentReview
      summary: Update an existing MandateDocumentReview.
      description: Update an existing MandateDocumentReview. Add additional information here for the this endpoint.
      operationId: updateMandateDocumentReview
      parameters:
      - name: id
        in: path
        description: id of the MandateDocumentReview that need to be updated
        required: true
        type: string
      - name: MandateDocumentReview
        in: body
        description: Request Body that contains data required for updating an existing MandateDocumentReview
        required: true
        schema:
          $ref: '#/definitions/MandateDocumentReviewModel'
      responses:
        200:
          description: Returns updated MandateDocumentReview
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDocumentReview
      summary: Deletes the MandateDocumentReview identified by given ID.
      description: Deletes the MandateDocumentReview identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteMandateDocumentReview
      parameters:
      - name: id
        in: path
        description: Id of the MandateDocumentReview that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  MandateDocumentReviewModel:
    description: MandateDocumentReview model
    type: object
    properties:
      id:
        description: Id of the MandateDocumentReview
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      mandateDocument:
        type: array
        items:
          $ref: '#/definitions/MandateDocumentModel'
  MandateDocumentModel:
    description: MandateDocument model
    type: object
    required:
    - documentId
    - documentName
    - documentType
    - documentVersion
    - documentLinkageId
    properties:
      id:
        description: Id of the MandateDocument
        type: string
      mandateDocumentReviewId:
        description: mandateDocumentReviewId
        type: string
      documentId:
        description: Document ID
        type: string
        maxLength: 36
      documentName:
        description: Document Name
        type: string
        maxLength: 105
      documentType:
        description: Document Type
        type: string
        maxLength: 36
      documentVersion:
        description: Document Version
        type: number
      documentLinkageId:
        description: Document Linkage ID
        type: string
      mandateDocumentParty:
        type: array
        items:
          $ref: '#/definitions/MandateDocumentPartyModel'
  MandateDocumentPartyModel:
    description: MandateDocumentParty model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the MandateDocumentParty
        type: string
      mandateDocId:
        description: mandateDocId
        type: string
      entityType:
        description: Entity Type
        type: string
        maxLength: 20
      partyNumber:
        description: Entity Type
        type: string
        maxLength: 20
      entityName:
        description: Entity Name
        type: string
        maxLength: 36
      responseStatus:
        description: RESPONSE_STATUS
        type: string
        maxLength: 20
      response:
        description: Response
        type: string
        maxLength: 20
      mandateDocumentPartyRole:
        type: array
        items:
          $ref: '#/definitions/MandateDocumentPartyRoleModel'
      mandateDocumentResponseDocument:
        type: array
        items:
          $ref: '#/definitions/MandateDocumentResponseDocumentModel'
  MandateDocumentPartyRoleModel:
    description: MandateDocumentPartyRole model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the MandateDocumentPartyRole
        type: string
      mandateDocPartyId:
        description: mandateDocPartyId
        type: string
      roleName:
        description: Role Name
        type: string
        maxLength: 35
  MandateDocumentResponseDocumentModel:
    description: MandateDocumentResponseDocument model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the MandateDocumentResponseDocument
        type: string
      mandateDocPartyId:
        description: mandateDocPartyId
        type: string
      documentLinkageId:
        description: documentLinkageId
        type: string
        maxLength: 50
      documentName:
        description: documentName
        type: string
        maxLength: 90
      documentType:
        description: documentType
        type: string
        maxLength: 35
  MandateDocumentReviewCollection:
    description: Collection of MandateDocumentReview.
    type: object
    properties:
      MandateDocumentReviewList:
        type: array
        items:
          $ref: '#/definitions/MandateDocumentReviewModel'
