swagger: "2.0"
info:
  description: "This is a sample server Risk Evaluation server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "Collateral Projection Service"
host: "whf00anh:7761"
basePath: "/risk-services"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "RiskEvaluationAPI"
    description: "API for Risk Evaluation Operations"
    
schemes:
- "https"

paths:      
  /web/v1/collateral/projection/rm/{rmId}:
    get:
      tags:
        - "CollateralProjectionWeb"
      summary: "Retrieves the Collateral Projections by RM Id."
      description:  "Retrieves the Collateral Projections by RM Id."
      operationId: "getCollateralProjectionByRmId"
      parameters:
        - name: "rmId"
          in: "path"
          description: "Entity Reference Number for which data needs to be fetched"
          required: true
          type: "string"
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true 
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false   
        - name: "contentType"
          in: "header"
          type: "string"
          required: false 
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false   
      responses:
        200:
          description: "Returns the Collateral Projection based on given RM id."
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
  /web/v1/collateral/projection/customer/{customerId}:          
    get:
      tags:
        - "CollateralProjectionWeb"
      summary: "Retrieves the Collateral Projections by Customer Id."
      description:  "Retrieves the Collateral Projections by Customer Id."
      operationId: "getCollateralProjectionByCustId"
      parameters:
        - name: "customerId"
          in: "path"
          description: "Entity Reference Number for which data needs to be fetched"
          required: true
          type: "string"
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true 
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false   
        - name: "contentType"
          in: "header"
          type: "string"
          required: false 
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false        
      responses:
        200:
          description: "Returns the Collateral Projection based on given Customer id"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"          
definitions:
  CustomerDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"    
      customerName:
        type: "string"      
      customerId:
        type: "string"      
      regNo:
        type: "string"      
      legalStatus:
        type: "string"      
      sicCode:
        type: "string"      
      dateOfIncorporation:
         type: "string"
         format: "date-time"      
      customerSince:
         type: "string"
         format: "date-time"       
      customerExposurePolicy:
        type: "string"      
      sanctionedLimit:
         type: "number"      
      availableLimit:
         type: "number"      
      utilizedLimit:
         type: "number"      
      earmarkLimits:
         type: "number"      
      collateralUtilization:
         type: "number"      
      earmarkCollateral:
         type: "number"      
      wipCount:
         type: "number"      
      collateralCurrency:
         type: "string"      
      completedCount:
         type: "number"      
      totalLtvPercent:
         type: "number"      
      movableCollateralPercent:
         type: "number"      
      immovableCollateralPercent:
         type: "number"      
      guidelineType:
         type: "string"      
      guidelineSubType:
         type: "string"      
      region:
         type: "string"
      rmId:
         type: "string"
      bankId:
         type: "string"  
  RMDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"        
      sanctionedLimit:
         type: "number"      
      availableLimit:
         type: "number"      
      utilizedLimit:
         type: "number"      
      earmarkLimits:
         type: "number"      
      collateralUtilization:
         type: "number"      
      earmarkCollateral:
         type: "number"      
      wipCount:
         type: "number"      
      collateralCurrency:
         type: "string"      
      completedCount:
         type: "number"      
      totalLtvPercent:
         type: "number"      
      movableCollateralPercent:
         type: "number"      
      immovableCollateralPercent:
         type: "number"  
      guidelineType:
         type: "string"      
      guidelineSubType:
         type: "string"      
      region:
         type: "string"             
      rmId:
         type: "string"
      bankId:
         type: "string"           
  LtvFacilityDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"
      parentId:
        type: "string"    
      facilityId:
         type: "string"      
      facilityType:
         type: "string"     
      sanctionedLimit:
         type: "number"     
      mappedCollateralValue:
         type: "number"       
      LTV:
         type: "number"          
  LtvDetailsModel:
    type: "object"
    properties:
      id:
        type: "string" 
      customerId:
        type: "string"     
      productType:
         type: "string"      
      amountSanctioned:
         type: "number"     
      linkedCollateralValue:
         type: "number"     
      headroomAvailable:
         type: "number"      
      reqLtv:
         type: "number"      
      effectiveValue:
         type: "number"      
      LTV:
         type: "number"
      ltvFacilityDetailsList:
        type: "array"
        items:
          $ref: "#/definitions/LtvFacilityDetailsModel" 
      rmId:
         type: "string"
      bankId:
         type: "string"                    
  CollateralDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"
      customerId:
        type: "string"     
      collateralId:
         type: "string"      
      collateralType:
         type: "string"      
      loanValue:
         type: "number"      
      chargeHierarchy:
         type: "string"      
      effectiveValue:
         type: "number"      
      agencyName:
         type: "string"      
      marketValue:
         type: "number"      
      bankHaircut:
         type: "number"      
      nextValnDt:
         type: "string"  
         format: "date-time"             
      collateralValue:
         type: "number"      
      valuationDate:
         type: "string" 
         format: "date-time"              
      nrDate:
         type: "string"     
         format: "date-time"          
      typeOfTransaction:
         type: "string"      
      transactionInitiatedDate:
         type: "string"     
         format: "date-time"          
      transactionStatus:
         type: "string"      
      collUtlization:
         type: "number" 
      rmId:
         type: "string"
      bankId:
         type: "string"            
  CovenantDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"   
      customerId:
        type: "string" 
      typeOfCovenant:
         type: "string"      
      covenantName:
         type: "string"
      status:
         type: "string"      
      branchDate:
         type: "string"     
         format: "date-time" 
      rmId:
         type: "string"
      bankId:
         type: "string"             
  AssociatesDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"    
      solicitorName:
         type: "string"      
      contactPerson:
         type: "string"
      contactNumber:
         type: "string"
      collUtlization:
         type: "number"              
      email:
         type: "string"
      rmId:
         type: "string"
      region:
         type: "string"
      type:
         type: "string"                  
      bankId:
         type: "string" 
  ValuationHistoryModel:
    type: "object"
    properties:
      id:
        type: "string"    
      collateralId:
         type: "string"      
      collateralType:
         type: "string"
      valauationDate:
         type: "string"
         format: "date-time" 
      collateralValue:
         type: "number"                 
  GuidelinesDetailsModel:
    type: "object"
    properties:
      id:
        type: "string"    
      policyId:
         type: "string"      
      policyName:
         type: "string"
      deviationAllowed:
         type: "string"              
      effectiveDate:
         type: "string" 
         format: "date-time" 
      deviationApproval:
         type: "string"
      guidelineType:
         type: "string"
      covenantName:
         type: "string"
      covenantType:
         type: "string"                  
      subType:
         type: "string"
      covenantTarget:
         type: "string"
      covenantFrequency:
         type: "string"                  
      rmId:
         type: "string"
      bankId:
         type: "string"           
  RMModel:
    type: "object"
    properties:
      CustomerDetails:
        $ref: '#/definitions/RMDetailsModel'   
      ltvList:
        type: "array" 
        items:
          $ref: "#/definitions/LtvDetailsModel"       
      collateralList:
        type: "array" 
        items:
          $ref: "#/definitions/CollateralDetailsModel"  
      covenantList:
        type: "array" 
        items:
          $ref: "#/definitions/CovenantDetailsModel"             
      associatesList:
        type: "array" 
        items:
          $ref: "#/definitions/AssociatesDetailsModel"
      collateralValuationList:
        type: "array" 
        items:
          $ref: "#/definitions/ValuationHistoryModel"
      guideLinesList:
        type: "array" 
        items:
          $ref: "#/definitions/GuidelinesDetailsModel" 
  CustomerModel:
    type: "object"
    properties:
      CustomerDetails:
        $ref: '#/definitions/CustomerDetailsModel'   
      ltvList:
        type: "array" 
        items:
          $ref: "#/definitions/LtvDetailsModel"       
      collateralList:
        type: "array" 
        items:
          $ref: "#/definitions/CollateralDetailsModel"  
      collateralValuationList:
        type: "array" 
        items:
          $ref: "#/definitions/ValuationHistoryModel"          
      covenantList:
        type: "array" 
        items:
          $ref: "#/definitions/CovenantDetailsModel"                                                                                     