# ----------------------------- OFSS-COPYRIGHT-BEGIN -----------------------------
#
# This source is part of the Oracle Banking Virtual Account Management Software Product.
# Copyright  2018 , 2021 , Oracle and/or its affiliates.  All rights reserved.
# 
# No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
# 
# Oracle Financial Services Software Limited.
# Oracle Park, Off Western Express Highway,
# Goregaon (East),
# Mumbai - 400 063, India.
# 
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------  
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : BankParametersService.yaml
#  **
#  ** Module     : obvam
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  Update the API document with latest changes and incorporated the document review comments
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This services is used to maintain entity mask and bank code for bank in OBVAM, any UI application can be invoked to validate and persist the data." 
 version: "1.0.0"
 title: "entitybankparameters Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "entitybankparametersservice"
   description: "This services is used to maintain entity mask and bank code for bank in OBVAM, any UI application can be invoked to validate and persist the data."

schemes:
- "https"

paths:
# path to fetch all valid records or by intent
#
#  supprorted http methods GET
#
# path example ../service/entitybankparameters
 /service/entitybankparameters:
  get:
   tags:
    - "entitybankparametersservice"
   summary: "Get all valid entitybankparameters."
   description:  "This endpoint adds a new entitybankparameters."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: makerId
     required: false
     type: string
   - in: query
     name: checkerId
     required: false
     type: string
   - in: query
     name: bankCode
     required: false
     type: string
   - in: query
     name: virtualEntityMask
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   - in: query
     name: authStat
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/EntityBankParametersServiceCollection"
    400:
     description: "Bad request error, the server is unable to process the request."
    401:
     description: "Unauthorized request error, invalid credentials."
    403:
     description: "Request denied, no permission to access the request. "
    405:
     description: "Request denied, invalid input."
    500:
     description: "Internal server error."

definitions:
 EntityBankParametersServiceDTO:
  type: object
  allOf:
  - type: object
    properties:
     bankCode:
      type: string
      description: "Bank code in which virtual account is created"
      minLength: 3
      maxLength: 4
      pattern: ^[a-zA-Z0-9]+$
     virtualEntityMask:
      type: string
      description: "Mask for virtual Entity identification number"
      minLength: 1
      maxLength: 12
      pattern: ^[an]+$
     makerId:
      type: string
      description: "Maker ID of Virtual Account"
     makerDateStamp:
      type: string
      description: "Date and Time when Virtual Account is created or modified or closed or reopened"
     checkerId:
      type: string
      description: "Checker ID of Virtual Account"
     checkerDateStamp:
      type: string
      description: "Date and Time when some action on Virtual Account is authorized"
     modNo:
      type: integer
      description: "Version number of Virtual Account"
     recordStatus: 
      type: string
      description: "Record Status of Virtual Account"
     authStatus:
      type: string
      description: "Authorization Status of Virtual Account"
     onceAuth:
      type: string
      description: "Flag that indicated if Virtual Account is authorized once or not"
     doerRemarks:
      type: string
      description: "Remarks made by Maker"
     approverRemarks:
      type: string 
      description: "Remarks made by Approver"
    required:
     - bankCode
     - virtualEntityMask
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 EntityBankParametersServiceCollection: 
  description: "Collection of bankparameters."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/EntityBankParametersServiceDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 EntityBankParametersServiceWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/EntityBankParametersServiceDTO"
