#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : liability.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/facilityLinkages:
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityLinkages
      summary: Updates FacilityLinkage.
      description: Update a FacilityLinkage
      operationId: updateFacilityLinkage
      parameters:
      - name: FacilityLinkage
        in: body
        description: Request Body that contains data required for updating a FacilityLinkage
        required: true
        schema:
          $ref: '#/definitions/FacilityLinkageModel'
      responses:
        200:
          description: Returns updated FacilityLinkage
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/liabilities:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Liabilities
      summary: Adds a new Liability.
      description: Adds a new Liability. Add additional information here for this endpoint.
      operationId: addLiability
      parameters:
      - name: Liability
        in: body
        description: Request Body that contains data required for creating a new Liability
        required: true
        schema:
          $ref: '#/definitions/LiabilityModel'
      responses:
        201:
          description: Returns the Id of the newly created Liability
          headers:
            Location:
              description: URL of newly created Liability
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Liabilities
      summary: Retrieves the list of  Liability.
      description: Retrieves the list of  Liability. Add additional information here for the this endpoint.
      operationId: getAllLiability
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/liabilities/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Liabilities
      summary: Get a  Liability.
      description: Get a  Liability by given id. Add additional information here for the this endpoint.
      operationId: getLiabilityById
      parameters:
      - name: id
        in: path
        description: id of the Liability that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated Liability
          schema:
            $ref: '#/definitions/LiabilityModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Liabilities
      summary: Update an  Liability.
      description: Update an  Liability. Add additional information here for the this endpoint.
      operationId: updateLiability
      parameters:
      - name: id
        in: path
        description: id of the Liability that need to be updated
        required: true
        type: string
      - name: Liability
        in: body
        description: Request Body that contains data required for updating an  Liability
        required: true
        schema:
          $ref: '#/definitions/LiabilityModel'
      responses:
        200:
          description: Returns updated Liability
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - Liabilities
      summary: Deletes the A Liability identified by given ID.
      description: Deletes the Liability identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLiability
      parameters:
      - name: id
        in: path
        description: Id of the Liability that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LiabilityModel:
   description: Liability model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      extLiabilityId:
        description: extLiabilityId of the Liability
        type: string
        maxLength: 36
      customerType:
        description: CustomerType  of the Liability
        type: string
      facilitiesCreate: 
          $ref: '#/definitions/FacilityCreateModel'
      facilitiesLinkage:
        type: array
        items:
          $ref: '#/definitions/FacilityLinkageModel'
      liabilityDocument:
        description: liabilityDocument of the AutomotiveInfoDetails
        type: array
        items:
          $ref: '#/definitions/LiabilityDocumentModel'
  LiabilityCollection:
    description: Collection of Liability.
    type: object
    properties:
      LiabilityList:
        type: array
        items:
          $ref: '#/definitions/LiabilityModel'
  FacilityLinkageModel:
    description: Facility model
    type: object
    properties:
      id:
        description: Id of the Facility
        type: string
        maxLength: 36
      liabilityId:
        description: liabilityId of the Facility
        type: string
        maxLength: 36
      extFacilityId:
        description: extFacilityId of the Facility
        type: string
        maxLength: 36
      facilityType:
        description: Facility Type of the Facility
        type: string
      facilityDescription:
        description: Facility Description of the Facility
        type: string
      facilityCategoryCode:
        description: facilityCategoryCode of the Facility
        type: string
        minLength: 0
        maxLength: 20
      facilityCategoryId:
        description: facilityCategoryId of the Facility
        type: string
        maxLength: 36
      facilityCurrencyCode:
        description: facilityCurrencyCode of the Facility
        type: string
        maxLength: 3
      startDate:
        description: startDate of the Facility
        type: string
      expiryDate:
        description: expiryDate of the Facility
        type: string
      lineCurrencyCode:
        description: lineCurrencyCode of the Facility
        type: string
        minLength: 0
        maxLength: 3
      limitAmount:
        description: limitAmount of the Facility
        type: number
        minimum: 0
      availableAmount:
        description: availableAmount of the Facility
        type: number
        minimum: 0
      utilizedAmount:
        description: utilizedAmount of the Facility
        type: number
        minimum: 0
      facilityBranchCode:
        description: facilityBranch of the Facility
        type: string
        maxLength: 3
      linkagePercent:
        description: linkagePercent
        type: integer
        format: int64
        minimum: 0
        maximum: 100
      utilizationOrder:
        description: utilizationOrder
        type: integer
        format: int64
      collateralsLinkage:
        type: array
        items:
          $ref: '#/definitions/CollateralLinkageModel'
      blockReferenceNumber:
        description: Block Reference Number
        type: string
      blockUnblockStatus:
        description: Block Unblock Status
        type: string
      extLiabilityId:
        description: Ext Liability Id
        type: string
      extLiabilityNumber:
        description: Ext Liability Number
        type: string
      lineCode:
        description: Line code
        type: string
      lineSerial:
        description: Line Serial
        type: string
  FacilityLinkageCollection:
    description: Collection of Facility.
    type: object
    properties:
      FacilityList:
        type: array
        items:
          $ref: '#/definitions/FacilityLinkageModel'
  FacilityCreateModel:
    description: Facility model
    type: object
    properties:
      id:
        description: Id of the Facility
        type: string
        maxLength: 36
      liabilityId:
        description: liabilityId of the Facility
        type: string
        maxLength: 36
      facilityCreationRequired:
        description: facilityCreationRequired of the Facility
        type: boolean
        default: false
      purposeOfFacility:
        description: purposeOfFacility of the Facility
        type: string
      balanceSheetSize:
        description: balanceSheetSize of the Facility
        type: number
        minimum: 0
      operationProfit:
        description: balanceSheetSize of the Facility
        type: number
        minimum: 0
      netProfit:
        description: balanceSheetSize of the Facility
        type: number
        minimum: 0
      currencyCode:
        description: currencyCode
        type: string
        maxLength: 3
      year:
        description: year
        type: integer
        format: int64
      camsProcessInitiated:
        description: camsProcessInitiated
        type: string
      facilityAmount:
        description: year
        type: integer
        format: int64
      facilityCurrencyCode:
        description: facilityCurrencyCode of the Facility
        type: string
        maxLength: 3
  FacilityCreateCollection:
    description: Collection of FacilityCreateModel.
    type: object
    properties:
      FacilityList:
        type: array
        items:
          $ref: '#/definitions/FacilityCreateModel'
  LiabilityDocumentModel:
    description: LiabilityDocument model
    type: object
    properties:
      id:
        description: Id
        type: string
        maxLength: 36
      liabilityId:
        description: liabilityId
        type: string
        maxLength: 36
      documentLinkageId:
        description: documentLinkageId
        type: string
        maxLength: 36
      documentName:
        description: documentName
        type: string
        maxLength: 105
      documentType:
        description: documentType
        type: string
        maxLength: 50
  LiabilityDocumentCollection:
    description: Collection of LiabilityDocumentModel.
    type: object
    properties:
      FacilityList:
        type: array
        items:
          $ref: '#/definitions/LiabilityDocumentModel'
  CollateralLinkageModel:
    description: Collateral model
    type: object
    properties:
      id:
        description: Id of the Collateral
        type: string
        maxLength: 36
      facilityLinkageId:
        description: facilityLinkageId of the Collateral
        type: string
        maxLength: 36
      collateralId:
        description: collateralId of the Collateral
        type: string
        maxLength: 36
      collateralDescription:
        description: collateralDescription of the Collateral
        type: string
        minLength: 0
        maxLength: 105
      collateralType:
        description: collateralType of the Collateral
        type: string
        minLength: 0
        maxLength: 20
      collateralCurrencyCode:
        description: collateralCurrencyCode of the Collateral
        type: string
        minLength: 0
        maxLength: 3
      availableFrom:
        description: availableFrom of the Collateral
        type: string
      purposeOfCollateral:
        description: purposeOfCollateral of the Collateral
        type: string
        minLength: 0
        maxLength: 300
      collateralAmount:
        description: collateralAmount of the Collateral
        type: number
        minimum: 0
      availableAmount:
        description: availableAmount of the Collateral
        type: number
        minimum: 0
      utilizedAmount:
        description: utilizedAmount of the Collateral
        type: number
        minimum: 0
      linkagePercent:
        description: linkagePercent
        type: integer
        format: int64
        minimum: 0
        maximum: 100
      utilizationOrder:
        description: utilizationOrder
        type: integer
        format: int64
  CollateralLinkageCollection:
    description: Collection of Collateral.
    type: object
    properties:
      CollateralList:
        type: array
        items:
          $ref: '#/definitions/CollateralLinkageModel'
  CollateralCreateModel:
    description: Collateral model
    type: object
    properties:
      id:
        description: Id of the Collateral
        type: string
        maxLength: 36
      facilityCreateId:
        description: facilityCreateId of the Collateral
        type: string
        maxLength: 36
      collateralDescription:
        description: collateralDescription of the Collateral
        type: string
        minLength: 0
        maxLength: 105
      collateralType:
        description: collateralType of the Collateral
        type: string
        maxLength: 20
      collateralCurrencyCode:
        description: collateralCurrencyCode of the Collateral
        type: string
        maxLength: 3
      collateralCategory:
        description: Collateral Category of the Collateral
        type: string
      availableFrom:
        description: availableFrom of the Collateral
        type: string
      purposeOfCollateral:
        description: purposeOfCollateral of the Collateral
        type: string
        maxLength: 300
      ownerEstimatedValue:
        description: ownerEstimatedValue of the Collateral
        type: number
  CollateralCreateCollection:
    description: Collection of Collateral.
    type: object
    properties:
      CollateralList:
        type: array
        items:
          $ref: '#/definitions/CollateralCreateModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type  