#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cam.policylibrary
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server sectorexperts server." 
 version: "1.0.0"
 title: "sectorexperts Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "sectorexperts"
   description: "A micro service that will maintain sector experts details in a separate table. This service will also provide APIs for GET, PUT, DELETE, GET by id, Authorize the given record, Reopen and Close APIs for the maintenance records."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../sectorexperts

 /sectorexperts:
  post:
   tags:
    - "sectorexperts"
   summary: "Adds a new sectorexperts."
   description: "Adds a new sectorexperts. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "sectorexperts" 
      in: "body" 
      description: "Request Body that contains data required for creating a new sectorexperts" 
      required: true
      schema:
       $ref: "#/definitions/CfpmTmPolicySectorExpertsDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for creating a new sectorexperts" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created sectorexperts" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "sectorexperts"
   summary: "Get all valid sectorexperts."
   description:  "Get all valid sectorexperts. This endpoints will be used to Get all valid sectorexperts maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: industryCode
     required: false
     type: string
   - in: query
     name: industryGrpCode
     required: false
     type: string
   - in: query
     name: sectorCode
     required: false
     type: string
   - in: query
     name: subIndustryCode
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CfpmTmPolicySectorExpertsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../sectorexperts/xxx
#   DELETE    .../sectorexperts/xxx
#   GET       .../sectorexperts/xxx
#   GET       .../sectorexperts/xxx?version=latestrecord
#   GET       .../sectorexperts/xxx?version=1

 /sectorexperts/{id}:
  put:
   tags:
    - "sectorexperts"
   summary: "Update an existing sectorexperts."
   description:  "Update an existing sectorexperts."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the sectorexperts Maintenance"
      required: true
      type: "string"
    - name: "sectorexperts"
      in: "body"
      description: "Request Body that contains data required for updating an existing sectorexperts"
      required: true
      schema:
       $ref: "#/definitions/CfpmTmPolicySectorExpertsDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for modify an existing record sectorexperts" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    200:
     description: "Returns updated sectorexperts"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "sectorexperts"
   summary: "Retrieves the sectorexperts by ID."
   description:  "Retrieves the sectorexperts by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the sectorexperts based on given id."
     schema:
      $ref: "#/definitions/CfpmTmPolicySectorExpertsWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "sectorexperts"
   summary: "Deletes the sectorexperts identified by given ID."
   description:  "Deletes the sectorexperts identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the sectorexperts maintenance"
      required: true
      type: "string"
    - name: "sectorexperts"
      in: "body"
      description: Request body contain sectorexperts and Modification no of sectorexperts maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../sectorexperts/xxx/approve

 /sectorexperts/{id}/approve:
  patch:
   tags:
    - "sectorexperts"
   summary: "Authorize the sectorexperts by given ID."
   description:  "Authorize the sectorexperts identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the sectorexperts maintenance"
      required: true
      type: "string"
    - name: "sectorexperts"
      in: "body"
      description: Request body contain sectorexperts and Modification no of sectorexperts maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../sectorexperts/xxx/close
 /sectorexperts/{id}/close:
  patch:
   tags:
    - "sectorexperts"
   summary: "Close the sectorexperts by given ID."
   description:  "Close the sectorexperts identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the sectorexperts maintenance"
      required: true
      type: "string"
    - name: "sectorexperts"
      in: "body"
      description: Request body contain sectorexperts and Modification no of sectorexperts maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../sectorexperts/xxx/reopen

 /sectorexperts/{id}/reopen:
  patch:
   tags:
    - "sectorexperts"
   summary: "reopen the sectorexperts by given ID."
   description:  "reopen the sectorexperts identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the sectorexperts maintenance"
      required: true
      type: "string"
    - name: "sectorexperts"
      in: "body"
      description: Request body contain sectorexperts and Modification no of sectorexperts maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../sectorexperts/xxx/unauthorized

 /sectorexperts/{id}/unauthorized:
  get:
   tags:
    - "sectorexperts"
   summary: "Retrives the sectorexperts by given ID."
   description:  "Retrives the sectorexperts identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the sectorexperts based on given id."
     schema:
       $ref: "#/definitions/CfpmTmPolicySectorExpertsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../sectorexperts/xxx/history

 /sectorexperts/{id}/history:
  get:
   tags:
    - "sectorexperts"
   summary: "Retrives the sectorexperts by given ID."
   description:  "Retrives the sectorexperts by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the sectorexperts based on given id."
     schema:
       $ref: "#/definitions/CfpmTmPolicySectorExpertsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CfpmTmPolicySectorExpertsDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     email:
      type: string
      description: "Email of the expert."
     industryCode:
      type: string
      description: "Code of the Industry."
     industryGrpCode:
      type: string
      description: "Code of the industry group."
     mobile:
      type: string
      description: "Mobile number of the expert."
     name:
      type: string
      description: "Name of the expert."
     designation:
      type: string
      description: "Designation of the expert."
     sectorCode:
      type: string
      description: "Code of the sector."
     subIndustryCode:
      type: string
      description: "Code of the sub industry."
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CfpmTmPolicySectorExpertsCollection: 
  description: "Collection of policysectorexperts."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CfpmTmPolicySectorExpertsDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CfpmTmPolicySectorExpertsWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CfpmTmPolicySectorExpertsDTO"
