#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cam.policylibrary
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server termsandconditions server." 
 version: "1.0.0"
 title: "termsandconditions Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "termsandconditions"
   description: "This service provide APIs for save, fetch, modify, authorize, close, reopen policy terms and conditions records. This service provide APIs for save, fetch, modify, authorize, close, reopen policy terms and conditions records. This service provide APIs for save, fetch, modify, authorize, close, reopen policy terms and conditions records. This service provide APIs for save, fetch, modify, authorize, close, reopen policy terms and conditions records."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../termsandconditions

 /termsandconditions:
  post:
   tags:
    - "termsandconditions"
   summary: "Adds a new termsandconditions."
   description: "Adds a new termsandconditions. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "termsandconditions" 
      in: "body" 
      description: "Request Body that contains data required for creating a new termsandconditions" 
      required: true
      schema:
       $ref: "#/definitions/CfpmTmTermsAndConditionsDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for creating a new termsandconditions" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created termsandconditions" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "termsandconditions"
   summary: "Get all valid termsandconditions."
   description:  "Get all valid termsandconditions. This endpoints will be used to Get all valid termsandconditions maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: conditionCode
     required: false
     type: string
   - in: query
     name: industryCode
     required: false
     type: string
   - in: query
     name: industryGrpCode
     required: false
     type: string
   - in: query
     name: sectorCode
     required: false
     type: string
   - in: query
     name: subIndustryCode
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CfpmTmTermsAndConditionsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../termsandconditions/xxx
#   DELETE    .../termsandconditions/xxx
#   GET       .../termsandconditions/xxx
#   GET       .../termsandconditions/xxx?version=latestrecord
#   GET       .../termsandconditions/xxx?version=1

 /termsandconditions/{id}:
  put:
   tags:
    - "termsandconditions"
   summary: "Update an existing termsandconditions."
   description:  "Update an existing termsandconditions."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the termsandconditions Maintenance"
      required: true
      type: "string"
    - name: "termsandconditions"
      in: "body"
      description: "Request Body that contains data required for updating an existing termsandconditions"
      required: true
      schema:
       $ref: "#/definitions/CfpmTmTermsAndConditionsDTO"
#    - name: "bindingResult" 
#      in: "body" 
#      description: "Request Body that contains data required for modify an existing record termsandconditions" 
#      required: false
#      schema:
#       $ref: "#/definitions/BindingResult"
   responses:
    200:
     description: "Returns updated termsandconditions"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "termsandconditions"
   summary: "Retrieves the termsandconditions by ID."
   description:  "Retrieves the termsandconditions by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the termsandconditions based on given id."
     schema:
      $ref: "#/definitions/CfpmTmTermsAndConditionsWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "termsandconditions"
   summary: "Deletes the termsandconditions identified by given ID."
   description:  "Deletes the termsandconditions identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the termsandconditions maintenance"
      required: true
      type: "string"
    - name: "termsandconditions"
      in: "body"
      description: Request body contain termsandconditions and Modification no of termsandconditions maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../termsandconditions/xxx/approve

 /termsandconditions/{id}/approve:
  patch:
   tags:
    - "termsandconditions"
   summary: "Authorize the termsandconditions by given ID."
   description:  "Authorize the termsandconditions identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the termsandconditions maintenance"
      required: true
      type: "string"
    - name: "termsandconditions"
      in: "body"
      description: Request body contain termsandconditions and Modification no of termsandconditions maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../termsandconditions/xxx/close
 /termsandconditions/{id}/close:
  patch:
   tags:
    - "termsandconditions"
   summary: "Close the termsandconditions by given ID."
   description:  "Close the termsandconditions identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the termsandconditions maintenance"
      required: true
      type: "string"
    - name: "termsandconditions"
      in: "body"
      description: Request body contain termsandconditions and Modification no of termsandconditions maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../termsandconditions/xxx/reopen

 /termsandconditions/{id}/reopen:
  patch:
   tags:
    - "termsandconditions"
   summary: "reopen the termsandconditions by given ID."
   description:  "reopen the termsandconditions identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the termsandconditions maintenance"
      required: true
      type: "string"
    - name: "termsandconditions"
      in: "body"
      description: Request body contain termsandconditions and Modification no of termsandconditions maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../termsandconditions/xxx/unauthorized

 /termsandconditions/{id}/unauthorized:
  get:
   tags:
    - "termsandconditions"
   summary: "Retrives the termsandconditions by given ID."
   description:  "Retrives the termsandconditions identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the termsandconditions based on given id."
     schema:
       $ref: "#/definitions/CfpmTmTermsAndConditionsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../termsandconditions/xxx/history

 /termsandconditions/{id}/history:
  get:
   tags:
    - "termsandconditions"
   summary: "Retrives the termsandconditions by given ID."
   description:  "Retrives the termsandconditions by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the termsandconditions based on given id."
     schema:
       $ref: "#/definitions/CfpmTmTermsAndConditionsCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 CfpmTmTermsAndConditionsDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     conditionCode:
      type: string
      description: "Condition code value"
     conditionDescription:
      type: string
      description: "Condition description value"
     industryCode:
      type: string
      description: "Industry code value"
     industryGrpCode:
      type: string
      description: "Inudstry group code value"
     sectorCode:
      type: string
      description: "Sector code vlaue"
     subIndustryCode:
      type: string
      description: ""
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 CfpmTmTermsAndConditionsCollection: 
  description: "Collection of termsandconditions."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CfpmTmTermsAndConditionsDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 CfpmTmTermsAndConditionsWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CfpmTmTermsAndConditionsDTO"
