#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : applicationmaintenance.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Application Maintenance Service
host: 10.184.157.121:9000
basePath: /applicationmaintenance-services
tags:
- name: ApplicationMaintenance
  description: API for application Maintenance
schemes:
- http
paths:
  /web/v1/applicationmaintenance/{type}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationMaintenance
      summary: Get the application maintenance details for a given type
      description: Get the application maintenance details for a given type. Add additional information here for the this endpoint.
      operationId: getApplicationMaintenanceDetails
      parameters:
      - name: type
        in: path
        description: Type for which the maintenance details to be fetched
        required: true
        type: string
      - name: code
        in: query
        description: Code for which the maintenance details to be fetched
        required: false
        type: string
      responses:
        200:
          description: Returns maintenance data for the given type
          schema:
            $ref: '#/definitions/ApplicationMaintenanceModelCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/datasegmentmaintenance/lifecycledatasegmentmapping:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DatasegmentMapping 
      summary: Adds a new Datasegment Mapping.
      description: Adds a new Datasegment Mapping.
      operationId: saveDatasegmentMapping
      parameters:
        - name: "lifecycleCode"
          in: "body"
          description: "Request Body that contains lifecycleCode required for creating a new Datasegment Mapping"
          required: true
          schema:
            $ref: '#/definitions/LifecycleDatasegmentMappingModel'
      responses:
        201:
          description: Returns the Id of the newly  Datasegment Mapping
          headers:
            Location:
              description: URL of newly created  Datasegment Mapping
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/datasegmentmaintenance/lifecycledatasegmentmapping/{lifecycleCode}:
    get:
      tags:
        - DatasegmentMapping
      summary: Datasegment Mapping lifecycleCode
      description: Datasegment Mapping lifecycleCode
      operationId: getByLifecycleCode
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: lifecycleCode
        in: path
        description: lifecycleCode
        required: true
        type: string
      responses:
        200:
          description: "Returns Datasegment Mapping based on lifecycleCode "
          schema:
            $ref: "#/definitions/LifecycleDatasegmentMappingCollection"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"   
  /web/v1/datasegmentmaintenance/datasegmentdependency:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DatasegmentDependency 
      summary: Adds a new Datasegment Dependency.
      description: Adds a new Datasegment Dependency.
      operationId: saveDatasegmentDependency
      parameters:
        - name: "lifecycleCode"
          in: "body"
          description: "Request Body that contains datasegmentCode required for creating a new Datasegment Dependency"
          required: true
          schema:
            $ref: '#/definitions/DatasegmentDependencyModel'
      responses:
        201:
          description: Returns the Id of the newly  Datasegment Dependency
          headers:
            Location:
              description: URL of newly created  Datasegment Dependency
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/datasegmentmaintenance/datasegmentdependency/{datasegmentCode}:
    get:
      tags:
        - DatasegmentDependency
      summary: Datasegment 
      description: Datasegment Mapping lifecycleCode
      operationId: getByDatasegmentCode
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: datasegmentCode
        in: path
        description: datasegmentCode
        required: true
        type: string
      responses:
        200:
          description: "Returns Datasegment deependancy bassed on datasegmentCode "
          schema:
            $ref: "#/definitions/DependencyCollection"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
          
  /web/v1/applicationmaintenance/biccodes:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationMaintenance
      summary: Retrieves the list of BIC Codes
      description: Retrieves the list of BIC Codes. Add additional information here for the this endpoint.
      operationId: getBicCodes
      parameters:
      - name: bicCode
        in: query
        description: BIC Code
        type: string
        required: false
      - name: offset
        in: query
        description: offset is starting no of records to be fetched
        required: false
        type: integer
      - name: limit
        in: query
        description: limit is maximum no of records to be fetched
        required: false
        type: integer
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/BankCodeMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/applicationmaintenance/coreaccount:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationMaintenance
      summary: Retrieves the list of core accounts
      description: Retrieves the list of core accounts. Add additional information here for the this endpoint.
      operationId: getCoreAccounts
      parameters:
      - name: customerNos
        in: query
        description: Customer number to which the account number is being linked
        required: true
        type: array
        items:
         type: string
      - name: custAccountNo
        description: Customer Account Number of selected account
        in: query
        required: false
        type: string
      - name: offset
        in: query
        description: offset is starting no of records to be fetched
        required: false
        type: integer
      - name: limit
        in: query
        description: limit is maximum no of records to be fetched
        required: false
        type: integer
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/CoreAccountCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/applicationmaintenance/documentcodelist:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationMaintenance
      summary: Retrieves the list of document codes
      description: Retrieves the list of document codes.
      operationId: getDocumentCodeList
      parameters:
      - name: offset
        in: query
        description: offset is starting no of records to be fetched
        required: false
        type: integer
      - name: limit
        in: query
        description: limit is maximum no of records to be fetched
        required: false
        type: integer
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/DocumentCodeListModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/applicationmaintenance/documentextract:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationMaintenance
      summary: Extracts Information from the uploaded document.
      description: Extracts Information from the uploaded document.
      operationId: getFieldsFromDocument
      parameters:
      - name: "documentextractmodel"
        in: "body"
        description: "Request Body that contains documentextractmodel required for extracting information from document"
        required: true
        schema:
          $ref: '#/definitions/DocumentExtractModel'
      responses:
        201:
          description: OCR and Api Fields Mapping
          headers:
            Location:
              description: URL of newly created Field Mapping
              type: string
          schema:
            $ref: '#/definitions/ResponseDocumentExtract'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ApplicationMaintenanceModel:
    description: Application Maintenance model
    type: object
    properties:
      code:
        description: Code
        type: string
      description:
        description: Description
        type: string
  LifecycleDatasegmentMappingModel:
    description: Lifecycle Datasegment Mapping Model
    type: object
    properties:
      Id:
        description: Id
        type: string    
      lifecycleCode:
        description: LifecycleCode
        type: string
      datasegmentCodes:
        description: DatasegmentCode
        type: array
        items:
          type: object
          properties:
            datasegmentCode:
              type: string
  DocumentExtractModel:
    description: Document Extract Mapping Model
    type: object
    properties:
      country:
        description: Document Country
        type: string
      docType:
        description: Document Type
        type: string
      docBase64s:
        description: Document Image
        type: array
        items:
          type: string
  DatasegmentDependencyModel:
    description:  Datasegment Dependency Model
    type: object
    properties:
      Id:
        description: Id
        type: string    
      datasegmentDependency:
        description: DatasegmentDependencyCode
        type: array
        items:
          type: object
          properties:
            datasegmentDependencyCode:
              type: string
      datasegmentCode:
        description: DatasegmentCode
        type: string
  DependencyModel:
    description:   Dependency Model
    type: object
    properties:
      datasegmentDependencyCode:
        description: DatesegmentDependencyCode
        type: string                  
  ApplicationMaintenanceModelCollection:
    description: Collection of ApplicationMaintenanceModel.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ApplicationMaintenanceModel'
      paging:
        $ref: '#/definitions/PagingDto'                          
  LifecycleDatasegmentMappingCollection:
    description: Collection of LifecycleDatasegmentMappingModel.
    type: object
    properties:
      data:
          $ref: '#/definitions/LifecycleDatasegmentMappingModel'
      paging:
        $ref: '#/definitions/PagingDto' 
  DatasegmentDependencyCollection:  
    description: Collection of DatasegmentDependencyModel.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/DatasegmentDependencyModel'
      paging:
        $ref: '#/definitions/PagingDto'      
  DependencyCollection:  
    description: Collection of DependencyModel.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/DependencyModel'

  BankCodeMasterModel:
    description: Bank Code Master Model
    type: object
    properties:
      data: 
        type: array
        items:
         $ref: '#/definitions/BankCodeModel' 
  BankCodeModel:
    description: "BankCodeModel Model"
    type: object
    properties:
      bicCode:
        description: Bic Code
        type: string
      bankCode:
        description: Bank Code
        type: string
      bankName:
        description: Bank Name
        type: string
      branchCode:
        description: Branch Code
        type: string
      branchName:
        description: Branch Name
        type: string

  ResponseDocumentExtract:
    description: Document Code List Model
    type: object
    properties:
      data:
        type: object
        items:
          $ref: '#/definitions/ResponseDocumentExtractModel'

  ResponseDocumentExtractModel:
    description: "Individual Details Model"
    type: object
    properties:
      id:
        description: Id of DocumentExtract Model
        type: string
        maxLength: 36
      firstName:
        description: firstName
        type: string
        maxLength: 25
      middleName:
        description: middleName
        type: string
        maxLength: 25
      lastName:
        description: lastName
        type: string
        maxLength: 25
      dateOfBirth:
        description: dateOfBirth
        type: string
      gender:
        description: gender
        type: string
      residentStatus:
        description: Resident/Non-Resident
        type: string
      countryOfResidence:
        description: Country of residence
        type: string
      citizenship:
        description: Country of Citizenship
        type: string
      birthPlace:
        description: place of birth
        type: string
      birthCountry:
        description: Country of birth
        type: string
      maritalStatus:
        description: maritalStatus
        type: string
      nationality:
        description: nationality
        type: string
      customerSegment:
        description: customer segment
        type: string
      uniqueIdType:
        description: uniqueIdType
        type: string
      uniqueIdNo:
        description: uniqueIdNo
        type: string
      uniqueIdExpiryDate:
        description: uniqueId Expiry date
        type: string
      address:
        description: Address
        type: string
      addressType:
        description: Address
        type: string
      building:
        description: Address Building
        type: string
      street:
        description: Address Street
        type: string
      city:
        description: Address City
        type: string
      state:
        description: Address State
        type: string
      country:
        description: Address Country
        type: string
      zipcode:
        description: Address Zipcode
        type: string
      issueDate:
        description: Unique ID Issue date
        type: string

  DocumentCodeListModel:
    description: Document Code List Model
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/DocumentCodeModel'

  DocumentCodeModel:
    description: "Document Code Model"
    type: object
    properties:
      id:
        description: Id of Document Code Model
        type: string
        maxLength: 36
      documentCode:
        description: documentCode
        type: string
        maxLength: 36
      cmcDocumentCode:
        description: cmcDocumentCode
        type: string
        maxLength: 36
      partyDocumentCode:
        description: partyDocumentCode
        type: string
        maxLength: 36
      countryCode:
        description: countryCode
        type: string
        maxLength: 3
      languageCode:
        description: languageCode
        type: string
        maxLength: 3
      defaultCountry:
        description: defaultCountry
        type: string
        maxLength: 1