#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : extCommDetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: External Communication Details
host: 10.184.157.121:9000
basePath: /extCommDetails
tags:
- name: ExtCommDetails
  description: API for External Communication Details
schemes:
- http
paths: 
  /clarificationdetails: 
    get: 
      description: "Service for getting Clariification details for an application number"
      operationId: getClarificationdetailsByProcessRefNo
      summary: "Service for getting BiDirectional details for an application number"
      tags: 
        - extCommDetails
      parameters:
        -
          in: query
          name: processRefNo
          required: false
          type: string
        - 
          in: query
          name: customerId
          required: false
          type: string
        - 
          in: query
          name: id
          required: false
          type: string
        - 
          in: query
          name: status
          required: false
          type: string
      produces: 
        - application/json
        - application/xml
      responses: 
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ClarificationDetailsList"
        400: 
          description: "Malformed syntax."
        401: 
          description: "Request does not have sufficient credentials."
        403: 
          description: "Request is not authorized."
        405: 
          description: "Invalid input"
        500: 
          description: "Internal error"
    put: 
      description: "Service for updating mutliple sub resources of ClarificationDetails Details  ."
      operationId: updateClarificationDetailsFields
      summary: "Service for updating mutliple sub resources of ClarificationDetails Details  ."
      tags: 
        - extCommDetails
      parameters:         
        - 
          in: body
          name: body
          required: true
          schema: 
            $ref: "#/definitions/ClarificationDetailsModel"
      produces: 
        - application/json
        - application/xml
      responses: 
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        500: 
          description: "Internal Server Error"
    post: 
      consumes: 
        - application/json
        - application/xml
      description: "Service for saving ClarificationDetails details."
      operationId: createClarificationDetails
      summary: "Service for saving ClarificationDetails details."
      tags: 
        - extCommDetails
      parameters: 
        - 
          in: body
          name: body
          required: false
          schema: 
            $ref: "#/definitions/ClarificationDetailsModel"
      produces: 
        - application/json
        - application/xml
      responses: 
        201: 
          description: "Returns the Id of the newly created bidding"
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        500: 
          description: "Internal Server Error"
  /clarificationdetails/{id}:
    get: 
      description: "Service for getting ClarificationDetails details for a specific ID."
      operationId: getClarificationDetails
      summary: "Service for getting ClarificationDetails details for a specific ID."
      tags: 
        - extCommDetails  
      parameters: 
        - 
          in: path
          name: id
          required: true
          type: string
        - 
          default: W
          in: query
          name: recordStat
          required: false
          type: string
      produces: 
        - application/json
        - application/xml
      responses: 
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ClarificationDetailsModel"
        400: 
          description: "Malformed syntax."
        401: 
          description: "Request does not have sufficient credentials."
        403: 
          description: "Request is not authorized."
        405: 
          description: "Invalid input"
        500: 
          description: "Internal error" 
  /notifyExtSysAddCustInfo:
    post: 
      description: "Service for initiating notification to External System for new Clarification/converstion."
      operationId: notifyExtSysAddCustInfo
      summary: "Service for initiating notification to External System for new Clarification/converstion."
      tags: 
        - extCommDetails  
      parameters: 
        - 
          in: body
          name: body
          required: false
          schema: 
            $ref: "#/definitions/AdditionalCustInfoMessageModel"
      produces: 
        - application/json
        - application/xml
      responses: 
        201: 
          description: "Returns the Id of the newly created bidding"
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/ResponseDtoWrapper"
        500: 
          description: "Internal Server Error"
  /clarificationProcessStatus:
    get: 
      description: "Service for checking the status of a Process Reference Number"
      operationId: getClarificationProcessStatus
      summary: "Service for checking the status of a Process Reference Number"
      tags: 
        - extCommDetails  
      parameters:
        -
          in: query
          name: applicationNo
          required: true
          type: string
        - 
          in: query
          name: processRefNo
          required: true
          type: string
      produces: 
        - application/json
        - application/xml
      responses: 
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ClarificationProcessStatus"
        400: 
          description: "Malformed syntax."
        401: 
          description: "Request does not have sufficient credentials."
        403: 
          description: "Request is not authorized."
        405: 
          description: "Invalid input"
        500: 
          description: "Internal error" 
definitions:
  ClarificationDetails: 
    properties:
      conversationDetails: 
        description: ConversationDetails
        type: object
        items: 
         $ref: '#/definitions/ClarificationDetailsList'
  ClarificationDetailsList: 
    properties: 
      clarificationDetails: 
        description: clarificationDetails
        type: array
        items: 
         $ref: '#/definitions/ClarificationDetailsModel'
  ClarificationDetailsModel: 
    required:
    - stageCode
    - applicationNumber
    - processRefNo
    - status
    - sequenceNo
    properties: 
      clarificationId:
        type: string
        description: ""
      stageCode:
        type: string
        description: ""
      applicationNumber:
        type: string
        description: ""
      processRefNo:
        type: string
        description: ""
      customerId:
        type: string
        description: ""
      domain:
        type: string
        description: ""
      clarificationDate:
        type: string
        format: date
        description: ""
      clarificationRaisedBy:
        type: string
        description: ""
      clarificationSubject:
        type: string
        description: ""
      status:
        type: string
        description: ""
      remarks:
        type: string
        description: ""
      sequenceNo:
        type: string
        format: number
        description: ""
      conversationDetails: 
        description: ConversationDetails
        type: array
        items: 
         $ref: '#/definitions/ConversationDetailsModel'
  ConversationDetailsModel: 
    required:
    - conversationMessage
    - sequenceNumber
    properties: 
     conversationId:
      type: string
      description: ""
     clarificationId:
      type: string
      description: ""
     conversationMessage:
      type: string
      description: ""
     conversationDate:
      type: string
      format: date
      description: ""
     sequenceNumber:
      type: string
      format: number
      description: ""
     conversationRaisedBy:
      type: string
      description: ""
     systemId:
      type: string
      description: ""
    xml: 
      name: ConversationDetailsModel
  AdditionalCustInfoMessageModel: 
    properties: 
     clarificationId:
      type: string
      description: ""
     conversationList:
      type: array
      items:
       $ref: string
     userId:
      type: string
      description: ""
     branchCode:
      type: string
      description: ""
  ClarificationProcessStatus: 
    properties: 
     processRefNo:
      type: string
      description: ""
     taskStatus:
      type: string