swagger: "2.0"
info:
  description: "Service to issue cheque book."
  version: "1.0.0"
  title: "AccountAddressUpdate"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "AccountAddressUpdate"
    description: ""

schemes:
  - "https"

paths:
 /AccountAddressUpdate/:
  get:
   tags:
   - "AccountAddressUpdate"
   operationId: "AccountAddressUpdate"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"

definitions:
  AccountAddressUpdateDTO:
    type: object
    description: "Customer Address"
    allOf:
      - type: object
        properties:
          id:
            type: string
            description: ""
          txnControllerRefNo:
            type: string
            description: ""
          recordId:
            type: string
            description: ""
          datasegment:
            type: string
            description: ""
          accBrn:
            type: string
            description: ""
          accNo:
            type: string
            description: ""            
          caddr1:
            type: string
            description: ""
          caddr2:
            type: string
            description: ""
          caddr3:
            type: string
            description: ""
          caddr4:
            type: string
            description: ""
          ccountry:
            type: string
            description: ""
          psameAsCor:
            type: string
            description: ""
          paddr1:
            type: string
            description: ""
          paddr2:
            type: string
            description: ""
          paddr3:
            type: string
            description: ""
          paddr4:
            type: string
            description: ""
          pcountry:
            type: string
            description: ""
          rsameAsPer:
            type: string
            description: ""
          raddr1:
            type: string
            description: ""
          raddr2:
            type: string
            description: ""
          raddr3:
            type: string
            description: ""
          raddr4:
            type: string
            description: ""
          rcountry:
            type: string
            description: ""
          createdBy:
            type: string
            description: ""
          createdTs:
            type: string
            format: date
            description: ""
          narrative:
            type: string
            description: ""
          reqDate:
            type: string
            format: date
            description: ""
          status:
            type: string
            description: ""
          txnBrnCode:
            type: string
            description: ""
          txnDate:
            type: string
            format: date
            description: ""
          txnRefNo:
            type: string
            description: ""
          updatedBy:
            type: string
            description: ""
          updatedTs:
            type: string
            format: date
            description: ""
          version:
            type: number
            description: ""
          pCode:
            type: string
            description: ""
          additionalFields:
            type: string
            description: ""
          addDtls:
              $ref: '#/definitions/AdditionalTransactionDetails'
          txnDtls:
              $ref: '#/definitions/TransactionDetails'
          overrideDtls:
            type: array
            items: 
              $ref: "#/definitions/BaseOutcomeModel"