#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : trancherepayment.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/trancherepaymentschedules:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheRepayment
      summary: Adds a new TrancheRepayment.
      description: Adds a new TrancheRepayment. Add additional information here for this endpoint.
      operationId: addTrancheRepayment
      parameters:
      - name: TrancheRepayment
        in: body
        description: Request Body that contains data required for creating a new TrancheRepayment
        required: true
        schema:
          $ref: '#/definitions/TrancheRepaymentModel'
      responses:
        201:
          description: Returns the Id of the newly created TrancheRepayment
          headers:
            Location:
              description: URL of newly created TrancheRepayment
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheRepayment
      summary: Retrieves the list of existing TrancheRepayment.
      description: Retrieves the list of existing TrancheRepayment. Add additional information here for the this endpoint.
      operationId: getAllTrancheRepayment
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/trancherepaymentschedules/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheRepayment
      summary: Retrieves the TrancheRepayment by id.
      description: Retrieves the TrancheRepayment by id. Add additional information here for the this endpoint.
      operationId: getTrancheRepaymentById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the TrancheRepayment based on given applicationNumber.
          schema:
            $ref: '#/definitions/TrancheRepaymentModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheRepayment
      summary: Update an existing TrancheRepayment.
      description: Update an existing TrancheRepayment. Add additional information here for the this endpoint.
      operationId: updateTrancheRepayment
      parameters:
      - name: id
        in: path
        description: id of the TrancheRepayment that need to be updated
        required: true
        type: string
      - name: TrancheRepayment
        in: body
        description: Request Body that contains data required for updating an existing TrancheRepayment
        required: true
        schema:
          $ref: '#/definitions/TrancheRepaymentModel'
      responses:
        200:
          description: Returns updated TrancheRepayment
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheRepayment
      summary: Deletes the TrancheRepayment identified by given ID.
      description: Deletes the TrancheRepayment identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteTrancheRepayment
      parameters:
      - name: id
        in: path
        description: Id of the TrancheRepayment that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  TrancheRepaymentModel:
    description: TrancheRepayment model
    type: object
    properties:
      id:
        description: Id of the TrancheRepayment
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      trancheRepaymentSchedules:
        type: array
        items:
          $ref: '#/definitions/TrancheRepaymentSchedulesModel'
  TrancheRepaymentSchedulesModel:
    description: TrancheRepaymentSchedules model
    type: object
    required:
    - trancheId
    properties:
      id:
        description: Id of the TrancheRepaymentSchedules
        type: string
      trnRpayId:
        description: trnRpayId
        type: string
      trancheId:
        description: Tranche Id of the repayment schedulues
        type: string
        maxLength: 36
      trancheName:
        description: Tranche Name of the repayment schedulues
        type: string
        maxLength: 36
      trancheType:
        description: Tranche Type of the repayment schedulues
        type: string
        maxLength: 36
      trancheEffDate:
        description: Tranche Effective date of the repayment schedulues
        type: string
      trancheEndDate:
        description: Tranche End date of the repayment schedulues
        type: string
      trancheCurrency:
        description: Tranche Currency of the repayment schedulues
        type: string
      trancheRepaymentScheduleDetails:
        type: array
        items:
          $ref: '#/definitions/TrancheRepaymentScheduleDetailsModel'
  TrancheRepaymentScheduleDetailsModel:
    description: TrancheRepaymentScheduleDetails model
    type: object
    properties:
      id:
        description: Id of the TrancheRepaymentScheduleDetails
        type: string
      trnRpaySchId:
        description: trnRpaySchId
        type: string
      scheduleType:
        description: Schedule Type Id of the repayment schedulues
        type: string
        maxLength: 20
      scheduleStartDate:
        description: Schedule start date of the repayment schedulues
        type: string
      noOfSchedules:
        description: number of schedules of the repayment schedulues
        type: number
      scheduleFrequency:
        description: Schedule Frequency of the repayment schedulues
        type: number
      scheduleFrequencyUnit:
        description: Schedule Frequency Unit of the repayment schedulues
        type: string
        maxLength: 20
      scheduleAmount:
        description: Schedule Amount of the repayment schedulues
        type: number
      scheduleCurrency:
        description: Schedule Currency of the repayment schedulues
        type: string
        maxLength: 3
  TrancheRepaymentCollection:
    description: Collection of TrancheRepayment.
    type: object
    properties:
      TrancheRepaymentList:
        type: array
        items:
          $ref: '#/definitions/TrancheRepaymentModel'
