#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : transactiondocumentreview.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/transactiondocumentreview:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TransactionDocumentReview
      summary: Adds a new TransactionDocumentReview.
      description: Adds a new TransactionDocumentReview. Add additional information here for this endpoint.
      operationId: addTransactionDocumentReview
      parameters:
      - name: TransactionDocumentReview
        in: body
        description: Request Body that contains data required for creating a new TransactionDocumentReview
        required: true
        schema:
          $ref: '#/definitions/TransactionDocumentReviewModel'
      responses:
        201:
          description: Returns the Id of the newly created TransactionDocumentReview
          headers:
            Location:
              description: URL of newly created TransactionDocumentReview
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TransactionDocumentReview
      summary: Retrieves the list of existing TransactionDocumentReview.
      description: Retrieves the list of existing TransactionDocumentReview. Add additional information here for the this endpoint.
      operationId: getAllTransactionDocumentReview
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/transactiondocumentreview/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TransactionDocumentReview
      summary: Retrieves the TransactionDocumentReview by id.
      description: Retrieves the TransactionDocumentReview by id. Add additional information here for the this endpoint.
      operationId: getTransactionDocumentReviewById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the TransactionDocumentReview based on given applicationNumber.
          schema:
            $ref: '#/definitions/TransactionDocumentReviewModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TransactionDocumentReview
      summary: Update an existing TransactionDocumentReview.
      description: Update an existing TransactionDocumentReview. Add additional information here for the this endpoint.
      operationId: updateTransactionDocumentReview
      parameters:
      - name: id
        in: path
        description: id of the TransactionDocumentReview that need to be updated
        required: true
        type: string
      - name: TransactionDocumentReview
        in: body
        description: Request Body that contains data required for updating an existing TransactionDocumentReview
        required: true
        schema:
          $ref: '#/definitions/TransactionDocumentReviewModel'
      responses:
        200:
          description: Returns updated TransactionDocumentReview
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - TransactionDocumentReview
      summary: Deletes the TransactionDocumentReview identified by given ID.
      description: Deletes the TransactionDocumentReview identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteTransactionDocumentReview
      parameters:
      - name: id
        in: path
        description: Id of the TransactionDocumentReview that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  TransactionDocumentReviewModel:
    description: TransactionDocumentReview model
    type: object
    properties:
      id:
        description: Id of the TransactionDocumentReview
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      transactionDocument:
        type: array
        items:
          $ref: '#/definitions/TransactionDocumentModel'
  TransactionDocumentModel:
    description: TransactionDocument model
    type: object
    required:
    - documentId
    - documentName
    - documentType
    - documentVersion
    - documentLinkageId
    properties:
      id:
        description: Id of the TransactionDocument
        type: string
      transactionDocumentReviewId:
        description: transactionDocumentReviewId
        type: string
      documentId:
        description: Document ID
        type: string
        maxLength: 36
      documentName:
        description: Document Name
        type: string
        maxLength: 105
      documentType:
        description: Document Type
        type: string
        maxLength: 36
      documentVersion:
        description: Document Version
        type: number
      documentLinkageId:
        description: Document Linkage ID
        type: string
      transactionDocumentParty:
        type: array
        items:
          $ref: '#/definitions/TransactionDocumentPartyModel'
  TransactionDocumentPartyModel:
    description: TransactionDocumentParty model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the TransactionDocumentParty
        type: string
      transactionDocId:
        description: transactionDocId
        type: string
      entityType:
        description: Entity Type
        type: string
        maxLength: 20
      partyId:
        description: Party Id
        type: string
      partyNumber:
        description: Entity Type
        type: string
        maxLength: 20
      entityName:
        description: Entity Name
        type: string
        maxLength: 36
      responseStatus:
        description: RESPONSE_STATUS
        type: string
        maxLength: 20
      response:
        description: Response
        type: string
        maxLength: 20
      transactionDocumentReviewPartyRole:
        type: array
        items:
          $ref: '#/definitions/TransactionDocumentReviewPartyRoleModel'
      transactionDocumentResponseDocument:
        type: array
        items:
          $ref: '#/definitions/TransactionDocumentResponseDocumentModel'
  TransactionDocumentReviewPartyRoleModel:
    description: TransactionDocumentPartyRole model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the TransactionDocumentPartyRole
        type: string
      trnDocPartyId:
        description: trnDocPartyId
        type: string
      roleName:
        description: Role Name
        type: string
        maxLength: 35
  TransactionDocumentResponseDocumentModel:
    description: TransactionDocumentResponseDocument model
    type: object
    required:
    - entityType
    - entityName
    properties:
      id:
        description: Id of the TransactionDocumentResponseDocument
        type: string
      trnDocPartyId:
        description: trnDocPartyId
        type: string
      documentLinkageId:
        description: documentLinkageId
        type: string
        maxLength: 50
      documentName:
        description: documentName
        type: string
        maxLength: 90
      documentType:
        description: documentType
        type: string
        maxLength: 35
  TransactionDocumentReviewCollection:
    description: Collection of TransactionDocumentReview.
    type: object
    properties:
      TransactionDocumentReviewList:
        type: array
        items:
          $ref: '#/definitions/TransactionDocumentReviewModel'
