#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ${enityName}.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: obcmtmcorpenrchpoolstupmstr
host: 10.184.157.121:9000
basePath: /obcmtmcorpenrchpoolstupmstr
tags:
- name: obcmtmcorpenrchpoolstupmstr
  description: API for obcmtmcorpenrchpoolstupmstr Operations
schemes:
- http
paths:
  /web/v1/obcmtmcorpenrchpoolstupmstr:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ObcmTmCorpEnrchPoolStupMstr
      summary: Adds a new ObcmTmCorpEnrchPoolStupMstr.
      description: Adds a new ObcmTmCorpEnrchPoolStupMstr. Add additional information here for this endpoint.
      operationId: addObcmTmCorpEnrchPoolStupMstr
      parameters:
      - name: ObcmTmCorpEnrchPoolStupMstr
        in: body
        description: Request Body that contains data required for creating a new ObcmTmCorpEnrchPoolStupMstr
        required: true
        schema:
          $ref: '#/definitions/ObcmTmCorpEnrchPoolStupMstrDTO'
      responses:
        201:
          description: Returns the Id of the newly created ObcmTmCorpEnrchPoolStupMstr
          headers:
            Location:
              description: URL of newly created ObcmTmCorpEnrchPoolStupMstr
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ObcmTmCorpEnrchPoolStupMstrDTO:
    description: ObcmTmCorpEnrchPoolStupMstr model
    type: object
    allOf:
    - $ref: '#/definitions/BaseGenericModelDS'
    - type: object
      properties:    
       id:
        type: string
        description: "Id"
       action:
        type: string
        description: "Action"
       autoAuth:
        type: string
        description: "Auto Auth"
       modificationStatus:
        type: string
        description: "Modification Status"   
       datasegmentCode:
        type: string
        description: "Datasegment Code"
       checkerRemarks:
        type: string
        description: "checkerRemarks" 
       makerRemarks:
        type: string
        description: "makerRemarks"
       enrichmentId:
        description: enrichmentId
        type: string
       txnControllerRefNo:
        type: string
        description: "Transaction Controller Reference Number"
       obcmTmCorpEnrchPoolStupDtls:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchPoolStupDtlsDTO'
  BaseGenericModelDS:
   allOf:
    - type: object
      discriminator: resource_type

  ObcmTmCorpEnrchPoolStupDtlsDTO:
    description: ObcmTmCorpEnrchPoolStupDtls model
    type: object
    properties:
      id:
        description: Id of the ObcmTmCorpEnrchPoolStupDtls
        type: string
      prodCategory:
        description: prodCategory
        type: string
      poolingLvl:
        description: poolingLvl
        type: string
      cdtConsolidationLvl:
        description: cdtConsolidationLvl
        type: string
      percentagePooling:
        description: percentagePooling
        type: string
      divCode:
        description: divCode
        type: string
      divDesc:
        description: divDesc
        type: string
      locCode:
        description: locCode
        type: string
      locDesc:
        description: locDesc
        type: string
      percentage:
        description: percentage
        type: number
      poolStupMstrId:
        description: poolStupMstrId
        type: string
      pooAccDesc:
        description: pooAccDesc
        type: string
      pooAccNo:
        description: pooAccNo
        type: string
      obcmTmCorpEnrchPoolStupMstr:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchPoolStupMstrDTO'
  ObcmTmCorpEnrchPoolStupMstrCollection:
    description: Collection of ObcmTmCorpEnrchPoolStupMstr.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchPoolStupMstrDTO'
  ObcmTmCorpEnrchPoolStupDetailsDTO:
    type: "object"
    description: "Corporate Enrichment Pool Setup Details Data"
    properties:
       prodCategory:
        type: "string"
        description: "Product Category used for corporate enrichment pool setup details"
       poolingLvl:
        type: "string"
        description: "Pooling level used for corporate enrichment pool setup details"
       cdtConsolidationLvl:
        type: "string"
        description: "Credit Consolidation Level 1 used for corporate enrichment pool setup details"
       percentagePooling:
        type: "string"
        description: "Percentage pooling used for corporate enrichment pool setup details"
       divCode:
        type: "string"
        description: "Division Code used for corporate enrichment pool setup details"
       divDesc:
        type: "string"
        description: "Division description used for corporate enrichment pool setup details"
       locCode:
        type: "string"
        description: "Location code used for corporate enrichment pool setup details"
       locDesc:
        type: "string"
        description: "Location description used for corporate enrichment pool setup details"
       percentage:
        type: "number"
        description: "Percentage used for corporate enrichment pool setup details"
       pooAccDesc:
        type: "string"
        description: "Pooling account description used for corporate enrichment pool setup details"
       pooAccNo:
        type: "string"
        description: "Pooling account number used for corporate enrichment pool setup details"