swagger: "2.0"
info:
  description: "Service to issue cheque book."
  version: "1.0.0"
  title: "Customer Account Statement Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "CustomerAccStatement"
    description: ""

schemes:
  - "https"

paths:
 /VAMService/:
  get:
   tags:
   - "VAMWeb"
   operationId: "cash"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"

definitions:
  VAMCallRequest:
    type: object
    properties:
          sourceCode: 
           type: string
           description: ""
          sourceReferenceNo: 
           type: string
           description: ""
          vatRequestDetServiceDTO:
           type: array
           items:
            $ref: '#/definitions/VAMAccounting'
  VAMAccounting:
    type: object
    properties:
          drCrInd: 
           type: string
           description: ""
          txnAccount: 
           type: string
           description: ""          
          txnAccountBrn: 
           type: string
           description: ""          
          txnCcy: 
           type: string
           description: ""          
          txnAccountCcy:
           type: string
           description: ""
          txnAmount: 
           type: number
           description: ""
          txnCode:
           type: string
           description: ""
          valueDate: 
           type: string
           description: ""
          skipDDAEntries: 
           type: string
           description: ""
          exchRate: 
           type: string
           description: ""
          reconRefNo: 
           type: string
           description: ""
          addlText:
           type: string
           description: ""
          ecaOrBlockRefNo: 
           type: string
           description: ""
          ddaOffset: 
           type: string
           description: ""
          forceDebit:
           type: string
           description: ""
          blkReleaseStatus: 
           type: string
           description: ""
          amtInTxnAccCcy:
            type: number
            description: ""