#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking CorpoparticipationPending Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : exceptionapproval.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/exceptionapproval:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ExceptionApproval
      summary: Adds a new exceptionapproval.
      description: Adds a new exceptionapproval. Add additional information here for this endpoint.
      operationId: addExceptionApproval
      parameters:
      - name: ExceptionApproval
        in: body
        description: Request Body that contains data required for creating a new exceptionapproval
        required: true
        schema:
          $ref: '#/definitions/ExceptionApprovalModel'
      responses:
        201:
          description: Returns the Id of the newly created Charges
          headers:
            Location:
              description: URL of newly created Charges
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ExceptionApproval
      summary: Retrieves the list of existing exceptionapproval.
      description: Retrieves the list of existing exceptionapproval. Add additional information here for the this endpoint.
      operationId: getAllExceptionApproval
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/exceptionapproval/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ExceptionApproval
      summary: Get a  exceptionapproval.
      description: Get a  exceptionapproval by given id. Add additional information here for the this endpoint.
      operationId: getExceptionApprovalById
      parameters:
      - name: id
        in: path
        description: id of the exceptionapproval that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated exceptionapproval
          schema:
            $ref: '#/definitions/ExceptionApprovalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ExceptionApproval
      summary: Update an existing exceptionapproval.
      description: Update an existing exceptionapproval. Add additional information here for the this endpoint.
      operationId: updateExceptionApproval
      parameters:
      - name: id
        in: path
        description: id of the exceptionapproval that need to be updated
        required: true
        type: string
      - name: ExceptionApproval
        in: body
        description: Request Body that contains data required for updating an existing exceptionapproval
        required: true
        schema:
          $ref: '#/definitions/ExceptionApprovalModel'
      responses:
        200:
          description: Returns updated exceptionapproval
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ExceptionApproval
      summary: Deletes the exceptionapproval identified by given ID.
      description: Deletes the exceptionapproval identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteExceptionApproval
      parameters:
      - name: id
        in: path
        description: Id of the exceptionapproval that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ExceptionApprovalModel:
    description: exceptionapproval model
    type: object
    properties:
      id:
        description: Id of the exceptionapproval
        type: string
      applicationNumber:
        description: Application Number of the exceptionapproval
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      exceptionDetails:
        type: array
        items:
          $ref: '#/definitions/ExceptionDetailsModel'  
  ExceptionApprovalCollection:
    description: Collection of exceptionapproval.
    type: object
    properties:
      ExceptionapprovalList:
        type: array
        items:
          $ref: '#/definitions/ExceptionApprovalModel'
  ExceptionDetailsModel:
    description: ExceptionDetails model
    type: object
    properties:
      id:
        description: Id of the ExceptionDetails
        type: string
        maxLength: 36
      exceptionapprovalId:
        description: exceptionapprovalId of the ExceptionDetails
        type: string
        maxLength: 36
      exceptionType:
        description: exceptionType of the ExceptionDetails
        type: string
        maxLength: 20
      exceptionCondition:
        description: exceptionCondition of the ExceptionDetails
        type: string
        maxLength: 20
      signoffRequest:
        description: signoffRequest of the ExceptionDetails
        type: string
        maxLength: 20
      signoffExpected:
        description: signoffExpected of the ExceptionDetails
        type: string
        maxLength: 20
      signoffResponseStatus:
        description: signoffResponseStatus of the ExceptionDetails
        type: string
        maxLength: 20
      signoffResponse:
        description: signoffResponse of the ExceptionDetails
        type: string
        maxLength: 20
  ExceptionDetailsCollection:
    description: Collection of ExceptionDetails.
    type: object
    properties:
      ExceptionDetailsList:
        type: array
        items:
          $ref: '#/definitions/ExceptionDetailsModel'
 