asyncapi: '2.0.0'
id: 'urn:com:oracle:fsgbu:obcm:asyncapi:productsUpdated'
info:
  title: Kafka Application - products updated event
  version: '1.0.0'
  description: Kafka Application - products updated event
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  development:
    url: whf00mip.in.oracle.com:9092
    description: Development server
    protocol: kafka
channels:
  productsUpdated:
    description: products updated topic
    subscribe:
      summary: Get products updated event
      message:
        description: Get updated products list
        $ref: '#/components/messages/UpdateProductsDto'          

components:
  messages:
    UpdateProductsDto:
      name: Update Products Message
      title: Update Products
      summary: Update Products Message
      contentType: application/json
      payload:
        $ref: "#/components/schemas/UpdateProductsDto"
  schemas:
    UpdateProductsDto:
      type: object  
      properties:
        id: 
          type: string
        modNo:
          type: string
        productCode:
          type: string
        productDescription:
          type: string
        productType:
          type: string
        productCategory:
          type: string
        branchCode:
          type: string
        branchDesc:
          type: string
        debtor:
          type: string
        effectiveFrom:
          type: string
        expiresOn:
          type: string
        autoFinanceApplicable:
          type: string
        autoSettlementApplicable:
          type: string
        preferredDisburesementMode:
          type: string
        preferredSettlementMode:
          type: string
        minFinancePercentage:
          type: string
        maxFinancePercentage:
          type: string
        minTenorAllowed:
          type: string
        maxTenorAllowed:
          type: string
        withRecourse:
          type: string
        creditLimitUtilization:
          type: string
        stalePeriod:
          type: string
        minWaitingPeriod:
          type: string
        prePaymentAllowed:
          type: string
        partPaymentAllowed:
          type: string
        maturityDateCalculation:
          type: string
        multipleDisbursementAllowed:
          type: string
        holidayTreatement:
          type: string
        appropriationSeqOnDueDate:
          type: string
        appropriationSeqBefDueDate:
          type: string
        appropriationSeqAftDueDate:
          type: string
        npaAppropriationSeq:
          type : string
        autoDebitApplicable:
          type : string
        debitPartyOnDueDate:
          type : string
        debitPartyAfterDueDate:
          type : string
        debitAcctTypeOnDueDate:
          type : string
        debitAcctTypeAfterDueDate:
          type : string
        reconciliationTowards:
          type : string
        graceDays:
          type : string
        makerId:
          type : string
        makerDtStamp:
          type : string
        checkerId:
          type : string
        checkerDtStamp:
          type : string
        countryCode:
          type : string
        countryName:
          type : string
        marginHandling:
          type : string
        marginPaymentMode:
          type : string
        interestRefundHandling:
          type : string
        interestRefundPaymentMode:
          type : string 