asyncapi: '2.0.0'
id: 'urn:com:oracle:fsgbu:obcm:asyncapi:productsTwUpdated'
info:
  title: Kafka Application - products tw updated event
  version: '1.0.0'
  description: Kafka Application - products tw updated event
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  development:
    url: whf00mip.in.oracle.com:9092
    description: Development server
    protocol: kafka
channels:
  productsTwUpdated:
    description: products tw updated topic
    subscribe:
      summary: Get products tw updated event
      message:
        description: Get updated tw products list
        $ref: '#/components/messages/UpdateProductsTwDto'          

components:
  messages:
    UpdateProductsTwDto:
      name: Update Products Tw Message
      title: Update Products Tw
      summary: Update Products Message
      contentType: application/json
      payload:
        $ref: "#/components/schemas/UpdateProductsTwDto"
  schemas:
    UpdateProdLimitExpHandlTwDto:
      type: object
      properties:
        id: 
          type: string
        productCode: 
          type: string
        limitDecnMasterId: 
          type: string
        subLevelApplicable: 
          type: string
        expiredLimitExceptionHandling: 
          type: string
        breachLimitExceptionHandling: 
          type: string
        expiredAndBreachLimitExceptionHandling: 
          type: string
        modNo: 
          type: string
    UpdateProdLimitDecnTwDto:
      type: object
      properties:
        modNo: 
          type: string
        eventCode: 
          type: string
        id: 
          type: string
        limitType: 
          type: string
        productCode: 
          type: string
        productMasterId: 
          type: string
        recourse: 
          type: string
        rootLimitEntityType: 
          type: string
        subLevelsApplicable: 
          type: string
        limitEvent: 
          type: string
        scfTmProdLimitExpHandlDTO: 
          type: array
          description: "Product Limit Exp Handl Records"
          items:
            $ref: "#/components/schemas/UpdateProdLimitExpHandlTwDto"
    UpdateProductsTwDto:
      type: object  
      properties:
        action:
          type: string
        keyId:
          type: string
        checkerRemarks:
          type: string
        makerRemarks:
          type: string
        appropriationSeqAftDueDate:
          type: string
        appropriationSeqBefDueDate:
          type: string
        appropriationSeqOnDueDate:
          type: string
        authStat:
          type: string
        autoDebitApplicable:
          type: string
        autoFinanceApplicable:
          type: string
        autoSettlementApplicable:
          type: string
        branchCode:
          type: string
        checkerDtStamp:
          type: string
        checkerId:
          type: string
        creditLimitUtilization:
          type: string
        debitAcctTypeAfterDueDate:
          type: string
        debitAcctTypeOnDueDate:
          type: string
        debitPartyAfterDueDate:
          type: string
        debitPartyOnDueDate:
          type: string
        debtor:
          type: string
        effectiveFrom:
          type: string
        expiresOn:
          type: string
        holidayTreatment:
          type: string
        id:
          type: string
        makerDateStamp:
          type: string
        makerId:
          type: string
        maturityDateCalculation:
          type: string
        maxFinancePercentage:
          type: string
        maxTenorAllowed:
          type: string
        minFinancePercentage:
          type: string
        minTenorAllowed:
          type: string
        minWaitingPeriod:
          type: string
        modNo:
          type: string
        multipleDisbursementAllowed:
          type: string
        npaAppropriationSeq:
          type: string
        onceAuth:
          type: string
        partRepaymentAllowed:
          type: string
        preferredDisbursementMode:
          type: string
        preferredSettlementMode:
          type: string
        prePaymentAllowed:
          type: string
        productCategory:
          type: string
        productCode:
          type: string
        productDescription:
          type: string
        productType:
          type: string
        recordStat:
          type: string
        stalePeriod:
          type: string
        withRecourse:
          type: string
        reconciliationTowards:
          type: string
        graceDays:
          type: string
        marginHandling:
         type: string
        marginPaymentMode:
         type: string
        interestRefundHandling:
         type: string
        interestRefundPaymentMode:
         type: string
        isAccountingApplicable:
          type: string
        isCreditLimitApplicable:
          type: string
        isAssignmentApplicable:
          type: string
        isAutoAssignment:
          type: string
        isAcceptanceApplicable:
          type: string
        isAutoAcceptance:
          type: string
        isDisbursementAuthRequired:
          type: string
        isDisbursementAutoProcessing:
          type: string
        isSettlementAuthRequired:
          type: string
        isSettlementAutoProcessing:
          type: string
        autoAcceptanceDays:
          type: string
        holidayTreatmentForFdd:
          type: string
        excessHandling:
          type: string
        excessRefundParty:
          type: string
        excessRefundPaymentMode:
          type: string
        scfTmProdLimitDecnDTO:
          type: array
          description: "Product Limit Decn Records"
          items:
            $ref: "#/components/schemas/UpdateProdLimitDecnTwDto"
        userId:
          type: string             
        serviceBranchCode:
          type: string