#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : covenants.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: syndicationapplication
host: 10.184.157.121:9000
basePath: /syndicationapplication
tags:
- name: Syndicationapplication
  description: API for Syndicationapplication Operations
schemes:
- http
paths:
  /web/v1/covenantsinfo:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CovenantsInfo
      summary: Adds a new CovenantsInfo.
      description: Adds a new CovenantsInfo. Add additional information here for this endpoint.
      operationId: addCovenantsInfo
      parameters:
      - name: CovenantsInfo
        in: body
        description: Request Body that contains data required for creating a new CovenantsInfo
        required: true
        schema:
          $ref: '#/definitions/CovenantsInfoModel'
      responses:
        201:
          description: Returns the Id of the newly created CovenantsInfo
          headers:
            Location:
              description: URL of newly created CovenantsInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CovenantsInfo
      summary: Retrieves the list of existing CovenantsInfo.
      description: Retrieves the list of existing CovenantsInfo. Add additional information here for the this endpoint.
      operationId: getAllCovenantsInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/covenantsinfo/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CovenantsInfo
      summary: Retrieves the CovenantsInfo by id.
      description: Retrieves the CovenantsInfo by id. Add additional information here for the this endpoint.
      operationId: getCovenantsInfoById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CovenantsInfo based on given applicationNumber.
          schema:
            $ref: '#/definitions/CovenantsInfoModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CovenantsInfo
      summary: Update an existing CovenantsInfo.
      description: Update an existing CovenantsInfo. Add additional information here for the this endpoint.
      operationId: updateCovenantsInfo
      parameters:
      - name: id
        in: path
        description: id of the CovenantsInfo that need to be updated
        required: true
        type: string
      - name: CovenantsInfo
        in: body
        description: Request Body that contains data required for updating an existing CovenantsInfo
        required: true
        schema:
          $ref: '#/definitions/CovenantsInfoModel'
      responses:
        200:
          description: Returns updated CovenantsInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - CovenantsInfo
      summary: Deletes the CovenantsInfo identified by given ID.
      description: Deletes the CovenantsInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCovenantsInfo
      parameters:
      - name: id
        in: path
        description: Id of the CovenantsInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  CovenantsInfoModel:
    description: CovenantsInfo model
    type: object
    properties:
      id:
        description: Id of the CovenantsInfo
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks
        type: string
      covenantDetails:
        type: array
        items:
          $ref: '#/definitions/CovenantDetailsModel'
  CovenantDetailsModel:
    description: CovenantDetails model
    type: object
    properties:
      id:
        description: Id of the CovenantDetails
        type: string
      name:
        description: covenantName
        type: string
      covenantInfoId:
        description: covenantInfoId
        type: string
      description:
        description: description
        type: string
      customerName:
        description: customerName
        type: string
      partyId:
        description: partyId
        type: string
      projectName:
        description: projectName
        type: string
      dealPersonalId:
        description: dealPersonalId
        type: string
      frequency:
        description: frequency
        type: string
      dueBy:
        description: dueBy
        type: string
      endBy:
        description: endBy
        type: string
      reminderDays:
        description: reminderDays
        type: number
  CovenantsInfoCollection:
    description: Collection of CovenantsInfo.
    type: object
    properties:
      CovenantsInfoList:
        type: array
        items:
          $ref: '#/definitions/CovenantsInfoModel'
