#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : incomingpayment.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Payment Application Service
host: 10.184.157.121:9000
basePath: /payment-services
tags:
- name: PaymentApplication
  description: API for PaymentApplication Operations
schemes:
- http
paths:
  /web/v1/incomingpayment:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - IncomingPayments
      summary: Adds a new IncomingPayments.
      description: Adds a new IncomingPayments. Add additional information here for this endpoint.
      operationId: addIncomingPayments
      parameters:
      - name: IncomingPayments
        in: body
        description: Request Body that contains data required for creating a new IncomingPayments
        required: true
        schema:
          $ref: '#/definitions/IncomingPaymentsModel'
      responses:
        201:
          description: Returns the Id of the newly created IncomingPayments
          headers:
            Location:
              description: URL of newly created IncomingPayments
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - IncomingPayments
      summary: Retrieves the list of existing IncomingPayments.
      description: Retrieves the list of existing IncomingPayments. Add additional information here for the this endpoint.
      operationId: getAllIncomingPayments
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
        
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/incomingpayment/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - IncomingPayments
      summary: Retrieves the IncomingPayments by id.
      description: Retrieves the IncomingPayments by id. Add additional information here for the this endpoint.
      operationId: getIncomingPaymentsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the IncomingPayments based on given applicationNumber.
          schema:
            $ref: '#/definitions/IncomingPaymentsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - IncomingPayments
      summary: Update an existing IncomingPayments.
      description: Update an existing IncomingPayments. Add additional information here for the this endpoint.
      operationId: updateIncomingPayments
      parameters:
      - name: id
        in: path
        description: id of the IncomingPayments that need to be updated
        required: true
        type: string
      - name: IncomingPayments
        in: body
        description: Request Body that contains data required for updating an existing IncomingPayments
        required: true
        schema:
          $ref: '#/definitions/IncomingPaymentsModel'
      responses:
        200:
          description: Returns updated IncomingPayments
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - IncomingPayments
      summary: Deletes the IncomingPayments identified by given ID.
      description: Deletes the IncomingPayments identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteIncomingPayments
      parameters:
      - name: id
        in: path
        description: Id of the IncomingPayments that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  IncomingPaymentsModel:
    description: IncomingPayments model
    type: object
    properties:
      id:
        description: Id of the IncomingPayments
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      borrowerNumber:
        description: borrowerNumber
        type: string
      borrowerName:
        description: borrowerName
        type: string
      currency:
        description: currency
        type: string
      valueDate:
        description: valueDate
        type: string
      transactionRefNo:
        description: transactionRefNo
        type: string
      matchingStatus:
        description: matchingStatus
        type: string
      amount:
        description: amount
        type: number
      contractRefNumber:
        description: contractRefNumber
        type: string      
      paymentApplicationNumber:
        description: paymentApplicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string                   
      incomingPaymentsDocs:
        type: array
        items:
          $ref: '#/definitions/IncomingPaymentsDocsModel'
  IncomingPaymentsDocsModel:
    description: IncomingPaymentsDocs model
    type: object
    properties:
      id:
        description: Id of the IncomingPaymentsDocs
        type: string
      parentDatasegmentId:
        description: parentDatasegmentId
        type: string
      documentLinkageId:
        description: documentLinkageId
        type: string
      documentType:
        description: documentType
        type: string
      documentName:
        description: documentName
        type: string
  IncomingPaymentsDocsWorkModel:
    description: IncomingPaymentsDocsWork model
    type: object
    properties:
      id:
        description: Id of the IncomingPaymentsDocsWork
        type: string
      parentDatasegmentId:
        description: parentDatasegmentId
        type: string
      documentLinkageId:
        description: documentLinkageId
        type: string
      documentType:
        description: documentType
        type: string
      documentName:
        description: documentName
        type: string
  IncomingPaymentsCollection:
    description: Collection of IncomingPayments.
    type: object
    properties:
      IncomingPaymentsList:
        type: array
        items:
          $ref: '#/definitions/IncomingPaymentsModel'
