#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : creditratingdetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Common Applicant Services
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-applicantservices
tags:
- name: ApplicantServices
  description: API for ApplicantServices Operations
schemes:
- http
paths:
  /web/v1/creditratingdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditRatingDetails
      summary: Adds a new CreditRatingDetails.
      description: Adds a new CreditRatingDetails. Add additional information here for this endpoint.
      operationId: addCreditRatingDetails
      parameters:
      - name: CreditRatingDetails
        in: body
        description: Request Body that contains data required for creating a new CreditRatingDetails
        required: true
        schema:
          $ref: '#/definitions/CreditRatingDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created CreditRatingDetails
          headers:
            Location:
              description: URL of newly created CreditRatingDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditRatingDetails
      summary: Retrieves the list of existing CreditRatingDetails.
      description: Retrieves the list of existing CreditRatingDetails. Add additional information here for the this endpoint.
      operationId: getAllCreditRatingDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/creditratingdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditRatingDetails
      summary: Retrieves the CreditRatingDetails by id.
      description: Retrieves the CreditRatingDetails by id. Add additional information here for the this endpoint.
      operationId: getCreditRatingDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CreditRatingDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/CreditRatingDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditRatingDetails
      summary: Update an existing CreditRatingDetails.
      description: Update an existing CreditRatingDetails. Add additional information here for the this endpoint.
      operationId: updateCreditRatingDetails
      parameters:
      - name: id
        in: path
        description: id of the CreditRatingDetails that need to be updated
        required: true
        type: string
      - name: CreditRatingDetails
        in: body
        description: Request Body that contains data required for updating an existing CreditRatingDetails
        required: true
        schema:
          $ref: '#/definitions/CreditRatingDetailsMasterModel'
      responses:
        200:
          description: Returns updated CreditRatingDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
 
definitions:
 CreditRatingDetailsMasterModel:
  description: CreditRatingDetailsMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the CreditRatigDetailsMasterModel
      type: string
      maxLength: 20  
     creditRatingMapModel:
      type: array
      items:
       $ref: '#/definitions/CreditRatingMapModel'
    required:
     - processRefNo
     - applicationNumber
     - creditRatingMapModel
 CreditRatingMapModel:
   description: "CreditRatingMapModel Model"
   type: object
   properties:
    id:
     description: Id of the CreditRatingMapModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the CreditRatingMapModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string 
    creditRatingDetailsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    applicantId:
     description: applicantId
     type: string
     maxLength: 36
    applicantName:
     description: applicantName
     type: string
     maxLength: 100
    deleteCreditRating:
     description: deleteCreditRating
     type: boolean
    primaryApplicant:
     description: primaryApplicant
     type: boolean
    creditRating:
     description: creditRating
     type: string
    creditRatingDetailsModel:
      type: array
      items:
       $ref: '#/definitions/creditRatingDetailsModel' 
   required:
    - processRefNo
    - applicationNumber
    - applicantId
    - creditRatingDetailsModel
 CreditRatingDetailsModel:
   description: "CreditRatingDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the CreditRatingDetailsModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the CreditRatingDetailsModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    creditRatingMapMasterId:
     description: Id of Map table
     type: string
     maxLength: 36
    externalRating:
     description: External Rating
     type: string
     maxLength: 10
    externalRatingAgency:
     description: External Rating Agency
     type: string
     maxLength: 25
    remarks:
     description: Rating Decription
     type: string
    seqNo:
     description: seq No
     type: integer
    documentId:
      description: Credit Report
      type: string
    additionalInfoDetailsModel:
      type: array
      items:
       $ref: '#/definitions/additionalInfoDetailsModel' 
   required:
    - processRefNo
    - applicationNumber
    - seqNo
 additionalInfoDetailsModel:
   description: "additionalInfoDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the additionalInfoDetailsModel
     type: string
     maxLength: 36
    creditRatingDetailsId:
     description: creditRatingDetailsId
     type: string
     maxLength: 36
    institutionName:
     description: institution Name
     type: string
     maxLength: 30
    accountNumber:
     description: accountNumber
     type: string
     maxLength: 25
    accountType:
     description: account Type
     type: string
    loanAmount:
     description: loanAmount
     type: string
    outstandingBalance:
     description: outstandingBalance
     type: string
    accountOpenDate:
     description: accountOpenDate
     type: string
    installmentAmount:
     description: installmentAmount
     type: string
    deliquencyDetails:
     type: array
     items:
      $ref: '#/definitions/deliquencyDetailsModel'
 deliquencyDetailsModel:
   description: "additionalInfoDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the deliquencyDetailsModel
     type: string
     maxLength: 36
    additionalInfoDetailsId:
     description: additionalInfoDetailsId
     type: string
     maxLength: 36
    deliquencyBucketName:
     description: deliquencyBucketName
     type: string
     maxLength: 25
    deliquencyAmount:
     description: deliquencyAmount
     type: string
     maxLength: 25
 
 CreditRatingDetailsMasterCollection:
   description: Collection of CreditRatingDetailsMasterModel.
   type: object
   properties:
    creditRatingDetailsMasterModelList:
     type: array
     items:
      $ref: '#/definitions/CreditRatingDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 