#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ddentitydetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/ddentitydetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownEntityDetails
      summary: Adds a new DrawdownEntityDetails.
      description: Adds a new DrawdownEntityDetails. Add additional information here for this endpoint.
      operationId: addDrawdownEntityDetails
      parameters:
      - name: DrawdownEntityDetails
        in: body
        description: Request Body that contains data required for creating a new DrawdownEntityDetails
        required: true
        schema:
          $ref: '#/definitions/DrawdownEntityDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created DrawdownEntityDetails
          headers:
            Location:
              description: URL of newly created DrawdownEntityDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownEntityDetails
      summary: Retrieves the list of existing DrawdownEntityDetails.
      description: Retrieves the list of existing DrawdownEntityDetails. Add additional information here for the this endpoint.
      operationId: getAllDrawdownEntityDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/ddentitydetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownEntityDetails
      summary: Retrieves the DrawdownEntityDetails by id.
      description: Retrieves the DrawdownEntityDetails by id. Add additional information here for the this endpoint.
      operationId: getDrawdownEntityDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DrawdownEntityDetails based on given applicationNumber.
          schema:
            $ref: '#/definitions/DrawdownEntityDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownEntityDetails
      summary: Update an existing DrawdownEntityDetails.
      description: Update an existing DrawdownEntityDetails. Add additional information here for the this endpoint.
      operationId: updateDrawdownEntityDetails
      parameters:
      - name: id
        in: path
        description: id of the DrawdownEntityDetails that need to be updated
        required: true
        type: string
      - name: DrawdownEntityDetails
        in: body
        description: Request Body that contains data required for updating an existing DrawdownEntityDetails
        required: true
        schema:
          $ref: '#/definitions/DrawdownEntityDetailsModel'
      responses:
        200:
          description: Returns updated DrawdownEntityDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownEntityDetails
      summary: Deletes the DrawdownEntityDetails identified by given ID.
      description: Deletes the DrawdownEntityDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteDrawdownEntityDetails
      parameters:
      - name: id
        in: path
        description: Id of the DrawdownEntityDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  DrawdownEntityDetailsModel:
    description: DrawdownEntityDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownEntityDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks
        type: string
      eDPartyDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownEDPartyDetailsModel'
  DrawdownEDPartyDetailsModel:
    description: DrawdownEDPartyDetails model
    type: object
    required:
    - partyId
    - partyName
    properties:
      id:
        description: Id of the DrawdownEDPartyDetails
        type: string
      entyDtlsId:
        description: entyDtlsId
        type: string
      partyId:
        description: Party ID
        type: string
        maxLength: 36
      partyNumber:
        description: Party Number
        type: string
        maxLength: 36
      partyName:
        description: Party Name
        type: string
        maxLength: 50
      eDPartyEntityDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownEDPartyEntityDetailsModel'
  DrawdownEDPartyEntityDetailsModel:
    description: DrawdownEDPartyEntityDetails model
    type: object
    required:
    - entityName
    - entityDescription
    - primaryEntity
    properties:
      id:
        description: Id of the DrawdownEDPartyEntityDetails
        type: string
      prtyDtlsId:
        description: prtyDtlsId
        type: string
      entityName:
        description: entityName
        type: string
      entityDescription:
        description: entityDescription
        type: string
      primaryEntity:
        description: primaryEntity
        type: string
  DrawdownEntityDetailsCollection:
    description: Collection of DrawdownEntityDetails.
    type: object
    properties:
      DrawdownEntityDetailsList:
        type: array
        items:
          $ref: '#/definitions/DrawdownEntityDetailsModel'
