#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking CorpoparticipationPending Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : feeshedule.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/feeshedule:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - feeshedule
      summary: Adds a new feeshedule.
      description: Adds a new feeshedule. Add additional information here for this endpoint.
      operationId: addfeeshedule
      parameters:
      - name: feeshedule
        in: body
        description: Request Body that contains data required for creating a new feeshedule
        required: true
        schema:
          $ref: '#/definitions/feeSheduleModel'
      responses:
        201:
          description: Returns the Id of the newly created Charges
          headers:
            Location:
              description: URL of newly created Charges
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - feeshedule
      summary: Retrieves the list of existing feeshedule.
      description: Retrieves the list of existing feeshedule. Add additional information here for the this endpoint.
      operationId: getAllfeeshedule
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/feeshedule/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - feeshedule
      summary: Get a  feeshedule.
      description: Get a  feeshedule by given id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: id of the feeshedule that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated feeshedule
          schema:
            $ref: '#/definitions/feeSheduleModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - feeshedule
      summary: Update an existing feeshedule.
      description: Update an existing feeshedule. Add additional information here for the this endpoint.
      operationId: updatefeeshedule
      parameters:
      - name: id
        in: path
        description: id of the feeshedule that need to be updated
        required: true
        type: string
      - name: feeshedule
        in: body
        description: Request Body that contains data required for updating an existing feeshedule
        required: true
        schema:
          $ref: '#/definitions/feeSheduleModel'
      responses:
        200:
          description: Returns updated feeshedule
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - feeshedule
      summary: Deletes the feeshedule identified by given ID.
      description: Deletes the feeshedule identified by given ID. Add additional information here for the this endpoint.
      operationId: deletefeeshedule
      parameters:
      - name: id
        in: path
        description: Id of the feeshedule that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FeeSheduleModel:
    description: feeshedule model
    type: object
    properties:
      id:
        description: Id of the feeshedule
        type: string
      applicationNumber:
        description: Application Number of the feeshedule
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      feeShedulesDetails:
        type: array
        items:
          $ref: '#/definitions/FeeShedulesDetailsModel'  
  FeeSheduleCollection:
    description: Collection of feeshedule.
    type: object
    properties:
      FeesheduleList:
        type: array
        items:
          $ref: '#/definitions/feeSheduleModel'
  FeeShedulesDetailsModel:
    description: FeeSheduleDetails model
    type: object
    properties:
      id:
        description: Id of the FeeSheduleDetails
        type: string
        maxLength: 36
      adminFeeId:
        description: adminFeeId of the FeeSheduleDetails
        type: string
      component:
        description: component of the FeeSheduleDetails
        type: string
      numberShedule:
        description: numberShedule of the FeeSheduleDetails
        type: number
      frequency:
        description: frequency of the FeeSheduleDetails
        type: string
        maxLength: 50
      unit:
        description: unit of the FeeSheduleDetails
        type: number
      amount:
        description: amount of the FeeSheduleDetails
        type: number
      currency:
        description: currency of the FeeSheduleDetails
        type: string
        maxLength: 20
      startDate:
        description: StartDate of the FeeSheduleDetails
        type: string
  FeeShedulesDetailsCollection:
    description: Collection of FeeSheduleDetails.
    type: object
    properties:
      FeeSheduleDetailsList:
        type: array
        items:
          $ref: '#/definitions/FeeShedulesDetailsModel'
 