#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  :  margindetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/margindetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MarginDetails
      summary: Adds a new MarginDetails.
      description: Adds a new MarginDetails. Add additional information here for this endpoint.
      operationId: addMarginDetails
      parameters:
      - name: TrancheMarginDetails
        in: body
        description: Request Body that contains data required for creating a new MarginDetails
        required: true
        schema:
          $ref: '#/definitions/MarginDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created MarginDetails
          headers:
            Location:
              description: URL of newly created MarginDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MarginDetails
      summary: Retrieves the list of  MarginDetails
      description: Retrieves the list of  MarginDetails Add additional information here for the this endpoint.
      operationId: getAllMarginDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: trancheId that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/margindetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MarginDetails
      summary: Get a  MarginDetails
      description: Update a  MarginDetails Add additional information here for the this endpoint.
      operationId: getMarginDetailsById
      parameters:
      - name: id
        in: path
        description: id of the MarginDetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated MarginDetails
          schema:
            $ref: '#/definitions/MarginDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MarginDetails
      summary: Update an  MarginDetails
      description: Update an  MarginDetails Add additional information here for the this endpoint.
      operationId: updateMarginDetails
      parameters:
      - name: id
        in: path
        description: id of the MarginDetails that need to be updated
        required: true
        type: string
      - name: TrancheMarginDetails
        in: body
        description: Request Body that contains data required for updating an  MarginDetails
        required: true
        schema:
          $ref: '#/definitions/MarginDetailsModel'
      responses:
        200:
          description: Returns updated MarginDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - MarginDetails
      summary: Deletes the MarginDetails identified by given ID.
      description: Deletes the MarginDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteMarginDetails
      parameters:
      - name: id
        in: path
        description: Id of the MarginDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  MarginDetailsModel:
    description: MarginDetails model
    type: object
    properties:
      id:
        description: Id of the MarginDetails
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the MarginDetails
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: Remarks of the MarginDetails
        type: string
        maxLength: 300
      dataSegmentCode:
        description: Data segment code
        type: string
      trancheMarginDetails:
        description: TrancheMarginDetails of the MarginDetails
        type: array
        items:
          $ref: '#/definitions/TrancheMarginDetailsModel'
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
  MarginDetailsCollection:
    description: Collection of TrancheMarginDetails.
    type: object
    properties:
      TrancheMarginDetailsList:
        type: array
        items:
          $ref: '#/definitions/MarginDetailsModel'
  TrancheMarginDetailsModel:
    description: TrancheMarginDetails model
    type: object
    properties:
      id:
        description: Id of the  TrancheMarginDetails
        type: string
        maxLength: 36
      marginDetailsId:
        description: MarginDetailsId of the  TrancheMarginDetails
        type: string
        maxLength: 36
      marginType:
        description: marginType of the TrancheMarginDetails
        type: string
        maxLength: 20
      trancheType:
        description: trancheType of the TrancheMarginDetails
        type: string
        maxLength: 50
      trancheEffectiveDate:
        description: trancheEffectiveDate of the TrancheMarginDetails
        type: string
        maxLength: 50
      trancheMaturityDate:
        description: trancheMaturityDate of the TrancheMarginDetails
        type: string
        maxLength: 50
      trancheId:
        description: Tranche Id of the TrancheMarginDetails
        type: string
        maxLength: 36  
      trancheName:
        description: trancheName of the TrancheMarginDetails
        type: string
        maxLength: 50      
      marginMethod:
        description: marginMethod of the TrancheMarginDetails
        type: string
        maxLength: 20
      amtDateFlag:
        description: amtDateFlag of the TrancheMarginDetails
        type: string
        maxLength: 20
      flatMarginRate:
        description: flatMarginRate of the TrancheMarginDetails
        type: number
        maxLength: 20  
      marginPricingDetails:
        description: marginPricingDetails of the TrancheMarginDetails
        type: array
        items:
          $ref: '#/definitions/MarginPricingDetailsModel'
  MarginPricingDetailsModel:
    description: MarginPricingDetails model
    type: object
    properties:
      id:
        description: Id of the MarginPricingDetails
        type: string
        maxLength: 36
      trancheMarginDetailsId:
        description: trancheMarginDetailsId
        type: string
        maxLength: 36
      amountCurrency:
        description: amountCurrency
        type: string
        maxLength: 3
      fromAmount:
        description: fromAmount
        type: number
        maxLength: 20
      toAmount:
        description: toAmount
        type: number
        maxLength: 20
      fromDate:
        description: fromDate
        type: string
        maxLength: 20
      toDate:
        description: toDate
        type: string
        maxLength: 20
      rate:
        description: rate
        type: number
        maxLength: 20 