#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : OBCM
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "Cash Withdrawal Alerts dto definitions yaml file" 
 version: "1.0.0"
 title: "Cash Withdrawal Alerts dto"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
 AlertDtoCollection:
    description: "Collection of Alert Dto."
    type: "object"
    properties:
      obcmWithdrawalEntryMainDto:
        description: "Withdrawal Entry Main Dto"
        $ref: "#/definitions/ObcmWithdrawalEntryMainDto"      
 DenominationModel:
    description: "Denomination model"
    type: "object"
    properties:
      id:
        description: "Id of the Denomination"
        type: "string"
      seqNo:
        description: "Sequence No of the Denomination"
        type: "integer"
        format: "int64"
      referenceNum:
        description: "Reference No of the Denomination"
        type: "string"
      depositSlipRefNo:
        description: "Deposit Slip Ref No of the Denomination"
        type: "string"
      depositSlipNo:
        description: "No of the Deposit Slip"
        type: "string"
      denominationRefNo:
        description: "Reference No of the Denomination"
        type: "string"
      denominationType:
        description: "Type of the Denomination"
        type: "string"      
      denominationValue:
        description: "Value of the Denomination"
        type: "number"
      denominationCount:
        description: "Count of the Denomination"
        type: "number"
      denominationAmount:
        description: "Amount of the Denomination"
        type: "number"
      denominationStatus:
        description: "Status of the Denomination"
        type: "string"
      denominationCcy:
        description: "Currency of the Denomination"
        type: "string"    
      makerId:
        type: "string"
        description: "Maker Id"
      makerDtStamp:
        type: "string"
        format: date
        description: "Maker Date Stamp"
      checkerId:
        type: "string"
        description: "Checker Id"
      checkerDtStamp:
        type: "string"
        format: date
        description: "Checker Date Stamp"     
             
 UpdatedPlaceholdersDto:
    description: "DTO for FlatAlertObj"
    type: object
    properties:
      id:
        description: "Id of the batch"
        type: "string"
      extReferenceNo:
        description: "External Reference No"
        type: "string"
      makerId:
        description: "Maker Id"
        type: "string"
      makerDtStamp:
        description: "Maker Date Stamp"
        type: "string"
      checkerId:
        description: "Checker Id"
        type: string
      checkerDtStamp:
        description: "Checker Date Stamp"
        type: string    
      checkerRemarks:
        description: "Checker Remarks"
        type: "string"
      makerRemarks:
        description: "Maker Remarks"
        type: "string"
      authStat:
        description: "Authorization Status"
        type: "string" 
      branchCode:
        description: "Branch Code"
        type: "string"
      corporateId:
        description: "Corporate Id"
        type: "string"
      corporateName:
        description: "Corporate Name"
        type: "string"
      debitAccountNo:
        description: "Debit Account No"
        type: "string"
      chequeDate:
        description: "Cheque Date"
        type: "string"
      chequeNo:
        description: "Cheque No"
        type: string
      slipNo:
        description: "Slip No"
        type: string    
      corporateRefNo:
        description: "Corporate Reference No"
        type: "string"
      denominationCount:
        description: "Denomination Count"
        type: "string"
      amount:
        description: "Amount"
        type: "string" 
      recipientName:
        description: "Recipient Name"
        type: "string"
      idProofType:
        description: "Id Proof Type"
        type: "string"
      idProofDetail:
        description: "Id Proof Detail"
        type: "string"
      contactNo:
        description: "Contact No"
        type: "string"
      courierCode:
        description: "Courier Code"
        type: "string"
      consignmentNo:
        description: "Consignment No"
        type: string
      consignmentDate:
        description: "Consignment Date"
        type: string    
      noOfMiscFields:
        description: "No Of Miscellaneous Fields"
        type: "string"
      misc1:
        description: "Miscellaneous Field 1"
        type: "string"
      misc2:
        description: "Miscellaneous Field 2"
        type: "string"
      misc3:
        description: "Miscellaneous Field 3"
        type: "string"
      misc4:
        description: "Miscellaneous Field 4"
        type: "string"
      misc5:
        description: "Miscellaneous Field 5"
        type: "string"
      misc6:
        description: "Miscellaneous Field 6"
        type: "string"
      misc7:
        description: "Miscellaneous Field 7"
        type: "string"
      misc8:
        description: "Miscellaneous Field 8"
        type: "string"
      misc9:
        description: "Miscellaneous Field 9"
        type: "string"
      misc10:
        description: "Miscellaneous Field 10"
        type: "string"
      misc11:
        description: "Miscellaneous Field 11"
        type: "string"
      misc12:
        description: "Miscellaneous Field 12"
        type: "string"
      misc13:
        description: "Miscellaneous Field 13"
        type: "string"
      misc14:
        description: "Miscellaneous Field 14"
        type: "string"
      misc15:
        description: "Miscellaneous Field 15"
        type: "string"
      misc16:
        description: "Miscellaneous Field 16"
        type: "string"
      misc17:
        description: "Miscellaneous Field 17"
        type: "string"
      misc18:
        description: "Miscellaneous Field 18"
        type: "string"
      misc19:
        description: "Miscellaneous Field 19"
        type: "string"
      misc20:
        description: "Miscellaneous Field 20"
        type: "string"
      misc21:
        description: "Miscellaneous Field 21"
        type: "string"
      misc22:
        description: "Miscellaneous Field 22"
        type: "string"
      misc23:
        description: "Miscellaneous Field 23"
        type: "string"
      misc24:
        description: "Miscellaneous Field 24"
        type: "string"
      misc25:
        description: "Miscellaneous Field 25"
        type: "string"
      misc26:
        description: "Miscellaneous Field 26"
        type: "string"
      misc27:
        description: "Miscellaneous Field 27"
        type: "string"
      misc28:
        description: "Miscellaneous Field 28"
        type: "string"
      misc29:
        description: "Miscellaneous Field 29"
        type: "string"
      misc30:
        description: "Miscellaneous Field 30"
        type: "string"
      modNo:
        description: "Mod No"
        type: "string"
      onceAuth:
        description: "Once Auth"
        type: "string"
      recordStat:
        description: "Record Status"
        type: "string"
      transactionRefNo:
        description: "Transaction Reference Number"
        type: "string"
      currency:
        description: "Currency"
        type: string
      exchangeRate:
        description: "Exchange Rate"
        type: "string"
      amtAccCcy:
        description: "Amtount Account Ccy"
        type: "string"
      deliveryPointCode:
        description: "Delivery Point Code"
        type: "string"
      deliveryPointDesc:
        description: "Delivery Point Desc"
        type: "string"
      recipientType:
        description: "Recipient Type"
        type: string
      stage:
        description: "Stage"
        type: "string"
      debitStatus:
        description: "Debit Status"
        type: "string"
      externalChannel:
        description: "External Channel"
        type: "string"
      lienNumber:
        description: "Lien Number"
        type: "string"
      lienAmount:
        description: "Lien Amount"
        type: string
      processingDate:
        description: "Processing Date"
        type: "string"
      requestedDate:
        description: "Requested Date"
        type: "string"
      lienDate:
        description: "Lien Date"
        type: "string"
      debitDate:
        description: "debitDate"
        type: "string"
      withdrawalSlipDate:
        description: "Withdrawal Slip Date"
        type: string
      debitACCY:
        description: "Debit Account CCY"
        type: "string"
      vaFlagYN:
        description: "va Flag YN"
        type: "string" 
 ObcmWithdrawalEntryMainDto:
    description: "Cash Withdrawal entry Dto"
    type: "object"
    properties:
      id:
        description: "Id of the batch"
        type: "string"
      extReferenceNo:
        description: "External Reference No"
        type: "string"
      makerId:
        description: "Maker Id"
        type: "string"
      makerDtStamp:
        description: "Maker Date Stamp"
        type: "string"
      checkerId:
        description: "Checker Id"
        type: string
      checkerDtStamp:
        description: "Checker Date Stamp"
        type: string    
      checkerRemarks:
        description: "Checker Remarks"
        type: "string"
      makerRemarks:
        description: "Maker Remarks"
        type: "string"
      authStat:
        description: "Authorization Status"
        type: "string" 
      branchCode:
        description: "Branch Code"
        type: "string"
      corporateId:
        description: "Corporate Id"
        type: "string"
      corporateName:
        description: "Corporate Name"
        type: "string"
      debitAccountNo:
        description: "Debit Account No"
        type: "string"
      chequeDate:
        description: "Cheque Date"
        type: "string"
      chequeNo:
        description: "Cheque No"
        type: string
      slipNo:
        description: "Slip No"
        type: string    
      corporateRefNo:
        description: "Corporate Reference No"
        type: "string"
      denominationCount:
        description: "Denomination Count"
        type: "string"
      amount:
        description: "Amount"
        type: "string" 
      recipientName:
        description: "Recipient Name"
        type: "string"
      idProofType:
        description: "Id Proof Type"
        type: "string"
      idProofDetail:
        description: "Id Proof Detail"
        type: "string"
      contactNo:
        description: "Contact No"
        type: "string"
      courierCode:
        description: "Courier Code"
        type: "string"
      consignmentNo:
        description: "Consignment No"
        type: string
      consignmentDate:
        description: "Consignment Date"
        type: string    
      noOfMiscFields:
        description: "No Of Miscellaneous Fields"
        type: "string"
      misc1:
        description: "Miscellaneous Field 1"
        type: "string"
      misc2:
        description: "Miscellaneous Field 2"
        type: "string"
      misc3:
        description: "Miscellaneous Field 3"
        type: "string"
      misc4:
        description: "Miscellaneous Field 4"
        type: "string"
      misc5:
        description: "Miscellaneous Field 5"
        type: "string"
      misc6:
        description: "Miscellaneous Field 6"
        type: "string"
      misc7:
        description: "Miscellaneous Field 7"
        type: "string"
      misc8:
        description: "Miscellaneous Field 8"
        type: "string"
      misc9:
        description: "Miscellaneous Field 9"
        type: "string"
      misc10:
        description: "Miscellaneous Field 10"
        type: "string"
      misc11:
        description: "Miscellaneous Field 11"
        type: "string"
      misc12:
        description: "Miscellaneous Field 12"
        type: "string"
      misc13:
        description: "Miscellaneous Field 13"
        type: "string"
      misc14:
        description: "Miscellaneous Field 14"
        type: "string"
      misc15:
        description: "Miscellaneous Field 15"
        type: "string"
      misc16:
        description: "Miscellaneous Field 16"
        type: "string"
      misc17:
        description: "Miscellaneous Field 17"
        type: "string"
      misc18:
        description: "Miscellaneous Field 18"
        type: "string"
      misc19:
        description: "Miscellaneous Field 19"
        type: "string"
      misc20:
        description: "Miscellaneous Field 20"
        type: "string"
      misc21:
        description: "Miscellaneous Field 21"
        type: "string"
      misc22:
        description: "Miscellaneous Field 22"
        type: "string"
      misc23:
        description: "Miscellaneous Field 23"
        type: "string"
      misc24:
        description: "Miscellaneous Field 24"
        type: "string"
      misc25:
        description: "Miscellaneous Field 25"
        type: "string"
      misc26:
        description: "Miscellaneous Field 26"
        type: "string"
      misc27:
        description: "Miscellaneous Field 27"
        type: "string"
      misc28:
        description: "Miscellaneous Field 28"
        type: "string"
      misc29:
        description: "Miscellaneous Field 29"
        type: "string"
      misc30:
        description: "Miscellaneous Field 30"
        type: "string"
      modNo:
        description: "Mod No"
        type: "string"
      onceAuth:
        description: "Once Auth"
        type: "string"
      recordStat:
        description: "Record Status"
        type: "string"
      transactionRefNo:
        description: "Transaction Reference Number"
        type: "string"
      currency:
        description: "Currency"
        type: string
      exchangeRate:
        description: "Exchange Rate"
        type: "string"
      amtAccCcy:
        description: "Amtount Account Ccy"
        type: "string"
      deliveryPointCode:
        description: "Delivery Point Code"
        type: "string"
      deliveryPointDesc:
        description: "Delivery Point Desc"
        type: "string"
      recipientType:
        description: "Recipient Type"
        type: string
      stage:
        description: "Stage"
        type: "string"
      debitStatus:
        description: "Debit Status"
        type: "string"
      externalChannel:
        description: "External Channel"
        type: "string"
      lienNumber:
        description: "Lien Number"
        type: "string"
      lienAmount:
        description: "Lien Amount"
        type: string
      processingDate:
        description: "Processing Date"
        type: "string"
      requestedDate:
        description: "Requested Date"
        type: "string"
      lienDate:
        description: "Lien Date"
        type: "string"
      debitDate:
        description: "debitDate"
        type: "string"
      withdrawalSlipDate:
        description: "Withdrawal Slip Date"
        type: string
      debitACCY:
        description: "Debit Account CCY"
        type: "string"
      vaFlagYN:
        description: "va Flag YN"
        type: "string"
      denominationDetails:
        type: "array"
        items:
          $ref: "#/definitions/DenominationModel"
        description: "Denomination Model"            