#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : obscf
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Auto Reconciliation Web Definitions"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
 ScfTmReconRuleDefMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     baseEntity:
      type: string
      description: "Base Entity"
     baseOnAttr:
      type: string
      description: "Base on attribute"
     genericCriteria:
      type: string
      description: "Generic Criteria"
     reconCategory:
      type: string
      description: "Recon Category"
     reconType:
      type: string
      description: "Recon Type"
     ruleDescription:
      type: string
      description: "Rule Description"
     txnControllerRefNo:
      type: string
      description: "Transaction Controller Reference Number"        
     ruleId:
      type: string
      description: "Rule Id"
     ScfTmExactReconMasterDTO:
      type: array
      items:
       $ref: '#/definitions/ScfTmExactReconMasterDTO' 
 ScfTmExactReconMasterDTO:
  type: object
  properties:
     id:
      type: string
      description: "Id"
     matchCriteria:
      type: string
      description: "Match Criteria"
     matchPattern:
      type: string
      description: "Match Pattern"
     patternLhs:
      type: string
      description: "Pattern Lhs"
     patternRhs:
      type: string
      description: "Pattern Rhs"
     reconEntityAttrLhs:
      type: string
      description: "Recon Entity Attribute Lhs"
     reconEntityAttrRhs:
      type: string
      description: "Recon Entity Attribute Rhs"
     reconEntityLhs:
      type: string
      description: "Recon Entity Lhs"
     reconEntityRhs:
      type: string
      description: "Recon Entity Rhs"
     recRuleDefMasterId:
      type: string
      description: "Recon Rule Definition Master Id"
     ruleId:
      type: string
      description: "Rule Id"
 ScfTmRecRuleDecMasterDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     filterAttr1:
      type: string
      description: "Filter Attribute 1"
     filterAttr1Name:
      type: string
      description: "Filter Attribute 1 Name"
     filterAttr2:
      type: string
      description: "Filter Attribute 2"
     filterAttr2Name:
      type: string
      description: "Filter Attribute 2 Name"
     filterAttr3:
      type: string
      description: "Filter Attribute 3"
     filterAttr3Name:
      type: string
      description: "Filter Attribute 3 Name"
     filterAttr4:
      type: string
      description: "Filter Attribute 4"
     filterAttr4Name:
      type: string
      description: "Filter Attribute 4 Name"
     filterAttr5:
      type: string
      description: "Filter Attribute 5" 
     filterAttr5Name:
      type: string
      description: "Filter Attribute 5 Name"
     filterCriteria:
      type: string
      description: "Filter Criteria"
     txnControllerRefNo:
      type: string
      description: "Transaction Controller Reference Number"        
     ruleDecisionId:
      type: string
      description: "Rule Decision ID"
     ScfTmRecRuleDecPriMasterDTO:
      type: array
      items:
       $ref: '#/definitions/ScfTmRecRuleDecPriMasterDTO'
 ScfTmRecRuleDecPriMasterDTO:
  type: object
  properties:
     id:
      type: string
      description: "Id"
     priority:
      type: number
      description: "Priority"
     reconCategory:
      type: string
      description: "Recon Category"
     reconType:
      type: string
      description: "Recon Type"
     recRuleDecMasterId:
      type: string
      description: "Recon Rule Decision Master Id"
     ruleDescription:
      type: string
      description: "Rule Description"
     ruleId:
      type: string
      description: "Rule Id"
     executeGeneric:
      type: string
      description: "Execute Generic"
     
      
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 ScfTmReconRuleDefMasterCollection: 
  description: "Collection of reconruledef."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ScfTmReconRuleDefMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 ScfTmRecRuleDecMasterCollection: 
  description: "Collection of recruledec."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ScfTmRecRuleDecMasterDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 ScfTmReconRuleDefMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/ScfTmReconRuleDefMasterDTO"
 ScfTmRecRuleDecMasterWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/ScfTmRecRuleDecMasterDTO"
 ScfFilterParamModel:
   description: "Scf Filter Parameters model"
   type: "object"
   properties:
     parameter:
       description: "Name of the parameter"
       type: "string"
     label:
       description: "Label of the parameter for given language"
       type: "string"
     columnName:
       description: "Name of the mapped column for given parameter"
       type: "string"
     fieldType:
       description: "Field Type"
       type: "string"
     endpointValue:
       description: "Endpoint Value"
       type: "string"
     reqParams:
       description: "Request Parameters"
       type: "string"
     lovConfig:
       description: "LOV Config Data"
       type: "array"
       items:
        $ref: '#/definitions/Map'
        
 ScfFilterParamModelCollection:
   description: "Collection of Scf filter parameters"
   type: "object"
   properties:
     type:
       description: "Filter criteria"
       type: "string"
     hierarchy:
       description: "hierarchy of the criteria"
       type: "string"
     ScfFilterParamModel:
       type: "array"
       items:
         $ref: "#/definitions/ScfFilterParamModel" 
 ScfFilterCriteriaModelKeyCollection:
   description: "Collection of list of Parameters."
   type: "object"
   properties:
     category:
       description: "category of the param"
       type: "string"
     ScfFilterParamModelCollection:
       type: "array"
       items:
         $ref: "#/definitions/ScfFilterParamModelCollection"
 StringStringMap:
    type: object
    additionalProperties:
      type: string
 ScfSystemParamCollection:
    description: "Collection of list of Parameters."
    type: "object"
    properties:
      ScfSystemParamModel:
        type: "array"
        items:
          $ref: "#/definitions/ScfSystemParamModel"
 ScfSystemParamModel:
    description: "Scf System Param model"
    type: "object"
    properties:
      id:
        description: "Id of the Parameter"
        type: "integer"
        format: "int64"
      key:
        description: "Key for the parameter.This is a unique constraint"
        type: "string"
      value:
        description: "Configured value which will be used in rest of application."
        type: "string"
 OrchestratorDTO: 
  type: "object"
  properties:
   resourceId:
    type: string
    description: "Id of the Orchestrator Resource"
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
    description: "Remark on Orchestrator"