#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : OBSCF
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
  version: "1.0.0"
  title: "Reconciliation Definition"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:

 ScfTmReconRuleDefinitionDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     allocationBasis:
      type: string
      description: "Allocation Basis"
     baseEntity:
      type: string
      description: "Base entity"
     baseOnAttr:
      type: string
      description: "Base On Attribute"
     genericCriteria:
      type: string
      description: "Generic Criteria"
     reconCategory:
      type: string
      description: "Recon Category"
     reconType:
      type: string
      description: "Recon Type"
     ruleDescription:
      type: string
      description: "Rule Description"
     ruleId:
      type: string
      description: "Rule Id"
     txnControllerRefNo:
      type: string
      description: "Transaction Controller Reference Number"
     ScfTmReconRuleGroupDTO:
      type: array
      items:
       $ref: '#/definitions/ScfTmReconRuleGroupDTO'
     ScfTmAllocationDTO:
      type: array
      items:
       $ref: '#/definitions/ScfTmAllocationDTO'
 ScfTmReconRuleGroupDTO:
  type: object
  properties:
     connectingOperator:
      type: string
      description: "Connecting Operator"
     id:
      type: string
      description: "Id"
     level:
      type: number
      description: "Level"
     parentIdentifier:
      type: string
      description: "Parent Identifier"
     reconRuleDefinitionId:
      type: string
      description: "Recon Rule Definition Id"
     ruleId:
      type: string
      description: "Rule Id"
     type:
      type: string
      description: "Type"
     typeIdentifier:
      type: string
      description: "Type Identifier"
     ScfTmRuleConditionDTO:
      type: array
      items:
       $ref: '#/definitions/ScfTmRuleConditionDTO'
 ScfTmAllocationDTO:
  type: object
  properties:
     action:
      type: string
      description: "Action"
     allocationParameter:
      type: string
      description: "Allocation Parameter"
     id:
      type: string
      description: "Id"
     percentage:
      type: number
      description: "Percentage"
     reconRuleDefinitionId:
      type: string
      description: "Recon Rule Definition Id"
     customerId:
      type: string
      
 ScfTmRuleConditionDTO:
  type: object
  properties:
     baseEntity:
      type: string
      description: "Base Entity"
     reconRuleGroupId:
      type: string
      description: "Recon Rule Group Id"
     expression:
      type: string
      description: "Expression"
     expressionId:
      type: string
      description: "Expression Id"
     id:
      type: string
      description: "Id"
     parentExpressionId:
      type: string
      description: "Parent Expression Id"
     ruleId:
      type: string
      description: "Rule Id"
     sequence:
      type: number
      description: "Sequence"
     type:
      type: string
      description: "Type"
     typeIdentifier:
      type: string
      description: "Type Identifier"
     conditionId:
      type: string
      description: "Condition Id"
     attribute:
      type: string
      description: "Attribute"
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 BindingResult:
  type: object
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 ScfTmReconRuleDefinitionCollection: 
  description: "Collection of reconruledefinition."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ReconRuleDefinitionDTO"
   paging:
    $ref: "#/definitions/PagingDto"

 ReconRuleDefinitionCollection: 
  description: "Collection of reconruledefinition."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ReconRuleDefinitionDTO"
   paging:
    $ref: "#/definitions/PagingDto"
    
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 ScfTmReconRuleDefinitionWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/ReconRuleDefinitionDTO"

 ReconRuleDefinitionWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/ReconRuleDefinitionDTO"

 ReconRuleDefinitionDTO:
  type: object
  properties:
   allocationBasis:
    type: string
    description: "Allocation Basis"
   baseEntity:
    type: string
    description: "Base Entity"
   baseOnAttr:
    type: string
    description: "Base on attribute"
   genericCriteria:
    type: string
    description: "Generic Criteria"
   reconCategory:
    type: string
    description: "Recon Category"
   reconType:
    type: string
    description: "Recon Type"
   ruleDescription:
    type: string
    description: "Rule Description"
   ruleId:
    type: string
    description: "Rule Id"
   txnControllerRefNo:
    type: string
    description: "Transaction Controller Reference Number"
   keyId:
    type: string
    description: "Key Id"
   modNo:
    type: number
    description: "Mod Number"
   recordStatus:
    type: string
    description: "Record Status"
   authStatus:
    type: string
    description: "Authorization Status"
   onceAuth:
    type: string
    description: "Once Auth"
   doerRemarks:
    type: string
    description: "Doer Remarks"
   approverRemarks:
    type: string
    description: "Approver Remarks"
   makerId:
    type: string
    description: "Maker Id"
   checkerId:
    type: string
    description: "Checker Id"
   makerDateStamp:
    type: string
    format: date
    description: "Maker Date Stamp"
   checkerDateStamp:
    type: string
    format: date
    description: "Checker Date Stamp"
   corporateId:
    type: string
   groupsAndConditions:
    type: array
    items:
     $ref: '#/definitions/RuleElementsDTO'
   reconAllocationDTO:
    type: array
    items:
     $ref: '#/definitions/ReconAllocationDTO'

 ReconAllocationDTO:
  type: object
  properties:
   action:
    type: string
    description: "Action"
   allocationParameter:
    type: string
    description: "Allocation Parameter"
   id:
    type: string
    description: "Id"
   percentage:
    type: number
    description: "Percentage"
   reconRuleDefinitionId:
    type: string
    description: "Recon Rule Definition Id"
   customerId:
    type: string
   

 RuleElementsDTO:
  type: object
  properties:
   id:
    type: string
    description: "Unique identifier for a group or condition"
   isGroup:
    type: boolean
    description: "Boolean value to identify whether this child is a group or condition"
   connectingOperator:
    type: string
    description: "Logical Operator applied between all groups, this is the connecting operator"
   level:
    type: number
    description: "This helps to identify the nesting level."
   matchingCriteria:
    type: string
    description: "Matching Criteria"
   reconEntityLHS:
    type: string
    description: "Should be null or not present if isGroup is true"
   reconEntityAttribLHS:
    type: string
    description: "Will be provided if Single entity is LHS entity or if single entity is N. Attribute which user wants to use for recon"
   reconEntityRHS:
    type: string
    description: "Should be null or not present if isGroup is true"
   reconEntityAttribRHS:
    type: string
    description: "Will be provided if Single entity is RHS entity or if single entity is N. Attribute which user wants to use for recon"
   patternTypeLHS:
    $ref: "#/definitions/PatternTypeDTO"
   patternTypeRHS:
    $ref: "#/definitions/PatternTypeDTO"
   groupsAndConditions:
    type: "array"
    items:
     $ref: "#/definitions/RuleElementsDTO"

 PatternTypeDTO:
  type: object
  properties:
   type:
    type: string
    description: "Type"
   inputValue1:
    type: string
    description: "Input Value1"
   inputValue2:
    type: string
    description: "Input Value2"
 OrchestratorDTO: 
  type: "object"
