swagger: "2.0"
info:
  description: "This is a sample server Legal Opinion server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "OBPY-Party-Services"
host: "whf00bdm:7801"
basePath: "/obpy-party-services"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "PartyAPI"
    description: "API for Party  Operations"

schemes:
  - "http"

paths:
  /web/v1/bankDemographics:
    post:
      tags:
        - "bankDemographicsWeb"
      summary: "Adds a new Party Demographic."
      description: "Adds a new Party Demographic."
      operationId: "createBankPartyDemographics"
      parameters:
        - name: "bankDemographics"
          in: "body"
          description: "Request Body that contains data required for creating a new Party Demographics"
          required: true
          schema:
            $ref: "#/definitions/BankDemographicsModel"
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date"
          required: false
      responses:
        201:
          description: "Successfully created a new Party Demographic Details"
          headers:
            Location:
              description: "URL of newly created Party Demographics"
              type: "string"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
  /web/v1/bankDemographics/{id}:
    put:
      tags:
        - "bankDemographicsWeb"
      summary: "Update a new Bank Demographic."
      description: "Update a new Bank Demographic."
      operationId: "updateBankPartyDemographics"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the party to be updated"
          required: true
          type: "string"
        - name: "bankDemographics"
          in: "body"
          description: "Request Body that contains data required for creating a new Party Demographics"
          required: true
          schema:
            $ref: "#/definitions/BankDemographicsModel"
        - name: "appId"
          in: "header"
          type: "string"
          required: true
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: true
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date"
          required: false
      responses:
        201:
          description: "Successfully created a new Party Demographic Details"
          headers:
            Location:
              description: "URL of newly created Party Demographics"
              type: "string"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        405:
          description: "Invalid input"
        500:
          description: "Internal error"
         
definitions:
  BankDemographicsModel:
    allOf:
      - $ref: '#/definitions/RepresentationModel'
      - type: "object"
        description: "Bank Party Demographics Master Model"
        properties:
          recordId:
            type: "string"
          partyId:
            type: "string"
          partyType:
            type: "string"
          partyCategory:
            type: "string"
          applicationNumber:
            type: "string"
          organizationName:
            type: "string"
          registrationNumber:
            type: "string"
          organizationType:
            type: "string"
          holdingPattern:
            type: "string"
          demographicType:
            type: "string"
          countryOfRisk:
            type: "string"            
          requestType:
            type: "string"
          incorporationDate:
            type: "string"
            format: "date"
          icrName:
            type: "string"
          fiCode:
            type: "string"
          bicCode:
            type: "string"
          fiOwnerShipType:
            type: "string"
          businessType:
            type: "string"
          micr:
            type: "string"            
          rtgs:
            type: "string"
          isEarMarkingMandated:
            type: "boolean"
          role:
            type: "string"
          borrowerSince:
            type: "string"
            format: "date"
          legalEntityCode:
            type: "string"
          headOfficeCountry:
            type: "string"
          isApprovedForExposure:
            type: "boolean"            
          isCorrespondentFI:
            type: "boolean"
          countyOfIncrptn:
            type: "string"
          organizationalURL:
            type: "string"
          facebookURL:
            type: "string"
          twitterURL:
            type: "string"
          rmId:
            type: "string"
          employeeStrength:
            type: "number"
          noOfYearsInBusiness:
            type: "number"
          noOfGrpCompanies:
            type: "number"
          isBlacklisted:
            type: "boolean"
          isKYCRequired:
            type: "boolean"
          isKYCCompliant:
            type: "boolean"
          lastKYCDate:
            type: "string"
            format: "date"
          isListedOrg:
            type: "boolean"
          language:
            type: "string"
          media:
            type: "string"
          recordStat:
            type: "string"
          versionNo:
            type: "integer"
            format: "int64"
          industryList:
            $ref: '#/definitions/PartyIndustryMasterModel'
          bankList:
            type: "array"
            items:  { $ref: '#/definitions/BankDemographicsModel'  }
  ResponseModel:
    properties:
      errors:
        type: object
      data:
        type: object
      paging:
        type: object
