#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : feedetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /clmo-syndicationapplication-services
tags:
- name: LoanApplication
  description: API for Syndication Application Operations
schemes:
- http
paths:
  /web/v1/fees:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Adds a new Fees.
      description: Adds a new Fees. Add additional information here for this endpoint.
      operationId: addFees
      parameters:
      - name: Fees
        in: body
        description: Request Body that contains data required for creating a new FeeDetails
        required: true
        schema:
          $ref: '#/definitions/FeeModel'
      responses:
        201:
          description: Returns the Id of the newly created FeeDetails
          headers:
            Location:
              description: URL of newly created FeeDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Retrieves the list of existing Fees.
      description: Retrieves the list of existing Fees. Add additional information here for the this endpoint.
      operationId: getAllFees
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: trancheId that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/fees/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Get a  Fee.
      description: Update a  Fee. Add additional information here for the this endpoint.
      operationId: getFeesById
      parameters:
      - name: id
        in: path
        description: id of the FeeDetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated Fee
          schema:
            $ref: '#/definitions/FeeModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Update an existing Fee.
      description: Update an existing FeeDetails. Add additional information here for the this endpoint.
      operationId: updateFees
      parameters:
      - name: id
        in: path
        description: id of the Fee that need to be updated
        required: true
        type: string
      - name: Fees
        in: body
        description: Request Body that contains data required for updating an existing FeeDetails
        required: true
        schema:
          $ref: '#/definitions/FeeModel'
      responses:
        200:
          description: Returns updated FeeDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Deletes the Fees identified by given ID.
      description: Deletes the FeeDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteFees
      parameters:
      - name: id
        in: path
        description: Id of the FeeDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/fees/feecomponents/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Retrieves the list of existing Fees.
      description: Retrieves the list of existing Fees. Add additional information here for the this endpoint.
      operationId: getFeeComponents
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: tranche id for which fee component is needed
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/components/{applicationNumber}/{type}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Fees
      summary: Retrieves the list of existing components for feeschedule.
      description: Retrieves the list of existing feeshedule. Add additional information here for the this endpoint.
      operationId: getAllComponents
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: type
        in: path
        description: type of the that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ComponentsModelCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FeeModel:
   description: FeeDetails model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      processRefNumber:
        description: Process Ref Number 
        type: string
      feeDetails:
        description: Fee Details of the Fee
        type: array
        items:
          $ref: '#/definitions/FeeDetailsModel' 
        maxLength: 20
  FeeDetailsModel:
     description: FeeDetails model
     type: object
     required:
     - feeType
     - feeMethod
     properties:
      id:
        description: Id of the FeeDetailsModel
        type: string
        maxLength: 36          
      feeId:
        description: feeId
        type: string
        maxLength: 36
      trancheId:
        description: Tranche Id of the FeeDetails
        type: string
        maxLength: 36
      trancheName:
        description: Tranche Name of the FeeDetails
        type: string
        maxLength: 20
      trancheType:
        description: Tranche Type of the FeeDetails
        type: string
        maxLength: 20
      trancheEffectiveDate:
        description: Tranche Effective Date of the FeeDetails
        type: string
      trancheMaturityDate:
        description: Tranche Maturity Date of the FeeDetails
        type: string
      feeType:
        description: Fee Type of the FeeDetails
        type: string
      feeMethod:
        description: feeMethod of the FeeDetails
        type: string
        minLength: 0
        maxLength: 20
      amtRateFlag:
        description: amtRateFlag of the FeeDetails
        type: string
        minLength: 0
        maxLength: 1
      amtDateFlag:
        description: amtDateFlag of the FeeDetails
        type: string
        minLength: 0
        maxLength: 1
      slabTierFlag:
        description: slabTierFlag of the FeeDetails
        type: string
        minLength: 0
        maxLength: 21
      flatFeeCurrency:
        description: Flat Fee Currency
        type: string
      flatFeeAmount:
        description: Flat Fee Amount
        type: number
      flatFeeRate:
        description: Rate
        type: number
      feePricingDetails:
        description: Fee Pricing Details
        type: array
        items:
          $ref: '#/definitions/FeePricingDetailsModel'
  FeePricingDetailsModel:
    description: FeePricingDetailsModel
    type: object
    properties:
      id:
        description: Id of the FeePricingDetailsModel
        type: string
        maxLength: 36          
      feeDetailsId:
        description: feePricingDetailsId
        type: string
        maxLength: 36
      amountCurrency:
        description: Amount Currency
        type: string
      amount:
        description: Amount
        type: number
      rate:
        description: Rate
        type: number
      fromAmount:
        description: From Amount
        type: number
      toAmount:
        description: To Amount
        type: number
      fromDate:
        description: From Date
        type: string
      toDate:
        description: To Date
        type: string
  FeeDetailsCollection:
    description: Collection of FeeDetails.
    type: object
    properties:
      FeeDetailsList:
        type: array
        items:
          $ref: '#/definitions/FeeDetailsModel'
  FeeComponentModelList:
    description: Collection of Fee Component.
    type: object
    properties:
      feeComponents:
        type: array
        items:
          $ref: '#/definitions/FeeComponentModel'
  FeeComponentModel:
    description: Collection of Fee Component.
    type: object
    properties:
      feeType:
        type: string
        description: Fee Type
      feeDescription:
        type: string
        description: Fee Description
  ComponentsModelCollection:
    description: Collection of ComponentsModelCollection.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ComponentsModel'
      paging:
        $ref: '#/definitions/PagingDto'
  ComponentsModel:
    description: Application Maintenance model
    type: object
    properties:
      code:
        description: Code
        type: string
      description:
        description: Description
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type