#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : approvalipadetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: In-Principle Approval Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-ipaservices
tags:
- name: IpaApplication
  description: API for In-Principle Approval Operations
schemes:
- http
paths:
  /web/v1/ipaapprovaldetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalIpaDetails
      summary: Adds a new ApprovalIpaDetails.
      description: Adds a new In-Principle Approval Details. Add additional information here for this endpoint.
      operationId: addApprovalIpaDetails
      parameters:
      - name: ApprovalIpaDetails
        in: body
        description: Request Body that contains data required for creating a new In-Principle Approval Details
        required: true
        schema:
          $ref: '#/definitions/ApprovalIpaDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created In-Principle Approval Details
          headers:
            Location:
              description: URL of newly created In-Principle Approval Details
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalIpaDetails
      summary: Retrieves the list of existing In-Principle Approval Details.
      description: Retrieves the list of existing In-Principle Approval Details. Add additional information here for the this endpoint.
      operationId: getAllApprovalIpaDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/ipaapprovaldetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalIpaDetails
      summary: Retrieves the In-Principle Approval Details by id.
      description: Retrieves the In-Principle Approval Details by id. Add additional information here for the this endpoint.
      operationId: getApprovalIpaDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the In-Principle Approval Details based on given processRefNo.
          schema:
            $ref: '#/definitions/ApprovalIpaDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalIpaDetails
      summary: Update an existing In-Principle Approval Details.
      description: Update an existing In-Principle Approval Details. Add additional information here for the this endpoint.
      operationId: updateApprovalIpaDetails
      parameters:
      - name: id
        in: path
        description: id of the In-Principle Approval Details that need to be updated
        required: true
        type: string
      - name: ApprovalIpaDetails
        in: body
        description: Request Body that contains data required for updating an existing In-Principle Approval Details
        required: true
        schema:
          $ref: '#/definitions/ApprovalIpaDetailsModel'
      responses:
        200:
          description: Returns updated ApprovalIpaDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalIpaDetails
      summary: Deletes the In-Principle Approval Details identified by given ID.
      description: Deletes the In-Principle Approval Details identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteApprovalIpaDetails
      parameters:
      - name: id
        in: path
        description: Id of the In-Principle Approval Details that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ApprovalIpaDetailsModel:
    description: In-Principle Approval Details model
    type: object
    properties:
      id:
        description: Id of the In-Principle Approval Details
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: Stage Code
        type: string
        maxLength: 36
      createdBy:
        description: Created By
        type: string
        maxLength: 36
      status:
        description: Status
        type: string
        maxLength: 36
      processRefNo:
        description: Process Reference No
        type: string
      applicationNumber:
        description: Application Number
        type: string
      loanCurrencyCode:
        description: Loan Currency Code
        type: string
        maxLength: 4
      eligibileLoanAmount:
        description: Eligible Loan Amount
        type: number
      loanTenure:
        description: loan Tenure
        type: string  
      purposeOfLoan:
        description: Purpose Of Loan
        type: string
      propertyType:
        description: Property Type
        type: string
      propertyLocationState:
        description: Property Location State
        type: string
        maxLength: 50
      propertyLocationCity:
        description: Property Location City
        type: string
        maxLength: 50
      builderName:
        description: Builder Name
        type: string
      vehicleCategory:
        description: Vehicle Category
        type: string 
      make:
        description: Make
        type: string
      model:
        description: Model
        type: string
      ipaRate:
        description: In-Principle Approval Rate
        type: number
        format: double
      ipaIssueDate:
        description: In-Principle Approval Issue Date
        type: string
      ipaExpiryDate:
        description: In-Principle Approval Expiry Date
        type: string
      validityPeriod:
        description: Validity Period
        type: string 
      accountType:
        description: Account Type
        type: string
      userResponse:
        description: User Response
        type: string
      reasonForReject:
        description: Reason For Rejection
        type: string 
      approvalDate:
        description: Date of Approval
        type: string 
      remarks:
        description: Remarks
        type: string
      version:
        description: Version
        type: integer
      recordStat:
        description: Record Stat
        type: string
  ApprovalIpaDetailsCollection:
    description: Collection of In-Principle Approval Details.
    type: object
    properties:
      ApprovalIpaDetailsList:
        type: array
        items:
          $ref: '#/definitions/ApprovalIpaDetailsModel'
