#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : commercialConstruction.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/commercialconstructionloan:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CommercialConstructionLoan
      summary: Adds a new Commercial Construction loan.
      description: Adds a new CommercialConstructionLoan. Add additional information here for this endpoint.
      operationId: addCommercialConstructionLoan
      parameters:
      - name: CommercialConstructionLoan
        in: body
        description: Request Body that contains data required for creating a new CommercialConstructionLoan
        required: true
        schema:
          $ref: '#/definitions/CommercialConstructionLoanModel'
      responses:
        201:
          description: Returns the Id of the newly created CommercialConstructionLoan
          headers:
            Location:
              description: URL of newly created CommercialConstructionLoan
              type: string
          schema:
            $ref: '../../commondefinitions.yaml#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CommercialConstructionLoan
      summary: Retrieves the list of  CommercialConstructionLoan.
      description: Retrieves the list of  CommercialConstructionLoan. Add additional information here for the this endpoint.
      operationId: getAllCommercialConstructionInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '../../commondefinitions.yaml#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/commercialconstructionloan/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CommercialConstructionLoan
      summary: Get a  CommercialConstructionLoan.
      description: Update a  CommercialConstructionLoan. Add additional information here for the this endpoint.
      operationId: getCommercialConstructionLoanById
      parameters:
      - name: id
        in: path
        description: id of the CommercialConstructionLoan that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated CommercialConstructionLoan
          schema:
            $ref: '#/definitions/CommercialConstructionLoanModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CommercialConstructionLoan
      summary: Update an  CommercialConstructionLoan.
      description: Update an  CommercialConstructionLoan. Add additional information here for the this endpoint.
      operationId: updateCommercialConstructionLoan
      parameters:
      - name: id
        in: path
        description: id of the CommercialConstructionLoan that need to be updated
        required: true
        type: string
      - name: CommercialConstructionLoan
        in: body
        description: Request Body that contains data required for updating an  CommercialConstructionLoan
        required: true
        schema:
          $ref: '#/definitions/CommercialConstructionLoanModel'
      responses:
        200:
          description: Returns updated CommercialConstructionLoan
          schema:
            $ref: '../../commondefinitions.yaml#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    
definitions:
  CommercialConstructionLoanModel:
   description: CommercialConstructionLoan model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      commercialPropertyDetails:
        description: Details of the Commercial Property
        type: array
        items:
          $ref: '#/definitions/CommercialPropertyDetailsModel'
  CommercialConstructionLoanCollection:
    description: Collection of CommercialConstructionLoan.
    type: object
    properties:
      CommercialConstructionLoanList:
        type: array
        items:
          $ref: '#/definitions/CommercialConstructionLoanModel'
  CommercialPropertyDetailsModel:
    description: CommercialPropertyDetails model
    type: object
    required:
    - propertyType
    - propertyDescription
    - addressLine1
    - addressLine2
    properties:
      id:
        description: Id of the Banking details model
        type: string
        format: int64
        maxLength: 36
      commercialLoanId:
        description: commercialLoanId of the Details model
        type: string
        maxLength: 36
      propertyType:
        description: propertyType of the Details model
        type: string
        maxLength: 35
      propertyDescription:
        description: propertyDescription of the Details model
        type: string
        maxLength: 2000
      addressLine1:
        description: addressLine1 of the Details model
        type: string
        maxLength: 105
      addressLine2:
        description: addressLine2 of the Details model
        type: string
        maxLength: 105
      addressLine3:
        description: addressLine3 of the Details model
        type: string
        maxLength: 105
      addressLine4:
        description: addressLine4 of the Details model
        type: string
        maxLength: 105
      city:
        description: city of the Details model
        type: string
        maxLength: 22
      state:
        description: state of the Details model
        type: string
        maxLength: 22
      country:
        description: country of the Details model
        type: string
        maxLength: 3
      constructionCostCurrency:
        description: construction cost currency of the Details model
        type: string
        maxLength: 3
      zipCode:
        description: zipCode of the Details model
        type: string
        maxLength: 8
      unit:
        description: unit of the Details model
        type: string
        maxLength: 20
      lessor:
        description: lessor of the Details model
        type: string
        maxLength: 105
      regulatorApproval:
        description: regulatorApproval of the Details model
        $ref: '../../commondefinitions.yaml#/definitions/RegulatorApproval'
      specialZone:
        description: specialZone of the Details model
        $ref: '../../commondefinitions.yaml#/definitions/SpecialZoneType'
      thirdPartyName:
        description: thirdPartyName of the Details model
        type: string
        maxLength: 50
      thirdPartyLocation:
        description: thirdPartyLocation of the Details model
        type: string
        maxLength: 50
      propertyTitleHolder:
        description: propertyTitleHolder of the Details model
        $ref: '../../commondefinitions.yaml#/definitions/PropertyHoldingType'
      constructionStartDate:
        description: constructionStartDate of the Details model
        type: string
      expectedEndDate:
        description: expectedEndDate of the Details model
        type: string     
      leaseEffectiveDate:
        description: leaseEffectiveDate of the Details model
        type: string    
      leaseExpiryDate:
        description: leaseExpiryDate of the Details model
        type: string
      totalConstructionArea:
        description: totalConstructionArea of the Details model
        type: "integer"
        format: "int64"
      constructionCost:
        description: constructionCost of the Details model
        type: "integer"
        format: "int64"    
      commercialRegulatorDetails:
        type: array
        items:
          $ref: '#/definitions/CommercialRegulatorDetailsModel'
      commercialSpecialZoneDetails:
        type: array
        items:
          $ref: '#/definitions/CommercialSpecialZoneDetailsModel'
      commercialSupplierDetails:
        type: array
        items:
          $ref: '#/definitions/CommercialSupplierDetailsModel'
      commercialDocumentDetails:
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  CommercialRegulatorDetailsModel:
    description: CommercialRegulatorDetails model
    type: object
    properties:
      id:
        description: Id of the CommercialRegulatorDetails
        type: string
        maxLength: 36
      regulatingAuthority:
        description: regulatingAuthority of the CommercialRegulatorDetailsModel
        type: string
        maxLength: 50
      authorityDescription:
        description: authorityDescription of the CommercialRegulatorDetailsModel
        type: string
        maxLength: 105
      commercialPropertyId:
        description: commercialPropertyId of CommercialRegulatorDetailsModel
        type: string
        maxLength: 36
  CommercialSpecialZoneDetailsModel:
    description: CommercialSpecialZoneDetails model
    type: object
    properties:
      id:
        description: Id of the CommercialSpecialZoneDetails
        type: string
        maxLength: 36
      zoneType:
        description: zoneType of the CommercialSpecialZoneDetails
        type: string
        maxLength: 50
      zoneDescription:
        description: zoneDescription of the CommercialSpecialZoneDetails
        type: string
        maxLength: 105
      commercialPropertyId:
        description: commercialPropertyId of CommercialSpecialZoneDetails
        type: string
        maxLength: 36
  CommercialSupplierDetailsModel:
    description: CommercialSupplierDetailsModel model
    type: object
    properties:
      id:
        description: Id of the CommercialSupplierDetailsModel
        type: string
        maxLength: 36
      supplierName:
        description: supplierName of the CommercialSupplierDetailsModel
        type: string
        maxLength: 36
      supplierLocation:
        description: supplierLocation of the CommercialSupplierDetailsModel
        type: string
        maxLength: 105
      commercialPropertyId:
        description: commercialPropertyId of CommercialSupplierDetailsModel
        type: string
        maxLength: 36
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type