#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
swagger: '2.0'
info:
  description: This is a sample server Sweep Reallocation server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: SweepReallocation
host: api-plato.us.oracle.com:8080
basePath: /api/1.0
consumes:
- application/json
- application/xml
produces:
- application/json
- application/xml
tags:
- name: SweepReallocationAPI
  description: API for Sweep Reallocation Operations
schemes:
- https
paths:
  /sweepRealloc:
    get:
      tags:
      - sweepRealloc
      summary: Get all valid sweepRealloc data.
      description: Get all valid sweepRealloc data. This endpoints will be used to Get all valid sweepRealloc maintenance records.
      operationId: fetchReallocationLog
      parameters:
      - name: offset
        in: query
        description: offset is starting no of records to be fetched
        required: false
        type: integer
      - name: limit
        in: query
        description: limit is maximum no of records to be fetched
        required: false
        type: integer
      - name: bookDateFrom
        in: query
        required: false
        type: string
      - name: bookDateTo
        in: query 
        required: false
        type: string
      - name: valueDateFrom
        in: query
        required: false
        type: string
      - name: valueDateTo
        in: query
        required: false
        type: string 
      - name: customerId
        in: query
        required: false
        type: string
      - name: structureId
        in: query
        required: false
        type: string
      - name: filterBy
        in: query
        required: false
        type: string
      responses:
        201:
          description: Returns message of succes or failure
          headers:
            Location:
              description: ''
              type: string
          schema:
            $ref: '#/definitions/LmsTbSweepReallocLogCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error

definitions:
  LmsTbSweepReallocLogDTO:
    type: object
    allOf:
    - $ref: '#/definitions/GenericDto'
    - type: object
      properties:
        amount:
          type: number
          description: ''
        balanceTimestamp:
          type: string
          description: ''
        customerId:
          type: string
          description: ''
        executionId:
          type: string
          description: ''
        sweepId:
          type: string
          description: ''
        extTransactionNo:
          type: string
          description: ''
        fromAccountBalance:
          type: number
          description: ''
        fromAccountNumber:
          type: string
          description: ''
        fromAccPostBal:
          type: number
          description: ''
        fromAmount:
          type: number
          description: ''
        fromBicCode:
          type: string
          description: ''
        fromBranchCode:
          type: string
          description: ''
        fromCurrencyCode:
          type: string
          description: ''
        fxRate:
          type: number
          description: ''
        instructionId:
          type: string
          description: ''
        isTwoway:
          type: string
          description: ''
        logTime:
          type: string
          description: ''
        status:
          type: string
          description: ''
        statusMessage:
          type: string
          description: ''
        structureId:
          type: string
          description: ''
        sweepMode:
          type: string
          description: ''
        sweepProduct:
          type: string
          description: ''
        toAccountBalance:
          type: number
          description: ''
        toAccountNumber:
          type: string
          description: ''
        toAccPostBal:
          type: number
          description: ''
        toAmount:
          type: number
          description: ''
        toBicCode:
          type: string
          description: ''
        toBranchCode:
          type: string
          description: ''
        toCurrencyCode:
          type: string
          description: ''
        valueDate:
          type: string
          description: ''
        fromExtAccno:
         type: string
         description: ''
        fromIBanForAccno:
         type: string
         description: ''
        fromAccnoDesc:
         type: string
         description: ''
        fromExtBranchRef:
         type: string
         description: ''
        fromAccBranchAdddr1:
         type: string
         description: ''
        fromAccBranchAdddr2:
         type: string
         description: ''
        fromAccBranchAdddr3:
         type: string
         description: ''
        fromAccBranchAdddr4:
         type: string
         description: ''
        fromAccBranchAdddr5:
         type: string
         description: ''
        toExtAccno:
         type: string
         description: ''
        toIBanForAccno:
         type: string
         description: ''
        toAccnoDesc:
         type: string
         description: ''
        toExtBranchRef:
         type: string
         description: ''
        toAccBranchAdddr1:
         type: string
         description: ''
        toAccBranchAdddr2:
         type: string
         description: ''
        toAccBranchAdddr3:
         type: string
         description: ''
        toAccBranchAdddr4:
         type: string
         description: ''
        toAccBranchAdddr5:
         type: string
         description: ''
        versionNo:
         type: number
         description: ''
        customerExtRef:
         type: string
         description: ''
        customerName:
         type: string
         description: ''
        headerBranch:
         type: string
         description: ''
        headerBranchExtRef:
         type: string
         description: ''
        balanceTimeStamp:
         type: string
         format: date
         description: '' 
        childExtAcc:
         type: boolean
         description: ''
        interfaceMasterId:
         type: string
         description: ''  
        structureMasterId:
         type: string
         description: ''
        sweepLogID:
         type: string
         description: ''
        toCountryCode:
         type: string
         description: ''
        fromCountryCode:
         type: string
         description: ''
        fromHostCode:
         type: string
         description: ''
        toHostCode:
         type: string
         description: ''
        headerHostCode:
         type: string
         description: ''
        isSimulate:
         type: string
         description: ''
        user:
         type: string
         description: ''
        paramName:
         type: string
         description: ''
         
  ResponseDto:
    type: object
    properties:
      id:
        type: string
      status:
        type: string
      codes:
        type: array
        items:
          $ref: '#/definitions/ResponseCode'
      requestId:
        type: string
  ResponseCode:
    type: object
    properties:
      Code:
        type: string
      Desc:
        type: string
      Type:
        type: string
      Language:
        type: string
      args:
        type: array
        items:
          type: object
      arg:
        type: string
  GenericDto:
    allOf:
    - type: object
      discriminator: resource_type
  LmsTbSweepReallocLogCollection:
    description: Collection of sweeplog.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/LmsTbSweepReallocLogDTO'
      paging:
        $ref: '#/definitions/PagingDto'
  PagingDto:
    type: object
    properties:
      totalResults:
        type: integer
  ResponseDtoWrapper:
    type: object
    properties:
      messages:
        $ref: '#/definitions/ResponseDto'
      data:
        $ref: '#/definitions/ResponseResourceSupport'
  ResponseResourceSupport:
    type: object         