#  * ******************************************************************************
#  *  * This source is part of the Oracle Banking Software Product.
#  *  * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
#  *  *
#  *  * No part of this work may be reproduced, stored in a retrieval system, adopted
#  *  * or transmitted in any form or by any means, electronic, mechanical, photographic,
#  *  * graphic, optic recording or otherwise, translated in any language or computer
#  *  * language, without the prior written permission of Oracle and/or its affiliates.
#  *  *
#  *  * Oracle Financial Services Software Limited.
#  *  * Oracle Park, Off Western Express Highway,
#  *  * Goregaon (East),
#  *  * Mumbai - 400 063, India.
#  *  *****************************************************************************
swagger: '2.0'
info:
  description: This is a sample server Sweep server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: ReverseSweepService
host: api-plato.us.oracle.com:8080
basePath: /api/1.0
consumes:
- application/json
- application/xml
produces:
- application/json
- application/xml
tags:
- name: ReverseSweepServiceAPI
  description: API for Reverse Sweep Service Operations
schemes:
- https
paths:
  /reversesweepservice/accpairasync:
    post:
      tags:
      - reversesweepaccpairservice
      summary: Run reverse sweep service for accounts.
      description: Run  sweep service for accounts.
      operationId: executeReverseAccountPairSweepAsync
      parameters:
      - name: SweepStructuresDTO
        in: body
        description: Request Body that contains data required for running a sweep batch
        required: true
        schema:
          $ref: '#/definitions/LmsSweepStructuresDTO'
      responses:
        201:
          description: Returns message of succes or failure
          headers:
            Location:
              description: URL of newly created sweepmaster data
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /reversesweepservice/accpair:
    post:
      tags:
      - sweepaccpairservice
      summary: Run sweep service for a structure.
      description: Run  sweep service for a acount pair.
      operationId: executeAccountPairReverseSweep
      parameters:
      - name: SweepStructuresDTO
        in: body
        description: Request Body that contains data required for running a sweep batch
        required: true
        schema:
          $ref: '#/definitions/LmsSweepStructuresDTO'
      responses:
        201:
          description: Returns message of succes or failure
          headers:
            Location:
              description: URL of newly created sweepmaster data
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error  
  /reversesweepservice/structure:
    post:
      tags:
      - reversesweepservice
      summary: Run reverse sweep service for a structure.
      description: Run reverse sweep service for a structure.
      operationId: executeRevSweepStructure
      parameters:
      - name: sweepStructureDTO
        in: body
        description: Request Body that contains data required for running a reverse sweep batch
        required: true
        schema:
          $ref: '#/definitions/LmsSweepStructuresDTO'
      responses:
        201:
          description: Returns message of succes or failure
          headers:
            Location:
              description: URL of newly created sweepmaster data
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /reversesweepservice/structureasync:
    post:
      tags:
      - reversesweepservice
      summary: Run reverse sweep service for a structure.
      description: Run reverse sweep service for a structure.
      operationId: executeRevSweepStrAsync
      parameters:
      - name: sweepStructureDTO
        in: body
        description: Request Body that contains data required for running a reverse sweep batch
        required: true
        schema:
          $ref: '#/definitions/LmsSweepStructuresDTO'
      responses:
        201:
          description: Returns message of succes or failure
          headers:
            Location:
              description: URL of newly created sweepmaster data
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error        
#  /reversesweepservice/settlement/accpair:
#    post:
#      tags:
#      - reversesweepaccpairservice
#      summary: Run reverse sweep for loan settlement
#      description: Run reverse sweep for loan settlement.
#      operationId: executeSettlementReverseSweep
#      parameters:
#      - name: SweepStructuresDTO
#        in: body
#        description: Request Body that contains data required for running a sweep batch
#        required: true
#        schema:
#          $ref: '#/definitions/LmsSettlementSweepStructuresDTO'
#      responses:
#        201:
#          description: Returns message of succes or failure
#          headers:
#            Location:
#              description: URL of newly created sweepmaster data
#              type: string
#          schema:
#            $ref: '#/definitions/ResponseDtoWrapper'
#        400:
#          description: Malformed syntax.
#        401:
#          description: Request does not have sufficient credentials.
#        403:
#          description: Request is not authorized.
#        405:
#          description: Invalid input
#        500:
#          description: Internal error

definitions:
 LmsTbReverseSweepContributionDetailDTO:
  type: object
  properties:
   id:
    type: string
    description: ""
   reverseSweepId:
    type: string
    description: ""
   reverseSweepLogId:
    type: string
    description: ""
   sweepId:
    type: string
    description: ""
   sweepLogId:
    type: string
    description: ""

# LmsReverseSweepStructuresDTO:
#  type: object
#  allOf:
#  - type: object
#    properties:
#     customerId:
#      type: string
#      description: ''
#     mode:
#      type: string
#      description: ''
#     overRidePending:
#      type: string
#      description: ''
#     branchCode:
#      type: string
#      description: ''
#     jobschedulerId:
#      type: string
#      description: ''
#     allowMBCCAccPair:
#      type: string
#      description: ''
#     simulate:
#      type: string
#      description: ''
#     adhocId:
#      type: string
#      description: ''
#     remarks:
#      type: string
#      description: ''  
#     allStructure:
#      type: string
#      description: ''
#     structureList:
#      type: array
#      items:
#       $ref: '#/definitions/ReverseSweepStructureListDTO'  
#     branchMap:
#      $ref: "#/definitions/BranchMap" 
#      
# ReverseSweepStructureListDTO:
#  type: object
#  properties:
#   structureId:
#    type: string
#   versionNo:
#    type: integer
#   accountList:
#    type: array
#    items:
#     $ref: '#/definitions/LmsReverseSweepAccountDTO'
#     
# LmsReverseSweepAccountDTO:
#  type: object
#  properties:
#   id:
#    type: string
#    description: ''
#   structureMasterId:
#    type: string
#    description: ''
#   accountNumber:
#    type: string
#    description: ''
#   branchCode:
#    type: string
#    description: ''
#   batchDataId:
#    type: string
#    description: ''
#   accountCurrency:
#    type: string
#    description: ''         
#   instructionId:
#    type: string
#    description: ''
#   frequencyId:
#    type: string
#    description: ''      
#   fromDate:
#    description: "starting Date"
#    type: string
#   toDate:
#    description: "ending Date"
#    type: string
#   extTransactionNo:
#    description: "Sweep Log ID"
#    type: string