#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : preferredinstitutions.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/preferredbank:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PreferredBanks
      summary: Adds a new Preferred Bank.
      description: Adds a new PreferredBank. Add additional information here for this endpoint.
      operationId: createPreferredBank
      parameters:
      - name: PreferredBank
        in: body
        description: Request Body that contains data required for creating a new PreferredBank
        required: true
        schema:
          $ref: '#/definitions/PreferredBankModel'
      responses:
        201:
          description: Returns the Id of the newly created PreferredBank
          headers:
            Location:
              description: URL of newly created PreferredBank
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PreferredBanks
      summary: Retrieves the list of existing PreferredBank.
      description: Retrieves the list of existing PreferredBank. Add additional information here for the this endpoint.
      operationId: getAllPreferredBanks
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/preferredbank/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PreferredBanks
      summary: Retrieves the PreferredBank by id.
      description: Retrieves the PreferredBank by id. Add additional information here for the this endpoint.
      operationId: getPreferredBankById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the PreferredBanks based on given applicationNumber.
          schema:
            $ref: '#/definitions/PreferredBankModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PreferredBanks
      summary: Update an existing PreferredBank.
      description: Update an existing PreferredBank. Add additional information here for the this endpoint.
      operationId: updatePreferredBanks
      parameters:
      - name: id
        in: path
        description: id of the PreferredBanks that need to be updated
        required: true
        type: string
      - name: PreferredBanks
        in: body
        description: Request Body that contains data required for updating an existing PreferredBanks
        required: true
        schema:
          $ref: '#/definitions/PreferredBankModel'
      responses:
        200:
          description: Returns updated PreferredBanks
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - PreferredBanks
      summary: Deletes the PreferredBank identified by given ID.
      description: Deletes the PreferredBank identified by given ID. Add additional information here for the this endpoint.
      operationId: deletePreferredBanks
      parameters:
      - name: id
        in: path
        description: Id of the PreferredBank that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  PreferredBankModel:
    description: PreferredBank model
    type: object
    properties:
      id:
        description: Id of the PreferredBank
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the PreferredBank
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
        maxLength: 300
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      preferredBankDetails:
        type: array
        items:
          $ref: '#/definitions/PreferredBankDetailsModel'
  PreferredBankDetailsModel:
    description: PreferredBankDetails model
    type: object
    required:
    - bankName
    - bankLocation
    - bankRole
    properties:
      id:
        description: Id of the disbursementdetail
        type: string
      preferredBankId:
        description: Id of the Preferred Bank Master
        type: string
      bankName:
        description: bankName
        type: string
        maxLength: 36
      bankLocation:
        description: bankLocation
        type: string
        maxLength: 105
      bankRole:
        description: bankRole
        type: string
        maxLength: 50
      preferredBank:
        description: preferredBank
        type: boolean
  PreferredBanksCollection:
    description: Collection of PreferredBanks.
    type: object
    properties:
      PreferredBankList:
        type: array
        items:
          $ref: '#/definitions/PreferredBankModel'
