#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ${enityName}.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: obcmtmcorpenrchdlvrymstr
host: 10.184.157.121:9000
basePath: /obcmtmcorpenrchdlvrymstr
tags:
- name: obcmtmcorpenrchdlvrymstr
  description: API for obcmtmcorpenrchdlvrymstr Operations
schemes:
- http
paths:
  /web/v1/obcmtmcorpenrchdlvrymstr:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ObcmTmCorpEnrchDlvryMstr
      summary: Adds a new ObcmTmCorpEnrchDlvryMstr.
      description: Adds a new ObcmTmCorpEnrchDlvryMstr. Add additional information here for this endpoint.
      operationId: addObcmTmCorpEnrchDlvryMstr
      parameters:
      - name: ObcmTmCorpEnrchDlvryMstr
        in: body
        description: Request Body that contains data required for creating a new ObcmTmCorpEnrchDlvryMstr
        required: true
        schema:
          $ref: '#/definitions/ObcmTmCorpEnrchDlvryMstrDTO'
      responses:
        201:
          description: Returns the Id of the newly created ObcmTmCorpEnrchDlvryMstr
          headers:
            Location:
              description: URL of newly created ObcmTmCorpEnrchDlvryMstr
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ObcmTmCorpEnrchDlvryMstrDTO:
    description: ObcmTmCorpEnrchDlvryMstr model
    type: object
    allOf:
    - $ref: '#/definitions/BaseGenericModelDS'
    - type: object
      properties:
       id:
        type: string
        description: "Id"
       action:
        type: string
        description: "Action"
       autoAuth:
        type: string
        description: "Auto Auth"
       modificationStatus:
        type: string
        description: "Modification Status"   
       datasegmentCode:
        type: string
        description: "Datasegment Code"
       checkerRemarks:
        type: string
        description: "checkerRemarks" 
       makerRemarks:
        type: string
        description: "makerRemarks"
       enrichmentId:
        description: enrichmentId
        type: string
       txnControllerRefNo:
        type: string
        description: "Transaction Controller Reference Number" 
       obcmTmCorpEnrchDlvryDtls:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchDlvryDtlsDTO'
  BaseGenericModelDS:
   allOf:
    - type: object
      discriminator: resource_type

  ObcmTmCorpEnrchDlvryDtlsDTO:
    description: ObcmTmCorpEnrchDlvryDtls model
    type: object
    properties:
      id:
        description: Id of the ObcmTmCorpEnrchDlvryDtls
        type: string
      addln1:
        description: addln1
        type: string
      addln2:
        description: addln2
        type: string
      addln3:
        description: addln3
        type: string
      addln4:
        description: addln4
        type: string
      agrmntDate:
        description: agrmntDate
        type: string
        format: date
      cntctPerson:
        description: cntctPerson
        type: string
      cntryCode:
        description: cntryCode
        type: string
      cntryName:
        description: cntryName
        type: string
      courierCode:
        description: courierCode
        type: string
      courierCodeDesc:
        description: courierCodeDesc
        type: string
      dayOfWeek:
        description: dayOfWeek
        type: string
      dlvryCode:
        description: dlvryCode
        type: string
      dlvryDesc:
        description: dlvryDesc
        type: string
      dlvryMstrId:
        description: dlvryMstrId
        type: string
      dlvryOnHldys:
        description: dlvryOnHldys
        type: string
      dlvrySlot:
        description: dlvrySlot
        type: string
      dlvryType:
        description: dlvryType
        type: string
      fax:
        description: fax
        type: number
      freq:
        description: freq
        type: string
      locationCode:
        description: locationCode
        type: string
      locationDesc:
        description: locationDesc
        type: string
      postalCode:
        description: postalCode
        type: number
      prEmailId:
        description: prEmailId
        type: string
      prPhoneNo:
        description: prPhoneNo
        type: number
      scEmailId:
        description: scEmailId
        type: string
      scPhoneNo:
        description: scPhoneNo
        type: number
      obcmTmCorpEnrchDlvryMstr:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchDlvryMstrDTO'
  ObcmTmCorpEnrchDlvryMstrCollection:
    description: Collection of ObcmTmCorpEnrchDlvryMstr.
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ObcmTmCorpEnrchDlvryMstrDTO'
      paging:
       $ref: "#/definitions/PagingDto"
  PagingDto:
   type: object
   properties:
    totalResults:
     type: integer
  status:
   type: "string"
   description: "Status Enum specifying the type of Request. ACTIVE - (CREATE/MODIFY) and DELETE"
  ObcmTmCorpEnrchDeliveryDetailsDTO:
   type: "object"
   allOf:
   - $ref: '#/definitions/ObcmTmCorpEnrchDlvryDetailsDTO'
   - type: "object"
   properties:
     status:
      $ref: '#/definitions/status'
  ObcmTmCorpEnrchDlvryDetailsDTO:
    type: "object"
    description: "Corporate Enrichment Delivery Details Data"
    properties:
       addln1:
        type: "string"
        description: "Address Line 1 used for corporate enrichment delivery details data"
       addln2:
        type: "string"
        description: "Address Line 2 used for corporate enrichment delivery details data"
       addln3:
        type: "string"
        description: "Address Line 3 used for corporate enrichment delivery details data"
       addln4:
        type: "string"
        description: "Address Line 4 used for corporate enrichment delivery details data"
       agrmntDate:
        type: "string"
        description: "Arragment used for corporate enrichment delivery details data"
       cntctPerson:
        type: "string"
        description: "Contact Person used for corporate enrichment delivery details data"
       cntryCode:
        type: "string"
        description: "Country Code used for corporate enrichment delivery details data"
       cntryName:
        type: "string"
        description: "Country name used for corporate enrichment delivery details data"
       courierCode:
        type: "string"
        description: "CourierCode used for corporate enrichment delivery details data"
       courierCodeDesc:
        type: "string"
        description: "CourierCodeDesc used for corporate enrichment delivery details data"
       dayOfWeek:
        type: "string"
        description: "DayOfWeek used for corporate enrichment delivery details data"
       dlvryCode:
        type: "string"
        description: "Delivery Code used for corporate enrichment delivery details data"
       dlvryDesc:
        type: "string"
        description: "Delivery Desc used for corporate enrichment delivery details data"
       dlvryOnHldys:
        type: "string"
        description: "DeliveryOnHldys used for corporate enrichment delivery details data"
       dlvrySlot:
        type: "string"
        description: "Delivery Slot used for corporate enrichment delivery details data"
       dlvryType:
        type: "string"
        description: "Delivery Type used for corporate enrichment delivery details data"
       fax:
        type: "number"
        description: "Faxx number used for corporate enrichment delivery details data"
       freq:
        type: "string"
        description: "Frequency used for corporate enrichment delivery details data"
       locationCode:
        type: "string"
        description: "LocationCode used for corporate enrichment delivery details data"
       locationDesc:
        type: "string"
        description: "LocationDesc used for corporate enrichment delivery details data"
       postalCode:
        type: "number"
        description: "PostalCode used for corporate enrichment delivery details data"
       prEmailId:
        type: "string"
        description: "Pre EmailId used for corporate enrichment delivery details data"
       prPhoneNo:
        type: "number"
        description: "Pre PhoneNo used for corporate enrichment delivery details data"
       scEmailId:
        type: "string"
        description: "Source EmailId used for corporate enrichment delivery details data"
       scPhoneNo:
        type: "number"
        description: "Source PhoneNo used for corporate enrichment delivery details data"
  ObcmTmCorpEnrchDlvryDTO:
    type: object
    properties:
       corporateId:
        type: string
        description: "Corporate Id"
       locationCode:
        type: string
        description: "Available location code"
       dlvryCode:
        type: string
        description: "Dlvry code mapped to corporate or location code will be returned"
       dlvryDesc:
        type: string
        description: "Name of the pick up point"
       cntctPerson:
        type: string
        description: "Name of the contact person"
       dlvryType:
        type: string
        description: "Constant value Adhoc / on call"
       courierCode:
        type: string
        description: "List of existing courier codes can be fetched from back office"
       addln1:
        type: string
        description: "Address line 1"
       addln2:
        type: string
        description: "Address line 2"
       addln3:
        type: string
        description: "Address line 3"
       addln4:
        type: string
        description: "Address line 4"
       cntryCode:
        type: string
        description: "Country Code of Dlvry point"
       cntryName:
        type: string
        description: "Country Name of Dlvry point"
       postalCode:
        type: number
        description: "Postal code of Dlvry point"
       prPhoneNo:
        type: number
        description: "Primary number of contact"
       prEmailId:
        type: string
        description: "Email of contact"
       authStatus:
        type: string
        description: "A or U"
       modNo:
        type: integer
        description: "Modification number of record"
       agrmntDate:
        type: string
        format: date
        description: ""
       courierCodeDesc:
        type: string
        description: ""
       dayOfWeek:
        type: string
        description: ""
       fax:
        type: number
        description: ""
       freq:
        type: string
        description: ""
       id:
        type: string
        description: ""
       locationDesc:
        type: string
        description: ""
       dlvryMstrId:
        type: string
        description: ""
       dlvryOnHldys:
        type: string
        description: ""
       dlvrySlot:
        type: string
        description: ""
       scEmailId:
        type: string
        description: ""
       scPhoneNo:
        type: number
        description: ""
  ObcmTmCorpEnrchDlvryDTOCollection: 
    description: "Collection of corpenrchdlvrydetails."
    type: "object"
    properties:
     data:
      type: "array"
      items: 
       type: object