#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : initialanalysis.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/initialanalysis:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InitialAnalysis
      summary: Adds a new InitialAnalysis.
      description: Adds a new InitialAnalysis. Add additional information here for this endpoint.
      operationId: addInitialAnalysis
      parameters:
      - name: InitialAnalysis
        in: body
        description: Request Body that contains data required for creating a new InitialAnalysis
        required: true
        schema:
          $ref: '#/definitions/InitialAnalysisModel'
      responses:
        201:
          description: Returns the Id of the newly created InitialAnalysis
          headers:
            Location:
              description: URL of newly created InitialAnalysis
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InitialAnalysis
      summary: Retrieves the list of existing InitialAnalysis.
      description: Retrieves the list of existing InitialAnalysis. Add additional information here for the this endpoint.
      operationId: getAllInitialAnalysis
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/initialanalysis/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InitialAnalysis
      summary: Retrieves the InitialAnalysis by id.
      description: Retrieves the InitialAnalysis by id. Add additional information here for the this endpoint.
      operationId: getInitialAnalysisById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the InitialAnalysis based on given applicationNumber.
          schema:
            $ref: '#/definitions/InitialAnalysisModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InitialAnalysis
      summary: Update an existing InitialAnalysis.
      description: Update an existing InitialAnalysis. Add additional information here for the this endpoint.
      operationId: updateInitialAnalysis
      parameters:
      - name: id
        in: path
        description: id of the InitialAnalysis that need to be updated
        required: true
        type: string
      - name: InitialAnalysis
        in: body
        description: Request Body that contains data required for updating an existing InitialAnalysis
        required: true
        schema:
          $ref: '#/definitions/InitialAnalysisModel'
      responses:
        200:
          description: Returns updated InitialAnalysis
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - InitialAnalysis
      summary: Deletes the InitialAnalysis identified by given ID.
      description: Deletes the InitialAnalysis identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteInitialAnalysis
      parameters:
      - name: id
        in: path
        description: Id of the InitialAnalysis that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  InitialAnalysisModel:
    description: InitialAnalysis model
    type: object
    properties:
      id:
        description: Id of the InitialAnalysis
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      remarks:
        description: remarks
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      creditAppRefNo:
        description: creditAppRefNo
        type: string
      initialAnalysisDetails:
        type: array
        items:
          $ref: '#/definitions/InitialAnalysisDetailsModel'
  InitialAnalysisDetailsModel:
    description: InitialAnalysisDetails model
    type: object
    properties:
      id:
        description: Id of the InitialAnalysisDetails
        type: string
      initialAnalysisId:
        description: initialAnalysisId
        type: string
      facilityType:
        description: Facility Type
        type: string
        maxLength: 20
      expectedFacilityAmount:
        description: Amount
        type: number
      initialAnalysisStatus:
        description: Analysis Status
        type: string
        maxLength: 20
      eligibleFacilityAmount:
        description: Eligibility
        type: number
      differenceFacilityAmount:
        description: Max No of Loans
        type: number
      facilityCurrency:
        description: Currency
        type: string
  InitialAnalysisCollection:
    description: Collection of InitialAnalysis.
    type: object
    properties:
      InitialAnalysisList:
        type: array
        items:
          $ref: '#/definitions/InitialAnalysisModel'
