#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : draftproposal.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/draftproposals:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Adds a new  Draft Proposal.
      description: Adds a new  Draft Proposal. Add additional information here for this endpoint.
      operationId: addDraftProposal
      parameters:
      - name: Draft Proposal
        in: body
        description: Request Body that contains data required for creating a new  Draft Proposal
        required: true
        schema:
          $ref: '#/definitions/DraftProposalModel'
      responses:
        201:
          description: Returns the Id of the newly created  Draft Proposal
          headers:
            Location:
              description: URL of newly created  Draft Proposal
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Retrieves the list of existing  Draft Proposal.
      description: Retrieves the list of existing  Draft Proposal. Add additional information here for the this endpoint.
      operationId: getAllDraftProposal
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/draftproposals/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Retrieves the  Draft Proposal by id.
      description: Retrieves the  Draft Proposal by id. Add additional information here for the this endpoint.
      operationId: getDraftProposalById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DraftProposal based on given applicationNumber.
          schema:
            $ref: '#/definitions/DraftProposalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Update an existing  Draft Proposal.
      description: Update an existing  Draft Proposal. Add additional information here for the this endpoint.
      operationId: updateDraftProposal
      parameters:
      - name: id
        in: path
        description: id of the DraftProposal that need to be updated
        required: true
        type: string
      - name: DraftProposal
        in: body
        description: Request Body that contains data required for updating an existing DraftProposal
        required: true
        schema:
          $ref: '#/definitions/DraftProposalModel'
      responses:
        200:
          description: Returns updated DraftProposal
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Deletes the  Draft Proposal identified by given ID.
      description: Deletes the  Draft Proposal identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteDraftProposal
      parameters:
      - name: id
        in: path
        description: Id of the  Draft Proposal that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/draftproposals/proposalNumberLOV:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DraftProposal
      summary: Retrieves the  LOV of Proposal Numbers.
      description: Retrieves the  LOV of Proposal Numbers.
      operationId: getListOfProposalNumbers
      parameters:
      - name: customerName
        in: query
        description: Retrieves the  LOV of Proposal Numbers
        required: false
        type: string
      - name: customerRMName
        in: query
        description: Retrieves the  LOV of Proposal Numbers
        required: false
        type: string
      - name: proposalNumber
        in: query
        description: Retrieves the  LOV of Proposal Numbers
        required: false
        type: string
      responses:
        200:
          description: Returns the List of Proposal Numbers.
          type: string
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  DraftProposalModel:
   description: Draft Proposal model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     required:
     - loanCurrency
     - loanTenor
     - rateType
     properties:
      loanCurrency:
        description: loanCurrency
        type: string
        maxLength: 3
      loanTenor:
        description: loanTenor
        type: string
        maxLength: 20
      rate:
        description: rate
        type: integer
        format: int64
      rateMax:
        description: rateMax
        type: integer
        format: int64
      rateMin:
        description: rateMin
        type: integer
        format: int64
      marginRate:
        description: marginRate
        type: integer
        format: int64
      marginRateMin:
        description: marginRateMin
        type: integer
        format: int64
      marginRateMax:
        description: marginRateMax
        type: integer
        format: int64
      feeRate:
        description: feeRate
        type: integer
        format: int64
      feeRateMin:
        description: feeRateMin
        type: integer
        format: int64
      feeRateMax:
        description: feeRateMax
        type: integer
        format: int64
      feeAmount:
        description: feeAmount
        type: number
        minimum: 0
      feeAmountMin:
        description: feeAmountMin
        type: number
        minimum: 0
      feeAmountMax:
        description: feeAmountMax
        type: number
        minimum: 0
      proposedLoanAmount:
        description: proposedLoanAmount
        type: number
        minimum: 0
      proposedLoanAmountMax:
        description: proposedLoanAmountMax
        type: number
        minimum: 0
      proposedLoanAmountMin:
        description: proposedLoanAmountMin
        type: number
        minimum: 0
      noOfProposalDays:
        description: noOfProposalDays
        type: integer
      rateType:
        description: rateType
        type: string
        maxLength: 20
      remarks:
        description: remarks
        type: string
        maxLength: 300
      amortiseFreq:
        description: amortiseFreq
        type: string
        maxLength: 20
      interestPaymentFreq:
        description: interestPaymentFreq
        type: string
        maxLength: 20
      schedulePrincipal:
        description: schedulePrincipal
        type: string
        maxLength: 20
      fee:
        description: fee
        type: string
        maxLength: 20
      bullet:
        description: bullet
        type: string
      collateralType:
        description: fee
        type: string
      feeType:
        description: feeType
        type: string
        minLength: 0
        maxLength: 1
      feeAmountCurrency:
        description: feeAmountCurrency
        type: string
        minLength: 0
        maxLength: 3
      collateralAmount:
        description: collateralAmount
        type: number
        minimum: 0
      collateralloanCurrency:
        description: collateralloanCurrency
        type: string
        maxLength: 3
      costOfFund:
        description: costOfFund
        type: string
      collateralList:
        description: collateralList
        type: string      
      collateralAmountMin:
        description: collateralAmountMin
        type: number
        minimum: 0
      collateralAmountMax:
        description: collateralAmountMax
        type: number
        minimum: 0
      draftProposalDocument:
        description: draftProposalDocument of the draftProposal
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
            
  DraftProposalCollection:
    description: Collection of Draft proposal.
    type: object
    properties:
      CustomerAcceptanceList:
        type: array
        items:
          $ref: '#/definitions/DraftProposalModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type