#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : facilitydetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/facilitydetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityDetails
      summary: Adds a new FacilityDetails.
      description: Adds a new FacilityDetails. Add additional information here for this endpoint.
      operationId: addFacilityDetails
      parameters:
      - name: FacilityDetails
        in: body
        description: Request Body that contains data required for creating a new FacilityDetails
        required: true
        schema:
          $ref: '#/definitions/FacilityDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created FacilityDetails
          headers:
            Location:
              description: URL of newly created FacilityDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityDetails
      summary: Retrieves the list of  FacilityDetails.
      description: Retrieves the list of  FacilityDetails. Add additional information here for the this endpoint.
      operationId: getAllFacilityDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/facilitydetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityDetails
      summary: Get a  FacilityDetails.
      description: Update a  FacilityDetails. Add additional information here for the this endpoint.
      operationId: getFacilityDetailsById
      parameters:
      - name: id
        in: path
        description: id of the FacilityDetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated FacilityDetails
          schema:
            $ref: '#/definitions/FacilityDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityDetails
      summary: Update an  FacilityDetails.
      description: Update an  FacilityDetails. Add additional information here for the this endpoint.
      operationId: updateFacilityDetails
      parameters:
      - name: id
        in: path
        description: id of the FacilityDetails that need to be updated
        required: true
        type: string
      - name: FacilityDetails
        in: body
        description: Request Body that contains data required for updating an  FacilityDetails
        required: true
        schema:
          $ref: '#/definitions/FacilityDetailsModel'
      responses:
        200:
          description: Returns updated FacilityDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - FacilityDetails
      summary: Deletes the A FacilityDetails identified by given ID.
      description: Deletes the FacilityDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteFacilityDetails
      parameters:
      - name: id
        in: path
        description: Id of the FacilityDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FacilityDetailsModel:
    description: FacilityDetails model
    type: object
    properties:
      id:
        description: Id of the FacilityDetails
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the FacilityDetails
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks of the FacilityDetails
        type: string
        maxLength: 300
      facilityProductCode:
        description: Facility Product Code
        type: string 
        maxLength: 30
      facilityStartDate:
        description: facilityStartDate
        type: string
        minLength: 0
        maxLength: 12
      facilityEndDate:
        description: facilityEndDate
        type: string
        minLength: 0
        maxLength: 12
      reportingCurrency:
        description: reportingCurrency
        type: string 
        maxLength: 4
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
  FacilityDetailsCollection:
    description: Collection of FacilityDetails.
    type: object
    properties:
      FacilityDetailsList:
        type: array
        items:
          $ref: '#/definitions/FacilityDetailsModel'      