swagger: "2.0"
info:
  description: "This is a sample server Valuation server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "Scoring Service"
host: "whf00bdm:7801"
basePath: "/scoring-services"
tags:
  - name: "ScoringAPI"
    description: "API for Scoring's Operations"
schemes:
- "http"

paths:
  /service/v1/internalScoring/{customerId}/{applicablePeriod}:
    get:
      produces:
        - "application/json"
        - "application/xml"
      tags:
        - "internalScoring"
      summary: "Retrieves the internal scoring."
      description:  "Retrieves the internal scoring."
      operationId: "getInternalScoring"
      parameters:
        - name: "customerId"
          in: "path"
          description: "Customer Id for which data needs to be fetched"
          required: true
          type: "string"
        - name: "applicablePeriod"
          in: "path"
          description: "Financial Year for which data needs to be fetched"
          required: true
          type: "string"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystem"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystemReferenceNo"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
definitions:
  InlineResponse:
    type: "object"
    description: "Response of the newly created resource"
    properties:
      message:
       type: "string"
  RepresentationModel:
    allOf:
      - type: object
        discriminator: resource_type
  InlineResponse201:
    type: "object"
    description: "Id of the newly created resource"
    properties:
      id:
       type: "string"
  InternalScoringModel:
    allOf:
      - $ref: '#/definitions/RepresentationModel'
      - type: "object"
        properties:
          customerId:
            type: "string"
          assessmentPeriod:
            type: "string"
          internalScore:
            type: "number"