#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : Charges.yaml
#  **
#  ** Module     : obscfcm
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
 
 
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Charges Enquiry Definitions Yaml file"
 
paths:
  /:
    get:
      responses:
        201:
          description: "Returns message of success or failure"
 
definitions:
 ObChargesTxnDTO:
  type: object
  properties:
    allowOverride:
      type: string
      description: "Allow Override"
    allowPrcModify:
      type: string
      description: "Allow Prc Modify"
    allowWaive:
      type: string
      description: "Allow Waive"
    applicationCode:
      type: string
      description: "Application Code"
    autoWaive:
      type: string
      description: "Auto Waive"
    branchCode:
      type: string
      description: "Branch code"
    calcErrorCode:
      type: string
      description: "Calculate Error Code"
    calcFreq:
      type: string
      description: "Calculate Frequency"
    calcRefPeriod:
      type: string
      description: "Calculate Reference Period"
    calcType:
      type: string
      description: "Calculate Type"
    calcUnits:
      type: number
      description: "Calculate Units"
    chargeAmount:
      type: number
      description: "Charge Amount"
    chargeCategory:
      type: string
      description: "Charge Category"
    chargeCode:
      type: string
      description: "Charge Code"
    chargeCodeDesc:
      type: string
      description: "Charge Code Description"
    chargeGroup:
      type: string
      description: "Charge Group"
    chargeType:
      type: string
      description: "Charge Type"
    chgCalcDate:
      type: string
      description: "Charge Calculate Date"
    txnCcy:
      type: string
      description: "Transaction Currency"
    chargeCriteria:
      type: string
      description: "Charge Criteria"
    chargeCriteriaValue:
      type: number
      description: "Charge Criteria Value"
    chgCriteriaCcy:
      type: string
      description: "Charge Criteria Currency"
    chgCriteriaCount:
      type: string
      description: "Charge Criteria Count"
    priceMethodDesc:
      type: string
      description: "Price Method Description"
    priceTemplateId:
      type: string
      description: "Price Template Id"
    chgSharing:
      type: string
      description: "Charge Sharing"
    collectionType:
      type: string
      description: "Collection Type"
    collectionFreq:
      type: string
      description: "Collection Frequency"
    collectionRefPeriod:
      type: string
      description: "Collection Reference Period"
    collectionUnits:
      type: number
      description: "Collection Units"
    parentChargeCode:
      type: string
      description: "Parent Charge Code"
    partyId:
      type: string
      description: "Party Id"
    partyToCharge:
      type: string
      description: "Party To Charge"
    postingErrorCode:
      type: string
      description: "Posting Error Code"
    referenceEndDate:
      type: string
      description: "Reference End Date"
    referenceStartDate:
      type: string
      description: "Reference Start Date"
    referenceEndDateValue:
      type: string
      description: "Reference End Date Value"
    referenceStartDateValue:
      type: string
      description: "Reference Start Date Value"
    txnRefNo:
      type: string
      description: "Transaction Reference Number"
    partyName:
      type: string
      description: "Party name"
    instrumentType:
      type: string
      description: "Instrument Type"
    eventCode:
      type: string
      description: "Event Code"
    exchangeRate:
      type: number
      description: "Exchange Rate"
    firstChgCalcDate:
      type: string
      description: "First Charge Calculation Date"
    nextChgCalcDate:
      type: string
      description: "Next Charge Calculation Date"
    chgCollDate:
      type: string
      description: "Charge Collection Date"
    firstChgCollDate:
      type: string
      description: "First Charge Collection Date"
    nextChgCollDate:
      type: string
      description: "Next Charge Collection Date"
    debitAccNumber:
      type: string
      description: "Debit Account Number"
    creditAccNumber:
      type: string
      description: "Credit Account Number"
    chgSharingPct:
      type: number
      description: "Charge Sharing Pct"
    postingDate:
      type: string
      description: "Posting Date"
    calcStartDate:
      type: string
      description: "Calculate Start Date"
    calcEndDate:
      type: string
      description: "Calculate End Date"
             
 InstrumentTxnDTO:
  type: object
  properties:
   obInvTxnId:
     type: string
     description: "OB Invoice TXN Id"
   txnRefNo:
    type: string
    description: "Transaction Reference Number"
   invoiceRefNo:
    type: string
    description: "Invoice Reference Number"
   invoiceStatus:
    type: string
    description: "Invoice Status"
   invoiceCcy:
    type: string
    description: "Invoice Currency"
   netInvoiceAmt:
    type: number
    description: "Net Invoice Amount"
   acceptanceAmount:
    type: number
    description: "Acceptance Amount"
   buyerId:
    type: string
    description: "Buyer id"
   supplierId:
    type: string
    description: "Supplier Id"
   invoiceDate:
    type: string
    description: "Invoice Date"
   invoiceDueDate:
    type: string
    description: "Invoice Due date"
   buyerName:
    type: string
    description: "Buyer Name"
   supplierName:
    type: string
    description: "Supplier Name"
   programCode:
    type: string
    description: "Program Code"
   relation:
    type: string
    description: "Relation"
   extInvoiceRefNo:
    type: string
    description: "External Invoice Reference Number"
   event:
    type: string
    description: "Event"
   processingDate:
    type: string
    description: "Processing Date"
      
 FinanceTxnDTO:
  type: object
  properties:
   txnRefNo:
    type: string
    description: "Transaction Reference Number"
   buyerId:
    type: string
    description: "Buyer Id"
   buyerName:
    type: string
    description: "Buyer Name"
   supplierId:
    type: string
    description: "Supplier Id"
   supplierName:
    type: string
    description: "Supplier Name"
   financeCcy:
    type: string
    description: "Finance Currency"
   financeAmt:
    type: number
    description: "Finance Amount"
   productCode:
    type: string
    description: "Product Code"
   productCodeDesc:
    type: string
    description: "Product Code Description"
   financeStartDate:
    type: string
    description: "Finance Start Date"
   financeDueDate:
    type: string
    description: "Finance Due Date"
   outdtandingAmt:
    type: number
    description: "Outstanding Amount"
   repaymentAmt:
    type: number
    description: "Repayment Amount"
   programCode:
    type: string
    description: "Program Code"
   eventCode:
    type: string
    description: "Event Code"
   processingDate:
    type: string
    description: "Processing Date"