#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : automotiveinfo.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/automotiveinfo:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AutomotiveInfos
      summary: Adds a new AutomotiveInfo.
      description: Adds a new AutomotiveInfo. Add additional information here for this endpoint.
      operationId: addAutomotiveInfo
      parameters:
      - name: AutomotiveInfoDetails
        in: body
        description: Request Body that contains data required for creating a new AutomotiveInfo
        required: true
        schema:
          $ref: '#/definitions/AutomotiveInfoModel'
      responses:
        201:
          description: Returns the Id of the newly created AutomotiveInfo
          headers:
            Location:
              description: URL of newly created AutomotiveInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AutomotiveInfos
      summary: Retrieves the list of  AutomotiveInfo.
      description: Retrieves the list of  AutomotiveInfo. Add additional information here for the this endpoint.
      operationId: getAllAutomotiveInfos
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/automotiveinfo/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AutomotiveInfos
      summary: Get a  AutomotiveInfo.
      description: Update a  AutomotiveInfo. Add additional information here for the this endpoint.
      operationId: getAutomotiveInfoById
      parameters:
      - name: id
        in: path
        description: id of the AutomotiveInfo that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated AutomotiveInfo
          schema:
            $ref: '#/definitions/AutomotiveInfoModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AutomotiveInfos
      summary: Update an  AutomotiveInfo.
      description: Update an  AutomotiveInfo. Add additional information here for the this endpoint.
      operationId: updateAutomotiveInfo
      parameters:
      - name: id
        in: path
        description: id of the AutomotiveInfo that need to be updated
        required: true
        type: string
      - name: AutomotiveInfoDetails
        in: body
        description: Request Body that contains data required for updating an  AutomotiveInfo
        required: true
        schema:
          $ref: '#/definitions/AutomotiveInfoModel'
      responses:
        200:
          description: Returns updated AutomotiveInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - AutomotiveInfos
      summary: Deletes the AutomotiveInfo identified by given ID.
      description: Deletes the AutomotiveInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAutomotiveInfo
      parameters:
      - name: id
        in: path
        description: Id of the AutomotiveInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  AutomotiveInfoModel:
   description: AutomotiveInfo model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      automotiveInfoDetail:
        description: AutomotiveInfoDetail of the AutomotiveInfo
        type: array
        items:
          $ref: '#/definitions/AutomotiveInfoDetailModel'
  AutomotiveInfoCollection:
    description: Collection of AutomotiveInfoDetails.
    type: object
    properties:
      AutomotiveInfoDetailsList:
        type: array
        items:
          $ref: '#/definitions/AutomotiveInfoModel'
  AutomotiveInfoDetailModel:
    description: AutomotiveInfoDetail model
    type: object
    required:
    - vehicleCategory
    - vehicleStatus
    - manufacturingYear
    - addressLine1
    - country
    - zipCode
    - vehicleMake
    - vehicleModel
    - engineNumber
    - vehicleIdentificationNumber
    - marketValue
    - marketValueCurrencyCode
    - eligibleValue
    - eligibleValueCurrencyCode
    - ownershipStatus
    - registeringAuthority
    - existingCharges
    properties:
      id:
        description: Id of the  AutomotiveInfoDetail
        type: string
        maxLength: 36
      automotiveinfoId:
        description: AutomotiveInfoId of the  AutomotiveInfoDetail
        type: string
        maxLength: 36
      vehicleCategory:
        description: VehicleCategory of the AutomotiveInfoDetails
        type: string
        maxLength: 35
      vehicleStatus:
        description: VehicleStatus of the AutomotiveInfoDetails
        $ref: '../../commondefinitions.yaml#/definitions/VehicleStatus'
      manufacturingYear:
        description: ManufacturingYear of the AutomotiveInfoDetails
        type: string
        maxLength: 4
      addressLine1:
        description: AddressLine1 of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      addressLine2:
        description: AddressLine2 of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      addressLine3:
        description: AddressLine3 of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      city:
        description: City of the AutomotiveInfoDetails
        type: string
        minLength: 0
        maxLength: 22
      state:
        description: State of the AutomotiveInfoDetails
        type: string
        maxLength: 22
      country:
        description: Country of the AutomotiveInfoDetails
        type: string
        maxLength: 3
      zipCode:
        description: ZipCode of the AutomotiveInfoDetails
        type: string
        maxLength: 8
      registrationNumber:
        description: RegistrationNumber of the AutomotiveInfoDetails
        type: number
        minimum: 0
        maxLength: 22
      registrationDate:
        description: RegistrationDate of the AutomotiveInfoDetails
        type: string
      vehicleMake:
        description: VehicleMake of the AutomotiveInfoDetails
        type: string
        maxLength: 20
      vehicleModel:
        description: VehicleModel of the AutomotiveInfoDetails
        type: string
        maxLength: 20
      engineNumber:
        description: EngineNumber of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      vehicleIdentificationNumber:
        description: VehicleIdentificationNumber of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      marketValue:
        description: MarketValue of the AutomotiveInfoDetails
        type: number
        maxLength: 22
        minimum: 0
      marketValueCurrencyCode:
        description: MarketValueCurrencyCode of the AutomotiveInfoDetails
        type: string
        minimum: 0
        maxLength: 4
      eligibleValue:
        description: EligibleValue of the AutomotiveInfoDetails
        type: number
        minimum: 0
        maxLength: 22
      eligibleValueCurrencyCode:
        description: EligibleValueCurrencyCode of the AutomotiveInfoDetails
        type: string
        minimum: 0
        maxLength: 4
      ownershipStatus:
        description: OwnershipStatus of the AutomotiveInfoDetails
        $ref: '../../commondefinitions.yaml#/definitions/OwnershipStatus'
      lessor:
        description: Lessor of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      leaseEffectiveDate:
        description: LeaseEffectiveDate of the AutomotiveInfoDetails
        type: string
      leaseExpiryDate:
        description: LeaseExpiryDate of the AutomotiveInfoDetails
        type: string
      registeringAuthority:
        description: RegisteringAuthority of the AutomotiveInfoDetails
        type: string
        maxLength: 105
      existingCharges:
        description: ExistingCharges of the AutomotiveInfoDetails
        $ref: '../../commondefinitions.yaml#/definitions/ExistingCharges' 
      automotiveDetailsDocument:
        description: automotiveDetailsDocument of the AutomotiveInfoDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
      automotiveDetailsCharges:
        description: automotiveDetailsCharges of the AutomotiveInfoDetails
        type: array
        items:
          $ref: '#/definitions/AutomotiveDetailsChargesModel'
  AutomotiveDetailsChargesModel:
    description: AutomotiveDetailsCharges model
    type: object
    properties:
      id:
        description: Id of the AutomotiveInfo
        type: string
        maxLength: 36
      automotiveDetailsId:
        description: automotiveDetailsId
        type: string
        maxLength: 36
      chargesType:
        description: chargesType
        type: string
        maxLength: 50
      chargesDescription:
        description: chargesDescription
        type: string
        maxLength: 1000
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type