#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : application_transaction_master.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Application Transaction Master Service
host: 10.184.157.121:9000
basePath: /applicationtransactionmaster-services
tags:
- name: ApplicationTransactionMaster
  description: API for Application Transaction master resource and its child resources
schemes:
- http
paths:  
  /web/v1/applicationtransactionmaster:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationTransactionMaster
      summary: Creates Application Transaction Master 
      description: save into the ApplicationTransactionMaster table. Add additional information here for this endpoint.
      operationId: logTransaction
      parameters:
      - name: applicationTransactionMasterModel
        in: body
        description: Request Body that contains data required for creating ApplicationTransactionMaster
        required: true
        schema:
          $ref: '#/definitions/ApplicationTransactionMasterModel'
      responses:
        201:
          description: Returns the Id of the stage movement
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/applicationtransactionmaster/{applicationNumber}:
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationTransactionMaster
      summary: Update Application Transaction Master
      description: Update Application Transaction Master. Add additional information here for this endpoint.
      operationId: updateTransaction
      parameters:
      - name: applicationNumber
        in: path
        description: Application number for which application data needs to be fetched
        required: true
        type: string
      - name: applicationTransactionMasterModel
        in: body
        description: Request Body that contains data required for creating ApplicationTransactionMaster
        required: true
        schema:
          $ref: '#/definitions/ApplicationTransactionMasterModel'
      responses:
        201:
          description: Returns the Id of the stage movement
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/applicationtransactionmaster/application/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationTransactionMaster
      summary: Fetches application transaction master details by application Number
      description:  Fetches application transaction master details by application number
      operationId: getTransactionDetailsByApplicationNumber
      parameters:
      - name: applicationNumber
        in: path
        description:  Application Number
        required: true
        type: string
      responses:
        200:
          description: returns JsonObject containing Application Transaction Master details
          schema:
            $ref: '#/definitions/AppTransactionMasterModelCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/applicationtransactionmaster/process/{processRefNo}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicationTransactionMaster
      summary: Fetches application transaction master details by application Number
      description:  Fetches application transaction master details by application number
      operationId: getTransactionDetailsByProcessRefNo
      parameters:
      - name: processRefNo
        in: path
        description:  Process Reference Number
        required: true
        type: string
      - name: businessProductCode
        in: query
        description:  Business Product Code
        required: false
        type: string
      responses:
        200:
          description: returns JsonObject containing Application Transaction Master details
          schema:
            $ref: '#/definitions/AppTransactionMasterModelCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  ApplicationTransactionMasterModel:
    description: ApplicationTransactionMasterModel
    type: object
    required:
    - applicationNumber
    properties:
      applicationNumber:
        description: Application Number
        type: string
        maxLength: 36
      processRefNumber:
        description: Process Reference Number
        type: string
        maxLength: 36
      initRefNumber:
        description: Initiation Reference Number
        type: string
        maxLength: 36
      channel:
        description: Channel
        type: string
        maxLength: 10
      currentStage:
        description: Current Stage
        type: string
        maxLength: 20  
      lastCompletedStage:
        description: Last Completed Stage
        type: string
        maxLength: 20  
      initiatedDtStamp:
        description: Initiated Date Stamp
        type: string
      lifeCycleCode:
        description: Life Cycle Code
        type: string
        maxLength: 20 
      status:
        description: Status of the Application
        type: string
      domain:
        description: Domain
        type: string
      productType:
        description: Product Type
        type: string
      subProductType:
        description: Sub Product Type
        type: string
      businessProductCode:
        description: businessProductCode
        type: string
      businessProductName:
        description: businessProcessName
        type: string
      allowedChannel:
        description: allowed channels
        type: string
  AppTransactionMasterModelCollection:
    description: AppTransactionMasterModelCollection
    type: object
    properties:
      data:
        type: "array"
        items: 
          $ref: "#/definitions/ApplicationTransactionMasterModel"