#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : cart.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Cart Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-process-driver-services
tags:
- name: cart
  description: API for Cart operations
schemes:
- http
paths:
  /web/v1/cart:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Cart
      summary: Add item to cart table
      description: Add item to cart table
      operationId: addToCart
      parameters:
      - name: cartDetailsModel
        in: body
        description: Cart Details
        required: true
        schema:
         $ref: "#/definitions/CartDetailsModel"
      responses:
        201:
          description: Returns the count of Products added to cart
          schema:
            $ref: '#/definitions/CartResponse'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Cart
      summary: Get data for all items in cart
      description: Get data for all items in cart
      operationId: getCartDetails
      parameters:
      - name: productDetailsRequired
        in: query
        description: Flag to return 
        required: false
        default: false
        type: boolean
      responses:
        200:
          description: Returns data
          schema:
            $ref: '#/definitions/CartDetailsResponse'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Cart
      summary: Clear cart details
      description: Clear cart details
      operationId: clearCart
      responses:
        200:
          description: Returns data
          schema:
            $ref: '#/definitions/CartResponse'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/cart/{businessProductCode}:
    delete:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Cart
      summary: Delete item from cart
      description: Delete item from cart
      operationId: deleteFromCart
      parameters:
      - name: businessProductCode
        in: path
        description: businessProductCode
        required: true
        type: string
      responses:
        200:
          description: Returns data
          schema:
            $ref: '#/definitions/CartResponse'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  CartResponse:
    description: Cart Response model for post & delete
    type: object
    properties:
      cartTotalCount:
        description: Total count of items in cart
        type: integer
      productCollection:
        description: Products available for the user according to producttype
        type: object
  CartDetailsResponse:
    description: Cart Details Response model for fetch
    type: object
    properties:
      cartTotalCount:
        description: Total count of items in cart
        type: integer
      products:
        type: array
        items:
          type: object
  CartDetailsModel:
    description: Business Product Details
    type: object
    properties:
      businessProductCode:
        description: Business Product Code
        type: string
      userId:
        description: userId
        type: string
      productType:
        description: Product Type
        type: string
      subProductType:
        description: Sub Product Type
        type: string
      ipaReferenceNumber:
        description: In-Principle Approval Reference Number
        type: string