#----------------------------- OFSS-COPYRIGHT-BEGIN -----------------------------
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East),
#  Mumbai - 400 063, India.
#
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : inquiry.yaml
#  **
#  ** Module     :
#  **

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :
#  Changed By         :
#  Change Description :
#  Change On          :
#  Search String      :
#
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: RPM Inquiry Services
host: 10.184.157.121:9000
basePath: /obremo-rpm-process-driver-services
tags:
  - name: inquiry
    description: API for Inquiry screen & all filters
schemes:
  - http
paths:
  /web/v1/inquiry/applicationsList:
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - inquiry
      summary: get list of all applications as per the filter
      description: get list of all applications as per the filter
      operationId: getListOfApplications
      parameters:
        - name: rmId
          in: query
          description: Relationship manager's user login ID
          required: true
          type: string
        - name: fromDate
          in: query
          description: Application date From Filter
          required: false
          type: string
        - name: toDate
          in: query
          description: Application date To Filter
          required: false
          type: string
        - name: applicationNo
          in: query
          description: Application number
          required: false
          type: string
        - name: processRefNo
          in: query
          description: Process reference number
          type: string
          required: false
        - name: productType
          in: query
          description: Product Type
          required: false
          type: string
        - name: productSubType
          in: query
          description: Product sub type
          required: false
          type: string
        - name: productName
          in: query
          description: Business Product name
          type: string
          required: false
        - name: custName
          in: query
          description: Customer Name
          required: false
          type: string
        - name: custMobile
          in: query
          description: Customer mobile number
          required: false
          type: string
        - name: custEmail
          in: query
          description: Customer email id
          required: false
          type: string
        - name: branchCode
          in: query
          description: branch code
          required: false
          type: string
        - name: channel
          in: query
          description: channel
          required: false
          type: string
        - name: offset
          in: query
          description: offset is starting no of records to be fetched
          required: false
          type: integer
        - name: limit
          in: query
          description: limit is maximum no of records to be fetched
          required: false
          type: integer
      responses:
        201:
          description: Returns the domain with the count of applications initiated by the RM
          schema:
            $ref: "#/definitions/ApplicationsList"
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/inquiry/applicationSearch:
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - inquiry
      summary: get application Details
      description: get application Details
      operationId: getApplicationsDetails
      parameters:
        - name: rmId
          in: query
          description: Relationship manager's user login ID
          required: true
          type: string
        - name: searchValue
          in: query
          description: Search Value
          required: false
          type: string
        - name: priority
          in: query
          description: priority
          required: false
          type: string 
        - name: period
          in: query
          description: period
          required: false
          type: string 
        - name: offset
          in: query
          description: offset
          required: false
          type: integer 
        - name: limit   
          in: query
          description: limit
          required: false
          type: integer                  
      responses:
        201:
          description: Returns the domain with the count of applications initiated by the RM
          schema:
            $ref: "#/definitions/ApplicationsSearchList"
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/inquiry/productDetails:
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - inquiry
      summary: get product details of a particular customer
      description: get product details of a particular customer
      operationId: getProductDetails
      parameters:
        - name: searchValue
          in: query
          description: Search Value
          required: false
          type: string                  
        - name: rmId
          in: query
          description: Relationship manager's user login ID
          required: true
          type: string
        - name: priority
          in: query
          description: priority
          required: false
          type: string 
        - name: period
          in: query
          description: period
          required: false
          type: string
        - name: offset
          in: query
          description: offset
          required: false
          type: integer 
        - name: limit   
          in: query
          description: limit
          required: false
          type: integer                                     
      responses:
        201:
          description: Returns the domain with the count of applications initiated by the RM
          schema:
            $ref: "#/definitions/ApplicationsDetailsList"
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/inquiry/getStageLists:
    get:
      produces:
        - application/json
        - application/xml
      tags:
        - inquiry
      summary: get stage list for a processRefNo
      description: get stage list for a processRefNo
      operationId: getStageList
      parameters:
        - name: processRefNo
          in: query
          description: Process Ref No.
          required: true
          type: string
      responses:
        201:
          description: Returns the domain with the count of applications initiated by the RM
          schema:
            $ref: "#/definitions/StageDetails"
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error