#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : arrangerinvitation.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/arrangerinvitation:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Adds a new arrangerinvitation.
      description: Adds a new arrangerinvitation. Add additional information here for this endpoint.
      operationId: addArrangerInvitation
      parameters:
      - name: arrangerinvitation
        in: body
        description: Request Body that contains data required for creating a new arrangerinvitation
        required: true
        schema:
          $ref: '#/definitions/ArrangerInvitationModel'
      responses:
        201:
          description: Returns the Id of the newly created arrangerinvitation
          headers:
            Location:
              description: URL of newly created arrangerinvitation
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Retrieves the list of existing arrangerinvitation.
      description: Retrieves the list of existing arrangerinvitation. Add additional information here for the this endpoint.
      operationId: getAllArrangerInvitation
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/arrangerinvitation/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Retrieves the arrangerinvitation by id.
      description: Retrieves the arrangerinvitation by id. Add additional information here for the this endpoint.
      operationId: getArrangerInvitationById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the arrangerinvitation based on given applicationNumber.
          schema:
            $ref: '#/definitions/ArrangerInvitationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Update an existing arrangerinvitation.
      description: Update an existing arrangerinvitation. Add additional information here for the this endpoint.
      operationId: updateArrangerInvitation
      parameters:
      - name: id
        in: path
        description: id of the arrangerinvitation that need to be updated
        required: true
        type: string
      - name: arrangerinvitation
        in: body
        description: Request Body that contains data required for updating an existing arrangerinvitation
        required: true
        schema:
          $ref: '#/definitions/ArrangerInvitationModel'
      responses:
        202:
          description: Returns updated arrangerinvitation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Deletes the arrangerinvitation identified by given ID.
      description: Deletes the arrangerinvitation identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteArrangerInvitation
      parameters:
      - name: id
        in: path
        description: Id of the arrangerinvitation that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/arrangerinvitation/summary/{applicationNumber}:  
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - arrangerinvitation
      summary: Retrieves the arrangerinvitation Summary.
      description: Retrieves the arrangerinvitation Summary.
      operationId: getArrangerInvitationSummary
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the arrangerinvitation that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the arrangerinvitation based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error      
definitions:
  ArrangerInvitationModel:
    description: arrangerinvitation model
    type: object
    properties:
      id:
        description: Id of the arrangerinvitation
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks
        type: string
      invitationStatus:
        description: invitationStatus
        type: string  
      arrangerDetails:
        type: array
        items:
          $ref: '#/definitions/ArrangerDetailsModel'
  ArrangerDetailsModel:
    description: ArrangerDetails model
    type: object
    required:
    - arrangerNumber
    - arrangerName
    properties:
      id:
        description: Id of the ParticipantDetails
        type: string
      arrangerInvitationId:
        description: arrangerInvitationId
        type: string
      arrangerId:
        description: arrangerId
        type: string
      arrangerNumber:
        description: id number of the participant
        type: string
        maxLength: 36
      arrangerName:
        description: arrangerName
        type: string
      status:
        description: status
        type: string
      arrangerAcceptenceStatus:
        description: acceptenceStatus
        type: string
      arrangerAcceptenceDate:
        description: acceptenceDate
        type: string
      arrangerAcceptenceBy:
        description: acceptenceBy
        type: string
      remarks:
        description: remarks
        type: string
      arrangerDocument:
        description: arrangerDocument of the LenderDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
  ArrangerInvitationCollection:
    description: Collection of arrangerinvitation.
    type: object
    properties:
      ArrangerInvitationInfoList:
        type: array
        items:
          $ref: '#/definitions/ArrangerInvitationModel'
