#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : loanschedule.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/loanschedules:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSchedules
      summary: Adds a new LoanSchedule.
      description: Adds a new LoanSchedule. Add additional information here for this endpoint.
      operationId: addLoanSchedule
      parameters:
      - name: LoanSchedule
        in: body
        description: Request Body that contains data required for creating a new LoanSchedule
        required: true
        schema:
          $ref: '#/definitions/LoanScheduleModel'
      responses:
        201:
          description: Returns the Id of the newly created LoanSchedule
          headers:
            Location:
              description: URL of newly created LoanSchedule
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSchedules
      summary: Retrieves the list of  LoanSchedule.
      description: Retrieves the list of  LoanSchedule. Add additional information here for the this endpoint.
      operationId: getAllLoanSchedule
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/loanschedules/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSchedules
      summary: Get a  LoanSchedule.
      description: Update a  LoanSchedule. Add additional information here for the this endpoint.
      operationId: getLoanScheduleById
      parameters:
      - name: id
        in: path
        description: id of the LoanSchedule that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated LoanSchedule
          schema:
            $ref: '#/definitions/LoanScheduleModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSchedules
      summary: Update an  LoanSchedule.
      description: Update an  LoanSchedule. Add additional information here for the this endpoint.
      operationId: updateLoanSchedule
      parameters:
      - name: id
        in: path
        description: id of the LoanSchedule that need to be updated
        required: true
        type: string
      - name: LoanSchedule
        in: body
        description: Request Body that contains data required for updating an  LoanSchedule
        required: true
        schema:
          $ref: '#/definitions/LoanScheduleModel'
      responses:
        200:
          description: Returns updated LoanSchedule
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSchedules
      summary: Deletes the A Banking info identified by given ID.
      description: Deletes the LoanSchedule identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLoanSchedule
      parameters:
      - name: id
        in: path
        description: Id of the LoanSchedule that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LoanScheduleModel:
   description: LoanSchedule model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      productCode:
        description: productCode of the LoanSchedule
        type: string
      componentCurrency:
        description: Component Currency
        type: string 
        maxLength: 3
      loanScheduleDetails:
        description: Details of the LoanSchedule
        type: array
        items:
          $ref: '#/definitions/LoanScheduleDetailsModel'
  LoanScheduleCollection:
    description: Collection of LoanSchedule.
    type: object
    properties:
      LoanScheduleList:
        type: array
        items:
          $ref: '#/definitions/LoanScheduleModel'
  LoanScheduleDetailsModel:
    description: Loan Schedule Details model
    type: object
    required:
    - scheduleType
    - componentName
    - componentCurrencyCode   
    - frequency
    - unit   
    - noOfSchedules
    - startDate
    - principalLiquidation
    properties:
      id:
        description: Id of the schedule details model
        type: string
        maxLength: 36
      loanScheduleId:
        description: loanScheduleId of the Details model
        type: string
        maxLength: 36
      scheduleType:
        description: scheduleType of the Details model
        type: string
        maxLength: 20
      componentName:
        description: componentName of the Details model
        type: string
        maxLength: 35
      componentCurrencyCode:
        description: componentCurrency of the Details model
        type: string
        maxLength: 3
      rateType:
        description: rateType of the Details model
        type: string
        maxLength: 20
      spread:
        description: spread of the schedule details model
        type: string
        format: int64
      rate:
        description: rate of the Details model
        type: number
        format: int64
      rateCode:
        description: rateCode of the Details model
        type: string
        maxLength: 20
      amount:
        description: amount of the Details model
        type: number
        minimum: 0
      noOfSchedules:
        description: noOfSchedules of the Details model
        type: integer
      unit:
        description: unit of the Details model
        type: integer
      frequency:
        description: frequency of the Details model
        type: string
        maxLength: 22
      startDate:
        description: startDate of the schedule details model
        type: string
        maxLength: 10
      principalLiquidation:
        description: principalLiquidation of the Details model
        type: string
        maxLength: 20
      scheduleNo:
        description: scheduleNo
        type: integer
      scheduleDate:
        description: scheduleDate
        type: string
      settlementCurrencyCode:
        description: settlementCurrencyCode
        type: string
        maxLength: 3
      amountToSettle:
        description: amountToSettle
        type: number
        minimum: 0
      amountDue:
        description: amountDue
        type: number
        minimum: 0
      loanScheduleDetailsDocument:
        description: loanScheduleDocument of the loanSchedule
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'         
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type  