#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : trancheliquidate.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/trancheliquidate:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheLiquidate
      summary: Adds a new TrancheLiquidate.
      description: Adds a new TrancheLiquidate. Add additional information here for this endpoint.
      operationId: addTrancheLiquidate
      parameters:
      - name: TrancheLiquidate
        in: body
        description: Request Body that contains data required for creating a new TrancheLiquidate
        required: true
        schema:
          $ref: '#/definitions/TrancheLiquidateModel'
      responses:
        201:
          description: Returns the Id of the newly created TrancheLiquidate
          headers:
            Location:
              description: URL of newly created TrancheLiquidate
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheLiquidate
      summary: Retrieves the list of existing TrancheLiquidate.
      description: Retrieves the list of existing TrancheLiquidate. Add additional information here for the this endpoint.
      operationId: getAllTrancheLiquidate
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/trancheliquidate/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheLiquidate
      summary: Retrieves the TrancheLiquidate by id.
      description: Retrieves the TrancheLiquidate by id. Add additional information here for the this endpoint.
      operationId: getTrancheLiquidateById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the TrancheLiquidate based on given applicationNumber.
          schema:
            $ref: '#/definitions/TrancheLiquidateModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheLiquidate
      summary: Update an existing TrancheLiquidate.
      description: Update an existing TrancheLiquidate. Add additional information here for the this endpoint.
      operationId: updateTrancheLiquidate
      parameters:
      - name: id
        in: path
        description: id of the TrancheLiquidate that need to be updated
        required: true
        type: string
      - name: TrancheLiquidate
        in: body
        description: Request Body that contains data required for updating an existing TrancheLiquidate
        required: true
        schema:
          $ref: '#/definitions/TrancheLiquidateModel'
      responses:
        200:
          description: Returns updated TrancheLiquidate
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - TrancheLiquidate
      summary: Deletes the TrancheLiquidate identified by given ID.
      description: Deletes the TrancheLiquidate identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteTrancheLiquidate
      parameters:
      - name: id
        in: path
        description: Id of the TrancheLiquidate that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  TrancheLiquidateModel:
    description: TrancheLiquidate model
    type: object
    properties:
      id:
        description: Id of the TrancheLiquidate
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      processRefNumber:
        description: Process Ref Number 
        maxLength: 36
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      remarks:
        description: remarks
        type: string
      trancheContractRefNumber:
        description: trancheContractRefNumber
        type: string
      trancheName:
        description: trancheName
        type: string
      amount:
        description: amount
        type: number
      borrower:
        description: borrower
        type: string
      effectiveDate:
        description: effectiveDate
        type: string
      expiryDate:
        description: expiryDate
        type: string
      cusipNumber:
        description: cusipNumber
        type: string
      maturityDate:
        description: maturityDate
        type: string
      productCode:
        description: productCode
        type: string
      liquidate:
        description: liquidate
        type: string
      availableBalance:
        description: availableBalance
        type: number
      currency:
        description: currency
        type: string
  TrancheLiquidateCollection:
    description: Collection of TrancheLiquidate.
    type: object
    properties:
      TrancheLiquidateList:
        type: array
        items:
          $ref: '#/definitions/TrancheLiquidateModel'
