#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : collateralinfo.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/collateralinfo:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralInfo
      summary: Adds a new Preferred Bank.
      description: Adds a new CollateralInfo. Add additional information here for this endpoint.
      operationId: createCollateralInfo
      parameters:
      - name: CollateralInfo
        in: body
        description: Request Body that contains data required for creating a new CollateralInfo
        required: true
        schema:
          $ref: '#/definitions/CollateralInfoModel'
      responses:
        201:
          description: Returns the Id of the newly created CollateralInfo
          headers:
            Location:
              description: URL of newly created CollateralInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralInfo
      summary: Retrieves the list of existing CollateralInfo.
      description: Retrieves the list of existing CollateralInfo. Add additional information here for the this endpoint.
      operationId: getAllCollateralInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/collateralinfo/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralInfo
      summary: Retrieves the CollateralInfo by id.
      description: Retrieves the CollateralInfo by id. Add additional information here for the this endpoint.
      operationId: getCollateralInfoById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CollateralInfo based on given applicationNumber.
          schema:
            $ref: '#/definitions/CollateralInfoModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralInfo
      summary: Update an existing CollateralInfo.
      description: Update an existing CollateralInfo. Add additional information here for the this endpoint.
      operationId: updateCollateralInfo
      parameters:
      - name: id
        in: path
        description: id of the CollateralInfo that need to be updated
        required: true
        type: string
      - name: CollateralInfo
        in: body
        description: Request Body that contains data required for updating an existing CollateralInfo
        required: true
        schema:
          $ref: '#/definitions/CollateralInfoModel'
      responses:
        200:
          description: Returns updated CollateralInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - CollateralInfo
      summary: Deletes the CollateralInfo identified by given ID.
      description: Deletes the CollateralInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCollateralInfo
      parameters:
      - name: id
        in: path
        description: Id of the CollateralInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  CollateralInfoModel:
    description: CollateralInfo model
    type: object
    properties:
      id:
        description: Id of the CollateralInfo
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the CollateralInfo
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string   
      remarks:
        description: remarks
        type: string
        maxLength: 300
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      collateralDetails:
        type: array
        items:
          $ref: '#/definitions/CollateralDetailsModel'
  CollateralDetailsModel:
    description: CollateralDetails model
    type: object
    required:
    - collateralType
    - collateralProvider
    - collateralExpectedValue
    - collateralExpectedValueCurrencyCode
    properties:
      id:
        description: Id of the Collateral Details
        type: string
        maxLength: 36
      collateralInfoId:
        description: Collateral Info Id
        type: string
        maxLength: 36
      collateralType:
        description: Collateral Type
        type: string
        maxLength: 20
      collateralDescription:
        description: Collateral Description
        type: string
        maxLength: 300
      collateralExpectedValue:
        description: Collateral Expected Value
        type: number
      collateralExpectedValueCurrencyCode:
        description: Collateral Expected Value Currency Code
        type: string
        maxLength: 4
      collateralProvider:
        description: Collateral Provider
        type: string
        maxLength: 20
      collateralReviewStatus:
        description: Collateral Review Status
        type: string
        maxLength: 20
      collateralEligibleValue:
        description: Collateral Eligible Value
        type: number
      collateralEligibleValueCurrencyCode:
        description: Collateral Expected Value Currency Code
        type: string
        maxLength: 4
      collateralMarketValue:
        description: Collateral Market Value
        type: number
      collateralMarketValueCurrencyCode:
        description: Collateral Market Value Currency Code
        type: string
        maxLength: 4
      collateralBorrowers:
        type: array
        items:
          $ref: '#/definitions/CollateralBorrowersModel'
      collateralTranches:
        type: array
        items:
          $ref: '#/definitions/CollateralTranchesModel'
  CollateralBorrowersModel:
    description: CollateralBorrowers model
    type: object
    properties:
      id:
        description: Id of the CollateralBorrower
        type: string
      collateralDetailsId:
        description: collateralBorrowerId
        type: string
      borrowerId:
        description: collateralBorrowerId
        type: string
      borrowerName:
        description: Name of Borrower
        type: string
        maxLength: 36
      borrowerNumber:
        description: Borrower Number
        type: string
        maxLength: 36
  CollateralTranchesModel:
    description: CollateralTranches model
    type: object
    properties:
      id:
        description: Id of the CollateralTranchesWork
        type: string
      collateralDetailsId:
        description: collateralTrancheId
        type: string
      trancheId:
        description: collateralTrancheId
        type: string
      trancheName:
        description: Name of Tranche
        type: string
  CollateralInfoCollection:
    description: Collection of CollateralInfo.
    type: object
    properties:
      CollateralInfoList:
        type: array
        items:
          $ref: '#/definitions/CollateralInfoModel'