#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : AccountDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Current and Savings Account Application Service
host: localhost:7001
basePath: /accountdetails
tags:
- name: Current Account Application
  description: API for Accound Details Data segment Operations
schemes:
- http
paths:
  /web/v1/accountdetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Adds a new AccountDetails.
      description: Adds a new AccountDetails. Add additional information here for this endpoint.
      operationId: addAccountDetails
      parameters:
      - name: accountDetails
        in: body
        description: Request Body that contains data required for creating a new AccountDetails
        required: true
        schema:
          $ref: '#/definitions/AccountDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created AccountDetails
          headers:
            Location:
              description: URL of newly created AccountDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Retrieves the list of existing AccountDetails.
      description: Retrieves the list of existing AccountDetails. Add additional information here for the this endpoint.
      operationId: getAllAccountDetails
      parameters:
      - name: processRefNo
        in: query
        description: process reference number of the AccountDetails that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: application number of the AccountDetails that needs to be fetched
        required: true
        type: string
      - name: businessProductCode
        in: query
        description: Business product code of the AccountDetails that needs to be fetched
        required: false
        type: string      
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/accountdetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Get By ID
      description: Retrieves the AccountDetails by Id Add additional information here for the this endpoint.
      operationId: getAccountDetailsById
      parameters:
      - name: id
        in: path
        description: ID of the Account details that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AccountDetails based on given ID.
          schema:
            $ref: '#/definitions/AccountDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Update an existing AccountDetails.
      description: Update an existing AccountDetails. Add additional information here for the this endpoint.
      operationId: updateAccountDetails
      parameters:
      - name: id
        in: path
        description: id of the AccountDetails that need to be updated
        required: true
        type: string
      - name: AccountDetails
        in: body
        description: Request Body that contains data required for updating an existing AccountDetails
        required: true
        schema:
          $ref: '#/definitions/AccountDetailsModel'
      responses:
        200:
          description: Returns updated AccountDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Deletes the AccountDetails identified by given ID.
      description: Deletes the AccountDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAccountDetails
      parameters:
      - name: id
        in: path
        description: Id of the AccountDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/validcurrency/{businessProductName}:
    get:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Get list of valid currencies
      description: Retrieves the List of currencies based on business product code
      operationId: getCurrencyByProductName
      parameters:
      - name: businessProductName
        in: path
        description: Business product name
        required: true
        type: string
      responses:
        200:
          description: Returns the List of Currencies
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
 
  /web/v1/stageskipping:
    get:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Get Details if Initial funding and Overdraft required
      description: Retrieves the flag if Initial funding and Overdraft stage is required
      operationId: stageSkipping
      parameters:
      - name: processRefNo
        in: query
        description: Process Reference Number
        required: true
        type: string
      responses:
        200:
          description: Returns if Initial Funding and overdraft is required for given Process Reference Number
          schema:
           $ref: '#/definitions/StageSkippingDetalModel' 
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error     
  /web/v1/validbranches/{businessProductCode}:
    get:
      produces:
      - application/json
      tags:
      - AccountDetails
      summary: Get list of valid branches
      description: Retrieves the List of branches based on business product code
      operationId: getBranchByProductCode
      parameters:
      - name: businessProductCode
        in: path
        description: Business product code
        required: true
        type: string
      responses:
        200:
          description: Returns the List of Branches
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error     
 
definitions:
  AccountDetailsModel:
   description: AccountDetails model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      action:
        type: string
        description: action
      processRefNo:
        description: Process Reference Number
        type: string
        maxLength: 20       
      accountType:
        description: Type of the account , will be defualted from application initiation. 
        type: string
        maxLength: 35
      accountBranch:
        description: Branch of the account.
        type: string
        maxLength: 4
      productCode:
        description: Code of the product, which will be defaulted from the initiation.
        type: string
        maxLength: 30  
      productName:
        description: Name of the product, which will be defaulted from the initiation. 
        type: string
        maxLength: 100
      accountCurrency:
        description: Currency of the account. 
        type: string
        maxLength: 3
      applicationDate:
        description: Date of the application, Default to Current Date. 
        type: string
      accountName:
        description: Name of the account.
        type: string
        maxLength: 100
      holdingPattern:
        description: Holding Pattern
        type: string
        maxLength: 30
      otherHoldingPattern:
        description: Holding pattern when existing values are not sufficient
        type: string
        maxLength: 30
      ownership:
        description: Ownership
        type: string
        maxLength: 30        
      existingCustomer:
        description: Is Existing Customer
        type: boolean
      modeOfOperation:
        description: Mode of operation, Single (default value)/Jointly/Either or Survivor/Former or Survivor/As per mandan
        type: string
        maxLength: 35    
      fundTheAccount:
        description: Initial funding mode to the while account creation.
        type: string
        maxLength: 1
      fundBy:
        description: Funded by.
        type: string
        maxLength: 35
      amount:
        description: Amount to be funded.
        type: number
      accountNumber:
        description: Account Number
        type: string
        maxLength: 105
      fundByAccountName:
        description: Fund By Account Name
        type: string
        maxLength: 105
      valueDate:
        description: Value Date
        type: string
      overdraft:
        description: Is over draft?
        type: string
        pattern: '[Y,N]'
      chequeNumber:
        description: Cheque Number.
        type: string
        maxLength: 50
      chequeDate:
        description: Cheque date.
        type: string      
      chequeBankName:
        description: Bank name on the cheque.
        type: string
      chequeBranchName:
        description: Branch name on the cheque.
        type: string
      chequeRoutingNumber:
        description: Routing Number on the cheque
        type: string
        pattern: '^\d{0,9}$'
      channel:
        description: Channel of application initiation (Default RPM)
        type: string               
      sourceEmpCode:
        description: Source by employee Code
        type: string
      sourceEmpName:
        description: Source by employee name
        type: string
      stageChanged:
        description: Is stage Changed?
        type: boolean
      #General Ledger
      glCode:
        type: string
        description: General Ledger Code.
      glDesc:
        type: string
        description: General Ledger Description.
      fundByCash:
        type: string
        description: fundByCash.
      fundByAcc:
        type: string
        description: fundByAcc.
      fundByCheque:
        type: string
        description: fundByCheque.
      bankName:
        type: string
        description: Bank Name
      bankCode:
        type: string
        description: Bank Code
      txnRefNumber:
        type: string
        description: Transaction Reference Number  
      sourceSystemAccBrn:
        type: string
        description: Source System Account Branch               
      businessProductDtls:
        $ref: '#/definitions/BusinessProductDtls'  
  BusinessProductDtls:
   type: object
   properties:
     businessProductCode:
      type: string
      description: "businessProductCode"
     businessProductImage:
      type: string
      description: "businessProductImage"
     businessProductSummary:
      type: string
      description: "businessProductSummary"
     productType:
      type: string
      description: "productType"
     productBrochure:
      type: string
      description: "productBrochure"
     termsandcondition:
      type: string
      description: "termsandcondition"         
  AccountDetailsCollection:
    description: Collection of AccountDetails.
    type: object
    properties:
      AccountDetailsList:
        type: array
        items:
          $ref: '#/definitions/AccountDetailsModel'        
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type
  StageSkippingDetalModel:
   type: object
   properties:
      processRefNo:
        description: Process Reference Number
        type: string
      initFundRqrd:
        description: Initial Funding Required
        type: string  
      applicationNumber:
        description: Initial Funding Required
        type: string    
      overDraftRqrd:
        description: Over Draft Required
        type: string