#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : InterestDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: interestDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /ininitalfundingdetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for Interest Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/ininitalfundingdetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - IninitalFundingDetails
      summary: Adds a new ininitalfundingdetails.
      description: Adds a new ininitalfundingdetails. Add additional information here for this endpoint.
      operationId: addInInitalFundingDetails
      parameters:
      - name: ininitalFundingDetails
        in: body
        description: Request Body that contains data required for creating a new ininitalfundingdetails
        required: true
        schema:
          $ref: '#/definitions/IninitalFundingDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created ininitalfundingdetails.
          headers:
            Location:
              description: URL of newly created ininitalfundingdetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - IninitalFundingDetails
      summary: Retrieves the list of existing ininitalfundingdetails.
      description: Retrieves the list of existing ininitalfundingdetails. Add additional information here for the this endpoint.
      operationId: getAllIninitalFundingDetails
      parameters:
      - name: processRefNo
        in: query
        description: process reference number of the IninitalFundingDetails that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the IninitalFundingDetails that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/ininitalfundingdetails/{id}:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - IninitalFundingDetails
      summary: Update an existing ininitalfundingdetails.
      description: Update an existing ininitalfundingdetails. Add additional information here for the this endpoint.
      operationId: updateIninitalFundingDetails
      parameters:
      - name: id
        in: path
        description: id of the InterestDetails that need to be updated
        required: true
        type: string
      - name: ininitalFundingDetails
        in: body
        description: Request Body that contains data required for updating an existing ininitalfundingdetails
        required: true
        schema:
          $ref: '#/definitions/IninitalFundingDetailsModel'
      responses:
        200:
          description: Returns updated ininitalfundingdetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  /web/v1/tellertxndetails:
    get:
      produces:
      - application/json
      tags:
      - IninitalFundingDetails
      summary: Retrieves the list of existing tellertxndetails.
      description: Retrieves the list of existing tellertxndetails. Add additional information here for the this endpoint.
      operationId: getTellerTxnDetails
      parameters:
      - name: processRefNo
        in: query
        description: process reference number of the tellertxndetails that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the tellertxndetails that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/TellerTxnModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error          
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - IninitalFundingDetails
      summary: Adds a new tellertxndetails.
      description: Adds a new tellertxndetails. Add additional information here for this endpoint.
      operationId: updateTellerTxnStatus
      parameters:
      - name: tellerTxnModel
        in: body
        description: Request Body that contains data required for creating a new tellertxndetails
        required: true
        schema:
          $ref: '#/definitions/TellerTxnModel'
      responses:
        201:
          description: Returns the Id of the newly created TellerTxnModel.
          headers:
            Location:
              description: URL of newly created TellerTxnModel.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error          
definitions:
 IninitalFundingDetailsModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     dataSegmentCode:
      description: Data segment code
      type: string
     stageCode:
      description: stage code
      type: string
      maxLength: 36            
     id:
      description: Id of the IninitalFundingDetails
      type: string
      maxLength: 36
     applicationNumber:
      description: Application Number of the IninitalFundingDetails
      type: string
      maxLength: 20
     applicationDate:
      description: Date of the application, Default to Current Date. 
      type: string 
     processRefNo:
      description: Process reference Number of the IninitalFundingDetails
      type: string
      maxLength: 20
     fundTheAccount:
      description: Initial funding mode to the while account creation.
      type: string
      maxLength: 1
     fundBy:
      description: Funded by.
      type: string
      maxLength: 35
     amount:
      description: Amount to be funded.
      type: number
     accountNumber:
      description: Account Number
      type: string
      maxLength: 105
     fundByAccountName:
      description: Fund By Account Name
      type: string
     valueDate:
      description: Value Date
      type: string 
     bankName:
      description: Name of the bank.
      type: string
     branchCode:
      description: Code of the branch.
      type: string      
     branchName:
      description: Name of the branch.
      type: string
     chequeNumber:
      description: Cheque Number.
      type: string
      maxLength: 50
     chequeDate:
      description: Cheque date.
      type: string      
     chequeBankName:
      description: Bank name on the cheque.
      type: string
     chequeBranchName:
      description: Branch name on the cheque.
      type: string 
     chequeRoutingNumber:
      description: Routing Number on the cheque
      type: string
      pattern: '^\d{0,9}$'
     tellerTxnRefNo:
      description: tellerTxnRefNo.
      type: string
     tellerTxnStatus:
      description: tellerTxnStatus.
      type: string            
     accountCurrency:
      description: Currency of the account. 
      type: string
      maxLength: 3  
     autoFunding:
      type: boolean
      description: If Funding is automatic or manual.
     glCode:
      type: string
      description: General Ledger Code.
     glDesc:
      type: string
      description: General Ledger Description. 
     txnTriggerStatus:
      type: string
      description: Automatic Transaction Trigger status 
 TellerTxnModel:
   description: "TellerTxnModel Model"
   type: object
   properties:
    id:
     description: Id of the TellerTxnModel
     type: string
     maxLength: 36
    processRefNo:
     description: "Process Reference Number of the TellerTxnModel"
     type: string
     maxLength: 20
    applicationNumber:
     description: "Application Number"
     type: string
     maxLength: 20 
    tellerTxnRefNo:
     description: "teller Transation Reference Number"
     type: string
     maxLength: 36     
    tellerTxnStatus:
     description: "teller Transation status"
     type: string
     maxLength: 30
    txnTriggerStatus:
     type: string
     description: Automatic Transaction Trigger status 
 IninitalFundingDetailsCollection:
    description: Collection of IninitalFundingDetails.
    type: object
    properties:
     ininitalFundingDetailsModelList:
      type: array
      items:
       $ref: '#/definitions/IninitalFundingDetailsModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type