#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : InterestDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: interestDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /interestdetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for Interest Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/interestdetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - interestDetails
      summary: Adds a new interestdetails.
      description: Adds a new Interestdetails. Add additional information here for this endpoint.
      operationId: addInterestDetails
      parameters:
      - name: Interestdetails
        in: body
        description: Request Body that contains data required for creating a new Interestdetails
        required: true
        schema:
          $ref: '#/definitions/InterestDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created InterestDetails.
          headers:
            Location:
              description: URL of newly created InterestDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - InterestDetails
      summary: Retrieves the list of existing InterestDetails.
      description: Retrieves the list of existing InterestDetails. Add additional information here for the this endpoint.
      operationId: getAllInterestDetails
      parameters:
      - name: processRefNo
        in: query
        description: process reference number of the Interest details that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the Interest Details that needs to be fetched
        required: false
        type: string  
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/interestdetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - InterestDetails
      summary: Get By ID
      description: Retrieves the Interestdetails by Id Add additional information here for the this endpoint.
      operationId: getInterestDetailsById
      parameters:
      - name: id
        in: path
        description: id of the InterestDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the InterestDetails based on given ID.
          schema:
            $ref: '#/definitions/InterestDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - InterestDetails
      summary: Update an existing InterestDetails.
      description: Update an existing InterestDetails. Add additional information here for the this endpoint.
      operationId: updateInterestDetails
      parameters:
      - name: id
        in: path
        description: id of the InterestDetails that need to be updated
        required: true
        type: string
      - name: InterestDetails
        in: body
        description: Request Body that contains data required for updating an existing InterestDetails
        required: true
        schema:
          $ref: '#/definitions/InterestDetailsMasterModel'
      responses:
        200:
          description: Returns updated InterestDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - InterestDetails
      summary: Deletes the InterestDetails identified by given ID.
      description: Deletes the InterestDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteInterestDetails
      parameters:
      - name: id
        in: path
        description: Id of the InterestDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 InterestDetailsMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process reference Number of the InterestDetailsModel
      type: string
      maxLength: 20
     productName:
      type: string
      description: Interest Product name
     hostCode:
      type: string
      description: Host code
     interestDetailsModel: 
      type: array
      items: 
        $ref: '#/definitions/InterestDetailsModel'        
    required:
     - stageCode
     - processRefNo
     - applicationNumber
 InterestDetailsModel:
    description: InterestDetails Model
    type: object
    properties:
      id:
        description: Id
        type: string
        maxLength : 36
      processRefNo:
        description: processRefNo
        type: string
      interestDetailsMasterId:
        description: InterestDetailsMasterId
        type: string 
      componentCode:
        description: componentCode
        type: string
      mainComponent:
        description: mainComponent
        type: boolean 
      udeId:
        description: udeId
        type: string 
      interestType: 
        description: Interest Rate Type
        type: string
      interestRate: 
        description: Interest Rate
        type: number
        format: double
      effectiveRate:
        description: Effective Rate
        type: number
        format: double
      customerMargin:
        description: Margin
        type: number
        format: double
      marginAllowed:
        description: margin Allowed
        type: boolean 
      seqNo:
        description: Seq No
        type: integer 
    required:
      - processRefNo
      - interestType
      - interestRate
      - effectiveRate
      - mainComponent
      - marginAllowed
      - seqNo    
 InterestDetailsMasterCollection:
    description: Collection of InterestDetailsMasterModel.
    type: object
    properties:
     interestDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/InterestDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type