#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ODAccountLimitDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: odAccountLimitDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /odAccountLimitDetails
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: SavingApplication
    description: API for odAccountLimit Details Data segment Operations
schemes:
  - http
paths:
  /web/v1/odAccountLimitDetails:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Adds a new odAccountLimitDetails.
      description: Adds a new odAccountLimitDetails. Add additional information here for this endpoint.
      operationId: addODAccountLimitDetails
      parameters:
        - name: odAccountLimitDetails
          in: body
          description: Request Body that contains data required for creating a new odAccountLimitDetails
          required: true
          schema:
            $ref: '#/definitions/odAccountLimitDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created odAccountLimitDetails.
          headers:
            Location:
              description: URL of newly created odAccountLimitDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Retrieves the list of existing odAccountLimitDetails.
      description: Retrieves the list of existing odAccountLimitDetails. Add additional information here for the this endpoint.
      operationId: getAllODAccountLimitDetails
      parameters:
        - name: applicationNumber
          in: query
          description: applicationNumber of the odAccountLimitDetails that needs to be fetched
          required: false
          type: string
        - name: processRefNo
          in: query
          description: processRefNo of the user odAccountLimitDetails needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/odAccountLimitDetails/{id}:
    get:
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Get By ID
      description: Retrieves the odAccountLimitDetails by Id Add additional information here for the this endpoint.
      operationId: getODAccountLimitDetailsById
      parameters:
        - name: id
          in: path
          description: ID of the odAccountLimitDetails that needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Returns the odAccountLimitDetails based on given ID.
          schema:
            $ref: '#/definitions/odAccountLimitDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Update an existing odAccountLimitDetails.
      description: Update an existing odAccountLimitDetails. Add additional information here for the this endpoint.
      operationId: updateODAccountLimitDetails
      parameters:
        - name: id
          in: path
          description: id of the odAccountLimitDetails that need to be updated
          required: true
          type: string
        - name: odAccountLimitDetails
          in: body
          description: Request Body that contains data required for updating an existing odAccountLimitDetails
          required: true
          schema:
            $ref: '#/definitions/odAccountLimitDetailsMasterModel'
      responses:
        200:
          description: Returns updated odAccountLimitDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Deletes the odAccountLimitDetails identified by given ID.
      description: Deletes the odAccountLimitDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteODAccountLimitDetails
      parameters:
        - name: id
          in: path
          description: Id of the odAccountLimitDetails that needs to be deleted
          required: true
          type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/underwritingstageskipping:
    get:
      produces:
        - application/json
      tags:
        - odAccountLimitDetails
      summary: Get Details if Underwriting is required
      description: Retrieves the flag if Underwriting stage is required
      operationId: underWritingStageSkipping
      parameters:
        - name: processRefNo
          in: query
          description: Process Reference Number
          required: true
          type: string
      responses:
        200:
          description: Returns if Underwriting is required for given Process Reference Number
          schema:
            $ref: '#/definitions/StageSkippingDetalModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  odAccountLimitDetailsMasterModel:
    type: object
    allOf:
      - $ref: '#/definitions/GenericDatasegmentModel'
      - type: object
        properties:
          processRefNo:
            description: "Process reference number of ODAccountLimit details master model"
            type: string
            maxLength: 20
          applicationDate:
            type: string
            description: "Date of application"
          channel:
            type: string
            description: Channel
          action:
            type: string
            description: action
          odApplicantDetailsList:
            type: array
            items:
              $ref: '#/definitions/odApplicantDetailsModel'
  odApplicantDetailsModel:
    description: Overdraft Applicant Details Model
    type: object
    properties:
      id:
        description: Id of the Overdraft Applicant Details Model
        type: string
      odAccountLimitDetailsMasterId:
        description: Id of OD Account Limit Details Master Table
        type: string
      applicationNumber:
        description: Application Number
        type: string
        maxLength: 20
      processRefNo:
        description: Process Ref Number
        type: string
        maxLength: 20
      applicantId:
        description: Applicant ID
        type: string
      partyId:
        description: Party ID
        type: string
      customerId:
        description: Customer ID
        type: string
      customerName:
        description: Customer Name
        type: string
      primaryApplicant:
        description: Primary Applicant Y/N
        type: boolean
      existingCustomer:
        description: Existing Customer Y/N
        type: boolean
      dateOfBirth:
        description: Date of Birth
        type: string
      email:
        description: Email
        type: string
      mobileNumber:
        description: Mobile Number
        type: integer
        format: int64
      mobileIsd:
        description: Mobile ISD
        type: string
      odAccountLimitDetailsList:
        type: array
        items:
          $ref: '#/definitions/odAccountLimitDetailsModel'
 
  odAccountLimitDetailsModel:
    description: "odAccountLimitDetailsModel"
    type: object
    properties:
      id:
        description: account limit details ID
        type: string
      odApplicantDetailsId:
        description: Id of Overdraft Applicant Details table
        type: string
      processRefNo:
        description: "Process reference number of ODAccountLimit details master model"
        type: string
        maxLength: 20
      applicationNumber:
        type: string
        description: "Application number"
      channel:
        type: string
        description: Channel
      action:
        type: string
        description: action
      limitType:
        type: string
        description: limitType
      linkageReference:
        type: string
        description: linkageReference
      branchCode:
        type: string
        description: branchCode
      branch:
        type: string
        description: branch
      odLimitAmountCcy:
        type: string
        description: odLimitAmountCcy
      odLimitAmount:
        type: number
        description: odLimitAmount
      limitStartDate:
        type: string
        description: limitStartDate
      limitEndDate:
        type: string
        description: limitEndDate
      linkedAmount:
        type: number
        description: linkedAmount
      rateValue:
        type: number
        description: rateValue
      rateCode:
        type: string
        description: rateCode
      spread:
        type: number
        description: spread
      finalRate:
        type: number
        description: finalRate
      avalLinkageAmountCcy:
        type: string
        description: avalLinkageAmountCcy
      avalLinkageAmount:
        type: number
        description: avalLinkageAmount
 
  odAccountLimitDetailsMasterCollection:
    description: Collection of odAccountLimitDetailsMasterModel.
    type: object
    properties:
      odAccountLimitDetailsMasterModelList:
        type: array
        items:
          $ref: '#/definitions/odAccountLimitDetailsMasterModel'
  GenericDatasegmentModel:
    allOf:
      - type: object
        discriminator: resource_type
  StageSkippingDetalModel:
    type: object
    properties:
      processRefNo:
        description: Process Reference Number
        type: string
      underWritingRqrd:
        description: Initial Funding Required
        type: string
      applicationNumber:
        description: Initial Funding Required
        type: string