#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ODAdvanceDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: odAdvanceDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /odAdvanceDetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for odAdvance Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/odAdvanceDetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odAdvanceDetails
      summary: Adds a new odAdvanceDetails.
      description: Adds a new odAdvanceDetails. Add additional information here for this endpoint.
      operationId: addODAdvanceDetails
      parameters:
      - name: odAdvanceDetails
        in: body
        description: Request Body that contains data required for creating a new odAdvanceDetails
        required: true
        schema:
          $ref: '#/definitions/odAdvanceDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created odAdvanceDetails.
          headers:
            Location:
              description: URL of newly created odAdvanceDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - odAdvanceDetails
      summary: Retrieves the list of existing odAdvanceDetails.
      description: Retrieves the list of existing odAdvanceDetails. Add additional information here for the this endpoint.
      operationId: getAllODAdvanceDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the odAdvanceDetails that needs to be fetched
        required: false
        type: string
      - name: processRefNo
        in: query
        description: processRefNo of the user odAdvanceDetails needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/odAdvanceDetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - odAdvanceDetails
      summary: Get By ID
      description: Retrieves the odAdvanceDetails by Id Add additional information here for the this endpoint.
      operationId: getODAdvanceDetailsById
      parameters:
      - name: id
        in: path
        description: ID of the odAdvanceDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the odAdvanceDetails based on given ID.
          schema:
            $ref: '#/definitions/odAdvanceDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odAdvanceDetails
      summary: Update an existing odAdvanceDetails.
      description: Update an existing odAdvanceDetails. Add additional information here for the this endpoint.
      operationId: updateODAdvanceDetails
      parameters:
      - name: id
        in: path
        description: id of the odAdvanceDetails that need to be updated
        required: true
        type: string
      - name: odAdvanceDetails
        in: body
        description: Request Body that contains data required for updating an existing odAdvanceDetails
        required: true
        schema:
          $ref: '#/definitions/odAdvanceDetailsMasterModel'
      responses:
        200:
          description: Returns updated odAdvanceDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - odAdvanceDetails
      summary: Deletes the odAdvanceDetails identified by given ID.
      description: Deletes the odAdvanceDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteODAdvanceDetails
      parameters:
      - name: id
        in: path
        description: Id of the odAdvanceDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 odAdvanceDetailsMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: "Process reference number of Mandate details master model"
      type: string
      maxLength: 20         
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action 
     applicationDate:
      type: string
      description: "Date of application"    
     limitId:
      type: string
      description: limit unique id 
     limitAmountCcy:
      type: string
      description: limit amount currency     
     limitAmount:
      type: number
      description: limit amount
     limitStartDate:
      type: string
      description: limit start date
     limitEndDate:
      type: string
      description: limit end date       
     addAufDetails:
      type: boolean
      description: Flag to check OD advance details validation
 odAdvanceDetailsMasterCollection:
    description: Collection of odAdvanceDetailsMasterModel.
    type: object
    properties:
     odAdvanceDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/odAdvanceDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type