#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ODSecuredDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: odSecuredDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /odSecuredDetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for odSecured Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/odSecuredDetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odSecuredDetails
      summary: Adds a new odSecuredDetails.
      description: Adds a new odSecuredDetails. Add additional information here for this endpoint.
      operationId: addODSecuredDetails
      parameters:
      - name: odSecuredDetails
        in: body
        description: Request Body that contains data required for creating a new odSecuredDetails
        required: true
        schema:
          $ref: '#/definitions/odSecuredDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created odSecuredDetails.
          headers:
            Location:
              description: URL of newly created odSecuredDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - odSecuredDetails
      summary: Retrieves the list of existing odSecuredDetails.
      description: Retrieves the list of existing odSecuredDetails. Add additional information here for the this endpoint.
      operationId: getAllODSecuredDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the odSecuredDetails that needs to be fetched
        required: false
        type: string
      - name: processRefNo
        in: query
        description: processRefNo of the user odSecuredDetails needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/odSecuredDetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - odSecuredDetails
      summary: Get By ID
      description: Retrieves the odSecuredDetails by Id Add additional information here for the this endpoint.
      operationId: getODSecuredDetailsById
      parameters:
      - name: id
        in: path
        description: ID of the odSecuredDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the odSecuredDetails based on given ID.
          schema:
            $ref: '#/definitions/odSecuredDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odSecuredDetails
      summary: Update an existing odSecuredDetails.
      description: Update an existing odSecuredDetails. Add additional information here for the this endpoint.
      operationId: updateODSecuredDetails
      parameters:
      - name: id
        in: path
        description: id of the odSecuredDetails that need to be updated
        required: true
        type: string
      - name: odSecuredDetails
        in: body
        description: Request Body that contains data required for updating an existing odSecuredDetails
        required: true
        schema:
          $ref: '#/definitions/odSecuredDetailsMasterModel'
      responses:
        200:
          description: Returns updated odSecuredDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - odSecuredDetails
      summary: Deletes the odSecuredDetails identified by given ID.
      description: Deletes the odSecuredDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteODSecuredDetails
      parameters:
      - name: id
        in: path
        description: Id of the odSecuredDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 odSecuredDetailsMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: "Process reference number of ODSecured details master model"
      type: string
      maxLength: 20    
     applicationDate:
      type: string
      description: "Date of application"    
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action
     collateralType:
      type: string
      description: collateralType
     collateralValueCcy:
      type: string
      description: collateralValueCcy 
     collateralValue:
      type: number
      description: collateralValue
     attributes:
      type: string
      description: attributes
     dimensionType:
      type: string
      description: dimensionType
     dimension:
      type: number
      description: dimension
     thirdPartyCollateral:
      type: string
      description: thirdPartyCollateral      
     securityReferenceNo:
      type: string
      description: securityReferenceNo
     branchCode:
      type: string
      description: branchCode
     avalLinkageAmountCcy:
      type: string
      description: avalLinkageAmountCcy
     avalLinkageAmount:
      type: number
      description: avalLinkageAmount
     odLimitAmountCcy:
      type: string
      description: odLimitAmountCcy
     odLimitAmount:
      type: number
      description: odLimitAmount
     linkagePercentage:
      type: number
      description: linkagePercentage
     limitStartDate:
      type: string
      description: limitStartDate
     limitEndDate:
      type: string
      description: limitEndDate
     rateValue:
      type: number
      description: rateValue
     rateType:
      type: string
      description: rateType
     spread:
      type: number
      description: spread
     finalRate:
      type: number
      description: finalRate
     make:
      type: string
      description: make
     model:
      type: string
      description: model
     investmentType:
      type: string
      description: Investment Type
     branch:
      type: string
      description: branch
     bank:
      type: string
      description: bank
     maturityDate:
      type: string
      description: maturity date
     name:
      type: string
      description: name    
 odSecuredDetailsMasterCollection:
    description: Collection of odSecuredDetailsMasterModel.
    type: object
    properties:
     odSecuredDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/odSecuredDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type