#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ODUnsecuredDetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: odUnsecuredTempDetails Service
host: "api-plato.us.oracle.com:8080"
basePath: /odUnsecuredTempDetails
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: SavingApplication
  description: API for odUnsecured Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/odUnsecuredTempDetails:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odUnsecuredTempDetails
      summary: Adds a new odUnsecuredTempDetails.
      description: Adds a new odUnsecuredTempDetails. Add additional information here for this endpoint.
      operationId: addODUnsecuredDetails
      parameters:
      - name: odUnsecuredTempDetails
        in: body
        description: Request Body that contains data required for creating a new odUnsecuredTempDetails
        required: true
        schema:
          $ref: '#/definitions/odUnsecuredTempDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created odUnsecuredTempDetails.
          headers:
            Location:
              description: URL of newly created odUnsecuredTempDetails.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - odUnsecuredTempDetails
      summary: Retrieves the list of existing odUnsecuredTempDetails.
      description: Retrieves the list of existing odUnsecuredTempDetails. Add additional information here for the this endpoint.
      operationId: getAllODUnsecuredDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the odUnsecuredTempDetails that needs to be fetched
        required: false
        type: string
      - name: processRefNo
        in: query
        description: processRefNo of the user odUnsecuredTempDetails needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/odUnsecuredTempDetails/{id}:
    get:
      produces:
      - application/json
      tags:
      - odUnsecuredTempDetails
      summary: Get By ID
      description: Retrieves the odUnsecuredTempDetails by Id Add additional information here for the this endpoint.
      operationId: getODUnsecuredDetailsById
      parameters:
      - name: id
        in: path
        description: ID of the odUnsecuredTempDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the odUnsecuredTempDetails based on given ID.
          schema:
            $ref: '#/definitions/odUnsecuredTempDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - odUnsecuredTempDetails
      summary: Update an existing odUnsecuredTempDetails.
      description: Update an existing odUnsecuredTempDetails. Add additional information here for the this endpoint.
      operationId: updateODUnsecuredDetails
      parameters:
      - name: id
        in: path
        description: id of the odUnsecuredTempDetails that need to be updated
        required: true
        type: string
      - name: odUnsecuredTempDetails
        in: body
        description: Request Body that contains data required for updating an existing odUnsecuredTempDetails
        required: true
        schema:
          $ref: '#/definitions/odUnsecuredTempDetailsMasterModel'
      responses:
        200:
          description: Returns updated odUnsecuredTempDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - odUnsecuredTempDetails
      summary: Deletes the odUnsecuredTempDetails identified by given ID.
      description: Deletes the odUnsecuredTempDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteODUnsecuredDetails
      parameters:
      - name: id
        in: path
        description: Id of the odUnsecuredTempDetails that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 odUnsecuredTempDetailsMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: "Process reference number of Mandate details master model"
      type: string
      maxLength: 20     
     applicationDate:
      type: string
      description: "Date of application"    
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action
     limitId:
      type: string
      description: limit unique id 
     limitAmountCcy:
      type: string
      description: limit amount currency     
     limitAmount:
      type: number
      description: limit amount
     limitStartDate:
      type: string
      description: limit start date
     limitEndDate:
      type: string
      description: limit end date
     renewTod:
      type: string
      description: renewTod
     renewPeriodType:
      type: string
      description: Renew Period Type
     renewPeriod:
      type: number
      description: Renew Period
     nextRenewalLimitCcy:
      type: string
      description: Next Renewal Limit CCY
     nextRenewalLimit:
      type: number
      description: Next Renewal Limit       
     addUnsecureTempDetails:
      type: boolean
      description: Flag to check Temporary OD Limit Details validation       
 odUnsecuredTempDetailsMasterCollection:
    description: Collection of odUnsecuredTempDetailsMasterModel.
    type: object
    properties:
     odUnsecuredTempDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/odUnsecuredTempDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type