#  This source is part of the Oracle Banking Virtual Account Management Software Product. 
#  Copyright  2018 , 2021 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : TxnExchQueueService.yaml
#  **
#  ** Module     : obvam
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  Rahul kumar 
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a server for hosting Transaction exchange rate queue." 
 version: "1.0.0"
 title: "Transaction exchange rate queue Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "txnExchQueueService"
   description: "API for Transaction exhange rate queue Operations. Header request parameters."

schemes:
- "https"

paths:

# path to update a record
#
#  supprorted http methods POST
#
# path example ../service/txnqueues

 /service/txnqueues:
  post:
   tags:
    - "txnExchQueueService"
   summary: "Update a transaction exchange rate queue record."
   description: "Update a transaction echange rate queue record and transaction status."
   operationId: "updateTxnQueue"
   parameters:
    - name: "txnqueues" 
      in: "body" 
      description: "Request Body that contains data required for updating a transaction echange rate queue record." 
      required: true
      schema:
       $ref: "#/definitions/TxnMasterServiceDTO"
   responses:
    201: 
     description: "Returns message of succes or failure." 
     headers:
      Location:
       description: "URL of updated transaction echange rate queue record" 
       type: "string"
     schema:
       $ref: "#/definitions/TxnRateQueueServiceResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
definitions:
 TxnMasterServiceDTO:
  type: object
  allOf:
  - type: object
    properties:
     txnRefNo:
      type: string
     sourceCode:
      type: string
     sourceReferenceNo:
      type: string
     bookingDate:
      type: string
      pattern: "[0-9]{4}[-][0-9]{2}[-][0-9]{2}"
     initiationDate:
      type: string
      pattern: "[0-9]{4}[-][0-9]{2}[-][0-9]{2}"
     authStatus:
      type: string
     transactionStatus:
      type: string
     originalReferenceNo:
      type: string
     checkerDtStamp:
      type: string
      format: date
     checkerId:
      type: string
     makerDtStamp:
      type: string
      format: date
     makerId:
      type: string
     initialMaker:
      type: string
     initialChecker:
      type: string   
     txnDetailsServiceDTOList:
      type: array
      items:
       $ref: '#/definitions/TxnDetailsServiceDTO'
 TxnDetailsServiceDTO:
  type: object
  properties:
     txnRefNo:
      type: string
     entrySerialNo:
      type: number
     drCrInd:
      type: string
     txnAccount:
      type: string
     txnAccountBrn:
      type: string
     txnCcy:
      type: string
     txnAmount:
      type: number
     txnCode:
      type: string
     valueDate:
      type: string
      pattern: "[0-9]{4}[-][0-9]{2}[-][0-9]{2}"
     txnAccountCcy:
      type: string
     amtInTxnAccCcy:
      type: number
     exchRate:
      type: number
     realAccCcy:
      type: string
     amtInRealAccCcy:
      type: number
     realAccClass:
      type: string
     excRateTxccyRaccy:
      type: number
     reconRefNo:
      type: string
     addlText:
      type: string
     reportingInfo:
      type: string
     accountType:
      type: string
     realAccountNo:
      type: string
     realAccountBrn:
      type: string
     ecaOrBlockRefNo:
      type: string
     ddaOffset:
      type: string
     forceDebit:
      type: string
     skipDDAEntries:
      type: string
     txnExchRateQueueServiceDTO:
       $ref: '#/definitions/TxnExchRateQueueServiceDTO' 
 TxnExchRateQueueServiceDTO:
  type: object
  properties:
     txnRefNo:
      type: string
     entrySerialNo:
      type: number
     excRateTxccyRaccy:
      type: number 
     amtInRealAccCcy:
      type: number
     newExcRateTxccyRaccy:
      type: number 
     newAmtInRealAccCcy:
      type: number
     authStatus:
      type: string     
     checkerDtStamp:
      type: string
      format: date
     checkerId:
      type: string
     makerDtStamp:
      type: string
      format: date
     makerId:
      type: string 
 TxnWrapperServiceDTO:
  type: object
  properties:
     data:
      $ref: '#/definitions/TxnMasterServiceDTO'
 TransactionWrapperServiceDTO:
  type: object
  properties:
     data:
      $ref: '#/definitions/TxnMasterServiceDTO'
 TxnRateQueueServiceResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/TxnRateQueueServiceResponseDto"
   data:
    $ref: "#/definitions/TxnMasterServiceDTO"
 ResponseResourceSupport:
  type: object
 TxnRateQueueServiceResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/TxnRateQueueServiceResponseCode"
   requestId:
    type: string
 TxnRateQueueServiceResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 ResourceSupport:
  allOf:
   - type: object
     discriminator: resource_type  
 TxnServiceCollection:
  type: object
  properties:
   data:
    type: array
    items:
     $ref: "#/definitions/TxnMasterServiceDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
