swagger: "2.0"
info:
  description: "This is a sample server Legal server.  You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)"
  version: "1.0.0"
  title: "Legal Service"
host: "whf00bdn:7751"
basePath: "/legal-services"
consumes:
  - "application/json"
  - "application/xml"
produces:
  - "application/json"
  - "application/xml"
tags:
  - name: "LegalAPI"
    description: "API for Legal's Operations"
    
schemes:
- "https"

paths:
  /service/v1/opinion/{entityRefNo}:
    get:
      tags:
        - "legalOpinionService"
      summary: "Retrieves the list of existing legals."
      description:  "Retrieves the list of existing legals."
      operationId: "getAllLegalMainByEntityRefNo"
      parameters:
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "entityRefNo"
          in: "path"
          description: "Id of the user that needs to be fetched"
          required: true
          type: "string"
        - name: "limit"
          in: "query"
          required: false
          description: "limit to be fetched"
          type: "integer"
        - name: "offset"
          in: "query"
          required: false
          description: "offset of the limit"
          type: "integer"
        - name: "externalSystem"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystemReferenceNo"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false                  
      responses:
        200:
          description: "Successful performs the operation"
          schema:
            $ref: "#/definitions/ResponseModel"
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"
  /service/v1/opinion/delete/{entityRefNo}:
    delete:
      tags:
        - "legalOpinionService"
      summary: "Soft Deletes the legal opinion identified by given ID."
      description:  "Soft Deletes the legal opinion identified by given ID."
      operationId: "softDeleteLegal"
      parameters:
        - name: "entityRefNo"
          in: "path"
          description: "collateral Id of the legal opinion that needs to be fetched"
          required: true
          type: "string"
        - name: "appId"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystem"
          in: "header"
          type: "string"
          required: false
        - name: "externalSystemReferenceNo"
          in: "header"
          type: "string"
          required: false
        - name: "userId"
          in: "header"
          type: "string"
          required: true
        - name: "branchCode"
          in: "header"
          type: "string"
          required: false
        - name: "authToken"
          in: "header"
          type: "string"
          required: true
        - name: "tenantId"
          in: "header"
          type: "string"
          required: false
        - name: "contentType"
          in: "header"
          type: "string"
          required: false
        - name: "branchDate"
          in: "header"
          type: "string"
          format: "date-time"
          required: false                        
      responses:
        200:
          description: "Successful operation."
        400:
          description: "Malformed syntax."
        401:
          description: "Request does not have sufficient credentials."
        403:
          description: "Request is not authorized."
        500:
          description: "Internal error"           