swagger: "2.0"
info:
  description: "This yaml contains all the clg model"
  version: "1.0.0"
  title: ""
basePath: "/clg"
tags:
- name: "ClgWeb"
schemes:
- "http"
paths:
 /clg/:
  get:
   tags:
   - "ClgWeb"
   operationId: "clg"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"
definitions:
  ClgTxnMasterModel:
    type: object
    description: "Clearing transaction master model"
    properties:
     datasegment:
       type: string
       description: "CCA Name"
     txnControllerRefNo:
       type: string
       description: "Txn ref no from UI"
     recordId:
       type: string
       description: "Id"
     txnRefNumber:
       type: string
       description: "Transaction Ref. No"
     batchNumber:
       type: number
       description: "Batch number"
     instrumentCcy:
       type: string
       description: "Instrument currency"
     totalAmt:
       type: string
       description: "Total amount"
     status:
       type: string
       description: "Txn Status"
     txnDate:
       type: string
       format: date
       description: "Txn Date"
     clgTxnType:
       type: string
       description: "Clearing Txn type"
     version:
       type: number
       description: "Version No"
     ecaTag:
       type: string
       description: "ECA Tag"
     createdBy:
       type: string
       description: "Created by"
     createdTs:
       type: string
       format: date
       description: "Created timestamp"
     updatedBy:
       type: string
       description: "Updated by"
     updatedTs:
       type: string
       format: date
       description: "Updated timestamp"
     clgTxnDSModelDtls:
       type: array
       items:
          $ref: '#/definitions/ClgTxnDSModel'
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     prcDtls:
       type: array
       items:
          $ref: "#/definitions/PrcDtlsModel"
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"
  ClgTxnDSModel:
    type: object
    description: "Clearing transaction model"
    properties:
     datasegment:
       type: string
       description: "CCA Name"
     txnControllerRefNo:
       type: string
       description: "Txn ref no from UI"
     parentId:
       type: string
     instrumentType:
       type: string
       description: "Instrument Type"
     payeeName:
       type: string
       description: "Payee Name"
     payeeRoutingNo:
       type: string
       description: "Payee routing no."
     clearingType:
       type: string
       description: "Clearing Type"
     handoffStatus:
       type: string
       description: "Handoff status"
     recordId:
       type: string
     cashAmtCcy:
       type: string
       description: "Cash Amount Curreny"
     cashAmt:
       type: number
       description: "Cash Amount"
     chequeDate:
       type: string
       format: date
       description: "Cheque Date"
     chequeNumber:
       type: string
       description: "Cheque Number"
     eventCode:
       type: string
       description: "Event Code"
     ejId:
       type: string
       description: "EJ ID"
     emailId:
       type: string
       description: "Email"
     fromAccountBranch:
       type: string
       description: "From Account Branch"
     fromAccountCcy:
       type: string
       description: "From Account Currency"
     fromAccountNumber:
       type: string
       description: "From Account Number"
     fromAccountAmt:
       type: number
       description: "From Account Amount"
     mobileNumber:
       type: string
       description: "Mobile Number"
     narrative:
       type: string
       description: "Narrative"
     orginalExchangeRate:
       type: number
       description: "Orginal Exchange Rate"
     payee:
       type: string
       description: "Payee"
     productCode:
       type: string
       description: "Product Code"
     reversalDate:
       type: string
       format: date
       description: "Reversal Date"
     stationId:
       type: string
       description: "Station ID"
     toAccountBranch:
       type: string
       description: "To Account Branch"
     toAccountCcy:
       type: string
       description: "To Account Currency"
     toAccountNumber:
       type: string
       description: "To Account Number"
     toAccountAmt:
       type: number
       description: "To Account Amount"
     txnBranchCode:
       type: string
       description: "Txn Branch Code"
     functionCode:
       type: string
       description: "Function Code"
     txnCustomer:
       type: string
       description: "Txn Customer"
     tellerId:
       type: string
       description: "TellerId"
     txnDate:
       type: string
       format: date
       description: "Txn Date"
     txnRefNumber:
       type: string
       description: "Transaction Ref. No"
     ecaRefNo:
       type: string
       description: "ECA Ref. No"
     txnSeqNumber:
       type: number
       description: "Teller Sl No"
     uniqueIdentifierNumber:
       type: string
       description: "Unique Identifier No"
     uniqueIdentifierType:
       type: string
       description: "Unique Identifier Type"
     userRefNumber:
       type: string
       description: "User Reference No"
     valueDate:
       type: string
       format: date
       description: "Value Date"
     versionNumber:
       type: number
       description: "Version No"
     exchangeRate:
       type: number
       description: "Exchange Rate"
     negotiatedExchangeRate:
       type: number
       description: "Negotiated Exchange Rate"
     negotiationReferenceNumber:
       type: string
       description: "negotiation Reference Number"
     createdBy:
       type: string
       description: ""
     createdTs:
       type: string
       format: date
       description: ""
     updatedBy:
       type: string
       description: ""
     updatedTs:
       type: string
       format: date
       description: ""
     chequeDepositDate:
       type: string
       format: date
       description: ""
     chequeAmt:
       type: number
       description: ""
     drawerAccountNo:
       type: string
       description: ""
     drawerName:
       type: string
       description: ""
     totalCharges:
       type: number
       description: ""
     clgBankCode:
       type: string
       description: ""
     clgBranchCode:
       type: string
       description: ""
     routingNo:
       type: string
       description: ""
     totalCharge:
       type: number
       description: ""
     payeeAccNo:
       type: number
       description: ""
     rejectCode:
       type: string
       description: "Cheque reject code"
     rejectReason:
       type: string
       description: "Cheque reject reason"
     orgSourceRef:
       type: string
       description: "Original transaction number of outward or inward clearing transaction for rejecting cheque"
     clgTxnType:
       type: string
       description: "Clearing Txn type"
     depositMode:
       type: string
       description: "Deposit mode account or GL"
     glDesc:
       type: string
       description: "GL acc description" 
     additionalFields:
       type: string
       description: ""
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     prcDtls:
       type: array
       items:
          $ref: "#/definitions/PrcDtlsModel"
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"
  ObpayClgReturnReq:
    properties:
      txnRefNo:
       type: string
       description: "Transaction Ref. No"
      functionCode:
       type: string
       description: "FunctionCode"
      version:
       type: string
       description: "version"
      header:
       $ref: '#/definitions/ClgReturnHeader'    
      txnDet:
       $ref: '#/definitions/ClgReturnTransactionDetail'
  ClgReturnHeader:
    properties:
      userId:
        type: string
  ClgReturnTransactionDetail:
    properties:
      txnBranch:
        type: string
      orgSourceCode:
        type: string
      orgSourceRefNo:
        type: string
      rejectCode:
        type: string
      orgTxnRefNo:
        type: string
      remarks:
        type: string