#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : EntityCreationDetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/entitycreations:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Entitycreation
      summary: Adds a new Entitycreation.
      description: Adds a new Entitycreation. Add additional information here for this endpoint.
      operationId: createEntitycreation
      parameters:
      - name: Entitycreation
        in: body
        description: Request Body that contains data required for creating a new Entitycreation
        required: true
        schema:
          $ref: '#/definitions/EntityCreationModel'
      responses:
        201:
          description: Returns the Id of the newly created Entitycreation
          headers:
            Location:
              description: URL of newly created Entitycreation
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Entitycreation
      summary: Retrieves the list of existing Entitycreation.
      description: Retrieves the list of existing Entitycreation. Add additional information here for the this endpoint.
      operationId: getAllEntitycreation
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/entitycreations/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - Entitycreation
      summary: Retrieves the Entitycreation by id.
      description: Retrieves the Entitycreation by id. Add additional information here for the this endpoint.
      operationId: getEntitycreationById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the Entitycreation based on given applicationNumber.
          schema:
            $ref: '#/definitions/EntityCreationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Entitycreation
      summary: Update an existing Entitycreation.
      description: Update an existing Entitycreation. Add additional information here for the this endpoint.
      operationId: updateEntitycreation
      parameters:
      - name: id
        in: path
        description: id of the Entitycreation that need to be updated
        required: true
        type: string
      - name: Entitycreation
        in: body
        description: Request Body that contains data required for updating an existing Entitycreation
        required: true
        schema:
          $ref: '#/definitions/EntityCreationModel'
      responses:
        200:
          description: Returns updated Entitycreation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - Entitycreation
      summary: Deletes the Entitycreation identified by given ID.
      description: Deletes the Entitycreation identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteEntitycreation
      parameters:
      - name: id
        in: path
        description: Id of the Entitycreation that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  EntityCreationModel:
    description: Entitycreation model
    type: object
    properties:
      id:
        description: Id of the Entitycreation
        type: string
        maxLength: 36
      applicationNumber:
        description: Application Number of the Entitycreation
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string   
      customerId:
        description: customerId
        type: string
        maxLength: 20
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      EntityCreationDetails:
        type: array
        items:
          $ref: '#/definitions/EntityCreationDetailsModel'
  EntityCreationDetailsModel:
    description: EntityCreationDetails model
    type: object
    required:
    - applicantNumber
    - applicantName
    properties:
      id:
        description: Id of the entity creation details
        type: string
      entitycreationId:
        description: Id of the entitycreation
        type: string
      prefix:
        description: prefix
        type: string
        maxLength: 10
      entityName:
        description: entityName
        type: string
        maxLength: 50
      entityDescription:
        description: entityDescription
        type: string
        maxLength: 100
      entityType:
        description: entityType
        type: string
        maxLength: 20
      faxReq:
        description: faxNoReq
        type: string
        maxLength: 1
      faxNo:
        description: faxNo
        type: string
        maxLength: 20
      phoneNoReq:
        description: phoneNoReq
        type: string
        maxLength: 1
      phoneNo:
        description: phoneNo
        type: string
        maxLength: 20
      isoCode:
        description: isoCode
        type: string
        maxLength: 10
      emailId:
        description: emailId
        type: string
      fpmlReq:
        description: fpmlReq
        type: string
        minLength: 0
        maxLength: 1
      affiliation:
        description: affiliation
        type: string
        maxLength: 100
  EntityCreationCollection:
    description: Collection of Entitycreation.
    type: object
    properties:
      EntitycreationList:
        type: array
        items:
          $ref: '#/definitions/EntityCreationModel'
