#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : Addoncardholder.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: addoncardholder Service
host: "api-plato.us.oracle.com:8080"
basePath: /addoncardholder
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: AddonCardService
  description: API for AddonCardService Data segment Operations
schemes:  
- http
paths:
  /web/v1/addoncardholder:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - AddoncardHolder
      summary: Adds a new Addoncardholder.
      description: Adds a new Addoncardholder. Add additional information here for this endpoint.
      operationId: addAddoncardHolder
      parameters:
      - name: Addoncardholder
        in: body
        description: Request Body that contains data required for creating a new Addoncardholder
        required: true
        schema:
          $ref: '#/definitions/AddoncardHolderMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created AddoncardHolder.
          headers:
            Location:
              description: URL of newly created AddoncardHolder.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - AddoncardHolder
      summary: Retrieves the list of existing AddoncardHolder.
      description: Retrieves the list of existing AddoncardHolder. Add additional information here for the this endpoint.
      operationId: getAllAddoncardHolder
      parameters:
      - name: processRefNo
        in: query
        description: Process Reference Number of the Addoncardholder that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the Addoncardholder that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/addoncardholder/{id}:
    get:
      produces:
      - application/json
      tags:
      - AddoncardHolder
      summary: Get By ID
      description: Retrieves the Addoncardholder by Id Add additional information here for the this endpoint.
      operationId: getAddoncardHolderById
      parameters:
      - name: id
        in: path
        description: ID of the Addoncardholder that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AddoncardHolder based on given ID.
          schema:
            $ref: '#/definitions/AddoncardHolderMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - AddoncardHolder
      summary: Update an existing AddoncardHolder.
      description: Update an existing AddoncardHolder. Add additional information here for the this endpoint.
      operationId: updateAddoncardHolder
      parameters:
      - name: id
        in: path
        description: id of the Addoncardholder that need to be updated
        required: true
        type: string
      - name: AddoncardHolder
        in: body
        description: Request Body that contains data required for updating an existing AddoncardHolder
        required: true
        schema:
          $ref: '#/definitions/AddoncardHolderMasterModel'
      responses:
        200:
          description: Returns updated AddoncardHolder
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - AddoncardHolder
      summary: Deletes the AddoncardHolder identified by given ID.
      description: Deletes the AddoncardHolder identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAddoncardHolder
      parameters:
      - name: id
        in: path
        description: Id of the AddoncardHolder that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'          
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

definitions:
 AddoncardHolderMasterModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Reference Number of the AddoncardHolderMasterModel
      type: string
      maxLength: 20
     applicationDate:
      type: string
      description: Date of application 
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action
     currencyCode:
      type: string
      description: Currency Code
     addoncardHolderModel:
      type: array
      items:
       $ref: '#/definitions/AddoncardHolderModel'
 AddoncardHolderModel:
   description: "AddoncardHolder Model"
   type: object
   properties:
    id:
     description: Id of the AddoncardHolderModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Reference Number of the AddoncardHolderModel
     type: string
     maxLength: 20
    applicationNumber:
     description: Application Number of the AddoncardHolderModel
     type: string
     maxLength: 20
    addoncardHolderMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    cardHolderImgId:
     description: AddonCard Holder Image Id
     type: string
    existingCustomer:
     description: Is Existing Customer?
     type: boolean
    cifNumber:
     description: CIFNumber
     type: string
     maxLength: 15
    relationType:
     type: string
     description: Relation type
    title:
     type: string
     description: Title
     maxLength: 8
    firstName:
     type: string
     description: First Name
     maxLength: 25
    middleName:
     description: Middle Name
     type: string
     maxLength: 25
    lastName:
     type: string
     description: Last Name
     maxLength: 25
    fullName:
     type: string
     description: Full Name
    gender:
     type: string
     description: Gender
    dateOfBirth:
     type: string
     description: Date of Birth
    idType:
     type: string
     description: ID Type
    uniqueIDNumber:
     type: string
     description: Unique ID Number
    validTill:
     type: string
     description: Valid Till
    embossedName:
     type: string
     description: Embossed Name
    limitAmount:
     type: number
     description: Card Limit Amount
    imgPicCard:
     type: string
     description: Image on Picture Card
    partyId:
     type: string
     description: Party ID
    address:
     type: array
     items:
      $ref: '#/definitions/Address'
 Address:
   description: "Address Model"
   type: object
   properties:
    id:
     description: Id of the Address model
     type: string
     maxLength: 36
    processRefNo:
     description: "Process Reference Number of the AddoncardHolder Model"
     type: string
     maxLength: 20     
    addoncardHolderDetailsId:
     description: Id of the parent model
     type: string
     maxLength: 36
    addressType:
     description: addressType
     type: string
     maxLength: 50
    preferredMailAddress:
     description: preferredMailAddress
     type: boolean
    buildingName:
     type: string
     description: buildingName
     maxLength: 50
    streetName:
     type: string
     description: streetName
     maxLength: 50
    localityName:
     type: string
     description: localityName
     maxLength: 50
    city:
     type: string
     description: City
     maxLength: 50
    state:
     type: string
     description: State
     maxLength: 50
    country:
     type: string
     description: Country
     maxLength: 50
    pinCode:
     type: string
     description: Pin code
     maxLength: 20
    email:
     type: string
     description: Email address
     maxLength: 50
    mobileIsd:
     type: string
     description: ISD of mobile number
     maxLength: 10
    mobileNo:
     type: integer
     format: int64
     description: Mobile number
     maxLength: 10
    phoneIsd:
     type: string
     description: ISD of phone number
     maxLength: 10
    phoneNo:
     type: integer
     format: int64
     description: Phone number
     maxLength: 10
 AddoncardHolderMasterCollection:
    description: Collection of AddoncardHolderMasterModel.
    type: object
    properties:
     addoncardHolderMasterModelList:
      type: array
      items:
       $ref: '#/definitions/AddoncardHolderMasterModel'
 AddoncardHolderInitiationModel:
   description: "AddoncardHolderInitiationModel"
   type: object
   properties:
    applicationNumber:
     description: Application Number to Initialize Applicant
     type: string
     maxLength: 20
    channel:
     description: source channel from where request came to Initialize Applicant
     type: string
     maxLength: 30
    initiationDetails:
     type: array
     items:
      $ref: '#/definitions/InitiationDetails'  
   required:
    - applicationNumber
 InitiationDetails:
   description: "InitiationDetails"
   type: object
   properties:
    processRefNo:
     description: "processRefNo for which Applicant data needs to be fetched"
     type: string  
     maxLength: 20     
    initializationId:
     description: initialization id to Initialize Applicant
     type: string
     maxLength: 20
   required:
    - processRefNo
    - initializationId
 AddoncardHolderSubmitModel:
    description: AddoncardHolderSubmitModel
    type: object
    properties:
      applicationNumber:
        description: Application Number
        type: string
        maxLength: 20
      id:
        description: Application Id
        type: string
      dataSegmentCode:
        description: DataSegment List
        type: string
      stageCode:
        description: Stage Code
        type: string
      processCode:
        description: Process Code
        type: string
      lastCompletedStageCode:
        description: Last Completed Stage Code
        type: string
      currentActiveStageCode:
        description: Current Active Stage Code
        type: string  
      applicationStatus:
        description: application status
        type: string 
    required:
     - applicationNumber
     - dataSegmentCode        
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type    
 AddoncardHolderCIFModel:
    description: AddoncardHolderCIFModel
    type: object
    properties:
     existingCustomer:
      description: Is Existing Customer
      type: boolean
     cifNumber:
      description: CIFNumber
      type: string
     applicantId:
      description: Applicant Id
      type: string
     applicantName:
      description: applicantName
      type: string  
     customerImage:
      description: customerImage
      type: "string"