#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : cardpreference.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: cardpreference Service
host: "api-plato.us.oracle.com:8080"
basePath: /cardpreference
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
- name: CardPreference
  description: API for CardPreference Details Data segment Operations
schemes:  
- http
paths:
  /web/v1/cardpreference:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - CardPreference
      summary: Adds a new CardPreference.
      description: Adds a new CardPreference. Add additional information here for this endpoint.
      operationId: addCardPreference
      parameters:
      - name: cardPreferenceModel
        in: body
        description: Request Body that contains data required for creating a new CardPreference
        required: true
        schema:
          $ref: '#/definitions/CardPreferenceModel'
      responses:
        201:
          description: Returns the Id of the newly created CardPreference.
          headers:
            Location:
              description: URL of newly created CardPreference.
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      tags:
      - CardPreference
      summary: Retrieves the list of existing CardPreference.
      description: Retrieves the list of existing CardPreference. Add additional information here for the this endpoint.
      operationId: getAllCardPreference
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the CardPreference that needs to be fetched
        required: true
        type: string
      - name: processRefNo
        in: query
        description: Process Reference Number of the CardPreference that needs to be fetched
        required: true
        type: string        
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/cardpreference/{id}:
    get:
      produces:
      - application/json
      tags:
      - CardPreference
      summary: Get By ID
      description: Retrieves the CardPreference by Id Add additional information here for the this endpoint.
      operationId: getCardPreferenceById
      parameters:
      - name: id
        in: path
        description: ID of the CardPreference that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CardPreference based on given ID.
          schema:
            $ref: '#/definitions/CardPreferenceModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - CardPreference
      summary: Update an existing CardPreference.
      description: Update an existing CardPreference. Add additional information here for the this endpoint.
      operationId: updateCardPreference
      parameters:
      - name: id
        in: path
        description: id of the CardPreference that need to be updated
        required: true
        type: string
      - name: cardPreferenceModel
        in: body
        description: Request Body that contains data required for updating an existing CardPreference
        required: true
        schema:
          $ref: '#/definitions/CardPreferenceModel'
      responses:
        200:
          description: Returns updated CardPreference
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      tags:
      - CardPreference
      summary: Deletes the CardPreference identified by given ID.
      description: Deletes the CardPreference identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCardPreference
      parameters:
      - name: id
        in: path
        description: Id of the CardPreference that needs to be deleted
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'          
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 CardPreferenceModel:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Reference Number
      type: string
      maxLength: 20
     applicationNumber:
      description: applicationNumber
      type: string      
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action
     applicantId:
      type: string
      description: Applicant ID
     cifNumber:
      type: string
      description: Cif Number
     applicantName:
      type: string
      description: Applicant Name
     cardType:
      type: string
      description: Card Type 
     affinityProgram:
      type: string
      description: Affinity Program
     pictureCard:
      type: string
      description: ""
      pattern: '[Y,N]' 
     nfc:
      type: string
      description: ""
      pattern: '[Y,N]'
     cardCurrency:
      type: string
      description: Card Currency
     cardLimit:
      type: number
      description: Card Limit
     addonAllowed:
      type: string
      description: Addon Card Allowed
     embossedName:
      type: string
      description: Embossed Name
     statementGenDate:
      type: integer
      description: Statement Generation Date
     statementType:
      type: string
      description: Statement Type
     noOfAddon:
      type: integer
      description: Number of Addon Card
     imgPicCard:
      type: string
      description: Image Picture on Card
     statementDeliveryType:
      type: array
      items:
       type: string
      description: Statement Delivery Type
     productImage:
      description: Business Product Image
      type: string
     productCode:
      description: Business Product Code
      type: string
     productName:
      type: string
      description: Business Product Name
     cardTxnLimitList:
      type: array
      items:
       $ref: '#/definitions/CardTransactionLimitModel'
 CardTransactionLimitModel:
  description: Card Transaction Limit Model
  type: object
  properties:
   id:
    description: Id of the CardTransactionLimitModel
    type: string
    maxLength: 36
   cardPreferenceId:
    description: Id of the Card Preference Model
    type: string
   limitType:
    description: Limit Type
    type: string
   maxLimitAmt:
    description: Maximum Limit Amount
    type: number
   dailyLimit:
    description: Daily Limit
    type: number
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type