#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : chargedetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: CreditCard Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-creditcardapplication-services
tags:
- name: CreditCardApplication
  description: API for CreditCardApplication Operations
schemes:
- http
paths:
  /web/v1/chargedetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ChargeDetails
      summary: Adds a new ChargeDetails.
      description: Adds a new ChargeDetails. Add additional information here for this endpoint.
      operationId: addChargeDetails
      parameters:
      - name: ChargeDetails
        in: body
        description: Request Body that contains data required for creating a new ChargeDetails
        required: true
        schema:
          $ref: '#/definitions/ChargeDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created ChargeDetails
          headers:
            Location:
              description: URL of newly created ChargeDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ChargeDetails
      summary: Retrieves the list of existing ChargeDetails.
      description: Retrieves the list of existing ChargeDetails. Add additional information here for the this endpoint.
      operationId: getAllChargeDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/chargedetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ChargeDetails
      summary: Retrieves the ChargeDetails by id.
      description: Retrieves the ChargeDetails by id. Add additional information here for the this endpoint.
      operationId: getChargeDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ChargeDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/ChargeDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ChargeDetails
      summary: Update an existing ChargeDetails.
      description: Update an existing ChargeDetails. Add additional information here for the this endpoint.
      operationId: updateChargeDetails
      parameters:
      - name: id
        in: path
        description: id of the ChargeDetails that need to be updated
        required: true
        type: string
      - name: ChargeDetails
        in: body
        description: Request Body that contains data required for updating an existing ChargeDetails
        required: true
        schema:
          $ref: '#/definitions/ChargeDetailsMasterModel'
      responses:
        200:
          description: Returns updated ChargeDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ChargeDetails
      summary: Deletes the ChargeDetails identified by given ID.
      description: Deletes the ChargeDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteChargeDetails
      parameters:
      - name: id
        in: path
        description: Id of the ChargeDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 ChargeDetailsMasterModel:
  description: ChargeDetailsMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the ChargeDetailsMasterModel
      type: string
      maxLength: 20 
     channel:
      type: string
      description: Channel
     action:
      type: string
      description: action
     totalCharges:
      description: Total Charges
      type: number
     currency:
      description: Currency
      type: string
     chargeDetailsModel:
      type: array
      items:
       $ref: '#/definitions/ChargeDetailsModel'
    required:
     - processRefNo
     - applicationNumber
     - totalCharges
     - stageCode
     - creditRatingDetailsModel
 ChargeDetailsModel:
   description: "ChargeDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the ChargeDetailsModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the ChargeDetailsModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    chargeDetailsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    componentCode:
     description: Component Code
     type: string 
    udeId:
     description: udeId
     type: string
    chargeType:
     description: Charge Type
     type: string
    amount:
     description: Amount
     type: number 
    rate:
     description: Rate
     type: number
     format: double   
    waive:
     description: Waive 
     type: boolean
    waiveAllowed:
     description: waiveAllowed
     type: boolean
    amendAllowed:
     description: amendAllowed
     type: boolean 
    udeType:
     description: udeType
     type: string 
    seqNo:
     description: Seq No
     type: integer 
   required:
    - processRefNo
    - applicationNumber
    - componentCode
    - udeId
    - chargeType
    - seqNo
 ChargeDetailsMasterCollection:
    description: Collection of ChargeDetailsMasterModel.
    type: object
    properties:
     chargeDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/ChargeDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 