#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : creditcarddetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: CreditCard Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cc-creditcardapplication-services
tags:
- name: CreditCardApplication
  description: API for CreditCardApplication Operations
schemes:
- http
paths:
  /web/v1/creditcarddetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Adds a new CreditCardDetails.
      description: Adds a new CreditCardDetails. Add additional information here for this endpoint.
      operationId: addCreditCardDetails
      parameters:
      - name: CreditCardDetails
        in: body
        description: Request Body that contains data required for creating a new CreditCardDetails
        required: true
        schema:
          $ref: '#/definitions/CreditCardDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created CreditCardDetails
          headers:
            Location:
              description: URL of newly created CreditCardDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Retrieves the list of existing CreditCardDetails.
      description: Retrieves the list of existing CreditCardDetails. Add additional information here for the this endpoint.
      operationId: getAllCreditCardDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      - name: businessProductCode
        in: query
        description: businessProductCode of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/creditcarddetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Retrieves the CreditCardDetails by id.
      description: Retrieves the CreditCardDetails by id. Add additional information here for the this endpoint.
      operationId: getCreditCardDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the CreditCardDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/CreditCardDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Update an existing CreditCardDetails.
      description: Update an existing CreditCardDetails. Add additional information here for the this endpoint.
      operationId: updateCreditCardDetails
      parameters:
      - name: id
        in: path
        description: id of the CreditCardDetails that need to be updated
        required: true
        type: string
      - name: CreditCardDetails
        in: body
        description: Request Body that contains data required for updating an existing CreditCardDetails
        required: true
        schema:
          $ref: '#/definitions/CreditCardDetailsModel'
      responses:
        200:
          description: Returns updated CreditCardDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Deletes the CreditCardDetails identified by given ID.
      description: Deletes the CreditCardDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteCreditCardDetails
      parameters:
      - name: id
        in: path
        description: Id of the CreditCardDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/updatecreditcardnumber/{processRefNo}/{cardNumber}:
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardDetails
      summary: Update an existing CreditCardDetails.
      description: Update an existing CreditCardDetails. Add additional information here for the this endpoint.
      operationId: updateCreditCardNumber
      parameters:
      - name: processRefNo
        in: path
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: cardNumber
        in: path
        description: businessProductCode of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns updated CreditCardDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
definitions:
  CreditCardDetailsModel:
    description: CreditCardDetails model
    type: object
    properties:
      id:
        description: Id of the CreditCardDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      cardType:
        description: Card Type
        type: string
      cardCurrencyCode:
        description: cardCurrencyCode
        type: string
        maxLength: 4
      cardLimitType:
        description: cardLimitType
        type: string      
      cardLimitAmount:
        description: cardLimitAmount
        type: number            
      productName:
        description: productName
        type: string
        maxLength: 100
      productCode:
        description: productCode
        type: string
        maxLength: 50
      applicationDate:
        description: Application Date
        type: string      
      productImage:
        description: Product Image
        type: string
      productSummary:
        description: Product Summary
        type: string
      bankName:
        description: Bank Name
        type: string
      branchName:
        description: Branch Name
        type: string
      remarks:
        description: remarks
        type: string
      version:
        description: version
        type: integer
      recordStat:
        description: version
        type: string
      channel:
        description: Channel
        type: string
      action:
        type: string
        description: action
      minCardLimit:
        description: min Card Limit
        type: number
      maxCardLimit:
        description: max Card Limit
        type: number
      cardNumber:
        description: Credit Card Number
        type: string
      
  CreditCardDetailsCollection:
    description: Collection of CreditCardDetails.
    type: object
    properties:
      CreditCardDetailsList:
        type: array
        items:
          $ref: '#/definitions/CreditCardDetailsModel'
