#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : creditcardproductdetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: CreditCard Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-cc-creditcardapplication-services
tags:
- name: CreditCardApplication
  description: API for CreditCardApplication Operations
schemes:
- http
paths:
  /service/v1/creditcardproductdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardProductDetails
      summary: Adds a new CreditCardProductDetails.
      description: Adds a new CreditCardProductDetails. Add additional information here for this endpoint.
      operationId: addCreditCardProductDetails
      parameters:
      - name: CreditCardProductDetails
        in: body
        description: Request Body that contains data required for creating a new CreditCardProductDetails
        required: true
        schema:
          $ref: '#/definitions/CreditCardProductDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created CreditCardProductDetails
          headers:
            Location:
              description: URL of newly created CreditCardProductDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error    
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardProductDetails
      summary: Retrieves the list of existing CreditCardDetails.
      description: Retrieves the list of existing CreditCardDetails. Add additional information here for the this endpoint.
      operationId: getCreditCardProductDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/CreditCardProductDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

  /service/v1/getHostProductList:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardProductDetails
      summary: Retrieves the list of existing HostDetails.
      description: Retrieves the list of existing HostDetails. Add additional information here for the this endpoint.
      operationId: getAllHostProductList
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/String'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

  /service/v1/getHostProductByCode/{productcode}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardProductDetails
      summary: Retrieves the HostDetails by product code.
      description: Retrieves the HostDetails by id. Add additional information here for the this endpoint.
      operationId: getHostProductByCode
      parameters:
      - name: productcode
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the HostDetails based on given processRefNo.
          schema:
              $ref: '#/definitions/String'      
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

  /service/v1/getCreditCardNumber:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - CreditCardProductDetails
      summary: Retrieves the CreditCardNumber.
      description: Retrieves the CreditCardNumber
      operationId: getCreditCardNumber
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/String'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

definitions:
  CreditCardProductDetailsModel:
    description: CreditCardProductDetails model
    type: object
    properties:
      processRefNo:
        description: Process Reference Number
        type: string
      applicationNumber:
        description: Application Number
        type: string
      businessProductCode:
        description: Business Product Code
        type: string
      businessProductName:
        description: businessProductName
        type: string
      productType:
        description: product type
        type: string
      productSubType:
        description: Product Sub Type
        type: string
      businessProductImage:
        description: business Product Image
        type: string
      businessProductSummary:
        description: business Product Summary
        type: string
      branchesAllowed:
        description: branches Allowed
        type: string
      hostProductCode:
        description: host productCode
        type: string
      hostProductDesc:
        description: host Product Desc
        type: string
      cardType:
        description: card Type
        type: string
      affnityProgName:
        description: affinity Program Name
        type: string
      pictureCard:
        description: picture Card
        type: string
      minCardLimit:
        description: min Card Limit
        type: number
      maxCardLimit:
        description: max Card Limit
        type: number
      nfc:
        description: nfc
        type: string
      addonCard:
        description: addOn Card Allowed
        type: string
      noofAddonCard:
        description: noOfAddOnCard
        type: number
      addonCardLimit: 
        description: addOn Card Limit
        type: string
      internationalUsage:
        description: internationalUsage
        type: string
      ccyDisallowed:
        description: currenciesAllowed
        type: string
      assessmentMethodCC:
        description: assessmentMode
        type: string                  
      stmtGenDt:
        description: Statement Generation Date
        type: string 
      stmtType:
        description: Statement Type
        type: string
      stmtDelType:
        description: Statement Delivery Mode
        type: string
      creditCardProductTxnLimitList:
        type: array
        items:
         $ref: '#/definitions/CreditCardProductTransactionModel'

    required:
      - processRefNo
      - applicationNumber
      - businessProductCode
  CreditCardProductDetailsCollection:
    description: Collection of CreditCardProductDetails.
    type: object
    properties:
      CreditCardProductDetailsList:
        type: array
        items:
          $ref: '#/definitions/CreditCardProductDetailsModel'

  CreditCardProductTransactionModel:
    description: CreditCardProductTransaction model
    type: object
    properties:
      productDetailsMasterId:
        description: Product Details Master ID
        type: string
      lmtTyp:
        description: Limit Type
        type: string
      maxAlwdLmt:
        description: Maximum Allowed Lmt
        type: number
      dlyLmt:
        description: daily Lmt
        type: number