#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : scheduleandmargin.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/scheduleandmargin:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleAndMargin
      summary: Adds a new ScheduleAndMargin.
      description: Adds a new ScheduleAndMargin. Add additional information here for this endpoint.
      operationId: addScheduleAndMargin
      parameters:
      - name: ScheduleAndMargin
        in: body
        description: Request Body that contains data required for creating a new ScheduleAndMargin
        required: true
        schema:
          $ref: '#/definitions/ScheduleAndMarginModel'
      responses:
        201:
          description: Returns the Id of the newly created ScheduleAndMargin
          headers:
            Location:
              description: URL of newly created ScheduleAndMargin
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleAndMargin
      summary: Retrieves the list of existing ScheduleAndMargin.
      description: Retrieves the list of existing ScheduleAndMargin. Add additional information here for the this endpoint.
      operationId: getAllScheduleAndMargin
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/scheduleandmargin/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleAndMargin
      summary: Retrieves the ScheduleAndMargin by id.
      description: Retrieves the ScheduleAndMargin by id. Add additional information here for the this endpoint.
      operationId: getScheduleAndMarginById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ScheduleAndMargin based on given applicationNumber.
          schema:
            $ref: '#/definitions/ScheduleAndMarginModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleAndMargin
      summary: Update an existing ScheduleAndMargin.
      description: Update an existing ScheduleAndMargin. Add additional information here for the this endpoint.
      operationId: updateScheduleAndMargin
      parameters:
      - name: id
        in: path
        description: id of the ScheduleAndMargin that need to be updated
        required: true
        type: string
      - name: ScheduleAndMargin
        in: body
        description: Request Body that contains data required for updating an existing ScheduleAndMargin
        required: true
        schema:
          $ref: '#/definitions/ScheduleAndMarginModel'
      responses:
        200:
          description: Returns updated ScheduleAndMargin
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ScheduleAndMargin
      summary: Deletes the ScheduleAndMargin identified by given ID.
      description: Deletes the ScheduleAndMargin identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteScheduleAndMargin
      parameters:
      - name: id
        in: path
        description: Id of the ScheduleAndMargin that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ScheduleAndMarginModel:
    description: ScheduleAndMargin model
    type: object
    properties:
      id:
        description: Id of the ScheduleAndMargin
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string
      remarks:
        description: remarks
        type: string
      drawdownTrancheDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownTrancheDetailsModel'
  DrawdownTrancheDetailsModel:
    description: DrawdownTrancheDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownTrancheDetails
        type: string
      scheduleMarginId:
        description: scheduleMarginId
        type: string
      trancheId:
        description: trancheId
        type: string
      trancheName:
        description: trancheName
        type: string
      drawdownProducts:
        type: array
        items:
          $ref: '#/definitions/DrawdownProductsModel'
  DrawdownProductsModel:
    description: DrawdownProducts model
    type: object
    properties:
      id:
        description: Id of the DrawdownProducts
        type: string
      drawdownTrancheDetailsId:
        description: drawdownTrancheDetailsId
        type: string
      drawdownProductCode:
        description: drawdownProductCode
        type: string
      drawdownScheduleDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownScheduleDetailsModel'
      drawdownMarginDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownMarginDetailsModel'
  DrawdownScheduleDetailsModel:
    description: DrawdownScheduleDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownScheduleDetails
        type: string
      drawdownProductsId:
        description: drawdownProductsId
        type: string
      component:
        description: component
        type: string
      startReference:
        description: startReference
        type: string
      frequency:
        description: frequency
        type: string
      unit:
        description: unit
        type: number
      month:
        description: month
        type: number
      scheduleDate:
        description: scheduleDate
        type: number
  DrawdownMarginDetailsModel:
    description: DrawdownMarginDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownMarginDetails
        type: string
      drawdownProductsId:
        description: drawdownProductsId
        type: string
      marginComponent:
        description: marginComponent
        type: string
      marginBasis:
        description: marginBasis
        type: string
      basisAmount:
        description: basisAmount
        type: string
      defaultMarginRate:
        description: defaultMarginRate
        type: number
  ScheduleAndMarginCollection:
    description: Collection of ScheduleAndMargin.
    type: object
    properties:
      ScheduleAndMarginList:
        type: array
        items:
          $ref: '#/definitions/ScheduleAndMarginModel'
