swagger: "2.0"
info:
  version: "1.0.0"
  title: "Loan And Payment Definitions"

paths:
  /:
    get:
      responses:
        201:
          description: ""

definitions:
  FinanceTransactionModel:
    description: "Finance Transaction Model"
    type: "object"
    properties:
      id:
        type: "string"
        description: "Id"
      financeRefNo:
        type: "string"
        description: "Finance Reference Number"
      seqNo:
        type: "integer"
        format: "int64"
        description: "Sequence Number"
      requestId:
        type: "string"
        description: "Request Id"
      branchCode:
        type: "string"
        description: "Branch Code"
      productCode:
        type: "string"
        description: "Product Code"
      operationCode:
        type: "string"
        description: "Operation Code"
      programCode:
        type: "string"
        description: "Program Code"
      programName:
        type: "string"
        description: "Program Name"
      buyerId:
        type: "string"
        description: "Buyer Id"
      buyerName:
        type: "string"
        description: "Buyer Name"
      buyerDivCode:
        type: string
        description: "Buyer Division Code"
      buyerDivName:
        type: string
        description: "Buyer Division Name"
      supplierId:
        type: "string"
        description: "Supplier Id"
      supplierName:
        type: "string"
        description: "Supplier Name"
      supplierDivCode:
        type: string
        description: "Supplier Division Code"
      supplierDivName:
        type: string
        description: "Supplier Division Name"
      debtor:
        type: "string"
        description: "Debtor"
      debtorName:
        type: "string"
        description: "Debtor Name"
      startDate:
        type: "string"
        description: "Start Date"
      tenor:
        type: "integer"
        format: "int64"
        description: "Tenor"
      maturityDate:
        type: "string"
        description: "Maturity Date"
      totalInstrumentAmtCcy:
        type: "string"
        description: "Total Instrument Amount Currency"
      totalInstrumentAmt:
        type: "number"
        description: "Total Instrument Amount"
      financePCT:
        type: "number"
        description: "Finance PCT"
      financeAmtCcy:
        type: "string"
        description: "Finance Amount Currency"
      financeAmt:
        type: "number"
        description: "Finance Amount"
      exchangeRate:
        type: "number"
        description: "Exchange Rate"
      processingDate:
        type: "string"
        description: "Processing Date"
      settlementProcessingDate:
        type: "string"
        description: "Settlement Processing Date"
      makerId:
        type: "string"
        description: "Maker Id"
      makerDateStamp:
        type: "string"
        description: "Maker Date Stamp"
      authId:
        type: "string"
        description: "Authorization Id"
      authDateStamp:
        type: "string"
        description: "Authorization Date Stamp"
      financeStatus:
        type: "string"
        description: "Finance Status"
      clRefNo:
        type: "string"
        description: "Cl Reference Number"
      settlementRefNo:
        type: "string"
        description: "Settlement Reference Number"
      settlementMethod:
        type: "string"
        description: "Settlement Method"
      totalSettlementAmt:
        type: "number"
        description: "Total Settlement Amount"
      creditReceived:
        type: "string"
        description: "Credit Received"
      creditAccount:
        type: "string"
        description: "Credit Account"
      paymentParty:
        type: "string"
        description: "Payment Party"
      accountType:
        type: "string"
        description: "Account Type"
      settlementAmtAllocated:
        type: "number"
        description: "Settlement Amount Allocated"
      balanceAmtToBeAllocated:
        type: "number"
        description: "Balance Amount To Be Allocated"
      settlementAmtAllocation:
        type: "string"
        description: "Settlement Amount Allocation"
      manualAllocation:
        type: "string"
        description: "Manual Allocation"
      pastDueDate:
        type: "string"
        description: "Past Due Date"
      valueDate:
        type: "string"
        description: "Value Date"
      principalOSAmount:
        type: "number"
        description: "Principal OS Amount"
      interestOSAmount:
        type: "number"
        description: "Interest OS Amount"
      totalOSAmount:
        type: "number"
        description: "Total OS Amount"
      valueDtdIntOSAmt:
        type: "number"
        description: "Value Dated Interest OS Amount"
      overdueIntOSAmt:
        type: "number"
        description: "Overdue Interest OS Amount"
      valueDtdOverdueIntOSAmt:
        type: "number"
        description: "Value Dated Overdue Interest OS Amount"
      paymentAmt:
        type: "number"
        description: "Payment Amount"
      appropPaymentAmt:
        type: "number"
        description: "Appropriate Payment Amount"
      appropriationSequence:
        type: "string"
        description: "Appropriation Sequence"
      pmtToPrncplOS:
        type: "number"
        description: "Payment To Principle OS"
      pmtToIntOS:
        type: "number"
        description: "Payment To Interest OS"
      pmtToOverdueIntOS:
        type: "number"
        description: "Payment To Overdue Interest OS"
      productDescription:
        type: "string"
        description: "Product Description"
      productCategory:
        type: "string"
        description: "Product Category"
      maxTenorAllowed:
        type: "number"
        description: "Maximum Tenor Allowed"
      minTenorAllowed:
        type: "number"
        description: "Minimum Tenor Allowed"
      minFinPCT:
        type: "number"
        description: "Minimum Finance PCT"
      maxFinPCT:
        type: "number"
        description: "Maximum Finance PCT"
      holidayTreatment:
        type: "string"
        description: "Holiday Treatment"
      productType:
        type: "string"
        description: "Product Type"
      preferredDisbursementMode:
        type: "string"
        description: "Preferred Disbursement Mode"
      settlementCcy:
        type: "string"
        description: "Settlement Currency"
      totalOSAmountSettlementCcy:
        type: "number"
        description: "Total OS Amount Settlement Currency"
      refund:
        type: "number"
        description: "Refund"
      settlementExchangeRate:
        type: "number"
        description: "Settlement Exchange Rate"
      totalOSPostAllocation:
        type: "number"
        description: "Total OS Post Allocation"
      settleFinExcRate:
        type: "number"
        description: "Settlement Finance Exchange Rate"
      stageId:
        type: "string"
        description: "Stage Id"
      errorCode:
       type: "string"
       description: "Error Code"
      errorDescription:
       type: "string"
       description: "Error Description"
      graceDays:
        type: "number"
        description: "Grace Days"
      partRepaymentAllowed:
        type: "string"
        description: "Part Repayment Allowed"
      staleStatus:
        type: "string"
        description: "Stale Status"
      minFinanciableAmt:
        type: "number"
        description: "Minimum Financiable Amount"
      maxFinanciableAmt:
        type: "number"
        description: "Maximum Financiable Amount"
      minReFinPCT:
        type: "number"
        description: "Minimum ReFin PCT"
      maxReFinPCT:
        type: "number"
        description: "Maximum ReFin PCT"
      penIntOSAmt:
        type: "number"
        description: "Pen Interest OS Amount"
      pmtToPenOnIntOS:
        type: "number"
        description: "Payment To Pen On Interest OS"
      valueDtdPenIntOSAmt:
        type: "number"
        description: "Value Dated Pen Interest OS Amount"
      interestAmortized:
        type: "number"
        description: "Interest Amortized"
      withRecourse:
        type: "string"
        description: "With Recourse"
      transactionFlow:
        type: "string"
        description: "Transaction Flow"
      totalMarginAmount:
        type: "number"
        description: "Total Margin Amount"
      interestType:
        type: "string"
        description: "Interest Type"
      interestRefundAmt:
        type: "number"
        description: "Interest Refund Amount"
      interestRefundHandling:
        type: "string"
        description: "Interest Refund Handling"
      interestRefundPmtMode:
        type: "string"
        description: "Interest Refund Payment Mode"
      interestBearingPartyRole:
        type: "string"
        description: "Interest Bearing Party Role"
      isFromRecon:
        type: "string"
        description: "Is From Recon"
      interestPaidUpfront:
        type: "number"
        description: "Interest Paid Upfront"
      delinquencyStatus:
        type: "string"  
        description: "Delinquency Status"
  FinanceTransactionCollection:
    description: "Collection of Finance Transaction Models."
    type: "object"
    properties:
      financeTransactionList:
        type: "array"
        items:
          $ref: "#/definitions/FinanceTransactionModel"  
  ResponseModel:
    description: "Response Model"
    type: "object"
    properties:
      data:
        type: "object"
      errors:
        type: "object"
      paging:
        type: "object"