#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : applicantfinancials.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/applicantfinancials:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicantFinancials
      summary: Adds a new ApplicantFinancials.
      description: Adds a new ApplicantFinancials. Add additional information here for this endpoint.
      operationId: addApplicantFinancials
      parameters:
      - name: ApplicantFinancials
        in: body
        description: Request Body that contains data required for creating a new ApplicantFinancials
        required: true
        schema:
          $ref: '#/definitions/ApplicantFinancialsModel'
      responses:
        201:
          description: Returns the Id of the newly created ApplicantFinancials
          headers:
            Location:
              description: URL of newly created ApplicantFinancials
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicantFinancials
      summary: Retrieves the list of existing ApplicantFinancials.
      description: Retrieves the list of existing ApplicantFinancials. Add additional information here for the this endpoint.
      operationId: getAllApplicantFinancials
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/applicantfinancials/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicantFinancials
      summary: Get a  ApplicantFinancials.
      description: Get a  ApplicantFinancial by given id. Add additional information here for the this endpoint.
      operationId: getApplicantFinancialsById
      parameters:
      - name: id
        in: path
        description: id of the ApplicantFinancials that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated ApplicantFinancials
          schema:
            $ref: '#/definitions/ApplicantFinancialsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicantFinancials
      summary: Update an existing ApplicantFinancials.
      description: Update an existing ApplicantFinancials. Add additional information here for the this endpoint.
      operationId: updateApplicantFinancials
      parameters:
      - name: id
        in: path
        description: id of the ApplicantFinancials that need to be updated
        required: true
        type: string
      - name: ApplicantFinancials
        in: body
        description: Request Body that contains data required for updating an existing ApplicantFinancials
        required: true
        schema:
          $ref: '#/definitions/ApplicantFinancialsModel'
      responses:
        200:
          description: Returns updated ApplicantFinancials
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ApplicantFinancials
      summary: Deletes the ApplicantFinancials identified by given ID.
      description: Deletes the ApplicantFinancials identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteApplicantFinancials
      parameters:
      - name: id
        in: path
        description: Id of the ApplicantFinancials that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ApplicantFinancialsModel:
   description: ApplicantFinancials model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     required:
     - applicationNumber
     - fixedAssets
     - intangibleAssets
     - issuedCapital
     - turnOver
     properties:
      fixedAssetsCurrencyCode:
        description: Fixed Assets Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      fixedAssets:
        description: Fixed Assets of the ApplicantFinancials
        type: string
        maxLength: 20
      intangibleAssetsCurrencyCode:
        description: Intangible Assets Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      intangibleAssets:
        description: Intangible Assets of the ApplicantFinancials
        type: string
        maxLength: 20
      nonCurrentAssetsCurrencyCode:
        description: Non Current Assets Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      nonCurrentAssets:
        description: Non Current Assets of the ApplicantFinancials
        type: string
        maxLength: 20
      currentAssetsCurrencyCode:
        description: current Assets Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      currentAssets:
        description: current Assets of the ApplicantFinancials
        type: string
        maxLength: 20
      issuedCapitalCurrencyCode:
        description: issued Capital Currency  of the ApplicantFinancials
        type: string
        maxLength: 3
      issuedCapital:
        description: issued Capital  of the ApplicantFinancials
        type: string
        maxLength: 20
      valuePaidUpCapitalCurrencyCode:
        description: value PaidUp Capital Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      valuePaidUpCapital:
        description: ' value PaidUp Capital of the ApplicantFinancials'
        type: string
        maxLength: 20
      subsidyFromGovtCurrencyCode:
        description: ' subsidy From Govt Currency of the ApplicantFinancials'
        type: string
        maxLength: 3
      subsidyFromGovt:
        description: subsidy From Govt  of the ApplicantFinancials
        type: string
        maxLength: 20
      generalReservesCurrencyCode:
        description: ' general Reserves Currency of the ApplicantFinancials'
        type: string
        maxLength: 3
      generalReserves:
        description: ' general Reserves of the ApplicantFinancials'
        type: string
        maxLength: 20
      creditBalanceInPlCurrencyCode:
        description: ' credit Balance In Pl Currency of the ApplicantFinancials'
        type: string
        maxLength: 3
      creditBalanceInPl:
        description: ' credit Balance In Pl of the ApplicantFinancials'
        type: string
        maxLength: 20
      termLiabilitiesCurrencyCode:
        description: ' term Liabilities Currency of the ApplicantFinancials'
        type: string
        maxLength: 3
      termLiabilities:
        description: ' term Liabilities of the ApplicantFinancials'
        type: string
        maxLength: 20
      currentLiabilitiesCurrencyCode:
        description: ' current Liabilities Currency of the ApplicantFinancials'
        type: string
        maxLength: 3
      currentLiabilities:
        description: ' current Liabilities of the ApplicantFinancials'
        type: string
        maxLength: 20
      turnOverCurrencyCode:
        description: turn Over Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      turnOver:
        description: turn Over of the ApplicantFinancials
        type: string
        maxLength: 20
      operationsActivitiesCurrencyCode:
        description: operations Activities Currency of the ApplicantFinancials
        type: string
        maxLength: 3
      operationsActivities:
        description: operations Activities  of the ApplicantFinancials
        type: string
        maxLength: 20
  ApplicantFinancialsCollection:
    description: Collection of ApplicantFinancials.
    type: object
    properties:
      ApplicantFinancialsList:
        type: array
        items:
          $ref: '#/definitions/ApplicantFinancialsModel'
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type