swagger: "2.0"
info:
  description: "Service to issue cheque book."
  version: "1.0.0"
  title: "Customer Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "CustomerAddress"
    description: ""

schemes:
  - "https"

paths:
 /customer/:
  get:
   tags:
   - "CashWeb"
   operationId: "cash"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"

definitions:
  CustomerAddressDTO:
    type: object
    description: "Customer Address"
    allOf:
      - type: object
        properties:
          id:
            type: string
            description: ""
          txnControllerRefNo:
            type: string
            description: ""
          recordId:
            type: string
            description: ""
          datasegment:
            type: string
            description: ""
          customerNo:
            type: string
          country:
            type: string
          loc:
            type: string
          language:
            type: string
          customerName1:
            type: string
          shortName:
            type: string
          caddr1:
            type: string
            description: ""
          caddr2:
            type: string
            description: ""
          caddr3:
            type: string
            description: ""
          caddr4:
            type: string
            description: ""
          ccountry:
            type: string
            description: ""
          psameAsCor:
            type: string
            description: ""
          paddr1:
            type: string
            description: ""
          paddr2:
            type: string
            description: ""
          paddr3:
            type: string
            description: ""
          paddr4:
            type: string
            description: ""
          pcountry:
            type: string
            description: ""
          rsameAsPer:
            type: string
            description: ""
          raddr1:
            type: string
            description: ""
          raddr2:
            type: string
            description: ""
          raddr3:
            type: string
            description: ""
          raddr4:
            type: string
            description: ""
          rcountry:
            type: string
            description: ""
          createdBy:
            type: string
            description: ""
          createdTs:
            type: string
            format: date
            description: ""
          narrative:
            type: string
            description: ""
          reqDate:
            type: string
            format: date
            description: ""
          status:
            type: string
            description: ""
          txnBrnCode:
            type: string
            description: ""
          txnDate:
            type: string
            format: date
            description: ""
          txnRefNo:
            type: string
            description: ""
          updatedBy:
            type: string
            description: ""
          updatedTs:
            type: string
            format: date
            description: ""
          version:
            type: number
            description: ""
          additionalFields:
            type: string
            description: ""
          addDtls:
              $ref: '#/definitions/AdditionalTransactionDetails'
          txnDtls:
              $ref: '#/definitions/TransactionDetails'
          overrideDtls:
            type: array
            items: 
              $ref: "#/definitions/BaseOutcomeModel"
  
  StopCardRequest:
    type: object
    description: "User Stop Card Request"
    allOf:
      - type: object
        properties:
          recordId:
            type: string
            description: ""
          txnControllerRefNo:
            type: string
            description: ""
          datasegment:
            type: string
            description: ""
          branchCode:
            type: string
            description: ""
          accountNumber:
            type: string
            description: ""
          cardNumber:
            type: string
            description: ""
          customerId:
            type: string
            description: ""
          txnRefNo:
            type: string
            description: ""
          status:
            type: string
            description: ""  
          addDtls:
            $ref: '#/definitions/AdditionalTransactionDetails'
          txnDtls:
            $ref: '#/definitions/TransactionDetails'
          overrideDtls:
            type: array
            items:
              $ref: "#/definitions/BaseOutcomeModel"
  
  ExtSysDtls:
    type: object
    description: "User Misc GL Credit Request"
    allOf:
      - type: object
        properties:
          sourceCode:
            type: string
            description: ""
          sourceUser:
            type: string
            description: ""
          sourceRole:
            type: string
            description: ""  
          sourceRefNo:
            type: string
            description: ""
          stationId:
            type: string
            description: ""
          txnBranch:
            type: string
            description: ""            
  
  ExtStopCardRequest:
    type: object
    description: "User Cheque Book Request"
    allOf:
      - type: object
        properties:
          extSysDtls:
              $ref: '#/definitions/ExtSysDtls'
          stopCardRequest:
              $ref: '#/definitions/StopCardRequest'               
