swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Application Invitation Status Service
host: 10.184.157.121:9000
basePath: /applicationinvitaionstatus-services
tags:
- name: ApplicationInvitationStatus
  description: API for Application invitation status
schemes:
- http
paths: 
  /web/v1/applicationinvitaionstatus:
   post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - Applicationinvitaionstatus
      summary: get the taskinfo details
      description: get the taskinfo details
      operationId: populateApplicationinvitaionstatusData
      parameters:
      - name: SyndicationInvitationStatusModel
        in: body
        description: Request Body that contains data required for populating invitation satus data for dashboard widget
        required: true
        schema:
          $ref: 'dashboards.yaml#/definitions/SyndicationInvitationStatusModel'
      responses:
        201:
          description: Returns the Id of the newly created SyndicationInvitationStatusModel
          headers:
            Location:
              description: URL of newly created SyndicationInvitationStatusModel
              type: string
          type: string
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error