#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : widgetfilterpreference.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Widget Filter Preference Service
host: 10.184.157.121:9000
basePath: /widgetfilterpreference-services
tags:
- name: WidgetFilterPreference
  description: API for Widget Filter Preference resource and its child resources
schemes:
- http
paths:  
  /web/v1/widgetfilterpreference:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - WidgetFilterPreference
      summary: Creates Widget Filter Preference 
      description: save into the WidgetFilterPreference table. Add additional information here for this endpoint.
      operationId: createWidgetFilterPreference
      parameters:
      - name: widgetFilterPreferenceModel
        in: body
        description: Request Body that contains data required for creating WidgetFilterPreference
        required: true
        schema:
          $ref: '#/definitions/WidgetFilterPreferenceModel'
      responses:
        201:
          description: Returns created status code.
          headers:
            Location:
              description: URL of newly created widgetFilterPreference
              type: string
          schema:
            $ref: '../commondefinitions.yaml#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - WidgetFilterPreference
      summary: Update Widget Filter Preference 
      description: update into the WidgetFilterPreference table. Add additional information here for this endpoint.
      operationId: updateWidgetFilterPreference
      parameters:
      - name: widgetFilterPreferenceModel
        in: body
        description: Request Body that contains data required for creating WidgetFilterPreference
        required: true
        schema:
          $ref: '#/definitions/WidgetFilterPreferenceModel'
      responses:
        200:
          description: Returns success status code.
          schema:
            $ref: '../commondefinitions.yaml#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - WidgetFilterPreference
      summary: Gets Widget Filter Preference of given  widgetName and filterName
      description: Gets Widget Filter Preference of given  widgetName and filterName
      operationId: getWidgetFilterPreference
      parameters:
      - name: widgetName
        in: query
        description: Widget Name for which Filter Preference needs to be fetched
        required: false
        type: string
      - name: filterName
        in: query
        description: Filter Name for which Preference needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: returns JsonObject containing Widget Filter Preference
          schema:
            $ref: '#/definitions/WidgetFilterPreferenceModelCollection'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error      
  /web/v1/widgetfilterpreference/{id}:
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - WidgetFilterPreference
      summary: Delete Widget Filter Preference of given ID
      description: Delete Widget Filter Preference of given ID
      operationId: deleteWidgetFilterPreference
      parameters:
      - name: id
        in: path
        description: ID for which Filter Preference needs to be delete
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
          schema:
            $ref: '../commondefinitions.yaml#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
  
definitions:
  WidgetFilterPreferenceModelCollection:
    description: WidgetFilterPreferenceModelCollection
    type: object
    properties:
      data:
          type: array
          items:
            $ref: '#/definitions/WidgetFilterPreferenceModel'
  WidgetFilterPreferenceModel:
    description: WidgetFilterPreferenceModel
    type: object
    required:
    - filterName
    - widgetName
    properties:
      id:
        description: Id of the Widget Filter Preference
        type: string
      userId:
        description: User Id
        type: string
        maxLength: 20
      filterName:
        description: Filter Name
        type: string
        maxLength: 50
      widgetName:
        description: Widget Name
        type: string
        maxLength: 50
      defaultFilter:
        description: Default Filter
        type: boolean
      filterPreference:
          $ref: '#/definitions/FilterPreferenceModel'
  FilterPreferenceModel:
    description: FilterPreferenceModel
    type: object
    properties:
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: processRefNumber
        type: string  
      rmId:
        description: rmId
        type: string
      processes:
          type: array
          items:
            $ref: '#/definitions/ProcessCodeModel'
  ProcessCodeModel:
    description: ProcessCodeModel
    type: object
    properties:
      processCode:
        description: Process Code
        type: string
        maxLength: 20
      stageCodes:
          type: array
          items:
            type: string