#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : cmc
#  ** 
# /*******************************************************************************
# * This source is part of the Oracle Banking Software Product.
# * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
# *
# * No part of this work may be reproduced, stored in a retrieval system, adopted or tr
# *
# * Oracle Financial Services Software Limited.
# * Oracle Park, Off Western Express Highway,
# * Goregaon (East),
# * Mumbai - 400 063, India.
# ******************************************************************************/
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server corevirtualaccounts server." 
 version: "1.0.0"
 title: "corevirtualaccounts Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "corevirtualaccounts"
   description: "This service is used to create virtual accounts in plato common core as external virtual accounts.
External Virtual Accounts will be populated from OBVAM account service on authorization of new Virtual account."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../corevirtualaccounts

 /service/corevirtualaccounts:
  get:
   tags:
    - "corevirtualaccounts"
   summary: "Get all valid corevirtualaccounts."
   description:  "Get all valid corevirtualaccounts. This endpoints will be used to Get all valid corevirtualaccounts maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: acOpenDate
     required: false
     type: string
     format: date
   - in: query
     name: authStat
     required: false
     type: string
   - in: query
     name: countryCode
     required: false
     type: string
   - in: query
     name: customerNo
     required: false
     type: string
   - in: query
     name: makerId
     required: false
     type: string
   - in: query
     name: checkerId
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   - in: query
     name: sourceSystem
     required: false
     type: string
   - in: query
     name: sourceSystemAccBrn
     required: false
     type: string
   - in: query
     name: virtualAccountNo
     required: false
     type: string
   - in: query
     name: virtualAcCcy
     required: false
     type: string
   - in: query
     name: virtualIban
     required: false
     type: string
   responses:
    201:
     description: "Returns message of success or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountServiceCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
     
  post:
   tags:
    - "corevirtualaccounts"
   summary: "Adds the new corevirtualaccounts."
   description: "Adds the new corevirtualaccounts. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
   - name: "cmcTmCoreVirtualAccountSaveDTO" 
     in: "body" 
     description: "Request Body that contains data required for creating a new corevirtualaccounts" 
     required: true
     schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountSaveDTO"
   responses:
    201: 
     description: "Returns message of success or failure " 
     headers:
      Location:
       description: "URL of newly created corevirtualaccounts" 
       type: "string"
     schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountResponseWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
 /service/corevirtualaccounts/{virtualAccountNo}:
  get:
   tags:
    - "corevirtualaccounts"
   summary: "Retrieves the corevirtualaccounts by natural key."
   description:  "Retrieves the corevirtualaccounts by natural key."
   operationId: "getByNaturalKey"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the corevirtualaccounts based on given natural key."
     schema:
      $ref: "#/definitions/CmcTmCoreVirtualAccountWrapperServiceDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  put:
   tags:
    - "corevirtualaccounts"
   summary: "Modifies the corevirtualaccounts for a  natural key."
   description:  "Modifies the corevirtualaccounts for a natural key."
   operationId: "modifyRecord"
   parameters:
   - name: "virtualAccountNo"
     in: "path"
     description: "Virtual Account Number"
     required: true
     type: "string"
   - name: "cmcTmCoreVirtualAccountSaveDTO" 
     in: "body" 
     description: "Request Body that contains data required for creating a new corevirtualaccounts" 
     required: true
     schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountSaveDTO"
   responses:
    200:
     description: "Returns the corevirtualaccounts based on given natural key."
     schema:
      $ref: "#/definitions/CmcTmCoreVirtualAccountResponseWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error" 
 /service/corevirtualaccounts/{virtualAccountNo}/close:
  patch:
   tags:
    - "corevirtualaccounts"
   summary: "Close the core virtual account by given Natural Key."
   description:  "Close the accounts identified by given Natural Key."
   operationId: "closeRecord"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
    - name: "CmcTmCoreVirtualAccountCloseReopenDTO"
      in: "body"
      description: Request body contain accounts and Modification no of accounts maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountCloseReopenDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/CmcTmCoreVirtualAccountResponseWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"  
 /service/corevirtualaccounts/{virtualAccountNo}/reopen:
  patch:
   tags:
    - "corevirtualaccounts"
   summary: "Reopen the core virtual account by given Natural Key."
   description:  "Reopen the accounts identified by given Natural Key."
   operationId: "reopenRecord"
   parameters:
    - name: "virtualAccountNo"
      in: "path"
      description: "Virtual Account Number"
      required: true
      type: "string"
    - name: "CmcTmCoreVirtualAccountCloseReopenDTO"
      in: "body"
      description: Request body contain accounts and Modification no of accounts maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/CmcTmCoreVirtualAccountCloseReopenDTO"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/CmcTmCoreVirtualAccountResponseWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"                
definitions:
 CmcTmCoreVirtualAccountSaveDTO:
  type: object
  allOf:
  - type: object
    properties:
     accountClass:
      type: string
      description: "Account class of the external virtual account"
     acOpenDate:
      type: string
      format: date
      description: "The date on which virtual account is being opened"
     acStatFrozen:
      type: string
      description: "Indicates that the virtual account status is frozen"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     acStatNoCr:
      type: string
      description: "Indicates that the virtual account does not have any credit facility"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     acStatNoDr:
      type: string
      description: "Indicates that the virtual account does not have any debit facility"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     address1:
      type: string
      description: "First line of the address"
      minLength: 0
      maxLength: 105
     address2:
      type: string
      description: "Second line of the address"
      minLength: 0
      maxLength: 105
     address3:
      type: string
      description: "Third line of the address"
      minLength: 0
      maxLength: 105
     address4:
      type: string
      description: "Fourth line of the address"
      minLength: 0
      maxLength: 105
     countryCode:
      type: string
      description: "Country Code"
      minLength: 0
      maxLength: 4
     customerNo:
      type: string
      description: "Customer number to which the virtual account number is being linked"
      minLength: 0
      maxLength: 20
     ecaCheckReq:
      type: string
      description: "Indicates that ECA check is required for the external virtual account"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     hostCode:
      type: string
      description: "The host code that is linked to the logged in user of the branch"
     isForgotten:
      type: string
      description: "Indicates that the customer is forgotten"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     sourceSystem:
      type: string
      description: "Name of the source system"
     sourceSystemAccBrn:
      type: string
      description: "Branch to which the account belongs to"
     sourceSystemAccNo:
      type: string
      description: "Virtual account number as in the source system"
     virtualAccountNo:
      type: string
      description: "External virtual account number"
      minLength: 1
      maxLength: 35
      pattern: '[a-zA-Z0-9]+'
     virtualAcCcy:
      type: string
      description: "Currency in which the virtual account is being created"
      minLength: 1
      maxLength: 3
     virtualAcName:
      type: string
      description: "Name of the virtual account holder"
      minLength: 0
      maxLength: 105
      pattern: '[a-zA-Z0-9\s]+'
     virtualIban:
      type: string
      description: "Virtual IBAN as in the source system"
      minLength: 0
      maxLength: 35
      pattern: '[a-zA-Z0-9]+'
    required:
     - customerNo
     - sourceSystem
     - sourceSystemAccBrn
     - sourceSystemAccNo
     - virtualAccountNo
     - virtualAcName
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 CmcTmCoreVirtualAccountResponseDTO:
  type: object
  allOf:
  - type: object
    properties:
     accountClass:
      type: string
      description: "Account class of the external virtual account"
     acOpenDate:
      type: string
      description: "The date on which virtual account is being opened"
     acStatFrozen:
      type: string
      description: "Indicates that the virtual account status is frozen"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     acStatNoCr:
      type: string
      description: "Indicates that the virtual account does not have any credit facility"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     acStatNoDr:
      type: string
      description: "Indicates that the virtual account does not have any debit facility"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     address1:
      type: string
      description: "First line of the address"
      minLength: 0
      maxLength: 105
     address2:
      type: string
      description: "Second line of the address"
      minLength: 0
      maxLength: 105
     address3:
      type: string
      description: "Third line of the address"
      minLength: 0
      maxLength: 105
     address4:
      type: string
      description: "Fourth line of the address"
      minLength: 0
      maxLength: 105
     countryCode:
      type: string
      description: "Country Code"
      minLength: 0
      maxLength: 4
     customerNo:
      type: string
      description: "Customer number to which the virtual account number is being linked"
      minLength: 0
      maxLength: 20
     ecaCheckReq:
      type: string
      description: "Indicates that ECA check is required for the external virtual account"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     hostCode:
      type: string
      description: "The host code that is linked to the logged in user of the branch"
     isForgotten:
      type: string
      description: "Indicates that the customer is forgotten"
      minLength: 0
      maxLength: 1
      pattern: '[Y,N]'
     sourceSystem:
      type: string
      description: "Name of the source system"
     sourceSystemAccBrn:
      type: string
      description: "Branch to which the account belongs to"
     sourceSystemAccNo:
      type: string
      description: "Virtual account number as in the source system"
     virtualAccountNo:
      type: string
      description: "External virtual account number"
      minLength: 1
      maxLength: 35
      pattern: '[a-zA-Z0-9]+'
     virtualAcCcy:
      type: string
      description: "Currency in which the virtual account is being created"
      minLength: 1
      maxLength: 3
     virtualAcName:
      type: string
      description: "Name of the virtual account holder"
      minLength: 0
      maxLength: 105
      pattern: '[a-zA-Z0-9\s]+'
     virtualIban:
      type: string
      description: "Virtual IBAN as in the source system"
      minLength: 0
      maxLength: 35
      pattern: '[a-zA-Z0-9]+' 
     makerId:
      type: string
      description: "Maker ID of Virtual Account"
     makerDateStamp:
      type: string
      description: "Date and Time when Virtual Account is created or modified or closed or reopened"
     checkerId:
      type: string
      description: "Checker ID of Virtual Account"
     checkerDateStamp:
      type: string
      description: "Date and Time when some action on Virtual Account is authorized"
     modNo:
      type: integer
      description: "Version number of Virtual Account"
     recordStatus: 
      type: string
      description: "Record Status of Virtual Account"
     authStatus:
      type: string
      description: "Authorization Status of Virtual Account"
     onceAuth:
      type: string
      description: "Flag that indicated if Virtual Account is authorized once or not"
     doerRemarks:
      type: string
      description: "Remarks made by Maker"
     approverRemarks:
      type: string 
      description: "Remarks made by Approver"  
 CmcTmCoreVirtualAccountServiceCollection: 
  description: "Collection of corevirtualaccount."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/CmcTmCoreVirtualAccountResponseDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 CmcTmCoreVirtualAccountResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
 CmcTmCoreVirtualAccountResponseWrapperDTO:
  type: object
  properties:
   messages:
    $ref: "#/definitions/CmcTmCoreVirtualAccountResDto"
   data:
    $ref: "#/definitions/CmcTmCoreVirtualAccountResponseDTO" 
 CmcTmCoreVirtualAccountWrapperServiceDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/CmcTmCoreVirtualAccountResponseDTO"    
 CmcTmCoreVirtualAccountResDto:
  type: object
  properties:
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/CmcTmCoreVirtualAccountResponseCode"   
 NKValuesDto:
  type: object
  properties:
   id:
    type: string
   modNo:
    type: integer
   wrapper:
     $ref: "#/definitions/ResponseDto"  
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string 
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string          
 CmcTmCoreVirtualAccountCloseReopenDTO:
  type: object
  properties:
   remarks:
    type: string 