#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : oblm
#  ** 
# /*******************************************************************************
# * This source is part of the Oracle Banking Software Product.
# * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
# *
# * No part of this work may be reproduced, stored in a retrieval system, adopted or tr
# *
# * Oracle Financial Services Software Limited.
# * Oracle Park, Off Western Express Highway,
# * Goregaon (East),
# * Mumbai - 400 063, India.
# ******************************************************************************/
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server country server." 
 version: "1.0.0"
 title: "country Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "country"
   description: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../country

 /country:
  post:
   tags:
    - "country"
   summary: "Adds a new country."
   description: "Adds a new country. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "country" 
      in: "body" 
      description: "Request Body that contains data required for creating a new country" 
      required: true
      schema:
       $ref: "#/definitions/LmmTmCountryParametersDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created country" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "country"
   summary: "Get all valid country."
   description:  "Get all valid country. This endpoints will be used to Get all valid country maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - in: query
     name: id
     required: false
     type: string
   - in: query
     name: countryCode
     required: false
     type: string
   - in: query
     name: currencyCode
     required: false
     type: string
   - in: query
     name: recordStat
     required: false
     type: string
   - in: query
     name: authStat
     required: false
     type: string
   - in: query   
     name: countryName
     required: false
     type: string     
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/LmmTmCountryParametersCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../country/xxx
#   DELETE    .../country/xxx
#   GET       .../country/xxx
#   GET       .../country/xxx?version=latestrecord
#   GET       .../country/xxx?version=1

 /country/{id}:
  put:
   tags:
    - "country"
   summary: "Update an existing country."
   description:  "Update an existing country."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the country Maintenance"
      required: true
      type: "string"
    - name: "country"
      in: "body"
      description: "Request Body that contains data required for updating an existing country"
      required: true
      schema:
       $ref: "#/definitions/LmmTmCountryParametersDTO"
   responses:
    200:
     description: "Returns updated country"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "country"
   summary: "Retrieves the country by ID."
   description:  "Retrieves the country by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the country based on given id."
     schema:
      $ref: "#/definitions/LmmTmCountryParametersWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "country"
   summary: "Deletes the country identified by given ID."
   description:  "Deletes the country identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the country maintenance"
      required: true
      type: "string"
    - name: "country"
      in: "body"
      description: Request body contain country and Modification no of country maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../country/xxx/approve

 /country/{id}/approve:
  patch:
   tags:
    - "country"
   summary: "Authorize the country by given ID."
   description:  "Authorize the country identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the country maintenance"
      required: true
      type: "string"
    - name: "country"
      in: "body"
      description: Request body contain country and Modification no of country maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../country/xxx/close
 /country/{id}/close:
  patch:
   tags:
    - "country"
   summary: "Close the country by given ID."
   description:  "Close the country identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the country maintenance"
      required: true
      type: "string"
    - name: "country"
      in: "body"
      description: Request body contain country and Modification no of country maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../country/xxx/reopen

 /country/{id}/reopen:
  patch:
   tags:
    - "country"
   summary: "reopen the country by given ID."
   description:  "reopen the country identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the country maintenance"
      required: true
      type: "string"
    - name: "country"
      in: "body"
      description: Request body contain country and Modification no of country maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../country/xxx/unauthorized

 /country/{id}/unauthorized:
  get:
   tags:
    - "country"
   summary: "Retrives the country by given ID."
   description:  "Retrives the country identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the country based on given id."
     schema:
       $ref: "#/definitions/LmmTmCountryParametersCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../country/xxx/history

 /country/{id}/history:
  get:
   tags:
    - "country"
   summary: "Retrives the country by given ID."
   description:  "Retrives the country by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the country based on given id."
     schema:
       $ref: "#/definitions/LmmTmCountryParametersCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 LmmTmCountryParametersDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     countryCode:
      type: string
      description: ""
     countryName:
      type: string
      description: ""
     currencyCode:
      type: string
      description: ""
     allowedAccountType:
      type: string
      description: ""
     sweep:
      type: string
      description: ""
     pool:
      type: string
      description: ""
     hybrid:
      type: string
      description: ""
     domesticSweep:
      type: string
      description: ""
     domesticPool:
      type: string
      description: ""
     domesticHybridSweep:
      type: string
      description: ""
     domesticHybridPool:
      type: string
      description: ""
     crossBorderSweep:
      type: string
      description: ""
     crossBorderPool:
      type: string
      description: ""
     crossBorderHybridSweep:
      type: string
      description: ""
     crossBorderHybridPool:
      type: string
      description: ""
     crossCcySweep:
      type: string
      description: ""
     crossCcyPool:
      type: string
      description: ""
     crossCcyHybridSweep:
      type: string
      description: ""
     crossCcyHybridPool:
      type: string
      description: ""
     ieBenefitAllowed:
      type: string
      description: ""
     ieParticipationAllowed:
      type: string
      description: ""
    required:
     - id
     - countryCode
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 LmmTmCountryParametersCollection: 
  description: "Collection of countryparameters."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/LmmTmCountryParametersDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 LmmTmCountryParametersWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/LmmTmCountryParametersDTO"
