#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : oblm
#  ** 
# /*******************************************************************************
# * This source is part of the Oracle Banking Software Product.
# * Copyright (c) 2018,2021, Oracle and/or its affiliates. All rights reserved.
# *
# * No part of this work may be reproduced, stored in a retrieval system, adopted or tr
# *
# * Oracle Financial Services Software Limited.
# * Oracle Park, Off Western Express Highway,
# * Goregaon (East),
# * Mumbai - 400 063, India.
# ******************************************************************************/
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server sweepproducts server." 
 version: "1.0.0"
 title: "Message Type Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "messagetype"
   description: ""

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../messagetype

 /messagetype:
  get:
   tags:
    - "messagetype"
   summary: "Get all valid messagetypes."
   description:  "Get all valid messagetypes. This endpoints will be used to Get all valid messagetypes maintenance records."
   operationId: "getAll"
   parameters:
    - name: messageType
      in: query
      description: type of message
      required: false
      type: string
    - name: offset
      in: query
      description: offset is starting no of records to be fetched
      required: false
      type: integer
    - name: limit
      in: query
      description: limit is maximum no of records to be fetched
      required: false
      type: integer   
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/LmmTmMessageTypeCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../messagetype/xxx
#   DELETE    .../messagetype/xxx
#   GET       .../messagetype/xxx
#   GET       .../messagetype/xxx?version=latestrecord
#   GET       .../messagetype/xxx?version=1

definitions:
 LmmTmMessageTypeDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     messageType:
      type: string
      description: ""
     messageDescription:
      type: string
      description: ""
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 LmmTmMessageTypeCollection: 
  description: "Collection of messagetypes."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/LmmTmMessageTypeDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 LmmTmMessageTypeWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/LmmTmMessageTypeDTO"
