#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : agriculturalfinancing.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/agriculturalfinancing:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AgriculturalFinancingInfo
      summary: Adds a new AgriculturalFinancingInfo.
      description: Adds a new AgriculturalFinancingInfo. Add additional information here for this endpoint.
      operationId: addAgriculturalFinancingInfo
      parameters:
      - name: AgriculturalFinancingInfoDetails
        in: body
        description: Request Body that contains data required for creating a new AgriculturalFinancingInfo
        required: true
        schema:
          $ref: '#/definitions/AgriculturalFinancingModel'
      responses:
        201:
          description: Returns the Id of the newly created AgriculturalFinancingInfo
          headers:
            Location:
              description: URL of newly created AgriculturalFinancingInfo
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AgriculturalFinancingInfo
      summary: Retrieves the list of  AgriculturalFinancingInfo.
      description: Retrieves the list of  AgriculturalFinancingInfo. Add additional information here for the this endpoint.
      operationId: getAllAgriculturalFinancingInfo
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/agriculturalfinancing/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AgriculturalFinancingInfo
      summary: Get a  AgriculturalFinancingInfo.
      description: Update a  AgriculturalFinancingInfo. Add additional information here for the this endpoint.
      operationId: getAgriculturalFinancingInfoById
      parameters:
      - name: id
        in: path
        description: id of the AgriculturalFinancingInfo that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated AgriculturalFinancingInfo
          schema:
            $ref: '#/definitions/AgriculturalFinancingModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AgriculturalFinancingInfo
      summary: Update an  AgriculturalFinancingInfo.
      description: Update an  AgriculturalFinancingInfo. Add additional information here for the this endpoint.
      operationId: updateAgriculturalFinancingInfo
      parameters:
      - name: id
        in: path
        description: id of the AgriculturalFinancingInfo that need to be updated
        required: true
        type: string
      - name: AgriculturalFinancingInfoDetails
        in: body
        description: Request Body that contains data required for updating an  AgriculturalFinancingInfo
        required: true
        schema:
          $ref: '#/definitions/AgriculturalFinancingModel'
      responses:
        200:
          description: Returns updated AgriculturalFinancingInfo
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - AgriculturalFinancingInfo
      summary: Deletes the AgriculturalFinancingInfo identified by given ID.
      description: Deletes the AgriculturalFinancingInfo identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAgriculturalFinancingInfo
      parameters:
      - name: id
        in: path
        description: Id of the AgriculturalFinancingInfo that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  AgriculturalFinancingModel:
   description: AgriculturalFinancingModel model
   type: object
   allOf:
   - $ref: '#/definitions/GenericDatasegmentModel'
   - type: object
     properties:
      agriculturalFinancingDetail:
        description: AgriculturalFinancingDetail of the AgriculturalFinancing
        type: array
        items:
          $ref: '#/definitions/AgriculturalFinancingDetailModel'
  AgriculturalFinancingCollection:
    description: Collection of AgriculturalFinancingDetails.
    type: object
    properties:
      AgriculturalFinancingDetailsList:
        type: array
        items:
          $ref: '#/definitions/AgriculturalFinancingModel'
  AgriculturalFinancingDetailModel:
    description: AgriculturalFinancingDetail model
    type: object
    required:
    - incomeRecvdCurrencyCode
    - agricultureCategory
    - areaOfFarmLand
    - unit
    - addressLine1
    - country
    - zipCode
    - latestInspectDate
    - incomeReceived
    properties:
      id:
        description: Id of the  AgriculturalFinancingDetail
        type: string
        maxLength: 36
      agriculturalFinanceInfoId:
        description: agriculturalFinanceInfoId of the  AgriculturalFinancingDetail
        type: string
        maxLength: 36
      agricultureCategory:
        description: agricultureCategory of the AgriculturalFinancingDetail
        type: string
        maxLength: 35
      typesOfCrops:
        description: typesOfCrops of the AgriculturalFinancingDetail
        type: string
        maxLength: 35
      categoryOfCrops:
        description: categoryOfCrops of the AgriculturalFinancingDetail
        type: string
        maxLength: 35
      typesOfLivestock:
        description: typesOfLivestock of the AgriculturalFinancingDetail
        type: string
        maxLength: 35
      numberOfLivestock:
        description: numberOfLivestock of the AgriculturalFinancingDetail
        type: number
        minimum: 0
        maxLength: 22
      areaOfFarmLand:
        description: areaOfFarmLand of the AgriculturalFinancingDetail
        type: number
        minimum: 0
        maxLength: 22      
      unit:
        description: unit of the AgriculturalFinancingDetail
        type: string
        maxLength: 10                          
      addressLine1:
        description: AddressLine1 of the AgriculturalFinancingDetail
        type: string
        maxLength: 105
      addressLine2:
        description: AddressLine2 of the AgriculturalFinancingDetail
        type: string
        maxLength: 105
      addressLine3:
        description: AddressLine3 of the AgriculturalFinancingDetail
        type: string
        maxLength: 105
      city:
        description: City of the AgriculturalFinancingDetail
        type: string
        minLength: 0
        maxLength: 22
      state:
        description: State of the AgriculturalFinancingDetail
        type: string
        maxLength: 22
      country:
        description: Country of the AgriculturalFinancingDetail
        type: string
        maxLength: 3
      zipCode:
        description: ZipCode of the AgriculturalFinancingDetail
        type: string
        maxLength: 8
      latestInspectDate:
        description: latestInspectDate of the AgriculturalFinancingDetail
        type: string
      incomeReceived:
        description: incomeReceived of the AgriculturalFinancingDetail
        type: number
        minimum: 0
        maxLength: 22
      incomeRecvdCurrencyCode:
        description: incomeRecvdCurrencyCode of the AgriculturalFinancingDetail
        type: string
        maxLength: 3
      productionRate:
        description: productionRate of the AgriculturalFinancingDetail
        type: number
        minimum: 0
        maxLength: 22
      agriculturalFinancingDetailsDocument:
        description: agriculturalFinancingDetailsDocument of the AgriculturalFinancingDetails
        type: array
        items:
          $ref: '../clmo-ds-utility/documentLinkage.yaml#/definitions/DocumentLinkageModel'
      agriculturalFinancingRegAuthority:
        description: agriculturalFinancingRegAuthority of the AgriculturalFinancingDetails
        type: array
        items:
          $ref: '#/definitions/AgriculturalFinancingRegAuthorityModel'
  AgriculturalFinancingRegAuthorityModel:
    description: AgriculturalFinancingRegAuthority model
    type: object
    properties:
      id:
        description: Id of the AgriculturalFinancing
        type: string
        maxLength: 36
      agriculturalFinanceDetailsId:
        description: agriculturalFinanceDetailsId
        type: string
        maxLength: 36
      regulatoryAuthorityName:
        description: regulatoryAuthority Name
        type: string
        maxLength: 50
      regulatoryAuthorityDescription:
        description: regulatoryAuthorityDescription
        type: string
        maxLength: 1000
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type