#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : assessmentdetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Assessment Details
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-scorecardservices
tags:
- name: Assessment Details
  description: API for Assessment Details
schemes:
- http
paths:
  /web/v1/assessmentdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentDetails
      summary: Adds a new AssessmentDetails.
      description: Adds a new AssessmentDetails. 
      operationId: addAssessmentDetails
      parameters:
      - name: AssessmentDetails
        in: body
        description: Request Body that contains data required for creating a new AssessmentDetails
        required: true
        schema:
          $ref: '#/definitions/AssessmentDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created AssessmentDetails
          headers:
            Location:
              description: URL of newly created AssessmentDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentDetails
      summary: Retrieves the list of existing AssessmentDetails.
      description: Retrieves the list of existing AssessmentDetails. 
      operationId: getAllAssessmentDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/assessmentdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentDetails
      summary: Retrieves the AssessmentDetails by id.
      description: Retrieves the AssessmentDetails by id. Add additional information here for the this endpoint.
      operationId: getAssessmentDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AssessmentDetails based on id.
          schema:
            $ref: '#/definitions/AssessmentDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentDetails
      summary: Update an existing AssessmentDetails.
      description: Update an existing AssessmentDetails. Add additional information here for the this endpoint.
      operationId: updateAssessmentDetails
      parameters:
      - name: id
        in: path
        description: id of the AssessmentDetails that need to be updated
        required: true
        type: string
      - name: AssessmentDetails
        in: body
        description: Request Body that contains data required for updating an existing AssessmentDetails
        required: true
        schema:
          $ref: '#/definitions/AssessmentDetailsMasterModel'
      responses:
        200:
          description: Returns updated AssessmentDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
 
definitions:
 AssessmentDetailsMasterModel:
  description: AssessmentDetailsMasterModel model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties: 
     processRefNo:
      description: Process Reference Number 
      type: string
      maxLength: 20
     requestedLoanAmount:
      description: requestedLoanAmount
      type: number
     requestedLoanAmountCurrency:
      description: requestedLoanAmountCurrency
      type: string    
     approvedLoanAmount:
      description: approvedLoanAmount
      type: number 
     approvedLoanAmountCurrency:
      description: approvedLoanAmountCurrency
      type: string
     loanTenure:
      description: loanTenure
      type: string
     interestRate:
      description: interestRate
      type: number
     hostMargin:
      description: hostMargin
      type: number
     rateType:
      description: rateType
      type: string
     cdmsReferenceNumber:
       description: cdmsReferenceNumber
       type: string
     proposedRateOfInterest:
       description: proposedRateOfInterest
       type: number
     effectiveRate:
       description: effectiveRateofInterest
       type: number
     decisionGradeMasterModel:
       $ref: '#/definitions/DecisionGradeMasterModel'
    required:
     - applicationNumber
     - processRefNo
     - stageCode
     - requestedLoanAmount
     - requestedLoanAmountCurrency
     - cdmsReferenceNumber
     - effectiveRateofInterest
 DecisionGradeMasterModel:
    description: DecisionGradeMasterModel model
    type: object
    properties:
     totalWeightedScore:
      description: totalWeightedScore
      type: integer
     systemRecommendedDecision:
      description: systemRecommendedDecision
      type: string
     systemRecommendedGrade:
      description: systemRecommendedGrade
      type: string
     decision:
       description: DecisionfromCDS
       type: string
 AssessmentDetailsMasterCollection:
  description: Collection of AssessmentDetailsMasterModel.
  type: object
  properties:
   assessmentDetailsMasterModelList:
    type: array
    items:
     $ref: '#/definitions/AssessmentDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 