#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : assessmentsummary.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Assessment Summary
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-scorecardservices
tags:
- name: Assessment Summary
  description: API for Assessment Summary
schemes:
- http
paths:
  /web/v1/assessmentsummary:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentSummary
      summary: Adds a new AssessmentSummary.
      description: Adds a new AssessmentSummary.
      operationId: addAssessmentSummary
      parameters:
      - name: AssessmentSummaryDetails
        in: body
        description: Request Body that contains data required for creating a new AssessmentSummary
        required: true
        schema:
          $ref: '#/definitions/AssessmentSummaryDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created AssessmentSummary
          headers:
            Location:
              description: URL of newly created AssessmentSummary
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentSummary
      summary: Retrieves the list of existing AssessmentSummary.
      description: Retrieves the list of existing AssessmentSummary.
      operationId: getAllAssessmentSummary
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error

  /web/v1/assessmentsummary/{id}:
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AssessmentSummary
      summary: Update an existing AssessmentSummary.
      description: Update an existing AssessmentSummary. Add additional information here for the this endpoint.
      operationId: updateAssessmentSummary
      parameters:
      - name: id
        in: path
        description: id of the AssessmentSummary that need to be updated
        required: true
        type: string
      - name: AssessmentSummaryDetails
        in: body
        description: Request Body that contains data required for updating an existing AssessmentDetails
        required: true
        schema:
          $ref: '#/definitions/AssessmentSummaryDetailsMasterModel'
      responses:
        200:
          description: Returns updated AssessmentSummary
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error

definitions:
  AssessmentSummaryDetailsMasterModel:
    description: AssessmentSummaryDetailsMasterModel model
    type: object
    allOf:
    - $ref: '#/definitions/GenericDatasegmentModel'
    - type: object
      properties:
       userRecommendation:
        description: userRecommendation
        type: string
       comment:
        description: comment
        type: string
       applicationNumber:
        description: application number
        type: string
       processRefNo:
        description: process ref No.
        type: string
       recommdLoanAmt:
        description: recommdLoanAmt
        type: number
       recommdLoanAmtCurrency:
        description: recommdLoanAmtCurrency
        type: string
       loanTenureYear:
        description: loanTenureYear
        type: number
       loanTenureMonth:
        description: loanTenureMonth
        type: number
       loanTenureDay:
        description: loanTenureDay
        type: number
       requestedLoanAmount:
        description: requestedLoanAmount
        type: number
       requestedLoanAmountCurrency:
        description: requestedLoanAmountCurrency
        type: string
       approvedLoanAmount:
        description: approvedLoanAmount
        type: number
       approvedLoanAmountCurrency:
        description: approvedLoanAmountCurrency
        type: string
       loanTenure:
        description: loanTenure
        type: string
       hostMargin:
         description: hostMargin
         type: number
       interestRate:
         description: interestRate
         type: number
       rateType:
         description: rateType
         type: string
       cdmsReferenceNumber:
         description: cdmsReferenceNumber
         type: string
       proposedRateOfInterest:
         description: proposedRateOfInterest
         type: number
       effectiveRate:
         description: effectiveRateofInterest
         type: number
       decisionGradeMasterModel:
         $ref: '#/definitions/DecisionGradeMasterModel'
  DecisionGradeMasterModel:
    description: DecisionGradeMasterModel model
    type: object
    properties:
      totalWeightedScore:
        description: totalWeightedScore
        type: integer
      systemRecommendedDecision:
        description: systemRecommendedDecision
        type: string
      systemRecommendedGrade:
        description: systemRecommendedGrade
        type: string
      decision:
        description: DecisionfromCDS
        type: string
  GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type     