#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : manualcreditrecommendation.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Manual Credit Recommendation
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-manualcreditrecommendation
tags:
- name: Manual Credit Recommendation
  description: API for Manual Credit Recommendation
schemes:
- http
paths:
  /web/v1/manualcreditrecommendation:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ManualCreditRecommendation
      summary: Adds a new ManualCreditRecommendation.
      description: Adds a new ManualCreditRecommendation. 
      operationId: addManualCreditRecommendationDetails
      parameters:
      - name: ManualCreditRecommendationDetails
        in: body
        description: Request Body that contains data required for creating a new ManualCreditRecommendationDetails
        required: true
        schema:
          $ref: '#/definitions/ManualCrdRecommDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created ManualCreditRecommendationDetails
          headers:
            Location:
              description: URL of newly created ManualCreditRecommendationDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ManualCreditRecommendation
      summary: Retrieves the list of existing ManualCreditRecommendationDetails.
      description: Retrieves the list of existing ManualCreditRecommendationDetails. 
      operationId: getAllManualCreditRecommendationDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/manualcreditrecommendation/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ManualCreditRecommendation
      summary: Retrieves the ManualCreditRecommendationDetails by id.
      description: Retrieves the ManualCreditRecommendationDetails by id. Add additional information here for the this endpoint.
      operationId: getManualCreditRecommendationDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ManualCreditRecommendationDetails based on id.
          schema:
            $ref: '#/definitions/ManualCrdRecommDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ManualCreditRecommendation
      summary: Update an existing ManualCreditRecommendationDetails.
      description: Update an existing ManualCreditRecommendationDetails. Add additional information here for the this endpoint.
      operationId: updateManualCreditRecommendationDetails
      parameters:
      - name: id
        in: path
        description: id of the ManualCreditRecommendationDetails that need to be updated
        required: true
        type: string
      - name: ManualCreditRecommendationDetails
        in: body
        description: Request Body that contains data required for updating an existing ManualCreditRecommendationDetails
        required: true
        schema:
          $ref: '#/definitions/ManualCrdRecommDetailsMasterModel'
      responses:
        200:
          description: Returns updated ManualCreditRecommendationDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error

definitions:
 ManualCrdRecommDetailsMasterModel: 
  description: ManualCreditRecommendationDetailsMasterModel model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     userRecommendation:
      description: userRecommendation
      type: string
     comment:
      description: comment
      type: string
     applicationNumber:
      description: application number
      type: string
     processRefNo:
      description: process ref No.    
      type: string
     recommdLoanAmt:
      description: recommdLoanAmt   
      type: number
     recommdLoanAmtCurrency:
      description: recommdLoanAmtCurrency   
      type: string
     loanTenureYear:
      description: loanTenureYear  
      type: number
     loanTenureMonth:
      description: loanTenureMonth  
      type: number
     loanTenureDay:
      description: loanTenureDay  
      type: number
     requestedLoanAmount:
      description: requestedLoanAmount
      type: number
     requestedLoanAmountCurrency:
      description: requestedLoanAmountCurrency
      type: string    
     approvedLoanAmount:
      description: approvedLoanAmount
      type: number 
     approvedLoanAmountCurrency:
      description: approvedLoanAmountCurrency
      type: string
     loanTenure:
      description: loanTenure
      type: string
     hostMargin:
       description: hostMargin
       type: number
     interestRate:
       description: interestRate
       type: number
     rateType:
       description: rateType
       type: string
     cdmsReferenceNumber:
       description: cdmsReferenceNumber
       type: string
     proposedRateOfInterest:
       description: proposedRateOfInterest
       type: number
     effectiveRate:
       description: effectiveRateofInterest
       type: number
     decisionGradeMasterModel:
       $ref: '#/definitions/DecisionGradeMasterModel'
    required:
     - userRecommendation
     - comment 
         
 DecisionGradeMasterModel:
  description: DecisionGradeMasterModel model
  type: object
  properties:
    totalWeightedScore:
      description: totalWeightedScore
      type: integer
    systemRecommendedDecision:
      description: systemRecommendedDecision
      type: string
    systemRecommendedGrade:
      description: systemRecommendedGrade
      type: string
    decision:
      description: DecisionfromCDS
      type: string
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type     