#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : qualitativeconfigurationds.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Qualitative Scorecard services
host: 10.184.157.121:9000
basePath: /obremo-rpm-cmn-scorecardservices
tags:
- name: Scorecard Services
  description: API for Scorecard Services Operations
schemes:
- http
paths:
  /web/v1/qualitativeconfiguration/ds:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - QualitativeConfigurationDs
      summary: Adds a new QualitativeConfigurationDs.
      description: Adds a new QualitativeConfigurationDs. Add additional information here for this endpoint.
      operationId: addQualitativeConfigurationDs
      parameters:
      - name: QualitativeConfigurationDs
        in: body
        description: Request Body that contains data required for creating a new QualitativeConfigurationDs
        required: true
        schema:
          $ref: '#/definitions/QualitativeConfigurationDsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created QualitativeConfigurationDs
          headers:
            Location:
              description: URL of newly created QualitativeConfigurationDs
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - QualitativeConfigurationDs
      summary: Retrieves the list of existing QualitativeConfigurationDs.
      description: Retrieves the list of existing QualitativeConfigurationDs. Add additional information here for the this endpoint.
      operationId: getAllQualitativeConfigurationDs
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/qualitativeconfiguration/ds/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - QualitativeConfigurationDs
      summary: Retrieves the QualitativeConfigurationDs by id.
      description: Retrieves the QualitativeConfigurationDs by id. Add additional information here for the this endpoint.
      operationId: getQualitativeConfigurationDsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the QualitativeConfigurationDs based on given applicationNumber.
          schema:
            $ref: '#/definitions/QualitativeConfigurationDsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - QualitativeConfigurationDs
      summary: Update an existing QualitativeConfigurationDs.
      description: Update an existing QualitativeConfigurationDs. Add additional information here for the this endpoint.
      operationId: updateQualitativeConfigurationDs
      parameters:
      - name: id
        in: path
        description: id of the QualitativeConfigurationDs that need to be updated
        required: true
        type: string
      - name: QualitativeConfigurationDs
        in: body
        description: Request Body that contains data required for updating an existing QualitativeConfigurationDs
        required: true
        schema:
          $ref: '#/definitions/QualitativeConfigurationDsMasterModel'
      responses:
        200:
          description: Returns updated QualitativeConfigurationDs
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
 
definitions:
 QualitativeConfigurationDsMasterModel:
  description: QualitativeConfigurationDs model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     id:
      description: Id of the QualitativeConfigurationDsMasterModel
      type: string
      maxLength: 36
     applicationNumber:
      description: Application Number of the QualitativeConfigurationDsMasterModel
      type: string
      maxLength: 20  
     processRefNo:
      description: Process Reference Number 
      type: string
      maxLength: 20
     remarks:
      description: remarks
      type: string
     noOfApplicants:
      description: noOfApplicants
      type: integer
     multipleApplicantHandling:
      description: multipleApplicantHandling
      type: string
     considerPrimaryApp:
      description: considerPrimaryApp
      type: string
     qualitativeConfigurationApplicantMapModel:
      type: array
      items:
       $ref: '#/definitions/QualitativeConfigurationApplicantMapModel'
    required:
     - applicationNumber
     - processRefNo
     - multipleApplicantHandling
     - considerPrimaryApp
     - qualitativeConfigurationApplicantMapModel
     - stageCode
 QualitativeConfigurationApplicantMapModel:
   description: "QualitativeConfigurationApplicantMapModel Model"
   type: object
   properties:
    id:
     description: Id of the QualitativeConfigurationApplicantMapModel
     type: string
     maxLength: 36
    applicationNumber:
     description: Application Number 
     type: string
     maxLength: 20
    processRefNo:
     description: Process Reference Number 
     type: string
     maxLength: 20
    dmlCode:
      description: DML Code
      type: string
      maxLength: 20
    scorecardDetailsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    applicantId:
     description: applicantId
     type: string
     maxLength: 36
    applicantName:
     description: applicantName
     type: string
    questionnaireCode:
      description: Questionnaire Id
      type: string
    questionnaireDescription:
      description: Questionnaire Description
      type: string
    dateOfIncorporation:
      description: Customer Name
      type: string
    businessName:
      description: businessName
      type: string
    customerType:
      description: customerType
      type: string
    primaryApplicant:
     description: primaryApplicant
     type: boolean
    qualitativeConfigurationQuestionModel:
      type: array
      items:
       $ref: '#/definitions/QualitativeConfigurationQuestionModel'
   required:
    - applicationNumber
    - processRefNo
    - dmlCode
    - applicantId
    - questionnaireCode
    - qualitativeConfigurationQuestionModel
 QualitativeConfigurationQuestionModel:
   description: "QualitativeConfigurationQuestionModel Model"
   type: object
   properties:
    id:
     description: Id of the QualitativeConfigurationQuestionModel
     type: string
     maxLength: 36
    applicationNumber:
     description: Application Number of the QualitativeConfigurationQuestionModel
     type: string
     maxLength: 20
    processRefNo:
     description: Process Reference Number 
     type: string
     maxLength: 20
    scorecardApplicantMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    questionId:
     description: questionId
     type: string
    questionDescription:
     description: questionDescription
     type: string
    questionType:
      description: questionType
      type: string
    questionCode:
      description: questionType
      type: string
    selectedAnswerOptionId:
      description: selectedAnswerOptionId
      type: string
    mandatory:
      description: mandatory
      type: string
    selectedAnswerDescription:
     description: selectedAnswerDescription
     type: string
    sequenceNumber:
      description: sequenceNumber
      type: integer
    qualitativeConfigurationAnswerModel:
      type: array
      items:
       $ref: '#/definitions/QualitativeConfigurationAnswerModel'
   required:
    - applicationNumber
    - processRefNo
    - questionId
    - questionCode
    - mandatory
    - questionDescription
    - selectedAnswerOptionId
    - selectedAnswerDescription
    - sequenceNumber
 QualitativeConfigurationAnswerModel:
   description: "QualitativeConfigurationAnswerModel Model"
   type: object
   properties:
    id:
     description: Id of the QualitativeConfigurationAnswerModel
     type: string
     maxLength: 36
    applicationNumber:
     description: Application Number of the QualitativeConfigurationAnswerModel
     type: string
     maxLength: 20
    processRefNo:
     description: Process Reference Number 
     type: string
     maxLength: 20
    scorecardQuestionsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    answerDescription:
     description: answerDescription
     type: string
    answerOptionId:
      description: answerDescription
      type: string
    sequenceNumber:
      description: seqAnsNo
      type: integer
   required:
    - applicationNumber
    - processRefNo
    - answerOptionId
    - answerDescription
    - sequenceNumber
 QualitativeConfigurationDsMasterCollection:
    description: Collection of QualitativeConfigurationDsMasterModel.
    type: object
    properties:
     qualitativeConfigurationDsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/QualitativeConfigurationDsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 