#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : common.yaml
#  **
#  ** Module     : obma
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: "This is a sample server reports server." 
 version: "1.0.0"
 title: "reports Service"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "reports"
   description: "This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description.This is description."

schemes:
- "https"

paths:

# path to create a new record and fetch all valid records or by intent
#
#  supprorted http methods POST and GET
#
# path example ../reports

 /reports:
  post:
   tags:
    - "reports"
   summary: "Adds a new reports."
   description: "Adds a new reports. Add additional information here for this endpoint."
   operationId: "saveRecord"
   parameters:
    - name: "reports" 
      in: "body" 
      description: "Request Body that contains data required for creating a new reports" 
      required: true
      schema:
       $ref: "#/definitions/ObmaTmReportMetadataDTO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created reports" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "reports"
   summary: "Get all valid reports."
   description:  "Get all valid reports. This endpoints will be used to Get all valid reports maintenance records."
   operationId: "getAll"
   parameters:
   - name: includecloseandunauth
     in: query
     description: includecloseandunauth need to be set to fetch summary record, defult value is false
     required: false
     type: boolean
   - name: offset
     in: query
     description: offset is starting no of records to be fetched
     required: false
     type: integer
   - name: limit
     in: query
     description: limit is maximum no of records to be fetched
     required: false
     type: integer
   - name: name
     in: query
     description: Report Name
     required: false
     type: string
   - name: description
     in: query
     description: Report Description
     required: false
     type: string
   - name: authStatus
     in: query
     description: Auth status of the record
     required: false
     type: string
   - name: recordStatus
     in: query
     description: Indicates whether record is marked open or close
     required: false
     type: string
   responses:
    201:
     description: "Returns message of succes or failure"
     headers: 
      Location:
       description: ""
       type: "string"
     schema:
       $ref: "#/definitions/ObmaTmReportMetadataCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"

# path to modify existing record, delete existing record and fetch valid records by id or by intent( includes latestRecord, version no)
#
#  supprorted http methods PUT, DELETE and GET
#
# path examples----
#   PUT       .../reports/xxx
#   DELETE    .../reports/xxx
#   GET       .../reports/xxx
#   GET       .../reports/xxx?version=latestrecord
#   GET       .../reports/xxx?version=1

 /reports/{id}:
  put:
   tags:
    - "reports"
   summary: "Update an existing reports."
   description:  "Update an existing reports."
   operationId: "modifyRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "key of the reports Maintenance"
      required: true
      type: "string"
    - name: "reports"
      in: "body"
      description: "Request Body that contains data required for updating an existing reports"
      required: true
      schema:
       $ref: "#/definitions/ObmaTmReportMetadataDTO"
   responses:
    200:
     description: "Returns updated reports"
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "reports"
   summary: "Retrieves the reports by ID."
   description:  "Retrieves the reports by ID."
   operationId: "getById"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
    - name: "version"
      in: "query"
      description: "Id of the user that needs to be fetched"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the reports based on given id."
     schema:
      $ref: "#/definitions/ObmaTmReportMetadataWrapperDTO"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
  delete:
   tags:
    - "reports"
   summary: "Deletes the reports identified by given ID."
   description:  "Deletes the reports identified by given ID. Add additional information here for the this endpoint."
   operationId: "delete"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the reports maintenance"
      required: true
      type: "string"
    - name: "reports"
      in: "body"
      description: Request body contain reports and Modification no of reports maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to Authorize existing record.
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../reports/xxx/approve

 /reports/{id}/approve:
  patch:
   tags:
    - "reports"
   summary: "Authorize the reports by given ID."
   description:  "Authorize the reports identified by given ID."
   operationId: "authorize"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the reports maintenance"
      required: true
      type: "string"
    - name: "reports"
      in: "body"
      description: Request body contain reports and Modification no of reports maintenance which need to be deleted"
      required: true
      schema:
       $ref: "#/definitions/ModListKeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to close existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../reports/xxx/close
 /reports/{id}/close:
  patch:
   tags:
    - "reports"
   summary: "Close the reports by given ID."
   description:  "Close the reports identified by given ID."
   operationId: "closeRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the reports maintenance"
      required: true
      type: "string"
    - name: "reports"
      in: "body"
      description: Request body contain reports and Modification no of reports maintenance which need to be closed"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to reopen existing record
#
#  supprorted http methods PATCH
#
# path examples----
#   PATCH       .../reports/xxx/reopen

 /reports/{id}/reopen:
  patch:
   tags:
    - "reports"
   summary: "reopen the reports by given ID."
   description:  "reopen the reports identified by given ID."
   operationId: "reopenRecord"
   parameters:
    - name: "id"
      in: "path"
      description: "Key of the reports maintenance"
      required: true
      type: "string"
    - name: "reports"
      in: "body"
      description: Request body contain reports and Modification no of reports maintenance which need to be reopen"
      required: true
      schema:
       $ref: "#/definitions/KeyDto"
   responses:
    200:
     description: "Successful operation."
     schema:
      $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to get all unauthorized records
#
#  supprorted http methods GET
#
# path examples----
#   GET       .../reports/xxx/unauthorized

 /reports/{id}/unauthorized:
  get:
   tags:
    - "reports"
   summary: "Retrives the reports by given ID."
   description:  "Retrives the reports identified by given ID."
   operationId: "authQuery"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the reports based on given id."
     schema:
       $ref: "#/definitions/ObmaTmReportMetadataCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"

# path to  history record for remitterid
#
#  supprorted http methods GETS
#
# path examples----
#   GET       .../reports/xxx/history

 /reports/{id}/history:
  get:
   tags:
    - "reports"
   summary: "Retrives the reports by given ID."
   description:  "Retrives the reports by ID."
   operationId: "getHistory"
   parameters:
    - name: "id"
      in: "path"
      description: "Id of the user that needs to be fetched"
      required: true
      type: "string"
   responses:
    200:
     description: "Returns the reports based on given id."
     schema:
       $ref: "#/definitions/ObmaTmReportMetadataCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 ObmaTmReportMetadataDTO:
  type: object
  allOf:
  - $ref: '#/definitions/GenericDto'
  - type: object
    properties:
     description:
      type: string
      description: ""
      maxLength: 120
     destination:
      $ref: '#/definitions/ReportDestinationType'
     name:
      type: string
      description: ""
      maxLength: 120
     outputType:
      $ref: '#/definitions/OutputMimeType'
     templateId:
      type: string
      description: ""
      maxLength: 36
     transformerType:
      $ref: '#/definitions/TransformerType'
    required:
     - name
     - outputType
     - templateId
 ModListKeyDto:
  type: object
  properties:
   modNos:
    type: array
    items:
     type: integer
   remarks:
    type: string
 KeyDto:
  type: object
  properties:
   modNo:
    type: integer
   remarks:
    type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 GenericDto:
  allOf:
   - type: object
     discriminator: resource_type
 ObmaTmReportMetadataCollection: 
  description: "Collection of reportmetadata."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ObmaTmReportMetadataDTO"
   paging:
    $ref: "#/definitions/PagingDto"
 PagingDto:
  type: object
  properties:
   totalResults:
    type: integer
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object
 ObmaTmReportMetadataWrapperDTO:
  type: object
  properties:
   data:
    $ref: "#/definitions/ObmaTmReportMetadataDTO"
