#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : lendercommitments.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/lendercommitments:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LenderCommitments
      summary: Adds a new LenderCommitments.
      description: Adds a new LenderCommitments. Add additional information here for this endpoint.
      operationId: addLenderCommitments
      parameters:
      - name: LenderCommitments
        in: body
        description: Request Body that contains data required for creating a new LenderCommitments
        required: true
        schema:
          $ref: '#/definitions/LenderCommitmentsModel'
      responses:
        201:
          description: Returns the Id of the newly created LenderCommitments
          headers:
            Location:
              description: URL of newly created LenderCommitments
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LenderCommitments
      summary: Retrieves the list of existing LenderCommitments.
      description: Retrieves the list of existing LenderCommitments. Add additional information here for the this endpoint.
      operationId: getAllLenderCommitments
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: trancheId
        in: query
        description: trancheId that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/lendercommitments/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LenderCommitments
      summary: Retrieves the LenderCommitments by id.
      description: Retrieves the LenderCommitments by id. Add additional information here for the this endpoint.
      operationId: getLenderCommitmentsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the LenderCommitments based on given applicationNumber.
          schema:
            $ref: '#/definitions/LenderCommitmentsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LenderCommitments
      summary: Update an existing LenderCommitments.
      description: Update an existing LenderCommitments. Add additional information here for the this endpoint.
      operationId: updateLenderCommitments
      parameters:
      - name: id
        in: path
        description: id of the LenderCommitments that need to be updated
        required: true
        type: string
      - name: LenderCommitments
        in: body
        description: Request Body that contains data required for updating an existing LenderCommitments
        required: true
        schema:
          $ref: '#/definitions/LenderCommitmentsModel'
      responses:
        200:
          description: Returns updated LenderCommitments
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LenderCommitments
      summary: Deletes the LenderCommitments identified by given ID.
      description: Deletes the LenderCommitments identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLenderCommitments
      parameters:
      - name: id
        in: path
        description: Id of the LenderCommitments that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LenderCommitmentsModel:
    description: LenderCommitments model
    type: object
    properties:
      id:
        description: Id of the LenderCommitments
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: remarks
        type: string
      commitmentSummaryAmount:
        description: Total Commitment Amount
        type: number
      commitmentSummaryCurrency:
        description: Total Commitment Amount Currency
        type: string
      lenderCommitmentSummary:
        type: array
        items:
          $ref: '#/definitions/LenderCommitmentSummaryModel'
      lenderTrancheSummary:
        type: array
        items:
          $ref: '#/definitions/LenderTrancheSummaryModel'
  LenderCommitmentSummaryModel:
    description: LenderCommitmentSummary model
    type: object
    required:
    - lenderId
    - lenderName
    - syndicationCcy
    properties:
      id:
        description: Id of the LenderCommitmentSummary
        type: string
      lenderCommitmentId:
        description: lenderCommitmentId
        type: string
      lenderId:
        description: Lender ID
        type: string
        maxLength: 36
      lenderName:
        description: Lender Name
        type: string
        maxLength: 36
      overallCommitment:
        description: Overall Commitment
        type: number
      syndicationCcy:
        description: Syndication Currency
        type: string
      lenderTrancheCommitments:
        type: array
        items:
          $ref: '#/definitions/LenderTrancheCommitmentsModel'
  LenderTrancheCommitmentsModel:
    description: LenderTrancheCommitments model
    type: object
    required:
    - trancheId
    - trancheName
    - trancheType
    - commitmentAmount
    - trancheCurrency
    - syndicationCurrency
    properties:
      id:
        description: Id of the LenderTrancheCommitments
        type: string
      lenderCommitmentSumId:
        description: lenderCommitmentSumId
        type: string
      trancheId:
        description: Tranche ID
        type: string
        maxLength: 36
      trancheName:
        description: Tranche Name
        type: string
      trancheType:
        description: Tranche Type
        type: string
        maxLength: 36
      lenderId:
        description: Lender ID
        type: string
        maxLength: 36
      lenderName:
        description: Lender Name
        type: string
        maxLength: 36
      commitmentAmount:
        description: Commitment Amount
        type: number
      trancheAmount:
        description: Tranche Amount
        type: number
      commitmentAmountScy:
        description: Commitment Amount Syndication Currency
        type: number
      trancheCurrency:
        description: Tranche Currency
        type: string
      syndicationCurrency:
        description: Syndication Currency
        type: string
  LenderTrancheSummaryModel:
    description: LenderTrancheSummary model
    type: object
    required:
    - trancheId
    - trancheName
    - trancheType
    - trancheCcy
    properties:
      id:
        description: Id of the LenderTrancheSummary
        type: string
      lenderCommitmentId:
        description: lenderCommitmentId
        type: string
      trancheId:
        description: Tranche ID
        type: string
        maxLength: 36
      trancheName:
        description: Tranche Name
        type: string
        maxLength: 35
      trancheType:
        description: Tranche Type
        type: string
        maxLength: 35
      totalCommitmentAmount:
        description: Total Commitment Amount
        type: number
      trancheCcy:
        description: Tranche Currency
        type: string
      partyNumber:
        description: Party Number
        type: string
      assetRatio:
        description: Asset Ratio
        type: string
  LenderCommitmentsCollection:
    description: Collection of LenderCommitments.
    type: object
    properties:
      LenderCommitmentsList:
        type: array
        items:
          $ref: '#/definitions/LenderCommitmentsModel'
