swagger: "2.0"
info:
  description: "This yaml contains all the ft model"
  version: "1.0.0"
  title: ""
basePath: "/ft"
tags:
- name: "FtWeb"
schemes:
- "http"
paths:
 /ft/:
  get:
   tags:
   - "FtWeb"
   operationId: "ft"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"
definitions:
  FtTxnDSModel:
    type: object
    description: "User Limits Model"
    properties:
     datasegment:
       type: string
       description: "CCA Name"
     txnControllerRefNo:
       type: string
       description: "Txn ref no from UI"
     recordId:
       type: string
     cashAmtCcy:
       type: string
       description: "Cash Amount Curreny"
     cashAmt:
       type: number
       description: "Cash Amount"
     chequeDate:
       type: string
       format: date
       description: "Cheque Date"
     chequeNumber:
       type: string
       description: "Cheque Number"
     eventCode:
       type: string
       description: "Event Code"
     ejId:
       type: string
       description: "EJ ID"
     emailId:
       type: string
       description: "Email"
     fromAccountBranch:
       type: string
       description: "From Account Branch"
     fromAccountCcy:
       type: string
       description: "From Account Currency"
     fromAccountNumber:
       type: string
       description: "From Account Number"
     fromAccountAmt:
       type: number
       description: "From Account Amount"
     mobileNumber:
       type: string
       description: "Mobile Number"
     narrative:
       type: string
       description: "Narrative"
     orginalExchangeRate:
       type: number
       description: "Orginal Exchange Rate"
     payee:
       type: string
       description: "Payee"
     productCode:
       type: string
       description: "Product Code"
     reversalDate:
       type: string
       format: date
       description: "Reversal Date"
     stationId:
       type: string
       description: "Station ID"
     toAccountBranch:
       type: string
       description: "To Account Branch"
     toAccountCcy:
       type: string
       description: "To Account Currency"
     toAccountNumber:
       type: string
       description: "To Account Number"
     toAccountAmt:
       type: number
       description: "To Account Amount"
     txnBranchCode:
       type: string
       description: "Txn Branch Code"
     functionCode:
       type: string
       description: "Function Code"
     txnCustomer:
       type: string
       description: "Txn Customer"
     tellerId:
       type: string
       description: "TellerId"
     txnDate:
       type: string
       format: date
       description: "Txn Date"
     txnRefNumber:
       type: string
       description: "Transaction Ref. No"
     txnSeqNumber:
       type: number
       description: "Teller Sl No"
     uniqueIdentifierNumber:
       type: string
       description: "Unique Identifier No"
     uniqueIdentifierType:
       type: string
       description: "Unique Identifier Type"
     userRefNumber:
       type: string
       description: "User Reference No"
     valueDate:
       type: string
       format: date
       description: "Value Date"
     versionNumber:
       type: number
       description: "Version No"
     exchangeRate:
       type: number
       description: "Exchange Rate"
     negotiatedExchangeRate:
       type: number
       description: "Negotiated Exchange Rate"
     negotiationReferenceNumber:
       type: string
       description: "negotiation Reference Number"
     clearingType:
       type: string
       description: "Clearing Type"
     drawerAccountNo:
       type: string
       description: ""
     drawerName:
       type: string
       description: ""
     routingNo:
       type: string
       description: ""
     chequeAmt:
       type: number
       description: ""
     createdBy:
       type: string
       description: ""
     createdTs:
       type: string
       format: date
       description: ""
     updatedBy:
       type: string
       description: ""
     updatedTs:
       type: string
       format: date
       description: ""
     modeOfTrf:
       type: string
       description: ""
     additionalFields:
       type: string
       description: ""
     demDtls:
       type: array
       items:
          $ref: "#/definitions/DenomTxnDtlsModel"
     prcDtls:
       type: array
       items:
          $ref: "#/definitions/PrcDtlsModel"
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     pcDtls:
       $ref: '#/definitions/pcDtlsModel'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"
  DenomTxnDtlsModel:
    type: object
    properties:
     recordId:
      type: string
      description: "Record Id"
     parentId:
      type: string
      description: "Parent ID"
     denomCode:
      type: string
      description: "Demon Code"
     denomCodeValue:
      type: string
      description: "Demon Code Value"
     denomType:
      type: string
      description: "Demon Type"
     units:
      type: number
      description: "Units"
     value:
      type: number
      description: "Value"
     inOutIndicator:
      type: string
      description: "InOut Indicator"
     tellerId:
      type: string
      description: "User ID"
  pcDtlsModel:
    type: object
    properties:
     benAcctType:
      type: string
      description: "Beneficiary Account type"
     benAddr1:
      type: string
      description: "Beneficiary address 1"
     benAddr2:
      type: string
      description: "Beneficiary address 2 "
     benAddr3:
      type: string
      description: "Beneficiary address 3"
     benAddr4:
      type: string
      description: "Beneficiary address 4"
     benName:
      type: string
      description: "Beneficiary name"
     branch:
      type: string
      description: "branch"
     commMode:
      type: string
      description: "Communication Mode"
     custAddr1:
      type: string
      description: "Customer address 1 "
     custAddr2:
      type: string
      description: "Customer address 2"
     custAddr3:
      type: string
      description: "Customer address 3"
     custAddr4:
      type: string
      description: "Customer address 4"
     custName:
      type: string
      description: "Customer name"
     emailid:
      type: string
      description: "email id"
     mobileno:
      type: string
      description: "mobile number"
     parentId:
      type: string
      description: "Parent Id"
     pcAccountNo:
      type: string
      description: "Beneficiary account number"
     pcBankCode:
      type: string
      description: "Bank code"
     pcNetworkId:
      type: string
      description: "Network Code"
     senderRecvrInfo1:
      type: string
      description: "Sender Receiver information 1"
     senderRecvrInfo2:
      type: string
      description: "Sender Receiver information 2"
     senderRecvrInfo3:
      type: string
      description: "Sender Receiver information 3"
     senderRecvrInfo4:
      type: string
      description: "Sender Receiver information 4"   
     benSwiftBicCode:
      type: string
      description: "Ben Swift BIC code"    
     remBicCode:
      type: string
      description: "Rem BIC code"    
  ObPayReqResModel:
    type: object
    properties:
     parentId:
      type: string
      description: "parent Id"
     pmErrorCode:
      type: string
      description: "OBPAY error codes"
     pmErrorParam:
      type: string
      description: "OBPAY error params"
     pmMsgstat:
      type: string
      description: "OBPAY msg stat"
     pmSourceId:
      type: string
      description: "OBPAY source Id"
     pmTxnid:
      type: string
      description: "OBPAY txn Id"
     pmTxnrefno:
      type: string
      description: "OBPAY txn ref no"
     requestStamp:
      type: string
      description: "Request Time stamp"
     responseStamp:
      type: string
      description: "Response Time stamp"
     status:
      type: string
      description: "Status "
     tellerSeqNo:
      type: number
      description: "Teller sequence number"
     txnRefNo:
      type: string
      description: "Transaction reference number"
     versionNo:
      type: number
      description: "Version Number"
     modNo:
      type: number
      description: "Mod Number"
     