#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : accountservices.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/accountservices:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AccountServices
      summary: Adds a new AccountServices.
      description: Adds a new AccountServices. Add additional information here for this endpoint.
      operationId: addAccountServices
      parameters:
      - name: AccountServices
        in: body
        description: Request Body that contains data required for creating a new AccountServices
        required: true
        schema:
          $ref: '#/definitions/AccountServicesMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created AccountServices
          headers:
            Location:
              description: URL of newly created AccountServices
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountServices
      summary: Retrieves the list of existing AccountServices.
      description: Retrieves the list of existing AccountServices. Add additional information here for the this endpoint.
      operationId: getAllAccountServices
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/accountservices/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountServices
      summary: Retrieves the AccountServices by id.
      description: Retrieves the AccountServices by id. Add additional information here for the this endpoint.
      operationId: getAccountServicesById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AccountServices based on given processRefNo.
          schema:
            $ref: '#/definitions/AccountServicesMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AccountServices
      summary: Update an existing AccountServices.
      description: Update an existing AccountServices. Add additional information here for the this endpoint.
      operationId: updateAccountServices
      parameters:
      - name: id
        in: path
        description: id of the AccountServices that need to be updated
        required: true
        type: string
      - name: AccountServices
        in: body
        description: Request Body that contains data required for updating an existing AccountServices
        required: true
        schema:
          $ref: '#/definitions/AccountServicesMasterModel'
      responses:
        200:
          description: Returns updated AccountServices
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountServices
      summary: Deletes the AccountServices identified by given ID.
      description: Deletes the AccountServices identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAccountServices
      parameters:
      - name: id
        in: path
        description: Id of the AccountServices that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 AccountServicesMasterModel:
  description: AccountServicesMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the AccountServicesMasterModel
      type: string
      maxLength: 20  
     channel:
      description: Channel
      type: string
     statementCycle:
      description: Statement Cycle
      type: string  
     startDate:
      description: Start Date
      type: string 
     statementType:
      description: Statement Type
      type: string 
     repaymentCycle:
      description: Repayment Cycle
      type: string
     accountServicesModel:
      type: array
      items:
       $ref: '#/definitions/AccountServicesModel'
 AccountServicesModel:
   description: "AccountServices Model"
   type: object
   properties:
    id:
     description: Id of the AccountServicesModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the AccountServicesModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    accountServicesMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    holidayPreferenceType:
     description: Holiday Preference Type
     type: string
     maxLength: 20
    ignoreHolidays:
     description: Ignore Holidays 
     type: boolean  
    holidayCheck:
     description: Holiday check
     type: string
     maxLength: 30
    cascadeSchedules:
     description: Cascade Schedules 
     type: boolean  
    moveAcrossMonth:
     description: Move Across Month 
     type: boolean
    scheduleMovement:
     description: Schedule Movement 
     type: string  
     maxLength: 20
    seqNo:
     description: seq No
     type: integer 
 AccountServicesMasterCollection:
    description: Collection of AccountServicesMasterModel.
    type: object
    properties:
     accountServicesMasterModelList:
      type: array
      items:
       $ref: '#/definitions/AccountServicesMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 