#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : accountcreation.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/accountcreation:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AccountCreation
      summary: Adds a new AccountCreation.
      description: Adds a new AccountCreation. Add additional information here for this endpoint.
      operationId: addAccountCreation
      parameters:
      - name: AccountCreation
        in: body
        description: Request Body that contains data required for creating a new AccountCreation
        required: true
        schema:
          $ref: '#/definitions/AccountCreationModel'
      responses:
        201:
          description: Returns the Id of the newly created AccountCreation
          headers:
            Location:
              description: URL of newly created AccountCreation
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountCreation
      summary: Retrieves the list of existing AccountCreation.
      description: Retrieves the list of existing AccountCreation. Add additional information here for the this endpoint.
      operationId: getAllAccountCreation
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/accountcreation/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountCreation
      summary: Retrieves the AccountCreation by id.
      description: Retrieves the AccountCreation by id. Add additional information here for the this endpoint.
      operationId: getAccountCreationById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the AccountCreation based on given processRefNo.
          schema:
            $ref: '#/definitions/AccountCreationModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - AccountCreation
      summary: Update an existing AccountCreation.
      description: Update an existing AccountCreation. Add additional information here for the this endpoint.
      operationId: updateAccountCreation
      parameters:
      - name: id
        in: path
        description: id of the AccountCreation that need to be updated
        required: true
        type: string
      - name: AccountCreation
        in: body
        description: Request Body that contains data required for updating an existing AccountCreation
        required: true
        schema:
          $ref: '#/definitions/AccountCreationModel'
      responses:
        200:
          description: Returns updated AccountCreation
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - AccountCreation
      summary: Deletes the AccountCreation identified by given ID.
      description: Deletes the AccountCreation identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAccountCreation
      parameters:
      - name: id
        in: path
        description: Id of the AccountCreation that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  AccountCreationModel:
    description: AccountCreationModel
    type: object
    properties:
      id:
        description: Id of the AccountCreation
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36  
      status:
        description: status
        type: string
        maxLength: 36
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      applicantName:
        description: applicantName
        type: string
      approvedLoanAmount:
        description: approvedLoanAmount
        type: number
      approvedLoanAmountCurrency:
        description: approvedLoanAmountCurrency
        type: string
      offerIssueDate:
        description: offerIssueDate
        type: string  
      offerAcceptedDate:
        description: offerAcceptedDate
        type: string 
      loanTenure:
        description: loan Tenure
        type: string  
      installmentType:
        description: Installment Type
        type: string 
      installmentFrequency:
        description: Installment Frequency
        type: string
      interestRate:
        description: Interest Rate
        type: number
        format: double
      principal:
        description: Principal
        type: number
      interest:
        description: Interest 
        type: number
      installmentAmount:
        description: Installment Amount
        type: number
      totalCharges:
        description: Total Charges
        type: number
        format: double
      disbursementAccount:
        description: Disbursement Account
        type: string
      repaymentAccount:
        description: Repayment Account
        type: string
      remarks:
        description: remarks
        type: string
      version:
        description: version
        type: integer
      recordStat:
        description: recordStat
        type: string
    required:
      - processRefNo
      - applicationNumber
      - offerAcceptedDate
      - offerIssueDate
      - stageCode
  AccountCreationCollection:
    description: Collection of AccountCreation.
    type: object
    properties:
      AccountCreationList:
        type: array
        items:
          $ref: '#/definitions/AccountCreationModel'
