#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : approvaldetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/approvaldetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalDetails
      summary: Adds a new ApprovalDetails.
      description: Adds a new ApprovalDetails. Add additional information here for this endpoint.
      operationId: addApprovalDetails
      parameters:
      - name: ApprovalDetails
        in: body
        description: Request Body that contains data required for creating a new ApprovalDetails
        required: true
        schema:
          $ref: '#/definitions/ApprovalDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created ApprovalDetails
          headers:
            Location:
              description: URL of newly created ApprovalDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalDetails
      summary: Retrieves the list of existing ApprovalDetails.
      description: Retrieves the list of existing ApprovalDetails. Add additional information here for the this endpoint.
      operationId: getAllApprovalDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/approvaldetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalDetails
      summary: Retrieves the ApprovalDetails by id.
      description: Retrieves the ApprovalDetails by id. Add additional information here for the this endpoint.
      operationId: getApprovalDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ApprovalDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/ApprovalDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalDetails
      summary: Update an existing ApprovalDetails.
      description: Update an existing ApprovalDetails. Add additional information here for the this endpoint.
      operationId: updateApprovalDetails
      parameters:
      - name: id
        in: path
        description: id of the ApprovalDetails that need to be updated
        required: true
        type: string
      - name: ApprovalDetails
        in: body
        description: Request Body that contains data required for updating an existing ApprovalDetails
        required: true
        schema:
          $ref: '#/definitions/ApprovalDetailsModel'
      responses:
        200:
          description: Returns updated ApprovalDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - ApprovalDetails
      summary: Deletes the ApprovalDetails identified by given ID.
      description: Deletes the ApprovalDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteApprovalDetails
      parameters:
      - name: id
        in: path
        description: Id of the ApprovalDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  ApprovalDetailsModel:
    description: ApprovalDetailsModel
    type: object
    properties:
      id:
        description: Id of the Approval Details
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: Stage Code
        type: string
        maxLength: 36
      createdBy:
        description: Created By
        type: string
        maxLength: 36  
      status:
        description: Status
        type: string
        maxLength: 36
      processRefNo:
        description: Process Ref No
        type: string
      applicationNumber:
        description: Application Number
        type: string
      accountType:
        description: Account Type
        type: string
      accountBranch:
        description: Account Branch
        type: string
      productCode:
        description: Product Code
        type: string
      productName:
        description: Product Name
        type: string
      approvedLoanAmount:
        description: Approved Loan Amount
        type: number
      approvedLoanAmountCurrency:
        description: Approved Loan Amount Currency
        type: string
      loanTenure:
        description: Loan Tenure
        type: string  
      installmentType:
        description: Installment Type
        type: string
      interestRate: 
        description: Interest Rate
        type: number
        format: double
      effectiveRate:
        description: Effective Rate
        type: number
        format: double
      customerMargin:
        description: Margin
        type: number
        format: double
      revisedLoanAmount:
        description: Revised Loan Amount
        type: number
      revisedLoanAmountCurrency:
        description: Revised Loan Amount Currency
        type: string
      revisedLoanTenure:
        description: Revised Loan Tenure
        type: string  
      revisedInstallmentType:
        description: Revised Installment Type
        type: string
      revisedInterestRate: 
        description: Revised Interest Rate
        type: number
        format: double
      revisedEffectiveRate:
        description: Revised Effective Rate
        type: number
        format: double
      revisedCustomerMargin:
        description: Revised Margin
        type: number
        format: double 
      isRevisionNeeded:
        description: isRevisionNeeded
        type: boolean
      userRecommendation:
        description: User Recommendation
        type: string 
      assessmentCalucationMode:
        description: Assessment Calculation Mode
        type: string 
      remarks:
        description: Remarks
        type: string
      version:
        description: Version
        type: integer
      recordStat:
        description: Record Stat
        type: string
      applicantModel:
        type: array
        items:
          $ref: '#/definitions/ApplicantModel'
  ApplicantModel:
    description: "ApplicantModel Model"
    type: object
    properties:
      applicantName:
        description: Applicant Name
        type: string
      primaryApplicant:
        description: Primary Applicant
        type: boolean
      seqNo:
        description: Seq No
        type: integer
  ApprovalDetailsCollection:
    description: Collection of ApprovalDetails.
    type: object
    properties:
      ApprovalDetailsList:
        type: array
        items:
          $ref: '#/definitions/ApprovalDetailsModel'
