#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : disbursementdetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/disbursementdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DisbursementDetails
      summary: Adds a new DisbursementDetails.
      description: Adds a new DisbursementDetails. Add additional information here for this endpoint.
      operationId: addDisbursementDetails
      parameters:
      - name: DisbursementDetails
        in: body
        description: Request Body that contains data required for creating a new DisbursementDetails
        required: true
        schema:
          $ref: '#/definitions/DisbursementDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created DisbursementDetails
          headers:
            Location:
              description: URL of newly created DisbursementDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DisbursementDetails
      summary: Retrieves the list of existing DisbursementDetails.
      description: Retrieves the list of existing DisbursementDetails. Add additional information here for the this endpoint.
      operationId: getAllDisbursementDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/disbursementdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DisbursementDetails
      summary: Retrieves the DisbursementDetails by id.
      description: Retrieves the DisbursementDetails by id. Add additional information here for the this endpoint.
      operationId: getDisbursementDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DisbursementDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/DisbursementDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DisbursementDetails
      summary: Update an existing DisbursementDetails.
      description: Update an existing DisbursementDetails. Add additional information here for the this endpoint.
      operationId: updateDisbursementDetails
      parameters:
      - name: id
        in: path
        description: id of the DisbursementDetails that need to be updated
        required: true
        type: string
      - name: DisbursementDetails
        in: body
        description: Request Body that contains data required for updating an existing DisbursementDetails
        required: true
        schema:
          $ref: '#/definitions/DisbursementDetailsMasterModel'
      responses:
        200:
          description: Returns updated DisbursementDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DisbursementDetails
      summary: Deletes the DisbursementDetails identified by given ID.
      description: Deletes the DisbursementDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteDisbursementDetails
      parameters:
      - name: id
        in: path
        description: Id of the DisbursementDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
 DisbursementDetailsMasterModel:
  description: DisbursementDetailsMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the DisbursementDetailsMasterModel
      type: string
      maxLength: 20  
     multiple:
      description: is multiple Disbursement
      type: boolean 
     frequancyBased:
      description: is frequancy based Disbursement
      type: boolean 
     noOfDisbursement:
      description: no of disbursement
      type: integer 
     disbursementFrequency:
      description: disbursement Frequency
      type: string
     firstDisbursementDate:
      description: first disbursement Date
      type: string 
     disbursementMode:
      description: Disbursement Mode
      type: string
     customerAccount:
      description: Customer Account
      type: string
     accountCurrency:
      description: accountCurrency
      type: string
     branch: 
      description: Branch
      type: string
     customerIds:
      description: Comma Separated Customer Ids
      type: string   
     loanAmount:
      description: Loan Amount
      type: number
     loanCurrency:
      description: Loan Currency
      type: string
     requestedLoanAmount:
      description: Total Requested Amount
      type: number
     requestedLoanCurrency:
       description: Total Requested Amount
       type: string
     totalDisbursementAmount:
      description: Total Disbursement Amount
      type: number
     totalDisbursementCurrency:
      description: Total Disbursement Currency
      type: string
     multipleDisbAllowed:
      description: multipleDisbAllowed
      type: boolean
     bicCode:
      description: Bic Code
      type: string
      maxLength: 11
     bankCode:
      description: Bank Code
      type: string
      maxLength: 4
     accountName:
       description: accountName
       type: string
       maxLength: 100
     bankName:
      description: Bank Name
      type: string
      maxLength: 100
     extBranchCode:
      description: External Branch Code
      type: string
      maxLength: 4
     extBranchName:
      description: External Branch Name
      type: string
      maxLength: 105
     extAccNumber:
      description: External Account Number
      type: string
      maxLength: 20
     beneficiaryName:
      description: Beneficiary Name
      type: string
      maxLength: 100
     ddIssueBranchCode:
      description: DD Issue Branch Code
      type: string
      maxLength: 4
     ddIssueBranchName:
      description: DD Issue Branch Name
      type: string
      maxLength: 105
     ddPayeeBranchCode:
      description: DD Payee Branch Code
      type: string
      maxLength: 4
     ddPayeeBranchName:
      description: DD Payee Branch Name
      type: string
      maxLength: 105
     ddPayeeName:
      description: DD Payee Name     
      type: string
      maxLength: 100
     ddAddressLine1:
      description: DD Address Line 1 
      type: string
      maxLength: 50
     ddAddressLine2:
      description: DD Address Line 2
      type: string
      maxLength: 50
     ddAddressLine3: 
      description: DD Address Line 3
      type: string
      maxLength: 50
     cqIssueBranchCode:
      description: Banker's Cheque Issue Branch Code   
      type: string
      maxLength: 4
     cqIssueBranchName:
      description: Banker's Cheque Issue Branch Name
      type: string
      maxLength: 105
     cqPayeeName:
      description: Banker's Cheque Payee Name
      type: string
      maxLength: 100
     cqAddressLine1:
      description: Banker's Cheque Address Line 1
      type: string
      maxLength: 50
     cqAddressLine2:
      description: Banker's Cheque Address Line 2
      type: string
      maxLength: 50
     cqAddressLine3:
      description: Banker's Cheque Address Line 3
      type: string
      maxLength: 50
     channel:
      description: Channel
      type: string      
     disbursementDetailsModel:
      type: array
      items:
       $ref: '#/definitions/DisbursementDetailsModel'
     glCode:
      type: string
      description: General Ledger Code.
     glDesc:
      type: string
      description: General Ledger Description.
     settlementRequired:
      type: boolean
      description: Settlement Required Action.

 DisbursementDetailsModel:
   description: "DisbursementDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the DisbursementDetailsModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the DisbursementDetailsModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    disbursementDetailsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    stage:
     description: Disbursement stage
     type: string
    disbursementDate:
     description: Disbursement Date
     type: string
     maxLength: 36 
    disbursementAmount:
     description: Disbursement Amount
     type: number
    totalAmount:
     description: Total Amount
     type: number
    seqNo:
     description: Seq Number
     type: integer 
 DisbursementDetailsMasterCollection:
    description: Collection of DisbursementDetailsMasterModel.
    type: object
    properties:
     disbursementDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/DisbursementDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 