#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : edufinancialdetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/edufinancialdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ParentOrGuardianFinancialDetails
      summary: Adds a new ParentOrGuardianFinancialDetails.
      description: Adds a new ParentOrGuardianFinancialDetails. Add additional information here for this endpoint.
      operationId: addEducationLoanFinancialDetails
      parameters:
      - name: ParentOrGuardianFinancialDetails
        in: body
        description: Request Body that contains data required for creating a new ParentOrGuardianFinancialDetails
        required: true
        schema:
          $ref: '#/definitions/ParentOrGuardianDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created ParentOrGuardianFinancialDetails
          headers:
            Location:
              description: URL of newly created ParentOrGuardianFinancialDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ParentOrGuardianFinancialDetails
      summary: Retrieves the list of existing ParentOrGuardianFinancialDetails.
      description: Retrieves the list of existing ParentOrGuardianFinancialDetails. Add additional information here for the this endpoint.
      operationId: getAllEducationLoanFinancialDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/edufinancialdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - ParentOrGuardianFinancialDetails
      summary: Retrieves the ParentOrGuardianFinancialDetails by id.
      description: Retrieves the ParentOrGuardianFinancialDetails by id. Add additional information here for the this endpoint.
      operationId: getEducationLoanFinancialDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the ParentOrGuardianFinancialDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/ParentOrGuardianDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - ParentOrGuardianFinancialDetails
      summary: Update an existing ParentOrGuardianFinancialDetails.
      description: Update an existing ParentOrGuardianFinancialDetails. Add additional information here for the this endpoint.
      operationId: updateEducationLoanFinancialDetails
      parameters:
      - name: id
        in: path
        description: id of the ParentOrGuardianFinancialDetails that need to be updated
        required: true
        type: string
      - name: ParentOrGuardianFinancialDetails
        in: body
        description: Request Body that contains data required for updating an existing ParentOrGuardianFinancialDetails
        required: true
        schema:
          $ref: '#/definitions/ParentOrGuardianDetailsMasterModel'
      responses:
        200:
          description: Returns updated ParentOrGuardianFinancialDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
 
definitions:
 ParentOrGuardianDetailsMasterModel:
  description: ParentOrGuardianDetailsMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the ParentOrGuardianDetailsMasterModel
      type: string
      maxLength: 20  
     loanCurrency:
      description: loanCurrency
      type: string
     channel:
      description: Channel
      type: string
     parentOrGuardianDetailsModel: 
      type: array
      items:
       $ref: '#/definitions/ParentOrGuardianDetailsModel'
 ParentOrGuardianDetailsModel: 
   description: "ParentOrGuardianDetails Model"
   type: object
   properties:
    id: 
     description: Id of the ParentOrGuardianDetails
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the ParentOrGuardianDetailsModel
     type: string 
    applicationNumber: 
     description: applicationNumber
     type: string
     maxLength: 20
    parentOrGuardianMasterId: 
     description: Id of master table
     type: string
     maxLength: 36
    existingCustomer: 
     description: existingCustomer
     type: boolean 
    cifNumber: 
     description: CIF Number of ExistingCustomer
     type: string 
    title:
     description: title
     type: string
    firstName: 
     description: firstName
     type: string
    lastName:
     description: lastName
     type: string
    middleName:
     description: middleName
     type: string
    gender:
     description: gender
     type: string
    dateOfBirth:
     description: Date Of Birth
     type: string
    relationshipWithStudent:
     description: relationship with student
     type: string
    maritalStatus:
     description: marital Status
     type: string
    uniqueIdNo:
     description: Unique Id No
     type: string 
    totalIncomeAmount:
     description: totalIncomeAmount
     type: number
    totalIncomeCurrencyCode:
     description: totalIncomeCurrencyCode
     type: string
     maxLength: 4
    totalExpenseAmount:
     description: totalExpenseAmount
     type: number
    totalExpenseCurrencyCode:
     description: totalExpenseCurrencyCode
     type: string
     maxLength: 4
    totalAssetsAmount:
     description: totalAssetsAmount
     type: number 
    totalAssetsCurrencyCode:
     description: totalAssetsCurrencyCode
     type: string
     maxLength: 4
    totalLiabilityAmount: 
     description: totalLiabilityAmount
     type: number
    totalLiabilityCurrencyCode:
     description: totalLiabilityCurrencyCode
     type: string
     maxLength: 4
    netAmount:
     description: netAmount
     type: number
    netCurrencyCode:
     description: netCurrencyCode
     type: string
     maxLength: 4
    seqParentDetailsNo: 
     description: ParentDetails Seq NUmber
     type: integer
    basicDetailsModel: 
     type: array
     items:
      $ref: '#/definitions/BasicDetailsModel'
    incomeModel: 
     type: array
     items:
      $ref: '#/definitions/IncomeModel'
    expenseModel: 
     type: array
     items:
      $ref: '#/definitions/ExpenseModel'
    assetModel:
     type: array
     items:
      $ref: '#/definitions/AssetModel'  
    liabilityModel:
     type: array
     items:
      $ref: '#/definitions/LiabilityModel' 
 BasicDetailsModel: 
   description: "BasicDetailsModel"
   type: object
   properties:
    id:
     description: Id of the BasicDetailsModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the BasicDetailsModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    parentOrGuardianDetailsId: 
     description: Id of summary table
     type: string
     maxLength: 36
    incomeType:
     description: incomeType
     type: string
    employmentType:
     description: employmentType
     type: string
    employeeNumber:
     description: employeeNumber
     type: string
    industry:
     description: industry
     type: string
    officeName:
     description: officeName
     type: string
    educationQualification:
     description: educationQualification
     type: string
    designation:
     description: designation
     type: string
    employmentStartDate:
     description: employmentStartDate
     type: string
    employmentEndDate:
     description: employmentEndDate
     type: string
    seqBasicDetailsNo: 
     description: seqBasicDetailsNo
     type: integer
    addressType: 
     description: addressType
     type: string
    address:
     $ref: '#/definitions/Address'
 Address: 
   description: "Address Model"
   type: object
   properties:
    country:
     description: country
     type: string
     maxLength: 50
    state:
     description: state
     type: string
     maxLength: 50
    city:
     description: city
     type: string
     maxLength: 50
    addressLine1:
     description: addressLine1
     type: string
     maxLength: 100
    addressLine2:
     description: addressLine2
     type: string
     maxLength: 100
    addressLine3:
     description: addressLine3
     type: string
     maxLength: 100
    pinCode:
     description: pinCode
     type: string
     maxLength: 10
    email:
     description: email
     type: string
     maxLength: 30
    mobileNo:
     description: mobileNo
     type: integer
     format: int64
    mobileIsd:
     description: mobileIsd
     type: string
     maxLength: 5
    phoneNo:
     description: phoneNo
     type: integer
     format: int64
    phoneIsd:
     description: phoneIsd
     type: string
     maxLength: 5
 IncomeModel: 
   description: "IncomeModel Model"
   type: object
   properties:
    id:
     description: Id of the IncomeModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the IncomeModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    parentOrGuardianDetailsId:
     description: Id of summary table
     type: string
     maxLength: 36
    incomeType:
     description: incomeType
     type: string
    incomeAmount:
     description: incomeAmount
     type: number
    incomeCurrencyCode: 
     description: incomeCurrencyCode
     type: string
     maxLength: 4
    seqIncomeNo: 
     description: seqIncomeNo
     type: integer
 ExpenseModel: 
   description: "ExpenseModel Model"
   type: object
   properties:
    id:
     description: Id of the ExpenseModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the ExpenseModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    parentOrGuardianDetailsId:
     description: Id of summary table
     type: string
     maxLength: 36
    expenseType:
     description: expenseType
     type: string
    expenseAmount:
     description: expenseAmount
     type: number
    expenseCurrencyCode: 
     description: expenseCurrencyCode
     type: string
     maxLength: 4
    seqExpenseNo: 
     description: seqExpenseNo
     type: integer
 AssetModel: 
   description: "Asset Model"
   type: object
   properties:
    id:
     description: Id of the Asset Model
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the Asset Model
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    parentOrGuardianDetailsId:
     description: Id of summary table
     type: string
     maxLength: 36
    assetType:
     description: assetType
     type: string
    assetAmount:
     description: assetAmount
     type: number
    assetCurrencyCode: 
     description: assetCurrencyCode
     type: string
     maxLength: 4
    seqAssetNo: 
     description: seqAssetNo
     type: integer
 LiabilityModel: 
   description: "Liability Model"
   type: object
   properties:
    id:
     description: Id of the Liability Model
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the Liability Model
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber
     type: string
    parentOrGuardianDetailsId:
     description: Id of summary table
     type: string
     maxLength: 36
    liabilityType:
     description: liabilityType
     type: string
    liabilityAmount:
     description: liabilityAmount
     type: number
    liabilityCurrencyCode:
     description: liabilityCurrencyCode
     type: string
     maxLength: 4
    seqLiabilityNo: 
     description: seqLiabilityNo
     type: integer
 ParentOrGuardianDetailsMasterCollection: 
    description: Collection of  ParentOrGuardianDetailsMasterModel.
    type: object
    properties:
     parentOrGuardianDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/ParentOrGuardianDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 