#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : loansummary.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/loansummary:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSummary
      summary: Adds a new LoanSummary.
      description: Adds a new LoanSummary. Add additional information here for this endpoint.
      operationId: addLoanSummary
      parameters:
      - name: LoanSummary
        in: body
        description: Request Body that contains data required for creating a new LoanSummary
        required: true
        schema:
          $ref: '#/definitions/LoanSummaryModel'
      responses:
        201:
          description: Returns the Id of the newly created LoanSummary
          headers:
            Location:
              description: URL of newly created LoanSummary
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSummary
      summary: Retrieves the list of existing LoanSummary.
      description: Retrieves the list of existing LoanSummary. Add additional information here for the this endpoint.
      operationId: getAllLoanSummary
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/loansummary/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSummary
      summary: Retrieves the LoanSummary by id.
      description: Retrieves the LoanSummary by id. Add additional information here for the this endpoint.
      operationId: getLoanSummaryById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the LoanSummary based on given processRefNo.
          schema:
            $ref: '#/definitions/LoanSummaryModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSummary
      summary: Update an existing LoanSummary.
      description: Update an existing LoanSummary. Add additional information here for the this endpoint.
      operationId: updateLoanSummary
      parameters:
      - name: id
        in: path
        description: id of the LoanSummary that need to be updated
        required: true
        type: string
      - name: LoanSummary
        in: body
        description: Request Body that contains data required for updating an existing LoanSummary
        required: true
        schema:
          $ref: '#/definitions/LoanSummaryModel'
      responses:
        200:
          description: Returns updated LoanSummary
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanSummary
      summary: Deletes the LoanSummary identified by given ID.
      description: Deletes the LoanSummary identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLoanSummary
      parameters:
      - name: id
        in: path
        description: Id of the LoanSummary that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LoanSummaryModel:
    description: Loan Summary Model
    type: object
    properties:
      id:
        description: Id of the Loan Summary
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: Stage Code
        type: string
        maxLength: 36
      createdBy:
        description: Created By
        type: string
        maxLength: 36  
      status:
        description: Status
        type: string
        maxLength: 36
      processRefNo:
        description: Process Ref No
        type: string
      applicationNumber:
        description: Application Number
        type: string
      accountType:
        description: Account Type
        type: string
      accountBranch:
        description: Account Branch
        type: string
      productCode:
        description: Product Code
        type: string
      productName:
        description: Product Name
        type: string
      productDesc:
        description: Product Description
        type: string
      hostProductCode:
        description: Host Product Code
        type: string
      hostProductDesc:
        description: Host Product Description
        type: string
      loanAmount:
        description: Loan Amount
        type: number
      loanAmountCurrency:
        description: Loan Amount Currency
        type: string
      loanTenure:
        description: Loan Tenure
        type: string  
      interestRate:
        description: Interest Rate
        type: number
        format: double
      repaymentType:
        description: Repayment Type
        type: string
      repaymentFrequency:
        description: Repayment Frequency
        type: string
      applicationDate:
        description: Application Date
        type: string
      assessmentApprovalMethod:
        description: Assessment Approval Method
        type: string
      offerIssueDate:
        description: Offer Issue Date
        type: string
      offerAcceptedDate:
        description: Offer Accepted Date
      userRecommendation:
        description: User Recommendation
        type: string 
      remarks:
        description: Remarks
        type: string
      version:
        description: Version
        type: integer
      recordStat:
        description: Record Stat
        type: string
      applicantModel:
        type: array
        items:
          $ref: '#/definitions/ApplicantModel'
      approvalAuthorityModel:
        type: array
        items:
          $ref: '#/definitions/ApprovalAuthorityModel'
  ApplicantModel:
    description: "ApplicantModel Model"
    type: object
    properties:
      applicantName:
        description: Applicant Name
        type: string
      customerId:
        description: Customer Id
        type: string
      primaryApplicant:
        description: Primary Applicant
        type: boolean
      seqNo:
        description: Seq No
        type: integer
  ApprovalAuthorityModel:
    description: ApprovalAuthorityModel model
    type: object
    properties:
      authorizedUserId:
        description: Authorized User Id
        type: string
      authorizedStage:
        description: Authorized Stage
        type: string
      dateOfAuthorization:
        description: Date of Authorization
        type: string
  LoanSummaryCollection:
    description: Collection of LoanSummary.
    type: object
    properties:
      LoanSummaryList:
        type: array
        items:
          $ref: '#/definitions/LoanSummaryModel'
