#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : loandetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/loandetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanDetails
      summary: Adds a new LoanDetails.
      description: Adds a new LoanDetails. Add additional information here for this endpoint.
      operationId: addLoanDetails
      parameters:
      - name: LoanDetails
        in: body
        description: Request Body that contains data required for creating a new LoanDetails
        required: true
        schema:
          $ref: '#/definitions/LoanDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created LoanDetails
          headers:
            Location:
              description: URL of newly created LoanDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanDetails
      summary: Retrieves the list of existing LoanDetails.
      description: Retrieves the list of existing LoanDetails. Add additional information here for the this endpoint.
      operationId: getAllLoanDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      - name: businessProductCode
        in: query
        description: businessProductCode of the user that needs to be fetched
        required: false
        type: string
      - name: ipaReferenceNumber
        in: query
        description: ipaReferenceNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/loandetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanDetails
      summary: Retrieves the LoanDetails by id.
      description: Retrieves the LoanDetails by id. Add additional information here for the this endpoint.
      operationId: getLoanDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the LoanDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/LoanDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanDetails
      summary: Update an existing LoanDetails.
      description: Update an existing LoanDetails. Add additional information here for the this endpoint.
      operationId: updateLoanDetails
      parameters:
      - name: id
        in: path
        description: id of the LoanDetails that need to be updated
        required: true
        type: string
      - name: LoanDetails
        in: body
        description: Request Body that contains data required for updating an existing LoanDetails
        required: true
        schema:
          $ref: '#/definitions/LoanDetailsModel'
      responses:
        200:
          description: Returns updated LoanDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanDetails
      summary: Deletes the LoanDetails identified by given ID.
      description: Deletes the LoanDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteLoanDetails
      parameters:
      - name: id
        in: path
        description: Id of the LoanDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  LoanDetailsModel:
    description: LoanDetails model
    type: object
    properties:
      id:
        description: Id of the LoanDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      loanCurrencyCode:
        description: loanCurrencyCode
        type: string
        maxLength: 4
      estimatedCost:
        description: Estimated Cost
        type: number
      customerContribution:
        description: Customer Contribution
        type: number
      loanAmount:
        description: loanAmount
        type: number
      loanTenureYears:
        description: loanTenureYears
        type: integer
        format: int64
        minimum: 0
      loanTenureMonths:
        description: loanTenureMonths
        type: integer
        format: int64
        minimum: 0
      loanTenureDays:
        description: loanTenureDays
        type: integer
        format: int64
        minimum: 0
      purposeOfLoan:
        description: purposeOfLoan
        type: string
      productName:
        description: productName
        type: string
        maxLength: 100
      productCode:
        description: productCode
        type: string
        maxLength: 50
      accountType:
        description: Account Type
        type: string
      accountBranch:
        description: Account Branch
        type: string
      applicationDate:
        description: Application Date
        type: string
      sourceEmpName:
        description: Source Emp Name
        type: string
      sourceEmpCode:
        description: Source Emp Code
        type: string
      productImage:
        description: Product Image
        type: string
      productSummary:
        description: Product Summary
        type: string
      bankName:
        description: Bank Name
        type: string
      branchName:
        description: Branch Name
        type: string
      remarks:
        description: remarks
        type: string
      version:
        description: version
        type: integer
      recordStat:
        description: version
        type: string
      channel:
        description: Channel
        type: string
      ipaReferenceNumber:
        description: Ipa Reference Number
        type: string
  LoanDetailsCollection:
    description: Collection of LoanDetails.
    type: object
    properties:
      LoanDetailsList:
        type: array
        items:
          $ref: '#/definitions/LoanDetailsModel'
