#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : loanapplicationservice.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /loanapplication-services
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  
  /service-api/v1/loanapplications/customeraccounts/{applicationNumber}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - LoanApplicationAggService
      summary: Retrieves the list of customer accounts
      description: Retrieves the list of customer accounts. Add additional information here for the this endpoint.
      operationId: getCustomerAccounts
      parameters:
      - name: applicationNumber
        in: path
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      - name: customerNo
        in: query
        description: comma seperated customerNo for the stage
        required: true
        type: string
      - name: accountCurrency
        in: query
        description: Account Currency
        type: string
        required: true
      - name: offset
        in: query
        description: offset is starting no of records to be fetched
        required: false
        type: integer
      - name: limit
        in: query
        description: limit is maximum no of records to be fetched
        required: false
        type: integer
      - name: customerId
        in: query
        description: Customer Id
        required: false
        type: string
      - name: accountNumber
        in: query
        description: Account Number
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/CustomerAccountMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
          
          
  /service-api/v1/customerdecision:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - LoanApplicationAggService
      summary: Adds a new CustomerDecision.
      description: Adds a new CustomerDecision. 
      operationId: addCustomerDecision
      parameters:
      - name: CustomerDecision
        in: body
        description: Request Body that contains data required for creating a new CustomerDecision
        required: true
        schema:
          $ref: '#/definitions/CustDecisionModel'
      responses:
        201:
          description: Returns the Id of the newly created CustomerDecision
          headers:
            Location:
              description: URL of newly created CustomerDecision
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
          
definitions:
  CustDecisionModel:
    description: CustDecision model
    type: object
    properties:
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      customerResponse:
        description: customerResponse
        type: string 
      offerAmendDate:
        description: offerAmendDate
        type: string
      dateOfOfferAcceptOrReject:
        description: dateOfOfferAcceptOrReject
        type: string
      reason:
        description: reason
        type: string
      remarks:
        description: remarks
        type: string
    required:
      - processRefNo
      - applicationNumber