#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : mandatedetails.yaml
#  **
#  ** Module     : 
#  ** 
 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/mandatedetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDetails
      summary: Adds a new MandateDetails.
      description: Adds a new MandateDetails. Add additional information here for this endpoint.
      operationId: addMandateDetails
      parameters:
      - name: MandateDetails
        in: body
        description: Request Body that contains data required for creating a new MandateDetails
        required: true
        schema:
          $ref: '#/definitions/MandateDetailsMasterModel'
      responses:
        201:
          description: Returns the Id of the newly created MandateDetails
          headers:
            Location:
              description: URL of newly created MandateDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDetails
      summary: Retrieves the list of existing MandateDetails.
      description: Retrieves the list of existing MandateDetails. Add additional information here for the this endpoint.
      operationId: getAllMandateDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the application  that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/mandatedetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDetails
      summary: Retrieves the MandateDetails by id.
      description: Retrieves the MandateDetails by id. Add additional information here for the this endpoint.
      operationId: getMandateDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the MandateDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/MandateDetailsMasterModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - MandateDetails
      summary: Update an existing MandateDetails.
      description: Update an existing MandateDetails. Add additional information here for the this endpoint.
      operationId: updateMandateDetails
      parameters:
      - name: id
        in: path
        description: id of the MandateDetails that need to be updated
        required: true
        type: string
      - name: MandateDetails
        in: body
        description: Request Body that contains data required for updating an existing MandateDetails
        required: true
        schema:
          $ref: '#/definitions/MandateDetailsMasterModel'
      responses:
        200:
          description: Returns updated MandateDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
 
definitions:
 MandateDetailsMasterModel:
  description: MandateDetailsMaster model
  type: object
  allOf:
  - $ref: '#/definitions/GenericDatasegmentModel'
  - type: object
    properties:
     processRefNo:
      description: Process Ref No of the MandateDetailsMasterModel
      type: string
      maxLength: 20
     channel:
      description: Channel
      type: string   
     registered:
      description: registered
      type: boolean
     noOfMandates:
      description: Number of Mandates
      type: integer
     mandateDetailsModel:
      type: array
      items:
       $ref: '#/definitions/MandateDetailsModel'
 MandateDetailsModel:
   description: "MandateDetailsModel Model"
   type: object
   properties:
    id:
     description: Id of the MandateDetailsModel
     type: string
     maxLength: 36
    processRefNo:
     description: Process Ref No of the MandateDetailsModel
     type: string
     maxLength: 20
    applicationNumber:
     description: applicationNumber of the MandateDetailsModel
     type: string
     maxLength: 20
    mandateDetailsMasterId:
     description: Id of master table
     type: string
     maxLength: 36
    applicantName:
     description: Applicant Name
     type: string
    collateralShare:
     description: collateralShare
     type: number
     format: double
    repaymentShare:
     description: repaymentShare
     type: number
     format: double
    applicantId:
     description: applicantId
     type: string
     maxLength: 36
    deleteMandate:
     description: deleteMandate
     type: boolean
    primaryApplicant:
     description: primaryApplicant
     type: boolean
    cifNumber:
     description: cifNumber
     type: string
    existingCustomer:
     description: existingCustomer
     type: boolean
    partyHandofftoHostStatus:
     description: partyHandofftoHostStatus
     type: string 
 MandateDetailsMasterCollection:
    description: Collection of MandateDetailsMasterModel.
    type: object
    properties:
     mandateDetailsMasterModelList:
      type: array
      items:
       $ref: '#/definitions/MandateDetailsMasterModel'
 GenericDatasegmentModel:
   allOf:
    - type: object
      discriminator: resource_type 