#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : postamendmentdetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/postamendmentdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PostAmendmentDetails
      summary: Adds a new PostAmendmentDetails.
      description: Adds a new PostAmendmentDetails. Add additional information here for this endpoint.
      operationId: addPostAmendmentDetails
      parameters:
      - name: PostAmendmentDetails
        in: body
        description: Request Body that contains data required for creating a new PostAmendmentDetails
        required: true
        schema:
          $ref: '#/definitions/PostAmendmentDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created PostAmendmentDetails
          headers:
            Location:
              description: URL of newly created PostAmendmentDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PostAmendmentDetails
      summary: Retrieves the list of existing PostAmendmentDetails.
      description: Retrieves the list of existing PostAmendmentDetails. Add additional information here for the this endpoint.
      operationId: getAllPostAmendmentDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/postamendmentdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - PostAmendmentDetails
      summary: Retrieves the PostAmendmentDetails by id.
      description: Retrieves the PostAmendmentDetails by id. Add additional information here for the this endpoint.
      operationId: getPostAmendmentDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the PostAmendmentDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/PostAmendmentDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - PostAmendmentDetails
      summary: Update an existing PostAmendmentDetails.
      description: Update an existing PostAmendmentDetails. Add additional information here for the this endpoint.
      operationId: updatePostAmendmentDetails
      parameters:
      - name: id
        in: path
        description: id of the PostAmendmentDetails that need to be updated
        required: true
        type: string
      - name: PostAmendmentDetails
        in: body
        description: Request Body that contains data required for updating an existing PostAmendmentDetails
        required: true
        schema:
          $ref: '#/definitions/PostAmendmentDetailsModel'
      responses:
        200:
          description: Returns updated PostAmendmentDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - PostAmendmentDetails
      summary: Deletes the PostAmendmentDetails identified by given ID.
      description: Deletes the PostAmendmentDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deletePostAmendmentDetails
      parameters:
      - name: id
        in: path
        description: Id of the PostAmendmentDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  PostAmendmentDetailsModel:
    description: PostAmendmentDetailsModel
    type: object
    properties:
      id:
        description: Id of the Post Amendment Details
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36  
      status:
        description: status
        type: string
        maxLength: 36
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      offerIssueDate:
        description: offerIssueDate
        type: string
      offerExpiryDate:
        description: offerExpiryDate
        type: string
      offerAmendDate:
        description: offerAmendDate
        type: string
      approvedLoanAmount:
        description: approvedLoanAmount
        type: number
      approvedLoanAmountCurrency:
        description: approvedLoanAmountCurrency
        type: string
      loanTenure:
        description: loan Tenure
        type: string  
      loanTenureYears:
        description: loanTenureYears
        type: integer
        format: int64
        minimum: 0
      loanTenureMonths:
        description: loanTenureMonths
        type: integer
        format: int64
        minimum: 0
      loanTenureDays:
        description: loanTenureDays
        type: integer
        format: int64
        minimum: 0
      installmentType:
        description: Installment Type
        type: string 
      rateOfInterest: 
        description: Rate of Interest
        type: number
        format: double
      effectiveRate:
        description: Effective Rate
        type: number
        format: double
      customerMargin:
        description: Margin
        type: number
        format: double
      interestTolerance:
        description: interestTolerance
        type: number
      udeMax:
        description: udeMax
        type: number
      udeMin:
        description: udeMin
        type: number
      remarks:
        description: remarks
        type: string
      version:
        description: version
        type: integer
      recordStat:
        description: recordStat
        type: string
      applicantModel:
        type: array
        items:
          $ref: '#/definitions/ApplicantModel'
    required:
      - processRefNo
      - applicationNumber
      - offerAmendDate
      - stageCode     
  ApplicantModel:
    description: "ApplicantModel Model"
    type: object
    properties:
      applicantName:
        description: Applicant Name
        type: string
      primaryApplicant:
        description: Primary Applicant
        type: boolean
      seqNo:
        description: Seq No
        type: integer
  PostAmendmentDetailsCollection:
    description: Collection of PostAmendmentDetailsModel.
    type: object
    properties:
      PostAmendmentDetailsList:
        type: array
        items:
          $ref: '#/definitions/PostAmendmentDetailsModel'
