#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : repaymentdetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Loan Application Service
host: 10.184.157.121:9000
basePath: /obremo-rpm-lo-loanapplications
tags:
- name: LoanApplication
  description: API for LoanApplication Operations
schemes:
- http
paths:
  /web/v1/repaymentdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Adds a new RepaymentDetails.
      description: Adds a new RepaymentDetails. Add additional information here for this endpoint.
      operationId: addRepaymentDetails
      parameters:
      - name: RepaymentDetails
        in: body
        description: Request Body that contains data required for creating a new RepaymentDetails
        required: true
        schema:
          $ref: '#/definitions/RepaymentDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created RepaymentDetails
          headers:
            Location:
              description: URL of newly created RepaymentDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Retrieves the list of existing RepaymentDetails.
      description: Retrieves the list of existing RepaymentDetails. Add additional information here for the this endpoint.
      operationId: getAllRepaymentDetails
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/repaymentdetails/schedule:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Retrieves the list of existing RepaymentScheduleDetails.
      description: Retrieves the list of existing RepaymentScheduleDetails. Add additional information here for the this endpoint.
      operationId: getRepaymentSchedule
      parameters:
      - name: processRefNo
        in: query
        description: processRefNo of the user that needs to be fetched
        required: true
        type: string
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      - name: repaymentType
        in: query
        description: repaymentType of the user that needs to be fetched
        required: false
        type: string
      - name: repaymentFrequency
        in: query
        description: repaymentFrequency of the user that needs to be fetched
        required: false
        type: string
      - name: firstRepaymentDate
        in: query
        description: firstRepaymentDate of the user that needs to be fetched
        required: false
        type: string
      - name: moratoriumPeriod
        in: query
        description: moratoriumPeriod of the user that needs to be fetched
        required: false
        type: integer
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/RepaymentScheduleModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/repaymentdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Retrieves the RepaymentDetails by id.
      description: Retrieves the RepaymentDetails by id. Add additional information here for the this endpoint.
      operationId: getRepaymentDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the RepaymentDetails based on given processRefNo.
          schema:
            $ref: '#/definitions/RepaymentDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Update an existing RepaymentDetails.
      description: Update an existing RepaymentDetails. Add additional information here for the this endpoint.
      operationId: updateRepaymentDetails
      parameters:
      - name: id
        in: path
        description: id of the RepaymentDetails that need to be updated
        required: true
        type: string
      - name: RepaymentDetails
        in: body
        description: Request Body that contains data required for updating an existing RepaymentDetails
        required: true
        schema:
          $ref: '#/definitions/RepaymentDetailsModel'
      responses:
        200:
          description: Returns updated RepaymentDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - RepaymentDetails
      summary: Deletes the RepaymentDetails identified by given ID.
      description: Deletes the RepaymentDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteRepaymentDetails
      parameters:
      - name: id
        in: path
        description: Id of the RepaymentDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  RepaymentDetailsModel:
    description: RepaymentDetails model
    type: object
    properties:
      id:
        description: Id of the RepaymentDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      createdTimeStamp:
        description: Created Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      processRefNo:
        description: processRefNo
        type: string
      applicationNumber:
        description: applicationNumber
        type: string
      repaymentType:
        description: repaymentType
        type: string
      maturityDate:
        description: maturityDate
        type: string
      firstRepaymentDate:
        description: firstRepaymentDate
        type: string
      repaymentMode:
        description: repaymentMode
        type: string
      customerAccount:
        description: customerAccount
        type: string
      branch:
        description: branch
        type: string
      customerIds:
        description: Comma Separated Customer Ids
        type: string 
      firstDisbursementDate:
        description: first disbursement Date
        type: string   
      repaymentFrequency:
        description: repaymentFrequency
        type: string   
      loanTenure:
        description: loanTenure
        type: string  
      loanCurrencyCode:
        description: loanCurrencyCode
        type: string 
      remarks:
        description: remarks
        type: string
      version:
        description: version
        type: integer
      recordStat:
        description: recordStat
        type: string 
      moratoriumAllowed:
        description: moratoriumAllowed
        type: boolean
      moratoriumPeriod:
        description: moratoriumPeriod
        type: integer
      channel:
        description: Channel
        type: string
      bicCode:
        description: Bic Code
        type: string
        maxLength: 11
      bankCode:
        description: Bank Code
        type: string
        maxLength: 4
      bankName:
        description: Bank Name
        type: string
        maxLength: 100
      extBranchCode:
        description: External Branch Code
        type: string
        maxLength: 4
      extBranchName:
        description: External Branch Name
        type: string
        maxLength: 105
      extAccNumber:
        description: External Account Number
        type: string
        maxLength: 20
      beneficiaryName:
        description: Beneficiary Name
        type: string
        maxLength: 100
  RepaymentScheduleModel:
     description: "RepaymentScheduleModel Model"
     type: object
     properties:
      dueDate:
       description: Due Date
       type: string
      principleAmount:
       description: Principle Amount
       type: number
      interestAmount:
       description: Interest Amount
       type: number
      emiAmount:
       description: Emi Amount
       type: number
  RepaymentDetailsCollection:
    description: Collection of RepaymentDetails.
    type: object
    properties:
      RepaymentDetailsList:
        type: array
        items:
          $ref: '#/definitions/RepaymentDetailsModel'
