#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ProcessTimePrediction.yaml
#  **
#  ** Module     : ML
#  ** 
#  ** This source is part of the Oracle FLEXCUBE  and is copyrighted by Oracle Financial Services Software Limited.  ** 
#  ** 
#  ** All rights reserved. No part of this work may be reproduced, stored in a retrieval system,
#  ** adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
#  ** graphic, optic recording or otherwise, translated in any language or computer language,
#  ** without the prior written permission of Oracle Financial Services Software Limited.
#  ** 
#  ** Oracle Financial Services Software Limited.
#  ** 10-11, SDF I, SEEPZ, Andheri (East),
#  ** Mumbai - 400 096.
#  ** India
#  ** Copyright 2017-2018 Oracle Financial Services Software Limited. All rights reserved.
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 description: ProcessTimePrediction
 version: "1.0.0"
 title: "ProcessTimePrediction"
host: "api-plato.us.oracle.com:8080"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "ProcessTimePrediction"

schemes:
- "https"

paths:
 /ml/accountOpeningDate:
  get:
    produces:
      - application/json
      - application/xml
    tags:
      - ProcessTimePrediction
    summary: get the account opening date
    description: get the account opening date
    operationId: getExpectedAccountOpeningDate    
    parameters:
    - name: caseidentifier
      in: query
      description: case identifier
      required: true
      type: string 
    responses:
      201:
        description: Returns the domain with the count of applications initiated by the RM
        schema:
          $ref: '#/definitions/String'
      400:
        description: Malformed syntax.
      401:
        description: Request does not have sufficient credentials.
      403:
        description: Request is not authorized.
      405:
        description: Invalid input
      500:
        description: Internal error
 /stageMovementData:
  post:
   tags:
    - "ProcessTimePrediction"
   summary: "Posts stage movement data."
   description: "Posts stage movement data"
   operationId: "saveStageMovementData"
   parameters:
    - name: "StageMovementModel" 
      in: "body" 
      description: "Request Body that contains data required for creating a new StageMovement" 
      required: true
      schema:
       $ref: "#/definitions/StageMovementModel"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created StageMovementModel" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
 /processPredictionTimeData:
  post:
   tags:
    - "ProcessTimePrediction"
   summary: "Adds a new ProcessPredictionTimeData."
   description: "Adds a new ProcessPredictionTimeData. Add additional information here for this endpoint."
   operationId: "saveProcessPredictionTimeData"
   parameters:
    - name: "ProcessTimePredictionModel" 
      in: "body" 
      description: "Request Body that contains data required for creating a new ProcessTimePredictionModel" 
      required: true
      schema:
       $ref: "#/definitions/ProcessTimePredictionModel"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     headers:
      Location:
       description: "URL of newly created ProcessTimePredictionModel" 
       type: "string"
     schema:
       $ref: "#/definitions/ResponseDtoWrapper"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Invalid input"
    500:
     description: "Internal error"
  get:
   tags:
    - "ProcessTimePrediction"
   summary: "Retrieves the ProcessTimePredictionModel by ID."
   description:  "Retrieves the ProcessTimePredictionModel by ID."
   operationId: "getProcessTimePredictionData"
   parameters:
    - name: "processId"
      in: "query"
      description: "Process Reference Number or Process ID"
      required: true
      type: "string"
    - name: "currStageCode"
      in: "query"
      description: "Current Stage Code"
      required: false
      type: "string"
   responses:
    200:
     description: "Returns the ProcessPredictionTimeData based on given id."
     schema:
      $ref: "#/definitions/ProcessTimePredictionModelCollection"
    400:
     description: "Malformed syntax."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    500:
     description: "Internal error"
definitions:
 ProcessTimePredictionModel:
  type: object
  allOf:
  - type: object
    properties:
     applicationNo:
      type: string
      description: ""
     applAmount:
      type: integer
      description: ""
     birthCountry:
      type: string
      description: ""
     ccy:
      type: string
      description: ""
     citizenshipBy:
      type: string
      description: ""
     cntDocReqd:
      type: integer
      description: ""
     collateralLegalOpinion:
      type: string
      description: ""
     collateralReqd:
      type: string
      description: ""
     countryOfResidence:
      type: string
      description: ""
     creditScore:
      type: string
      description: ""
     currStageCode:
      type: string
      description: ""
     customerAge:
      type: integer
      description: ""
     customerContribution:
      type: integer
      description: ""
     customerGender:
      type: string
      description: ""
     customerSegment:
      type: string
      description: ""
     customerSubType:
      type: string
      description: ""
     custDetailsAmended:
      type: string
      description: ""
     custRespReqd:
      type: string
      description: ""
     employeeType:
      type: string
      description: ""
     existingCustomer:
      type: string
      description: ""
     guarantorAdded:
      type: string
      description: ""
     guarantorAge:
      type: integer
      description: ""
     guarantorRelationWithCust:
      type: string
      description: ""
     highestDelinquencyBucket:
      type: string
      description: ""
     idType:
      type: string
      description: ""
     industryType:
      type: string
      description: ""
     jointAccount:
      type: string
      description: ""
     kycComplianceStatus:
      type: string
      description: ""
     submitHourCatg:
      type: integer
      description: ""
     lastStageCompletedTimestamp:
      type: string
      format: date
      description: ""
     maritalStatus:
      type: string
      description: ""
     nationality:
      type: string
      description: ""
     noOfApplicants:
      type: integer
      description: ""
     noOfCollaterals:
      type: integer
      description: ""
     noOfCustClarification:
      type: integer
      description: ""
     noOfGuarantor:
      type: integer
      description: ""
     noOfRecordsInAdditionalCbdetails:
      type: integer
      description: ""
     organisationType:
      type: string
      description: ""
     overdraftRequested:
      type: string
      description: ""
     pendStages:
      type: integer
      description: ""
     predTime:
      type: integer
      description: ""
     primaryCollateralCatg:
      type: string
      description: ""
     primaryCollateralType:
      type: string
      description: ""
     processId:
      type: string
      description: ""
     prodCode:
      type: string
      description: ""
     prodType:
      type: string
      description: ""
     residentialStatus:
      type: string
      description: ""
     stageTimeSpent:
      type: integer
      description: ""
     submitDay:
      type: integer
      description: ""
     submitMonth:
      type: string
      description: ""
     tenureInDays:
      type: integer
      description: ""
     time2Complete:
      type: integer
      description: ""
     totalCoverValue:
      type: integer
      description: ""
     totalLoanAmount:
      type: integer
      description: ""
     totalOutstandingAmount:
      type: integer
      description: ""
     totNumStages:
      type: integer
      description: ""
 StageMovementModel:
  type: object
  allOf:
  - type: object
    properties:
      applicationNumber:
        description: Application Number
        type: string
        maxLength: 36
      processRefNo:
        description: Process Reference Number
        type: string
        maxLength: 36
      currentStageCode:
        description: Current Stage Code
        type: string
      currentStageName:
        description: Current Stage Name
        type: string
      status:
        description: Status
        type: string
      productCode:
        description: Product Code
        type: string
      productType:
        description: Product Type
        type: string
      isInstantAccStage:
        description: Check if the stage is for Instant Account
        type: string
 ResponseDto:
  type: object
  properties:
   id:
    type: string
   status:
    type: string
   codes:
    type: array
    items:
     $ref: "#/definitions/ResponseCode"
   requestId:
    type: string
 ResponseCode:
  type: object
  properties:
   Code:
    type: string
   Desc:
    type: string
   Type:
    type: string
   Language:
    type: string
   args:
    type: array
    items:
     type: object
   arg:
    type: string
 ProcessTimePredictionModelCollection: 
  description: "Collection of mlpredprctime."
  type: "object"
  properties:
   data:
    type: "array"
    items: 
     $ref: "#/definitions/ProcessTimePredictionModel"
 ResponseDtoWrapper:
  type: object
  properties:
   messages:
    $ref: "#/definitions/ResponseDto"
   data:
    $ref: "#/definitions/ResponseResourceSupport"
 ResponseResourceSupport:
  type: object