#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking CorpoparticipationPending Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : agreementdetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: syndicationapplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/agreementdetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - agreementdetails
      summary: Adds a new agreementdetails.
      description: Adds a new agreementdetails. Add additional information here for this endpoint.
      operationId: addAgreementDetails
      parameters:
      - name: AgreementDetailsModel
        in: body
        description: Request Body that contains data required for creating a new agreementdetails
        required: true
        schema:
          $ref: '#/definitions/AgreementDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created Charges
          headers:
            Location:
              description: URL of newly created Charges
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - agreementdetails
      summary: Retrieves the list of existing agreementdetails.
      description: Retrieves the list of existing agreementdetails. Add additional information here for the this endpoint.
      operationId: getAllAgreementDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/agreementdetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - agreementdetails
      summary: Get a  agreementdetails.
      description: Get a  agreementdetails by given id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: id of the agreementdetails that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated agreementdetails
          schema:
            $ref: '#/definitions/AgreementDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - agreementdetails
      summary: Update an existing agreementdetails.
      description: Update an existing agreementdetails. Add additional information here for the this endpoint.
      operationId: updateAgreementDetails
      parameters:
      - name: id
        in: path
        description: id of the agreementdetails that need to be updated
        required: true
        type: string
      - name: agreementdetails
        in: body
        description: Request Body that contains data required for updating an existing agreementdetails
        required: true
        schema:
          $ref: '#/definitions/AgreementDetailsModel'
      responses:
        200:
          description: Returns updated agreementdetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - agreementdetails
      summary: Deletes the agreementdetails identified by given ID.
      description: Deletes the agreementdetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteAgreementDetails
      parameters:
      - name: id
        in: path
        description: Id of the agreementdetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error    
definitions:
  AgreementDetailsModel:
    description: agreementdetails model
    type: object
    required:
    - applicationNumber
    - agreementDate
    - processRefNumber
    properties:
      id:
        description: Id of the agreementdetails
        type: string
      applicationNumber:
        description: Application Number of the agreement details
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string   
      agreementDate:
        description: agreementDate of the agreement details
        type: string 
      agreementEndDate:
        description: agreementEndDate of the agreement details
        type: string
      signingDate:
        description: signingDate of the agreement details
        type: string
      approvalDate:
        description: approvalDate of the agreement details
        type: string
      approvalAmount:
        description: approvalAmount of the agreement details
        type: number
      approvalCurrency:
        description: approvalCurrency of the agreement details
        type: string  
      withheldAmount:
        description: withheldAmount of the agreement details
        type: number
      withheldCurrency:
        description: withheldCurrency of the agreement details
        type: string
      decreaseWithheldAmount:
        description: decreaseWithheldAmount of the agreement details
        type: number
      decreaseWithheldCurrency:
        description: decreaseWithheldCurrency of the agreement details
        type: string
      signingAmount:
        description: signingAmount of the agreement details
        type: number
      signingCurrency:
        description: signingCurrency of the agreement details
        type: string 
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      remarks:
        description: Remarks
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36       
  AgreementDetailsCollection:
    description: Collection of agreementdetails.
    type: object
    properties:
      fundingstatusList:
        type: array
        items:
          $ref: '#/definitions/AgreementDetailsModel'
  