#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : floorceiling.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  sog
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/floorceiling:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FloorCeiling
      summary: Adds a new FloorCeiling.
      description: Adds a new FloorCeiling. Add additional information here for this endpoint.
      operationId: addFloorCeiling
      parameters:
      - name: FloorCeiling
        in: body
        description: Request Body that contains data required for creating a new FloorCeiling
        required: true
        schema:
          $ref: '#/definitions/FloorCeilingModel'
      responses:
        201:
          description: Returns the Id of the newly created Charges
          headers:
            Location:
              description: URL of newly created Charges
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FloorCeiling
      summary: Retrieves the list of existing FloorCeiling.
      description: Retrieves the list of existing FloorCeiling. Add additional information here for the this endpoint.
      operationId: getAllFloorCeiling
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/floorceiling/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - FloorCeiling
      summary: Get a  FloorCeiling.
      description: Get a  FloorCeiling by given id. Add additional information here for the this endpoint.
      operationId: getById
      parameters:
      - name: id
        in: path
        description: id of the FloorCeiling that need to be retrieved
        required: true
        type: string
      responses:
        200:
          description: Returns updated FloorCeiling
          schema:
            $ref: '#/definitions/FloorCeilingModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - FloorCeiling
      summary: Update an existing FloorCeiling.
      description: Update an existing FloorCeiling. Add additional information here for the this endpoint.
      operationId: updateFloorCeiling
      parameters:
      - name: id
        in: path
        description: id of the FloorCeiling that need to be updated
        required: true
        type: string
      - name: FloorCeiling
        in: body
        description: Request Body that contains data required for updating an existing FloorCeiling
        required: true
        schema:
          $ref: '#/definitions/FloorCeilingModel'
      responses:
        200:
          description: Returns updated FloorCeiling
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - FloorCeiling
      summary: Deletes the FloorCeiling identified by given ID.
      description: Deletes the FloorCeiling identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteFloorCeiling
      parameters:
      - name: id
        in: path
        description: Id of the FloorCeiling that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  FloorCeilingModel:
   description: FloorCeiling model
   type: object
   properties:
      id:
        description: Id of the floor ceiling
        type: string
        maxLength: 36
      syndicationappAggregateId:
        description: syndication application ID
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      applicationNumber:
        description: Application Number of the floor ceiling
        type: string
        maxLength: 20
      processRefNumber:
        description: Process Ref Number 
        type: string  
      remarks:
        description: Remarks of the floor ceiling
        type: string
        maxLength: 300
      FloorCeilingDetails:
        type: array
        items:
          $ref: '#/definitions/FloorCeilingDetailsModel'
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36     
  FloorCeilingCollection:
    description: Collection of FloorCeiling.
    type: object
    properties:
      FloorCeilingList:
        type: array
        items:
          $ref: '#/definitions/FloorCeilingModel'
  FloorCeilingDetailsModel:
    description: FloorCeilingDetails model
    type: object
    properties:
      id:
        description: Id of the FloorCeilingDetails
        type: string
        maxLength: 36
      floorCeilingId:
        description: floorCeilingId of the FloorCeilingDetails
        type: string
        maxLength: 36
      trancheId:
        description: trancheId of the FloorCeilingDetails
        type: string
        maxLength: 36      
      trancheName: 
        description: "trancheName of the FloorCeilingDetails"
        maxLength: 35
        type: string
      trancheType: 
        description: "trancheType of the FloorCeilingDetails"
        maxLength: 20
        type: string
      trancheEffectiveDate: 
        description: "trancheEffectiveDate of the FloorCeilingDetails"
        type: string
      trancheMaturityDate: 
        description: "trancheMaturityDate of the FloorCeilingDetails"
        type: string
      currency:
        description: currency of the FloorCeilingDetails
        type: string
        maxLength: 3
      effectiveDate:
        description: effectiveDate of the FloorCeilingDetails
        type: string
      baseFloorCeil:
        description: baseFloorCeil of the FloorCeilingDetails
        type: string
        maxLength: 1
      ddProduct:
        description: ddproduct of the FloorCeilingDetails
        type: string
        maxLength: 36
      interestComponent:
        description: interestcomponent of the FloorCeilingDetails
        type: string
        maxLength: 36
      basefloor:
        description: basefloor of the FloorCeilingDetails
        type: number
        maxLength: 22
        minimum: 0
      baseCeiling:
        description: baseCeiling of the FloorCeiling
        type: number
      allInRateFloor: 
        description: allInRateFloor of the FloorCeiling
        type: number
      allInRateCeiling: 
        description: allInRateCeiling of the FloorCeiling
        type: number
      marginAdjComponent: 
        description: marginAdjComponent of the FloorCeiling
        type: string
        maxLength: 36
  FloorCeilingDetailsCollection:
    description: Collection of FloorCeilingDetails.
    type: object
    properties:
      FloorCeilingDetailsList:
        type: array
        items:
          $ref: '#/definitions/FloorCeilingDetailsModel'