swagger: "2.0"
info:
  description: "This yaml contains all the remittance model"
  version: "1.0.0"
  title: ""
basePath: "/remittance"
tags:
- name: "RemittanceWeb"
schemes:
- "http"
paths:
 /remittance/:
  get:
   tags:
   - "RemittanceWeb"
   operationId: "remittance"
   summary: "This is not required"
   description:  "This is a dummy get"
   responses:
    201:
     description: "returns message of succes or failure"
    400:
     description: "malformed syntax."
    401:
     description: "request does not have sufficient credentials."
    403:
     description: "request is not authorised."
    405:
     description: "invalid input"
    500:
     description: "internal error"
definitions:
  CashRemittanceDTO:
    type: object
    description: "Remittance Cash Transfer transaction data transfer object"
    properties:
     datasegment:
       type: string
       description: "CCA Name"
     txnControllerRefNo:
       type: string
       description: "Txn ref no from UI"
     recordId:
       type: string
       description: "Id"
     txnRefNumber:
       type: string
       description: "Transaction Ref. No"
     txnDate:
       type: string
       format: date
       description: "Issuing date"
     txnBranchCode:
       type: string
       description: "Transaction Branch Code"
     fromAccountBranch:
       type: string
       description: "Funding/Remittance Account Branch Code"
     fromAccountCcy:
       type: string
       description: "Funding/Remittance account currency"
     fromAccountNumber:
       type: string
       description: "Funding/Remittance Account Number"
     fromAccountAmt:
       type: number
       description: "Funding/Remittance Amount"
     exgRate:
       type: string
       description: "Remittance amount exchange rate"
     toAccountBranch:
       type: string
       description: "Payble Branch Code"
     toAccountCcy:
       type: string
       description: "Account Currency"
     toAccountNumber:
       type: string
       description: "Beneficiary Account Number"
     toAccountAmt:
       type: number
       description: "Beneficiary Amount"
     glAccDesc:
       type: string
       description: "GL Account Description"
     glAccCcy:
       type: string
       description: "GL Account Ccy"
     remitterName:
       type: string
       description: "Remitter Name"
     rAddr1:
       type: string
       description: "Remitter Address1"
     rAddr2:
       type: string
       description: "Remitter Address2"
     rAddr3:
       type: string
       description: "Remitter Address3"
     rAddr4:
       type: string
       description: "Remitter Address4"
     rIdenType:
       type: string
       description: "Beneficiary Identification Type"
     rIdenNo:
       type: string
       description: "Beneficiary Identification Number"
     rChequeNo:
       type: number
       description: "Remittance Cheque Number"
     rChequeDt:
       type: string
       format: date
       description: "Remittance Cheque Date"
     totalCharges:
       type: string
       description: "Remittance total charges"
     chargeMode:
       type: string
       description: "Remittance amount charge mode"
     operationType:
       type: string
       description: "Operation Type PAYMENT/CANCEL/REFUND"
     operationMode:
       type: string
       description: "Mode of operation"
     liquidationMode:
       type: string
       description: "Mode of Liquidation"
     liquidationDt:
       type: string
       format: date
       description: "Liquidation/Payment Date"
     refundDt:
       type: string
       format: date
       description: "Refund Date"
     cancelDt:
       type: string
       format: date
       description: "Cancel Date"
     beneficaryName:
       type: string
       description: "Payment Beneficiary Name"
     bAddr1:
       type: string
       description: "Payment Beneficiary Address1"
     bAddr2:
       type: string
       description: "Payment Beneficiary Address2"
     bAddr3:
       type: string
       description: "Payment Beneficiary Address3"
     bAddr4:
       type: string
       description: "Payment Beneficiary Address4"
     bIdenType:
       type: string
       description: "Payment Beneficiary Identification Type"
     bIdenNo:
       type: string
       description: "Payment Beneficiary Identification Number"
     functionCode:
       type: string
       description: "function code"
     ecaRefNo:
       type: string
       description: "ECA Reference Number"
     narrative:
       type: string
       description: "Narrative"
     version:
       type: number
       description: "Version Number"
     status:
       type: string
       description: "Txn Status"
     createdBy:
       type: string
       description: "Created by"
     createdTs:
       type: string
       format: date
       description: "Created timestamp"
     updatedBy:
       type: string
       description: "Updated by"
     updatedTs:
       type: string
       format: date
       description: "Updated timestamp"
     remittanceDtls:
       $ref: '#/definitions/remittanceDtlsDTO'
     addDtls:
       $ref: '#/definitions/AdditionalTransactionDetails'
     txnDtls:
       $ref: '#/definitions/TransactionDetails'
     prcDtls:
       type: array
       items:
          $ref: "#/definitions/PrcDtlsModel"
     overrideDtls:
       type: array
       items: 
          $ref: "#/definitions/BaseOutcomeModel"
     demDtls:
        type: array
        items:
          $ref: "#/definitions/DenomTxnDtlsModel"
  RemittanceDtlsDTO:
    type: object
    description: "Remittance Details data transafer obeject"
    properties:
     recordId:
       type: string
       description: "ID"
     parentId:
       type: string
       description: "Parrent ID"
     issuingBankCode:
       type: string
       description: "Issuing Bank Code"
     issuingBankName:
       type: string
       description: "Issuing Bank Name"
     issuingBranchCode:
       type: string
       description: "Issuing Branch Code"
     issuingBranchName:
       type: string
       description: "Issuing Branch Name"
     paybleBankCode:
       type: string
       description: "Payble Bank Code"
     paybleBankName:
       type: string
       description: "Payble Bank Name"
     paybleBranchCode:
       type: string
       description: "Payble Branch Code"
     paybleBranchName:
       type: string
       description: "Payble Branch Name"
     remittanceAmount:
       type: number
       description: "Remittance Amount"
     remittanceNo:
       type: string
       description: "Remittance Number"
     remittanceDt:
       type: string
       format: date
       description: "Remittance Date"
     testKeyNo:
       type: string
       description: "OBPM will generte this on handoff in case of inter branch transfer"
     narrative:
       type: string
       description: "Narrative" 
     issueMode:
       type: string
       description: "Issuing Mode"
     issuedDate:
       type: string
       format: date
       description: "Issued Date"
     beneficaryName:
       type: string
       description: "Beneficiary Name"
     bAccNo:  
       type: string
       description: "Beneficiary Account Number"
     bAddr1:
       type: string
       description: "Beneficiary Address1"
     bAddr2:
       type: string
       description: "Beneficiary Address2"
     bAddr3:
       type: string
       description: "Beneficiary Address3"
     bAddr4:
       type: string
       description: "Beneficiary Address4"
     bIdenType:
       type: string
       description: "Beneficiary Identification Type"
     bIdenNo:
       type: string
       description: "Beneficiary Identification Number"
     version:
       type: number
       description: "Version Number"
     isSameBank:
       type: string
       description: "flag which indicates remittance is between same bank branches or different bank branches"
     instrumentNo:
       type: string
       description: "Intrument number which will be received from obpm on remittance issue"
     inwardRemittanceRef:
       type: string
       description: "Inward remittance refernce number"
