#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : interestmargindetails.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Syndication Application Service
host: 10.184.157.121:9000
basePath: /syndicationapplication-services
tags:
- name: SyndicationApplication
  description: API for SyndicationApplication Operations
schemes:
- http
paths:
  /web/v1/interestmargindetails:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InterestDetails
      summary: Adds a new InterestDetails.
      description: Adds a new InterestDetails. Add additional information here for this endpoint.
      operationId: addInterestDetails
      parameters:
      - name: InterestDetails
        in: body
        description: Request Body that contains data required for creating a new InterestDetails
        required: true
        schema:
          $ref: '#/definitions/InterestDetailsModel'
      responses:
        201:
          description: Returns the Id of the newly created InterestDetails
          headers:
            Location:
              description: URL of newly created InterestDetails
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InterestDetails
      summary: Retrieves the list of existing InterestDetails.
      description: Retrieves the list of existing InterestDetails. Add additional information here for the this endpoint.
      operationId: getAllInterestDetails
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/interestmargindetails/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - InterestDetails
      summary: Retrieves the InterestDetails by id.
      description: Retrieves the InterestDetails by id. Add additional information here for the this endpoint.
      operationId: getInterestDetailsById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the InterestDetails based on given applicationNumber.
          schema:
            $ref: '#/definitions/InterestDetailsModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - InterestDetails
      summary: Update an existing InterestDetails.
      description: Update an existing InterestDetails. Add additional information here for the this endpoint.
      operationId: updateInterestDetails
      parameters:
      - name: id
        in: path
        description: id of the InterestDetails that need to be updated
        required: true
        type: string
      - name: InterestDetails
        in: body
        description: Request Body that contains data required for updating an existing InterestDetails
        required: true
        schema:
          $ref: '#/definitions/InterestDetailsModel'
      responses:
        200:
          description: Returns updated InterestDetails
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - InterestDetails
      summary: Deletes the InterestDetails identified by given ID.
      description: Deletes the InterestDetails identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteInterestDetails
      parameters:
      - name: id
        in: path
        description: Id of the InterestDetails that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  InterestDetailsModel:
    description: InterestDetails model
    type: object
    properties:
      id:
        description: Id of the InterestDetails
        type: string
        maxLength: 36
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      remarks:
        description: remarks
        type: string
      processRefNumber:
        description: Process Ref Number 
        type: string        
      interestComponentsDetails:
        type: array
        items:
          $ref: '#/definitions/InterestComponentsDetailsModel'
  InterestComponentsDetailsModel:
    description: InterestComponentsDetails model
    type: object
    properties:
      id:
        description: Id of the InterestComponentsDetails
        type: string
      interestComponentsId:
        description: interestComponentsId
        type: string
      component:
        description: component
        type: string
      rateType:
        description: rateType
        type: string
      tenor:
        description: tenor
        type: number
      rateCalculationType:
        description: rateCalculationType
        type: string
      interestBasis:
        description: interestBasis
        type: string
      rate:
        description: rate
        type: number
      margin:
        description: margin
        type: number
      allInRate:
        description: allInRate
        type: number
      rateFixingRequired:
        description: rateFixingRequired
        type: string
      rateFixingDays:
        description: rateFixingDays
        type: number
      waived:
        description: waived
        type: string
      rateFixingDetails:
        type: array
        items:
          $ref: '#/definitions/RateFixingDetailsModel'
      interestMarginDetails:
        type: array
        items:
          $ref: '#/definitions/InterestMarginDetailsModel'
  RateFixingDetailsModel:
    description: RateFixingDetails model
    type: object
    properties:
      id:
        description: Id of the RateFixingDetails
        type: string
      rateFixingDetailsId:
        description: rateFixingDetailsId
        type: string
      rateCode:
        description: rateCode
        type: string
      rate:
        description: rate
        type: number
      currency:
        description: currency
        type: string
      rateFixingDate:
        description: rateFixingDate
        type: string
      rateEffectiveStartDate:
        description: rateEffectiveStartDate
        type: string
      rateEffectiveEndDate:
        description: rateEffectiveEndDate
        type: string
      nextRateFixingDate:
        description: nextRateFixingDate
        type: string
      nextNotificationDate:
        description: nextNotificationDate
        type: string
      nextEffectiveStartDate:
        description: nextEffectiveStartDate
        type: string
      tenorValue:
        description: tenorValue
        type: number
  InterestMarginDetailsModel:
    description: InterestMarginDetails model
    type: object
    properties:
      id:
        description: Id of the InterestMarginDetails
        type: string
      marginDetailsId:
        description: marginDetailsId
        type: string
      component:
        description: component
        type: string
      componentDescription:
        description: componentDescription
        type: string
      marginBasis:
        description: marginBasis
        type: string
      basisAmount:
        description: basisAmount
        type: string
      rate:
        description: rate
        type: number
  InterestDetailsCollection:
    description: Collection of InterestDetails.
    type: object
    properties:
      InterestDetailsList:
        type: array
        items:
          $ref: '#/definitions/InterestDetailsModel'
