#----------------------------- OFSS-COPYRIGHT-BEGIN ----------------------------- 
#
#  This source is part of the Oracle Banking Corporate Lending Process Management.
#  Copyright  2018 , Oracle and/or its affiliates.  All rights reserved.
#  
#  No part of this work may be reproduced, stored in a retrieval system, adopted or transmitted in any form or by any means, electronic, mechanical, photographic, graphic, optic recording or otherwise, translated in any language or computer language, without the prior written permission of Oracle and/or its affiliates.
#  
#  Oracle Financial Services Software Limited.
#  Oracle Park, Off Western Express Highway,
#  Goregaon (East), 
#  Mumbai - 400 063, India. 
#  
# ------------------------------- OFSS-COPYRIGHT-END -----------------------------
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : ddpartyrole.yaml
#  **
#  ** Module     : 
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  System
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: '2.0'
info:
  description: You can find out more about Swagger at [swagger.io](http://swagger.io) and about data types at [Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)
  version: 1.0.0
  title: Party Role Service for OBCLPM
host: 10.184.157.121:9000
basePath: /clmo-party-role-services
tags:
- name: party-role-services
  description: API for party-role-services Operations
schemes:
- http
paths:
  /web/v1/drawdownpartyrole:
    post:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Adds a new DrawdownParty.
      description: Adds a new DrawdownParty. Add additional information here for this endpoint.
      operationId: addParty
      parameters:
      - name: Party
        in: body
        description: Request Body that contains data required for creating a new DrawdownParty
        required: true
        schema:
          $ref: '#/definitions/DrawdownPartyModel'
      responses:
        201:
          description: Returns the Id of the newly created DrawdownParty
          headers:
            Location:
              description: URL of newly created DrawdownParty
              type: string
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Retrieves the list of existing DrawdownParty.
      description: Retrieves the list of existing DrawdownParty. Add additional information here for the this endpoint.
      operationId: getAllParty
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      - name: partyNumber
        in: query
        description: partyNumber of the party to be fetched
        required: false
        type: string
      - name: roles
        in: query
        description: roles of the parties to be fetched
        required: false
        type: array
        items:
           type: string          
      responses:
        200:
          description: Successful performs the operation
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/drawdownpartyrole/summary:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Retrieves the Drawdown Party party details
      description: Retrieves the Drawdown Party details. Add additional information here for the this endpoint.
      operationId: summary
      parameters:
      - name: applicationNumber
        in: query
        description: applicationNumber of the user that needs to be fetched
        required: false
        type: string
      - name: partyNumber
        in: query
        description: partyNumber of the party to be fetched
        required: false
        type: string
      - name: roles
        in: query
        description: roles of the parties to be fetched
        required: false
        type: array
        items:
           type: string
      responses:
        200:
          description: Returns the Party based on given applicationNumber.
          schema:
            $ref: '#/definitions/ResponseModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
  /web/v1/drawdownpartyrole/{id}:
    get:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Retrieves the DrawdownParty by id.
      description: Retrieves the DrawdownParty by id. Add additional information here for the this endpoint.
      operationId: getPartyById
      parameters:
      - name: id
        in: path
        description: Id that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Returns the DrawdownParty based on given applicationNumber.
          schema:
            $ref: '#/definitions/DrawdownPartyModel'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
    put:
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Update an existing DrawdownParty.
      description: Update an existing DrawdownParty. Add additional information here for the this endpoint.
      operationId: updateParty
      parameters:
      - name: id
        in: path
        description: id of the DrawdownParty that need to be updated
        required: true
        type: string
      - name: Party
        in: body
        description: Request Body that contains data required for updating an existing DrawdownParty
        required: true
        schema:
          $ref: '#/definitions/DrawdownPartyModel'
      responses:
        200:
          description: Returns updated DrawdownParty
          schema:
            $ref: '#/definitions/ResponseDtoWrapper'
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Invalid input
        500:
          description: Internal error
    delete:
      produces:
      - application/json
      - application/xml
      tags:
      - DrawdownParty
      summary: Deletes the DrawdownParty identified by given ID.
      description: Deletes the DrawdownParty identified by given ID. Add additional information here for the this endpoint.
      operationId: deleteParty
      parameters:
      - name: id
        in: path
        description: Id of the DrawdownParty that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation.
        400:
          description: Malformed syntax.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        500:
          description: Internal error
definitions:
  DrawdownPartyModel:
    description: DrawdownParty model
    type: object
    properties:
      id:
        description: Id of the DrawdownParty
        type: string
        maxLength: 36
      processRefNumber:
        description: Process ref Number
        type: string
      dataSegmentCode:
        description: Data segment code
        type: string
      updatedBy:
        description: Updated By
        type: string
      updatedTimeStamp:
        description: Updated Time Stamp
        type: string
      stageCode:
        description: stageCode
        type: string
        maxLength: 36
      createdBy:
        description: createdBy
        type: string
        maxLength: 36
      status:
        description: status
        type: string
        maxLength: 36
      applicationNumber:
        description: applicationNumber
        type: string
      validateSave:
        description: validateSave
        type: string
      remarks:
        description: remarks
        type: string
      partyDetails:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyDetailsModel'
  DrawdownPartyDetailsModel:
    description: DrawdownPartyDetails model
    type: object
    properties:
      id:
        description: Id of the DrawdownPartyDetails
        type: string
      partyId:
        description: partyId
        type: string
      partyNumber:
        description: partyNumber
        type: string
      partyName:
        description: partyName
        type: string
      maintenancePartyId:
        description: maintenancePartyId
        type: string
      countryOfIncorporation:
        description: countryOfIncorporation
        type: string
      dateOfIncorporation:
        description: dateOfIncorporation
        type: string
      legalStatus:
        description: legalStatus
        type: string
      kycStatus:
        description: kycStatus
        type: string
      holdingPattern:
        description: holdingPattern
        type: string
      partyType:
        description: partyType
        type: string
      placeOfIncorporation:
        description: placeOfIncorporation
        type: string
      demographicType:
        description: demographicType
        type: string
      organizationType:
        description: organizationType
        type: string
      onboardingRefNumber:
        description: onboardingRefNumber
        type: string
      onboardingStatus:
        description: onboardingStatus
        type: string
      existingParty:
        description: existingParty
        type: string
      externalCustomer:
        description: externalCustomer
        type: string
      updatePartyMaintenance:
        description: updatePartyMaintenance
        type: string
      languageCode:
        description: languageCode
        type: string
      reportLocale:
        description: reportLocale
        type: string
      address:
        $ref: '#/definitions/DrawdownAddressModel'
      partyContact:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyContactModel'
      partyRole:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyRoleModel'
  DrawdownPartyContactModel:
    description: DrawdownPartyContact model
    type: object
    properties:
      id:
        description: Id of the DrawdownPartyContact
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      MaintenanceContactId:
        description: MaintenanceContactId
        type: string
      salutation:
        description: salutation
        type: string
      firstName:
        description: firstName
        type: string
      lastName:
        description: lastName
        type: string
      designation:
        description: designation
        type: string
      partyContactMedia:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyContactMediaModel'
      partyContactRole:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyContactRoleModel'
  DrawdownPartyContactMediaModel:
    description: DrawdownPartyContactMedia model
    type: object
    properties:
      id:
        description: Id of the DrawdownPartyContactMedia
        type: string
      maintenanceContactMediaId:
        description: maintenanceContactMediaId
        type: string
      mediaAddress:
        description: mediaAddress
        type: string
      mediaType:
        description: mediaType
        type: string
      partyContactId:
        description: partyContactId
        type: string
      preferredFlag:
        description: preferredFlag
        type: string
      address:
        $ref: '#/definitions/DrawdownAddressModel'
  DrawdownPartyContactRoleModel:
    description: DrawdownPartyContactRole model
    type: object
    properties:
      id:
        description: Id of the DrawdownPartyContactRole
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      role:
        description: role
        type: string
      partyContactId:
        description: partyContactId
        type: string
  DrawdownPartyRoleModel:
    description: DrawdownPartyRole model
    type: object
    properties:
      id:
        description: Id of the DrawdownPartyRole
        type: string
      partyDetailsId:
        description: partyDetailsId
        type: string
      role:
        description: role
        type: string
  DrawdownAddressModel:
    description: DrawdownAddress model
    type: object
    properties:
      id:
        description: Id of the DrawdownAddress
        type: string
      parentId:
        description: parentId
        type: string
      maintenanceAddressId:
        description: maintenanceAddressId
        type: string
      addressType:
        description: addressType
        type: string
      area:
        description: area
        type: string
      building:
        description: building
        type: string
      city:
        description: city
        type: string
      country:
        description: country
        type: string
      landmark:
        description: landmark
        type: string
      locality:
        description: locality
        type: string
      state:
        description: state
        type: string
      street:
        description: street
        type: string
      zipcode:
        description: zipcode
        type: string
  DrawdownPartyCollection:
    description: Collection of DrawdownParty.
    type: object
    properties:
      DrawdownPartyList:
        type: array
        items:
          $ref: '#/definitions/DrawdownPartyModel'
